### ISSUE TITLE
run-onnx-lib can not run nonmaxsuppression models.

### ISSUE THREAD

**Issue by sjkbar-furiosa** [onnx/onnx-mlir#1005]
NMS required i64 input but run-onnx-lib(https://github.com/onnx/onnx-mlir/blob/master/utils/RunONNXLib.cpp#L362) does not support i64.
It makes following assertion failure
```
Assertion failed: (tensor && "add support for the desired type"), function omTensorListCreateFromInputSignature, file /Users/jungyoungseong/Code/onnx-mlir/utils/RunONNXLib.cpp, line 375.

```
#######################
[    { "type" : "f32" , "dims" : [1 , 10 , 4] , "name" : "boxes" }
 ,    { "type" : "f32" , "dims" : [1 , 1 , 10] , "name" : "scores" }
 ,    { "type" : "i64" , "dims" : [1] , "name" : "max_output_boxes_per_class" }
 ,    { "type" : "f32" , "dims" : [1] , "name" : "iou_threshold" }
 ,    { "type" : "f32" , "dims" : [1] , "name" : "score_threshold" }

]

**Comment by AlexandreEichenberger** [comment]
Hi @tungld can you estimate if adding support for 64bit quantities is difficult?
@sjkbar-furiosa would you be open to adding the functionality if it is not too hard?

**Comment by tungld** [comment]
> Hi @tungld can you estimate if adding support for 64bit quantities is difficult?

@AlexandreEichenberger the input  `max_output_boxes_per_class` of NMS has type of `tensor(int64)` and our implementation supports it. The issue here is @sjkbar-furiosa would like to run NMS with `RunONNXLib.cpp` which has not yet not supported i64 for inputs.  Perhaps PR #1006 is enough.

**Comment by AlexandreEichenberger** [comment]
#1006 is now merged. @sjkbar-furiosa please try to see if it works after rebasing

**Comment by sjkbar-furiosa** [comment]
Thanks. It works
