### ISSUE TITLE
failed at cmake --build . (/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(common.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be us ed when making a shared object; recompile with -fPIC)

### ISSUE THREAD

**Issue by zhangxj19** [onnx/onnx-mlir#1012]
I failed at the onnx-mlir building stage of "cmake --build ."
Here is my error info:
```
[1/2] Linking CXX shared library Debug/lib/libOnnxMlirCompiler.so
FAILED: Debug/lib/libOnnxMlirCompiler.so
: && /usr/bin/c++ -fPIC -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter
 -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizi
ng-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -DSUPPRES
S_THIRD_PARTY_WARNINGS -g  -Wl,-z,defs -Wl,-z,nodelete -shared -Wl,-soname,libOnnxMlirCompiler.so -o Debug/lib/libOnnxMlirCompiler.so src/C
ompiler/CMakeFiles/OnnxMlirCompiler.dir/OnnxMlirCompiler.cpp.o  Debug/lib/libCompilerUtils.a  Debug/lib/libOMONNXToKrnl.a  /mnt/d/Desktop/w
orkspace/onnx-mlir/llvm-project/build/lib/libMLIRMathTransforms.a  Debug/lib/libOMKrnlToLLVM.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-pro
ject/build/lib/libMLIRAffineToStandard.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libMLIRMathToLLVM.a  /mnt/d/Desktop/wor
kspace/onnx-mlir/llvm-project/build/lib/libMLIRMemRefToLLVM.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libMLIRReconcileUn
realizedCasts.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libMLIRSCFToStandard.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-
project/build/lib/libMLIRShapeToStandard.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libMLIRShape.a  Debug/lib/libOMKrnlTo
Affine.a  Debug/lib/libOMSpecializedKernelOpInterface.a  Debug/lib/libOMElideConstants.a  Debug/lib/libOMInstrumentONNX.a  Debug/lib/libOMO
pTransform.a  Debug/lib/libOMONNXRewrite.a  Debug/lib/libOMConstPropHelper.a  Debug/lib/libOMShapeInference.a  Debug/lib/libOMShapeInferenc
eOpInterface.a  Debug/lib/libOMONNXPreKrnlVerifyONNX.a  Debug/lib/libOMElideKrnlGlobalConstants.a  Debug/lib/libOMEnableMemoryPool.a  Debug
/lib/libOMOptimizeMemoryPools.a  Debug/lib/libOMBundleMemoryPools.a  Debug/lib/libOMDisconnectKrnlDimFromAlloc.a  Debug/lib/libOMLowerKrnlS
hape.a  Debug/lib/libOMSupport.a  Debug/lib/libOMKrnlOps.a 
...
...
...
onnx-mlir/llvm-project/build/lib/libLLVMRemarks.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libLLVMBitstreamReader.a  /mnt
/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libLLVMSupport.a  -lrt  -ldl  -lpthread  -lm  /usr/lib/x86_64-linux-gnu/libz.so  /usr
/lib/x86_64-linux-gnu/libtinfo.so  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libLLVMDemangle.a && :
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against symbol `_ZN6google8protobuf8internal9Are
naImpl13thread_cache_E' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(common.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be us
ed when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

It looks like the problem is about protobuf.
Here is how I install protobuf
```
PROTOC_ZIP=protoc-3.19.1-linux-x86_64.zip
curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/$PROTOC_ZIP
sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
rm -f $PROTOC_ZIP
```
But there's nothing to do with "/usr/lib/blablabla"

**Comment by flyingcow8** [comment]
i met this problem too!

**Comment by flyingcow8** [comment]
> I failed at the onnx-mlir building stage of "cmake --build ." Here is my error info:
> 
> ```
> [1/2] Linking CXX shared library Debug/lib/libOnnxMlirCompiler.so
> FAILED: Debug/lib/libOnnxMlirCompiler.so
> : && /usr/bin/c++ -fPIC -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter
>  -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizi
> ng-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -DSUPPRES
> S_THIRD_PARTY_WARNINGS -g  -Wl,-z,defs -Wl,-z,nodelete -shared -Wl,-soname,libOnnxMlirCompiler.so -o Debug/lib/libOnnxMlirCompiler.so src/C
> ompiler/CMakeFiles/OnnxMlirCompiler.dir/OnnxMlirCompiler.cpp.o  Debug/lib/libCompilerUtils.a  Debug/lib/libOMONNXToKrnl.a  /mnt/d/Desktop/w
> orkspace/onnx-mlir/llvm-project/build/lib/libMLIRMathTransforms.a  Debug/lib/libOMKrnlToLLVM.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-pro
> ject/build/lib/libMLIRAffineToStandard.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libMLIRMathToLLVM.a  /mnt/d/Desktop/wor
> kspace/onnx-mlir/llvm-project/build/lib/libMLIRMemRefToLLVM.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libMLIRReconcileUn
> realizedCasts.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libMLIRSCFToStandard.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-
> project/build/lib/libMLIRShapeToStandard.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libMLIRShape.a  Debug/lib/libOMKrnlTo
> Affine.a  Debug/lib/libOMSpecializedKernelOpInterface.a  Debug/lib/libOMElideConstants.a  Debug/lib/libOMInstrumentONNX.a  Debug/lib/libOMO
> pTransform.a  Debug/lib/libOMONNXRewrite.a  Debug/lib/libOMConstPropHelper.a  Debug/lib/libOMShapeInference.a  Debug/lib/libOMShapeInferenc
> eOpInterface.a  Debug/lib/libOMONNXPreKrnlVerifyONNX.a  Debug/lib/libOMElideKrnlGlobalConstants.a  Debug/lib/libOMEnableMemoryPool.a  Debug
> /lib/libOMOptimizeMemoryPools.a  Debug/lib/libOMBundleMemoryPools.a  Debug/lib/libOMDisconnectKrnlDimFromAlloc.a  Debug/lib/libOMLowerKrnlS
> hape.a  Debug/lib/libOMSupport.a  Debug/lib/libOMKrnlOps.a 
> ...
> ...
> ...
> onnx-mlir/llvm-project/build/lib/libLLVMRemarks.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libLLVMBitstreamReader.a  /mnt
> /d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libLLVMSupport.a  -lrt  -ldl  -lpthread  -lm  /usr/lib/x86_64-linux-gnu/libz.so  /usr
> /lib/x86_64-linux-gnu/libtinfo.so  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libLLVMDemangle.a && :
> /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against symbol `_ZN6google8protobuf8internal9Are
> naImpl13thread_cache_E' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(common.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be us
> ed when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: bad value
> collect2: error: ld returned 1 exit status
> ninja: build stopped: subcommand failed.
> ```
> 
> It looks like the problem is about protobuf. Here is how I install protobuf
> 
> ```
> PROTOC_ZIP=protoc-3.19.1-linux-x86_64.zip
> curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/$PROTOC_ZIP
> sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
> sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
> rm -f $PROTOC_ZIP
> ```
> 
> But there's nothing to do with "/usr/lib/blablabla"

I solved it. Maybe you used apt to install the protobuf compiler. Please remove it and build it from source.

**Comment by zhangxj19** [comment]
> 

That helps. Thank you very much!

**Comment by zhangxj19** [comment]
> > I failed at the onnx-mlir building stage of "cmake --build ." Here is my error info:
> > ```
> > [1/2] Linking CXX shared library Debug/lib/libOnnxMlirCompiler.so
> > FAILED: Debug/lib/libOnnxMlirCompiler.so
> > : && /usr/bin/c++ -fPIC -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter
> >  -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizi
> > ng-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -DSUPPRES
> > S_THIRD_PARTY_WARNINGS -g  -Wl,-z,defs -Wl,-z,nodelete -shared -Wl,-soname,libOnnxMlirCompiler.so -o Debug/lib/libOnnxMlirCompiler.so src/C
> > ompiler/CMakeFiles/OnnxMlirCompiler.dir/OnnxMlirCompiler.cpp.o  Debug/lib/libCompilerUtils.a  Debug/lib/libOMONNXToKrnl.a  /mnt/d/Desktop/w
> > orkspace/onnx-mlir/llvm-project/build/lib/libMLIRMathTransforms.a  Debug/lib/libOMKrnlToLLVM.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-pro
> > ject/build/lib/libMLIRAffineToStandard.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libMLIRMathToLLVM.a  /mnt/d/Desktop/wor
> > kspace/onnx-mlir/llvm-project/build/lib/libMLIRMemRefToLLVM.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libMLIRReconcileUn
> > realizedCasts.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libMLIRSCFToStandard.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-
> > project/build/lib/libMLIRShapeToStandard.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libMLIRShape.a  Debug/lib/libOMKrnlTo
> > Affine.a  Debug/lib/libOMSpecializedKernelOpInterface.a  Debug/lib/libOMElideConstants.a  Debug/lib/libOMInstrumentONNX.a  Debug/lib/libOMO
> > pTransform.a  Debug/lib/libOMONNXRewrite.a  Debug/lib/libOMConstPropHelper.a  Debug/lib/libOMShapeInference.a  Debug/lib/libOMShapeInferenc
> > eOpInterface.a  Debug/lib/libOMONNXPreKrnlVerifyONNX.a  Debug/lib/libOMElideKrnlGlobalConstants.a  Debug/lib/libOMEnableMemoryPool.a  Debug
> > /lib/libOMOptimizeMemoryPools.a  Debug/lib/libOMBundleMemoryPools.a  Debug/lib/libOMDisconnectKrnlDimFromAlloc.a  Debug/lib/libOMLowerKrnlS
> > hape.a  Debug/lib/libOMSupport.a  Debug/lib/libOMKrnlOps.a 
> > ...
> > ...
> > ...
> > onnx-mlir/llvm-project/build/lib/libLLVMRemarks.a  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libLLVMBitstreamReader.a  /mnt
> > /d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libLLVMSupport.a  -lrt  -ldl  -lpthread  -lm  /usr/lib/x86_64-linux-gnu/libz.so  /usr
> > /lib/x86_64-linux-gnu/libtinfo.so  /mnt/d/Desktop/workspace/onnx-mlir/llvm-project/build/lib/libLLVMDemangle.a && :
> > /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against symbol `_ZN6google8protobuf8internal9Are
> > naImpl13thread_cache_E' can not be used when making a shared object; recompile with -fPIC
> > /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(common.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be us
> > ed when making a shared object; recompile with -fPIC
> > /usr/bin/ld: final link failed: bad value
> > collect2: error: ld returned 1 exit status
> > ninja: build stopped: subcommand failed.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It looks like the problem is about protobuf. Here is how I install protobuf
> > ```
> > PROTOC_ZIP=protoc-3.19.1-linux-x86_64.zip
> > curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/$PROTOC_ZIP
> > sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
> > sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
> > rm -f $PROTOC_ZIP
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But there's nothing to do with "/usr/lib/blablabla"
> 
> I solved it. Maybe you used apt to install the protobuf compiler. Please remove it and build it from source.

That helps. Thank you very much!
