### ISSUE TITLE
[easy fix] docker/onnx-mlir.py quits silently if docker pull returns an error code

### ISSUE THREAD

**Issue by renxida** [onnx/onnx-mlir#1020]
https://github.com/onnx/onnx-mlir/blob/5a01b4cd2a20e0d6f42cb16705fcf306c20903ee/docker/onnx-mlir.py#L51

This line would end the script silently if docker-pull returns an error.

Took me a while learning to use pdb to figure this out.

Would be nice if other people don't have to do it

**Comment by gongsu832** [comment]
Some docker error message should have been printed? The script wasn't meant to be used non-interactively but feel free to create a PR that return nonzero in error cases.

**Comment by renxida** [comment]
Oh i was using the script interactively. It's less about the return value, more about something going wrong and me having no way to figure out what happened.

I'll write up a fix and send in a PR!
