### ISSUE TITLE
A bug in NonMaxSuppression implementation

### ISSUE THREAD

**Issue by efenniht-furiosa** [onnx/onnx-mlir#1035]
I found that NonMaxSuppression may have different outputs between onnx-mlir and onnxruntime. I made an ONNX model of a single NMS operator and ran with following (randomly generated) inputs:
```python
boxes = np.array([[0.50830555, 0.9977801, 0.92337203, 0.40146697],
  [0.85780585, 0.92481315, 0.8863284, 0.34971297],
  [0.8387263, 0.7752226, 0.40883058, 0.8470917],
  [0.1270749, 0.5904764, 0.8664146, 0.8541841],
  [0.53008854, 0.74445647, 0.46482396, 0.12454158],
  [0.5697415, 0.7804538, 0.7437527, 0.7868514]])

scores = np.array([0.595507, 0.036617756, 0.25852472, 0.6341265, 0.7362056, 0.9318451])
max_boxes_per_class = 1501274884
iou_threshold = 0.9092919
score_threshold = 0.104928255
```
I expected output would be (and onnxruntime returned) `[[0, 0, 5], [0, 0, 4], [0, 0, 3], [0, 0, 0], [0, 0, 2]]`, but binary compiled by onnx-mlir returned `[[0, 0, 5], [0, 0, 3], [0, 0, 2]]` instead.

Thanks to the [python implementation in the comment](https://github.com/onnx/onnx-mlir/blob/78feb5371ca25b46c60e32a450f007ee8ce946b9/src/Conversion/ONNXToKrnl/ObjectDetection/NonMaxSuppression.cpp#L473), I debugged and made a patch of the python code to fix the behavior.

```diff
             effective_max_output_per_class = 0
             removed_indices = np.full((spatial_size), False)
             for s in range(spatial_size):
+                # Pick the bounding box with the largest score.
+                selected_box_index = order[b, c, s]
+                selected_box = boxes[b, selected_box_index, :]
+
                 # Discard bounding boxes using score threshold.
-                if (scores[b, c, s] <= score_threshold):
+                if (scores[b, c, selected_box_index] <= score_threshold):
                     continue
                 # Have enough the number of outputs.
                 if (effective_max_output_per_class >= max_output_per_class):
                     continue
                 # Removed, ignore.
-                if removed_indices[s]:
+                if removed_indices[selected_box_index]:
                     continue
 
-                # Pick the bounding box with the largest score.
-                selected_box_index = order[b, c, s]
-                selected_box = boxes[b, selected_box_index, :]
 
                 # Store the index of the picked box to the output.
                 out_index = b * batch_size + c * max_output_per_class + effective_max_output_per_class
```
Could you please make corresponding change in the codegen?

**Comment by tungld** [comment]
@efenniht-furiosa thank you for finding the root cause! Do you think just moving `selected_box_index = order[b, c, s]` up  and using `selected_box_index` instead of `s` are enough?

Are you interested in creating a PR for the change? The NMS implementation is quite similar to the python code. Since you have a test example, you can check the correctness quickly.
