### ISSUE TITLE
RunONNXModel.py doesn't find PyRuntime.cpython-38-x86_64-linux-gnu.so

### ISSUE THREAD

**Issue by renxida** [onnx/onnx-mlir#1038]
By default, `utils/RunONNXModel.py` looks for `PyRuntime.cpython-38-x86_64-linux-gnu.so` under `$ONNX_MLIR_HOME//lib`.

However, `PyRuntime.cpython-38-x86_64-linux-gnu.so` is built by default under `build/Debug/lib`.

I am using the docker images. Running "make PyRuntime" under `build` puts the binary in `build/Debug` by default.

Am I doing something wrong / unexpected?

If not, i'll submit a PR making RunONNXModel check `$ONNX_MLIR_HOME/Debug/lib` as well as `$ONNX_MLIR_HOME/lib`

**Comment by tungld** [comment]
@renxida we usually set `ONNX_MLIR_HOME` to `build/Debug` so the script will find the .so in its `lib`. 

@gongsu832 `make PyRuntime` puts the generated .so to into `build/Debug`. Is it expected or should we put it into `build/Debug/lib`?

**Comment by gongsu832** [comment]
The .a/.so libraries used to be under `build/lib` but are now under `build/Debug/lib` or `build/Release/lib` depending on the build type since we switched to multi-config. The `onnx-mlir-dev` image is a Debug build so the libraries are under `build/Debug/lib`. They were never put under `$ONNX_MLIR_HOME/lib`.

**Comment by tungld** [comment]
@gongsu832 thanks for the information! 

@renxida could you please check with your environment again? When I ran `make PyRuntime` in my environemnt (not docker), the .so file was under `build/Debug/lib` correctly:
```
Consolidate compiler generated dependencies of target PyRuntime
[100%] Linking CXX shared module ../../Debug/lib/PyRuntime.cpython-38-s390x-linux-gnu.so
[100%] Built target PyRuntime
```

**Comment by renxida** [comment]
@gongsu832 Yes, they are built to `build/Debug/lib`, and I'm saying that `utils/RunONNXModel.py` should be edited to give a clear message about where to look for it.

@tungld I have no problem about where the `.so` file goes. I just want `util/RunONNXModel.py` to either (1) be able to locate the `.so` file on its own or (2) give an informative message about where the `.so` file could be found.
