### ISSUE TITLE
PyRuntime Error during inference: ModuleNotFoundError

### ISSUE THREAD

**Issue by Diksha-G** [onnx/onnx-mlir#1041]
I am trying to run inference on an onnx model compiled using onnx-mlir. When I execute the python script, it throws the following error:

`ModuleNotFoundError: No module named 'PyRuntime'`

The path to my PyRuntime is:
```
root@onnx-mlir:~/llvm-project/build/onnx-mlir/build/src/Runtime/CMakeFiles# ls
ExecutionSession.dir  OMTensorUtils.dir  PyRuntime.dir  cruntime.dir
```

So, I created a create a symbolic link to it:
`root@onnx-mlir:~/llvm-project/build/onnx-mlir/build/Debug/bin# ln -s /llvm-project/build/onnx-mlir/build/src/Runtime/CMakeFiles `

Then on running my script:
```
root@onnx-mlir:~/llvm-project/build/onnx-mlir/build/Debug/bin# python3 inference_googlenet.py 
Traceback (most recent call last):
  File "inference_googlenet.py", line 2, in <module>
    from PyRuntime import ExecutionSession
```

I would greatly appreciate help with this.

**Comment by imaihal** [comment]
http://onnx.ai/onnx-mlir/UsingPyRuntime.html

How about creating a link to `onnx-mlir/build/lib`?

**Comment by renxida** [comment]
See my other issue.

PyRuntime actually requires building, and builds to build/Debug/lib

**Comment by Diksha-G** [comment]
> http://onnx.ai/onnx-mlir/UsingPyRuntime.html
> 
> How about creating a link to `onnx-mlir/build/Debug/lib`?

Sorry, did not work.

**Comment by Diksha-G** [comment]
> 

From which directory should I execute the `make PyRuntime`? 

Also, the /build/Debug/lib contains: `PyRuntime.cpython-38-x86_64-linux-gnu.so` and set `ONNX_MLIR_HOME=/root/llvm-project/build/onnx-mlir/build/onnx-mlir/build/Debug/lib`.

Problem still persists:

`root@onnx-mlir:~/llvm-project/build/onnx-mlir/build/Debug/bin# python3 test_onnxmlir.py 
Traceback (most recent call last):
  File "test_onnxmlir.py", line 2, in <module>
    from PyRuntime import ExecutionSession
ModuleNotFoundError: No module named 'PyRuntime'`

**Comment by renxida** [comment]
hi @Diksha-G !

execute `make PyRuntime` under build to generate the `.so` file.

Set `ONNX_MLIR_HOME=/root/llvm-project/build/onnx-mlir/build/onnx-mlir/build/Debug/` . note that `lib` is not part of the variable, and is concatenated on by the `RunONNXModel.py`

**Comment by renxida** [comment]
Let me know if it works! I struggled HARD through this process and I want you to have to struggle a bit less. So I'm here for you.

**Comment by Diksha-G** [comment]
> hi @Diksha-G !
> 
> execute `make PyRuntime` under build to generate the `.so` file.
> 
> Set `ONNX_MLIR_HOME=/root/llvm-project/build/onnx-mlir/build/onnx-mlir/build/Debug/` . note that `lib` is not part of the variable, and is concatenated on by the `RunONNXModel.py`

hi @renxida 

I tried the following like you suggested:

`root@onnx-mlir:~/llvm-project/build/onnx-mlir/build# make PyRuntime
make: *** No rule to make target 'PyRuntime'.  Stop.
root@onnx-mlir:~/llvm-project/build/onnx-mlir/build# `

Thanks for your help. Would appreciate any lead :)

**Comment by AlexandreEichenberger** [comment]
To help us figuring out what is going on, do you mind trying the end to end example I recently added:

https://github.com/onnx/onnx-mlir/blob/main/docs/mnist_example/README.md

I ran it on my mac and it worked fine. Let me know also the machine on which you run, Linux, Mac, Windows?

**Comment by renxida** [comment]
> hi @renxida
> 
> I tried the following like you suggested:
> 
> `root@onnx-mlir:~/llvm-project/build/onnx-mlir/build# make PyRuntime make: *** No rule to make target 'PyRuntime'. Stop. root@onnx-mlir:~/llvm-project/build/onnx-mlir/build# `

Hi Diksha! from the following quote

> Also, the /build/Debug/lib contains: PyRuntime.cpython-38-x86_64-linux-gnu.so and set ONNX_MLIR_HOME=/root/llvm-project/build/onnx-mlir/build/onnx-mlir/build/Debug/lib.

You seem to have already have PyRuntime compiled.

So try removing the `/lib` at the end of `ONNX_MLIR_HOME=/root/llvm-project/build/onnx-mlir/build/onnx-mlir/build/Debug/lib` and it might work.

**Comment by Diksha-G** [comment]
> To help us figuring out what is going on, do you mind trying the end to end example I recently added:
> 
> https://github.com/onnx/onnx-mlir/blob/main/docs/mnist_example/README.md
> 
> I ran it on my mac and it worked fine. Let me know also the machine on which you run, Linux, Mac, Windows?

Hey Alexander, 

I am running this on Ubuntu 20.04 on a VM. I am trying the new example right now that you mentioned in the earlier post.

**Comment by Diksha-G** [comment]
> 

I can see the PyRuntime.cpython-…so  file in my lib folder. I have created the symbolic link from Debug/bin to Debug/lib folder. But when I open python3 and type “from PyRuntime import ExecutionSession”, it throws the error that PyRuntime not found.

**Comment by Diksha-G** [comment]
> 

I can see the PyRuntime.cpython-…so  file in my lib folder. I have created the symbol link from Debug/bin to Debug/lib folder. But when I open python3 and type “from PyRuntime import ExecutionSession”, it throws the error that PyRuntime not found.

**Comment by Diksha-G** [comment]
Update @AlexandreEichenberger 

I have been able to solve the PyRuntime Not found Error. When I execute the python script for resnet50 model, I get the following:

`  File "mlir-test.py", line 6, in <module>
    session = ExecutionSession(model, "run_main_graph")
RuntimeError: Cannot open library: 'resnet50.so'`

What am I missing here?

**Comment by renxida** [comment]
Hi @Diksha-G !

If you don't mind, I would love to have a chat by zoom and see if I can help you. I just sent you an email!

**Comment by AlexandreEichenberger** [comment]
@renxida 

> Let me know if it works! I struggled HARD through this process and I want you to have to struggle a bit less. So I'm here for you.

Sorry about this. Can you make a list of things that, in retrospect, would have helped you. I really want to make this a smoother experience for external users. We are in the process to reorganize the docs, esp the readme, so any feedback from an external source would be very useful. Please make sure to specify which OS you are using, thanks

**Comment by AlexandreEichenberger** [comment]
@Diksha-G 

> I have been able to solve the PyRuntime Not found Error. When I execute the python script for resnet50 model, I get the following:

> File "mlir-test.py", line 6, in <module> session = ExecutionSession(model, "run_main_graph") RuntimeError: Cannot open library: 'resnet50.so'

> What am I missing here?

We are building resnet in our `make check-onnx-backend`. Is it failing there, or when you are trying on a separate model.

**Comment by Diksha-G** [comment]
@AlexandreEichenberger 

I was able to get onnx-mlir to compile the onnx model and run inference on my VM after setting the LD_LIBRARY_PATH variable.

**Comment by Diksha-G** [comment]
> @AlexandreEichenberger
> 
> I was able to get onnx-mlir to compile the onnx model and run inference on my VM after setting the LD_LIBRARY_PATH variable.
