### ISSUE TITLE
OMInstrument.h not found on onnx-mlir::amd64 docker image and got compilation error

### ISSUE THREAD

**Issue by chenqiny** [onnx/onnx-mlir#1042]
I used latest onnx-mlir::amd64 docker image (ID: b8fa440f0203) 

When I compile my sample code which calls cruntime, I got OMInstrument.h not found error.

See the error below. OnnxMlirRuntime.h requires OMInstrument.h, but it is not found. There is only OnnxDataType.h in the /usr/local/include/onnx-mlir/Runtime/

```
root@72371de3e96e:/external/onnx-mlir-demo# g++ -I /usr/local/include/ onnx-mlir-runtime.cc
In file included from onnx-mlir-runtime.cc:8:
/usr/local/include/OnnxMlirRuntime.h:25:10: fatal error: onnx-mlir/Runtime/OMInstrument.h: No such file or directory
   25 | #include <onnx-mlir/Runtime/OMInstrument.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

```
root@72371de3e96e:/external/onnx-mlir-demo# ll /usr/local/include/onnx-mlir/Runtime/
total 8
drwxr-xr-x 1 root root   76 Dec  3 22:05 ./
drwxr-xr-x 1 root root   30 Dec  3 22:05 ../
-rw-r--r-- 1 root root 2104 Dec  3 21:39 OnnxDataType.h
-rw-r--r-- 1 root root 1454 Dec  3 21:39 OnnxDataTypeMetaData.inc
```

**Comment by gongsu832** [comment]
`onnx-mlir` is a minimal image to allow you to compile ONNX models without any compilation and installation on the host. For development work, you should use the `onnx-mlir-dev` image.

**Comment by chenqiny** [comment]
Thank you.
