### ISSUE TITLE
onnx-mlir building error

### ISSUE THREAD

**Issue by ljppro** [onnx/onnx-mlir#106]
Hi,
I'm using the llvm github from https://github.com/clang-ykt/llvm-project and build llvm successfully. But build the onnx-mlir with the following errors:
[ 22%] Built target OMShapeInferenceOpInterface
In file included from /docker/liujp/llvm-project/mlir/include/mlir/Transforms/DialectConversion.h:16:0,
                 from /docker/liujp/onnx-mlir/src/Dialect/Krnl/KrnlHelper.hpp:21,
                 from /docker/liujp/onnx-mlir/src/Dialect/Krnl/KrnlOps.hpp:20,
                 from /docker/liujp/onnx-mlir/src/Dialect/Krnl/KrnlHelper.cpp:15:
/docker/liujp/llvm-project/mlir/include/mlir/IR/PatternMatch.h: In instantiation of ‘OpTy mlir::PatternRewriter::create(mlir::Location, Args ...) [with OpTy = mlir::KrnlDefineLoopsOp; Args = {int}]’:
/docker/liujp/onnx-mlir/src/Dialect/Krnl/KrnlHelper.cpp:182:73:   required from here
/docker/liujp/llvm-project/mlir/include/mlir/IR/PatternMatch.h:221:16: error: no matching function for call to ‘mlir::KrnlDefineLoopsOp::build(mlir::PatternRewriter&, mlir::OperationState&, int&)’
     OpTy::build(*this, state, args...);
                ^

Could you have a check? 

Many thanks!

ljppro

**Comment by AlexandreEichenberger** [comment]
Are you using the specific version of llvm-project we list in the README?

cd llvm-project && git checkout 3ce0ad1b336e67a76d78ae7ff7d66fe127586620 && cd ..

**Comment by ljppro** [comment]
Hi AlexandreEichenberger,

Many thanks for your attending this problem!

Actually, I tried two versions of llvm, the one with the version you pasted above (same with the readme.md) and the other from https://github.com/clang-ykt/llvm-project (from the troubleshooting section). But both can't pass the building. Above I just pasted error when building the second llvm version.

Do you need the first one error when using version 3ce0ad1b336e67a76d78ae7ff7d66fe127586620?

Thanks again!

Jinpeng

**Comment by tjingrant** [comment]
Hi @ljppro , after chatting with Doru, we will probably take off the recommendation to use clang-ykt/llvm-project. So yes, it would be nice to see the error log when using version 3ce0a, given that it's the one we actively test against.

**Comment by ljppro** [comment]
Hi @tjingrant, I have changed the llvm to version 3ce0a. But this time the error is different from the last time:
[ 16%] Building ONNXDecompose.inc...
Scanning dependencies of target OMShapeInferenceOpInterface
In file included from /docker/liujp/onnx-mlir/src/Transform/ONNX/ElideConstants.cpp:23:0:
/****/onnx-mlir/src/Dialect/ONNX/ONNXOps.hpp:39:44: fatal error: src/Dialect/ONNX/ONNXOps.hpp.inc: No such file or directory

Many thanks!

**Comment by tjingrant** [comment]
@doru1004 It seems like we are missing dependency from `OMElideConstants` to `OMONNXOps`.

**Comment by gongsu832** [comment]
Try this patch:
```
diff --git a/src/Transform/ONNX/CMakeLists.txt b/src/Transform/ONNX/CMakeLists.txt
index d34127e..dd653ff 100644
--- a/src/Transform/ONNX/CMakeLists.txt
+++ b/src/Transform/ONNX/CMakeLists.txt
@@ -13,6 +13,8 @@ add_library(OMElideConstants
 target_include_directories(OMElideConstants
         PRIVATE ${ONNX_MLIR_SRC_ROOT} ${ONNX_MLIR_BIN_ROOT}
         ${ONNF_MLIR_SRC_ROOT})
+add_dependencies(OMElideConstants
+        OMONNXOpsIncGen ShapeInferenceOpInterfaceIncGen)

 set(LLVM_TARGET_DEFINITIONS ONNXRewrite.td)
 onnx_mlir_tablegen(ONNXRewrite.inc -gen-rewriters)
```

**Comment by ljppro** [comment]
@gongsu832, thanks for your attending this problem. But it seems this patch can't work on my git base - I cloned the latest onnx-mlir - and the error is attached below:
# patch < patch.diff
patching file CMakeLists.txt
Hunk #1 FAILED at 13.
1 out of 1 hunk FAILED -- saving rejects to file CMakeLists.txt.rej
# cat CMakeLists.txt.rej
--- CMakeLists.txt
+++ CMakeLists.txt
@@ -13,6 +13,8 @@ add_library(OMElideConstants
 target_include_directories(OMElideConstants
         PRIVATE ${ONNX_MLIR_SRC_ROOT} ${ONNX_MLIR_BIN_ROOT}
         ${ONNF_MLIR_SRC_ROOT})
+add_dependencies(OMElideConstants
+        OMONNXOpsIncGen ShapeInferenceOpInterfaceIncGen)

 set(LLVM_TARGET_DEFINITIONS ONNXRewrite.td)
 onnx_mlir_tablegen(ONNXRewrite.inc -gen-rewriters)

Could you have a double check and any suggestion?

Many thanks!

**Comment by gongsu832** [comment]
It's a git patch. Use `git apply patch.diff`

**Comment by ljppro** [comment]
@gongsu832, many thanks! This command works and this error doesn't occur. But I still have the error when I first time try the 3ce0 version of llvm as below. Can you have a check? 
Many thanks!

> onnx_mlir::CreateArrayAttribute(onnx::TensorProto) [with T = float]’:
onnx-mlir/src/Builder/FrontendDialectHelper.cpp:147:50:   required from here
onnx-mlir/src/Builder/FrontendDialectHelper.cpp:114:30: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedField<float>’ and ‘int’)
   return std::vector<T>(&data[0], &data[0] + size);

onnx-mlir/src/Builder/FrontendDialectHelper.cpp:114:40: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedField<float>’ and ‘int’)
   return std::vector<T>(&data[0], &data[0] + size);
                                        ^
onnx-mlir/src/Builder/FrontendDialectHelper.cpp: In instantiation of ‘std::vector<_RealType> onnx_mlir::CreateArrayAttribute(onnx::TensorProto) [with T = int]’:
onnx-mlir/src/Builder/FrontendDialectHelper.cpp:156:52:   required from here
onnx-mlir/src/Builder/FrontendDialectHelper.cpp:114:30: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedField<int>’ and ‘int’)
   return std::vector<T>(&data[0], &data[0] + size);
                              ^
onnx-mlir/src/Builder/FrontendDialectHelper.cpp:114:40: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedField<int>’ and ‘int’)
   return std::vector<T>(&data[0], &data[0] + size);
                                        ^
onnx-mlir/src/Builder/FrontendDialectHelper.cpp: In instantiation of ‘std::vector<_RealType> onnx_mlir::CreateArrayAttribute(onnx::TensorProto) [with T = long int]’:
onnx-mlir/src/Builder/FrontendDialectHelper.cpp:165:52:   required from here
onnx-mlir/src/Builder/FrontendDialectHelper.cpp:114:30: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedField<long int>’ and ‘int’)
   return std::vector<T>(&data[0], &data[0] + size);
                              ^
onnx-mlir/src/Builder/FrontendDialectHelper.cpp:114:40: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedField<long int>’ and ‘int’)
   return std::vector<T>(&data[0], &data[0] + size);

**Comment by gongsu832** [comment]
Your protobuf version may be too low. As indicated in the README, you need 3.11.0 and above.

**Comment by ljppro** [comment]
@gongsu832, many thanks! After applying the git patch an upgrading the protobuf, I can build onnx-mlir now. But when I test the command, it coredumped as below. Could you have a check? Or I have to raise a new issue?
# ./onnx-mlir --EmitONNXIR squeezenet1.0-3.onnx
onnx-mlir: onnx-mlir/src/Builder/FrontendDialectTransformer.cpp:488: void onnx_mlir::ImportFrontendModelFile(std::__cxx11::string, mlir::MLIRContext&, mlir::OwningModuleRef&): Assertion `parse_success && "Onnx Model Parsing Failed."' failed.
Aborted (core dumped)

**Comment by tjingrant** [comment]
@ljppro could you share the model? Either the file or the url is fine.

**Comment by tjingrant** [comment]
@ljppro also something to check - did you specify the model name correctly? Sometimes I get this assertion failure when the path to the model file is not correctly specified.

**Comment by ljppro** [comment]
@tjingrant, I just download the model from https://github.com/onnx/models/blob/master/vision/classification/squeezenet/model/squeezenet1.0-3.onnx and put the file in the same directory with onnx-mlir executable. 
And many thanks for your quick reply.

**Comment by tjingrant** [comment]
@ljppro firstly can you verify (by opening the onnx model in Netron) that the onnx model you downloaded is valid? For instance, if you do a `wget` on the url you gave me, a html page will be downloaded instead of the model.

Secondly, even though model parsing works for me, `onnx-mlir` failed on lowering the `GlobalAveragePool` op, which we should be able to support reasonably soon.

**Comment by tjingrant** [comment]
I'd recommend trying out mnist first, from https://onnxzoo.blob.core.windows.net/models/opset_8/mnist/mnist.tar.gz .

**Comment by ljppro** [comment]
@tjingrant, many thanks! After double check, the model I downloaded is actually a HTML file. And when test against the mnist model, it passed.
Thanks again and sorry for the inconvenient!
