### ISSUE TITLE
Segmentation fault when a model was compiled with -O0, -O1

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#1061]
I got segmentation fault with many models if they were compiled using `-O0` or `-O1`, e.g. with resnet50:
```
ONNX_MLIR_HOME=/home/tungld/dl/onnx-mlir/build/Debug python ../utils/RunONNXModel.py resnet50.onnx --compile_args="-mcpu=z14 -O0"
Temporary directory has been created at /tmp/tmpjf_k8lqx
Generating random inputs ...
  - 1st input's shape (1, 3, 224, 224)
  done.

Compiling the model ...
Shared library /tmp/tmpjf_k8lqx/model.so has been compiled.
  took  57.782129378058016  seconds.

Running inference ...
Segmentation fault (core dumped)
```

There was no issue when using `-O2` or `-O3`.

**Comment by AlexandreEichenberger** [comment]
Maybe you can quickly determine that the unoptimized LLVM IR we gen at -O3 or -O1 are the same, and if they are, then we know it is an llvm issue.

I wonder if calling `opt` at low level of optimization is the problem. @etiotto do you know? We could try skipping `opt` all together, at the very least just to see what would happen.

**Comment by etiotto** [comment]
IIRC `clag` calls executes `opt` passes even at -O0. Although clang does not actually calls the `opt` tools directly but rather executes opt passes internally. I haven't looked exactly how that happens in `clang` but I suspect it does not matter whether we call opt explicitly or not. 

This is something that we will need to trace in LLVM.

**Comment by AlexandreEichenberger** [comment]
@etiotto any progress on using -O0?

**Comment by imiiii** [comment]
Hi, I get 
6540 segmentation fault (core dumped)  when running ./onnx-mlir --EmitMLIR model.onnx --O1
But I did not get any error when I am running 
./onnx-mlir --EmitMLIR model.onnx --O3
It dumped model.onnx.mlir, I want to know that is this file usable for entry to mlir-opt in MLIR project ??

**Comment by whitneywhtsang** [comment]
I got similar result as @imiiii, where there is a compile time segfault at lower opts.
\> ./onnx-mlir -O3 [resnet50-v1-7.onnx](https://github.com/onnx/models/blob/main/vision/classification/resnet/model/resnet50-v1-7.onnx) --EmitMLIR
(no errors)
\> ./onnx-mlir -O2 [resnet50-v1-7.onnx](https://github.com/onnx/models/blob/main/vision/classification/resnet/model/resnet50-v1-7.onnx) --EmitMLIR
[1]    1207696 segmentation fault (core dumped)
\> ./onnx-mlir -O1 [resnet50-v1-7.onnx](https://github.com/onnx/models/blob/main/vision/classification/resnet/model/resnet50-v1-7.onnx) --EmitMLIR
[1]    1216720 segmentation fault (core dumped)
\> ./onnx-mlir -O0 [resnet50-v1-7.onnx](https://github.com/onnx/models/blob/main/vision/classification/resnet/model/resnet50-v1-7.onnx) --EmitMLIR
[1]    1217010 segmentation fault (core dumped)

`--EmitONNXIR` is fine at all opts.

**Comment by whitneywhtsang** [comment]
When enabling `enableTiling` in `FrontendToKrnlLoweringPass`, [resnet50-v1-7.onnx](https://github.com/onnx/models/blob/main/vision/classification/resnet/model/resnet50-v1-7.onnx) compile and run successfully at `-O1` and above on LoP, but fail at `-O0` at runtime.
```
   FrontendToKrnlLoweringPass(int optLevel)
       : FrontendToKrnlLoweringPass(
            /*emitDealloc=*/false, /*enableTiling=*/optLevel >= 3) {}
```

**Comment by AlexandreEichenberger** [comment]
@whitneywhtsang thanks for looking into this.

**Comment by whitneywhtsang** [comment]
I have narrowed down the problem to an alloc and its users inside a multiple levels nested loop nest with big outer loops trip count, which can cause segfault when run out of stack space.
At `-O1` and above, `InstCombine` is able to remove such alloc and all their users, as they are actually dead code.
<img width="560" alt="Screen Shot 2022-04-28 at 11 07 02 AM" src="https://user-images.githubusercontent.com/54643204/165784003-ab294dfc-69d5-4426-9e6f-b4fbd40e717d.png">

**Comment by AlexandreEichenberger** [comment]
aha... 

One approach is  to increase stack size when running our benchmarks? When we don't use multiple threads (or not that many), increasing stack size is not too bad.

Maybe a better approach would be to alloc always outside of the inner loops.

**Comment by whitneywhtsang** [comment]
> Maybe a better approach would be to alloc always outside of the inner loops.

Right, I am actually looking into this approach. I tried to change `ONNXConvOpLowering` which helped a lot (much less `InstCombine` needed), but still cannot completely run successfully without `InstCombine`. I am in the process of re-narrowing down to another single different that cause it to fail, after the change in `ONNXConvOpLowering`.

**Comment by whitneywhtsang** [comment]
> allocation out of loops with

@tungld Thanks for the suggestion! I found a way to avoid the problem by changing how the `alloca` instructions are created in the first place.

**Comment by whitneywhtsang** [comment]
#1397 only fixes runtime failure, there is still compile time failure remains.

**Comment by whitneywhtsang** [comment]
Verified that [resnet50-v1-7.onnx](https://github.com/onnx/models/blob/main/vision/classification/resnet/model/resnet50-v1-7.onnx) can now compile and run successfully at `-O0`, `-O1`, `-O2`, and `-O3` on LoP.
@tungld Please reopen if there are other models that still need to be looked at.

**Comment by whitneywhtsang** [comment]
Verified that backend tests can run successfully at `-O0`. 
FYI @gongsu832 @AlexandreEichenberger

**Comment by whitneywhtsang** [comment]
Thanks @gongsu832 . What are the usages of the dev and user image? Are they going to impact the PR checks?

**Comment by gongsu832** [comment]
@whitneywhtsang The PR checks are actually done through the dev and user images, which also get published. Dev image is meant for developers who want to build and contribute to onnx-mlir. User image is meant for users want just want to use onnx-mlir to compile ONNX models without having to install anything on their host.

**Comment by gongsu832** [comment]
I don't know how much longer the tests will take with -O0. We will see when the PR is submitted.

**Comment by whitneywhtsang** [comment]
Sounds good, I saw an increase from 30mins to 1hr30mins by changing backend tests from `-O3` to -O0`.

**Comment by AlexandreEichenberger** [comment]
@gongsu832 @whitneywhtsang is that increase experienced during each CIs for our PRs? Or only for the final vetting of images?
Maybe we could consider a smaller set than testing all tests for the -O0?

**Comment by gongsu832** [comment]
Running tests with -O0 in the dev image increases the Jenkins CI build 10-20 minutes. It's still shorter than Windows CI so there is no effect on how long we have to wait before merging. However, we can change to build the user image first so errors can be detect quicker.
