### ISSUE TITLE
Add an option to stop compilation after the object file is produced

### ISSUE THREAD

**Issue by etiotto** [onnx/onnx-mlir#1089]
We have a number of options to stop the compilation process at various points: 
 
 ```
 ONNX MLIR Options:
These are frontend options.

  Choose target to emit:
      --EmitONNXBasic                                  - Ingest ONNX and emit the basic ONNX operations without inferred shapes.
      --EmitONNXIR                                     - Ingest ONNX and emit corresponding ONNX dialect.
      --EmitMLIR                                       - Lower model to MLIR built-in transformation dialect.
      --EmitLLVMIR                                     - Lower model to LLVM IR (LLVM dialect).
      --EmitLib                                        - Lower model to LLVM IR, emit (to file) LLVM bitcode for model, compile and link it to a shared library.
      --EmitJNI                                        - Lower model to LLVM IR -> LLVM bitcode -> JNI shared library -> jar
```

I propose to add an option to stop the compilation/link process immediately after the object is generated. In most traditional C/C++ compiler (clang/gcc/xlc/...) that options is named `-c` so, I would propose we add the `-c` option to `onnx-mlir`. 

An alternative name could be `-EmitObj`. Opinions/preferences ?

**Comment by AlexandreEichenberger** [comment]
Is the goal to generate a .o but not the .so? The .so also include the runtime library, so you suggest that the .o would only contain the graph plus the get signatures (which are custom generated I think)? Can you indicate the use case that you are thinking about?

Also, if we are looking at a more LLVM behavior, the syntax of the options should be more like `--emit-onnx-basic` than `--EmitONNXBasic`.

If I had my choice of rewording options, I would have

--emit-mlir-onnx-preprocess (generate mlir onnx dialect without any preprocessing ) 
--emit-mlir-onnx  (mlir onnx dialect)
--emit-mlir (mlir high-level dialects)
--emit-mlir-llvm (mlir llvm dialect)

--emit-lib (default)
--emit-jni  or --emit-jar (not sure which one is more descriptive of what we generate: generate JNI jar file)

and Ideally, we could add a comment in the MLIR file generated by the first 4 options that allow us to feed it back to onnx-mlir, e.g.:

```
onnx-mlir -O3 --emit-mlir-onnx -o monist-high-level.mlir mnist.onnx
onn-mlir -O3 monist-high-level.mlir 
```

**Comment by etiotto** [comment]
>> Is the goal to generate a .o but not the .so? The .so also include the runtime library, so you suggest that the .o would only contain the graph plus the get signatures (which are custom generated I think)? Can you indicate the use case that you are thinking about?

Yes, that is the goal.  The use case is to support cross compilation where the .o(s) are generated on a build host (say Linux on Z) but for another target architecture and the link step is done on a different OS (say z/OS).  The link step (which creates the shared library) would invoke the system linker of the target architecture, and link the onnx-mlir runtime library as well as any system library required.

**Comment by gongsu832** [comment]
Isn't .o already machine instructions so not good for cross compilation?

**Comment by etiotto** [comment]
> Isn't .o already machine instructions so not good for cross compilation?

Depends, by default yes the object file would contain machine instruction for the architecture of the machine where the object was compiled. When `onnx-mlir` is explicitly given a triple via the `-mtriple` option we can instruct the compiler to generate objects for the architecture encoded in that triple. In that scenario the assembly code in the object would work on the target machine.
