### ISSUE TITLE
Garbled filename after running onnx-mlir on a model

### ISSUE THREAD

**Issue by kwu91** [onnx/onnx-mlir#112]
**OS:** Ubuntu 18.04 64-bit
**Commit id:** f5f336db
**Steps to reproduce**: 
I downloaded a model from https://github.com/onnx/models and ran the follow command:
`onnx-mlir --EmitONNXIR model.onnx`. Only model.mlir was outputted while model.onnx.mlir was missing. 

Secondly, after running `onnx-mlir --EmitLLVMIR model.onnx`, model.onnx.mlir was nowhere to be found. Instead, a file with a garbled filename showed up. The content of the file was fine though.

It appears to be an issue with the way the concatenation is done here :https://github.com/onnx/onnx-mlir/blob/137ce767e6bf25b0fa09f34c84d36393f8a408a0/src/MainUtils.cpp#L110-L111

If I change this to something like below, the filename corruption goes away.
```cpp
string tempFilename = filename + extension;
freopen(tempFilename.c_str(), "w", stderr);
```

Let me know what you think. Thanks.

**Comment by chentong319** [comment]
Ran into the same problem. I tried the suggested fix and it works for me. It is a correct fix.

**Comment by chentong319** [comment]
@kwu91 Will you submit your fix or do you want me to do that for you?

**Comment by kwu91** [comment]
> @kwu91 Will you submit your fix or do you want me to do that for you?

Sure I can submit a PR. Thanks
