### ISSUE TITLE
onnx-mlir does not check types and shapes of inputs

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#1125]
Currently, onnx-mlir does not check the shapes of inputs passed to a model, which would cause wrong results or even segfault.

For example, an input program is:
```mlir
module {
  func private @main_graph(%arg0 : tensor<4x4xf32>, %arg1 : tensor<4x3xf32>) -> tensor<*xf32> {
     %0 ="onnx.MatMul"(%arg0, %arg1) : (tensor<4x4xf32>, tensor<4x3xf32>) -> tensor<*xf32>
    "std.return"(%0) : (tensor<*xf32>) -> ()
  }
  "onnx.EntryPoint"() {func = @main_graph, numInputs = 2 : i32, numOutputs = 1 : i32, signature = ""} : () -> ()
}
```

which expects 4x4 and 4x3 matrices.

A python program for the above program is:
```python
import numpy as np
from PyRuntime import ExecutionSession

model = 'test.so'
sess = ExecutionSession(model, "run_main_graph")
a = np.arange(16).astype('float32') # shape is (16,)
b = np.arange(12).astype('float32') # shape is (12,)
y = sess.run([a, b])
print(y[0])
```
This program produces a correct result though the input shapes does not match the model input shapes, that is:
```
[[ 42.  48.  54.]
 [114. 136. 158.]
 [186. 224. 262.]
 [258. 312. 366.]]
```

A real issue happens when `a` has less than 16 elements, say `a = np.arange(10).astype('float32')`, there is no error but a wrong result:
```
[[ 42.    48.    54.  ]
 [114.   136.   158.  ]
 [ 27.    44.    61.  ]
 [ 15.75  17.5   19.25]]
```

**Comment by AlexandreEichenberger** [comment]
That is true. Broadening the scope of this issue.

At this time, we do shape verification for ops with shapes known at compile time (e.g. above if the mat multiple was 4x3 * 4x4, we would report an error). We do not insert any code when the dimensions are dynamic. So we assume anything at runtime is fine.

So in general, we do not do any dynamic type checking. To do so, we would essentially need to extend the ShapeInference approach to have a `VerifyShape` in addition of the current `ComputeShape`. When called by a verifier, it would do compile time check on constant dimensions. When called during lowering to Krnl, that same method would generate code that does the checking. This can be done using IndexExpressions. The result would be an `assert` with error message when failing at runtime.

**Comment by chentong319** [comment]
We can check the input shape using the input signature when the model is invoked, outside of the onnx-mlir .so. It's a good task for students.

**Comment by tungld** [comment]
> When called during lowering to Krnl, that same method would generate code that does the checking. This can be done using IndexExpressions

Would this generated code affect optimizing the whole code?
Given that IndexExprs are composable, we can call `VerifyShape` for all ops at once which results in a single IndexExpr whose generated code would be very lightweight.

**Comment by tungld** [comment]
Updated the title to cover input types.

**Comment by AlexandreEichenberger** [comment]
Is the proposal to always check that if the inputs of a function have a compile time shape and type are indeed meeting expectations? Or only in "debug mode"?

Also, I don't think we have support to generate errors during the evaluation at this time
