### ISSUE TITLE
Embed compiler identification string 

### ISSUE THREAD

**Issue by etiotto** [onnx/onnx-mlir#1206]
I have seen compilers that embed the name of the compiler used to create the executable in the .comment section of the exec (on Linux). For example for an exec compiled using clang (note `clang version 12.0.1` in the dump below):
```
❱❱❱ readelf -p .comment a.out

String dump of section '.comment':
  [     0]  GCC: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
  [    29]  clang version 12.0.1
```
  
For a `.so` corresponding to a simple model (compiled by onnx-mlir), we have:
```
 ❱❱❱ readelf -p .comment ./docs/doc_example/add.so

String dump of section '.comment':
  [     0]  GCC: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

So the string to identify the compiler is missing.

The fact that `clang` is able to embed a string in the `.comment` section is evidence that we have the basic support in LLVM itself.  We would have to find a way to generate an annotation in the LLVM IR we produce, something like:
```
!llvm.ident = !{!2}
!2 = !{!"onnx-mlir version 1.0.0"}
```
I think this would work on Linux like OSes.  And should work on other OSes as well, given that the `!llvm.ident` in LLVM IR exists and so most LLVM backends (i.e. `llc`) would lower it to an appropriate format in the generated object files.

**Comment by etiotto** [comment]
@whitneywhtsang want to take a look when you have some time?

**Comment by etiotto** [comment]
Should be able to attach metadata to the module, similar to what is done in PR https://github.com/onnx/onnx-mlir/pull/1205/files

**Comment by whitneywhtsang** [comment]
https://github.com/onnx/onnx-mlir/pull/1211
