### ISSUE TITLE
Cpp check warnings from onnx-mlir

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#1235]
We detected warnings from cppcheck when scanning the latest onnx-mlir. The first appears to be from a party dependency so I'm unsure if that can be resolved here. The others appear to be a possible legitimate issue related to the c_str() return at https://github.com/onnx/onnx-mlir/blob/8a290108a3a5175da0a84e7ea3681718bea61ddc/src/Compiler/OnnxMlirCompiler.cpp#L45

```
<results version="2">
<cppcheck version="1.90"/>
<errors>
<error id="deallocret" severity="error" msg="Returning/dereferencing 'bench' after it is deallocated / released" verbose="Returning/dereferencing 'bench' after it is deallocated / released" cwe="672">
<location file="DLCpp/third_party/onnx-mlir/third_party/benchmark/src/benchmark_register.cc" line="187" column="3"/>
<location file="DLCpp/third_party/onnx-mlir/third_party/benchmark/src/benchmark_register.cc" line="184" column="40"/>
<symbol>bench</symbol>
</error>
<error id="returnDanglingLifetime" severity="error" msg="Returning pointer to local variable 'val' that will be invalid when returning." verbose="Returning pointer to local variable 'val' that will be invalid when returning." cwe="562">
<location file="DLCpp/third_party/onnx-mlir/src/Compiler/OnnxMlirCompiler.cpp" line="45" column="19"/>
<location file="DLCpp/third_party/onnx-mlir/src/Compiler/OnnxMlirCompiler.cpp" line="44" column="15" info="Variable created here."/>
<location file="DLCpp/third_party/onnx-mlir/src/Compiler/OnnxMlirCompiler.cpp" line="45" column="10" info="Pointer to container is created here."/>
</error>
<error id="stlcstr" severity="error" msg="Dangerous usage of c_str(). The value returned by c_str() is invalid after this call." verbose="Dangerous usage of c_str(). The c_str() return value is only valid until its string is deleted." cwe="664">
<location file="DLCpp/third_party/onnx-mlir/src/Compiler/OnnxMlirCompiler.cpp" line="45" column="3"/>
</error>
</errors>
</results>
```

**Comment by AlexandreEichenberger** [comment]
First issue is being addressed by #1210 which is approved and will merge very soon.

**Comment by cjvolzka** [comment]
Excellent! That's the one I was worried about. The other, from benchmark, I believe is just used during testing so I wasn't too worried there.

Should I keep this open to track the benchmark warning or is that out of scope for onnx-mlir?

**Comment by AlexandreEichenberger** [comment]
Ok, and I checked the pattern for the benchmark. It is a very special pattern.

The error comes from here
```cpp
Benchmark* RegisterBenchmarkInternal(Benchmark* bench) {
  std::unique_ptr<Benchmark> bench_ptr(bench);
  BenchmarkFamilies* families = BenchmarkFamilies::GetInstance();
  families->AddBenchmark(std::move(bench_ptr));
  return bench;
}
```

Basically, the original pointer `bench` is uniqued_ptr`ed and its lifetime is associated with the variable `families`.
The raw pointer is then returned to the user. So technically, the raw pointer can be safely used until `families` is destroyed.

A look at the `BenchmarkFamilies::GetInstance();` shows that that variable is a method static.... so it exists for the duration of the program.

```
BenchmarkFamilies* BenchmarkFamilies::GetInstance() {
  static BenchmarkFamilies instance;
  return &instance;
}
```

So this end up ok.

**Comment by AlexandreEichenberger** [comment]
You can open an issue against benchmark... it would require ripping the unique_ptr and have a more explicit memory management. Not sure if it is worth it, but maybe others have complained too. I don't have the bandwidth to do a PR on this one since it appears to be ok.

**Comment by cjvolzka** [comment]
Sounds good. Thanks for taking a look! We'll see about opening an issue with benchmark. I'm closing this issue since the onnx-mlir warning will be covered by https://github.com/onnx/onnx-mlir/pull/1210
