### ISSUE TITLE
Modify codebase to use builder based interface to generate Krnl loops

### ISSUE THREAD

**Issue by etiotto** [onnx/onnx-mlir#1251]
We document 2 sets of interfaces to generate Krnl loops, and old interface (see LoweringCode.md - 'Older interface to generate loops') and a new interface based on `KrnlBuilder` (see LoweringCode.md - 'Builder based interface to generate Krnl loops'). 

Having 2 alternatives to accomplish the same task is not ideal. We should use the new interfaces throughout the project and then get rid of the old interfaces.

**Comment by whitneywhtsang** [comment]
#1250 only partially completed #1251, so reopening.

**Comment by whitneywhtsang** [comment]
https://github.com/onnx/onnx-mlir/pull/1283 only partially completed https://github.com/onnx/onnx-mlir/issues/1251, so reopening.

**Comment by whitneywhtsang** [comment]
https://github.com/onnx/onnx-mlir/pull/1292 only partially completed https://github.com/onnx/onnx-mlir/issues/1251, so reopening.

**Comment by whitneywhtsang** [comment]
https://github.com/onnx/onnx-mlir/pull/1303 only partially completed https://github.com/onnx/onnx-mlir/issues/1251, so reopening.

**Comment by whitneywhtsang** [comment]
https://github.com/onnx/onnx-mlir/pull/1308 only partially completed https://github.com/onnx/onnx-mlir/issues/1251, so reopening.

**Comment by whitneywhtsang** [comment]
https://github.com/onnx/onnx-mlir/pull/1314 only partially completed https://github.com/onnx/onnx-mlir/issues/1251, so reopening.

**Comment by whitneywhtsang** [comment]
https://github.com/onnx/onnx-mlir/pull/1316 only partially completed https://github.com/onnx/onnx-mlir/issues/1251, so reopening.

**Comment by whitneywhtsang** [comment]
https://github.com/onnx/onnx-mlir/pull/1317 only partially completed https://github.com/onnx/onnx-mlir/issues/1251, so reopening.
