### ISSUE TITLE
Memory issue with memref<memref<>>

### ISSUE THREAD

**Issue by chentong319** [onnx/onnx-mlir#1254]
memref<memref<>> is used to implement onnx sequence. I found that the Bufferization::Deallocate pass can not handle such memref correctly. The underlying reason is that a memref is "escaped" when it is stored into memref<memref<>>. In detail, there three cases:

1.  Deallocate the escape memref.  
      ```
      memref.store (%12, %2, %arg3) : (memref<1xf32>, memref<?xmemref<1xf32>>, index) -> ()
      memref.dealloc %12 : memref<1xf32>
      ```
2. Failed to deallocate the memref extracted from memref<memref<>>
3. No deep deallocation when memref<memref<>> is deallocated

Solution
1. Introduce sequence op which will be lowered to memref ops after deallocation
2. SeqStore for writing to a sequence. The input tensor will be copied inside SeqStore.
3. SeqExtract for extracting an element tensor from the sequence. This op is given AllocationOpInterface and will be treated as allocation by deallocation pass
4. SeqCreate for creating a sequence. This op is also give AllocationOpInterface and the deep deallocation can be defined in its buildDealloc() function

Implementation details:

- We need a separate conversion pass, which is after Deallocation and before KrnlToLLVM. The reason is that the type converter in KrnlToLLVM will make it difficult to lower the seq ops at llvm level.
- The Krnl Ops are lowered in different stages. Should they be put into different groups/dialects?

**Comment by etiotto** [comment]
@chentong319 I tried to reproduce the behaviour described above with this simple MLIR test:
```
func @allocation(%arg0: index) {
  %0 = memref.alloc() : memref<1xf32> 
  %1 = memref.alloc() : memref<2xmemref<1xf32>> 
  memref.store %0, %1[%arg0] :  memref<2xmemref<1xf32>> 
  return
 } 
 ```
 
The test allocates a memref of one element (%0) and stores it into another memref (%1). 
If I use `mlir-opt` and run the buffer deallocation pass `-buffer-deallocation` I see the pass injecting the 2 deallocations:

% ~/Source/onnx/llvm-project/build/bin/mlir-opt memreftest.mlir -buffer-deallocation --print-ir-before-all  --print-ir-after-all 
```
// -----// IR Dump Before BufferDeallocation //----- //
func @allocation(%arg0: index) {
  %0 = memref.alloc() : memref<1xf32>
  %1 = memref.alloc() : memref<2xmemref<1xf32>>
  memref.store %0, %1[%arg0] : memref<2xmemref<1xf32>>
  return
}

// -----// IR Dump After BufferDeallocation //----- //
func @allocation(%arg0: index) {
  %0 = memref.alloc() : memref<1xf32>
  %1 = memref.alloc() : memref<2xmemref<1xf32>>
  memref.store %0, %1[%arg0] : memref<2xmemref<1xf32>>
  memref.dealloc %1 : memref<2xmemref<1xf32>>
  memref.dealloc %0 : memref<1xf32>
  return
}

It would seem that, at least for this simple test case, the buffer deallocation pass is able to recognise that both allocated memref do not escape the function scope and so it deallocaters them. 

This is likely not exactly the situation you were describing. For my curiosity, do you have a small test that would describe the problem?

**Comment by chentong319** [comment]
I was working on test case with LoopOp. In that case,  %0 is allocated inside loop body and %1 is live through the loop. The deallocation of %0 was inserted inside the loop body. That's  the problem. Let me regenerate the output of my test case.

**Comment by chentong319** [comment]
Here is the result. Pay more attention to the bolded lines.

// -----// IR Dump After BufferDeallocation //----- //
func @main_graph(%arg0: memref<i64>, %arg1: memref<i1>, %arg2: memref<1xf32>) -> (memref<1xf32>, memref<?x1xf32>) attributes {input_names = ["trip_count", "cond", "y"], output_names = ["res_y", "res_scan"]} {
  %0 = memref.load %arg0[] : memref<i64>
  %1 = arith.index_cast %0 : i64 to index
  %2 = memref.alloc(%1) {alignment = 16 : i64} : memref<?xmemref<1xf32>>
  %3 = memref.alloc() : memref<i1>
  %4 = memref.load %arg1[] : memref<i1>
  memref.store %4, %3[] : memref<i1>
  %5 = memref.load %arg0[] : memref<i64>
  %6 = arith.index_cast %5 : i64 to index
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  scf.for %arg3 = %c0 to %6 step %c1 {
    %8 = memref.load %3[] : memref<i1>
    scf.if %8 {
      %9 = arith.index_cast %arg3 : index to i64
      %10 = memref.alloc() : memref<i64>
      memref.store %9, %10[] : memref<i64>
      memref.dealloc %10 : memref<i64>
      %11 = "krnl.global"() {name = "constant_0", shape = [5], value = dense<[1.000000e+00, 2.000000e+00, 3.000000e+00, 4.000000e+00, 5.000000e+00]> : tensor<5xf32>} : () -> memref<5xf32>
      %12 = memref.alloc() {alignment = 16 : i64} : memref<1xf32>
      %c0_2 = arith.constant 0 : index
      %c1_3 = arith.constant 1 : index
      %c1_4 = arith.constant 1 : index
      scf.for %arg4 = %c0_2 to %c1_3 step %c1_4 {
        %14 = memref.load %11[%arg4] : memref<5xf32>
        memref.store %14, %12[%arg4] : memref<1xf32>
      }
      %13 = memref.load %arg1[] : memref<i1>
      memref.store %13, %3[] : memref<i1>
      memref.store %12, %2[%arg3] : memref<?xmemref<1xf32>>
      **_memref.dealloc %12 : memref<1xf32>_**
    }
  }
  memref.dealloc %3 : memref<i1>
  %7 = memref.alloc(%1) {alignment = 16 : i64} : memref<?x1xf32>
  %c0_0 = arith.constant 0 : index
  %c1_1 = arith.constant 1 : index
  scf.for %arg3 = %c0_0 to %6 step %c1_1 {
    **_%8 = memref.load %2[%arg3] : memref<?xmemref<1xf32>>_**
    %c0_2 = arith.constant 0 : index
    %c1_3 = arith.constant 1 : index
    %c1_4 = arith.constant 1 : index
    scf.for %arg4 = %c0_2 to %c1_3 step %c1_4 {
      %9 = memref.load %8[%arg4] : memref<1xf32>
      memref.store %9, %7[%arg3, %arg4] : memref<?x1xf32>
    }
  }
  **_memref.dealloc %2 : memref<?xmemref<1xf32>>_**
  return %arg2, %7 : memref<1xf32>, memref<?x1xf32>
}

**Comment by etiotto** [comment]
Reduced test (memreftest1.mlir):
```
func @allocate() -> memref<10xmemref<2xi32>> {
  %outer_alloc = memref.alloc() : memref<10xmemref<2xi32>> 
  %zero = arith.constant 0 : index
  %ten = arith.constant 10 : index
  %one = arith.constant 1 : index
  scf.for %idx = %zero to %ten step %one {
    %inner_alloc = memref.alloc() : memref<2xi32> 
    memref.store %inner_alloc, %outer_alloc[%idx] :  memref<10xmemref<2xi32>> 
  }
  return %outer_alloc : memref<10xmemref<2xi32>> 
} 
```

**Comment by chentong319** [comment]
The reduced test case looks good.
