### ISSUE TITLE
ssd-10 model returns tensors with -1 elements

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#1270]
# Description

After calling `run_main_graph()` on the [ssd-10](https://github.com/onnx/models/blob/main/vision/object_detection_segmentation/ssd/model/ssd-10.onnx) model, the expected number of tensors (3) are returned in the output TensorList. However iterating over the returned tensors and calling `omTensorGetNumElems()` returns -1 for each instead of the expected values (800, 200, and 200 respectively).

# Notes: 
* I don't see this behavior when I try on the [mnist-8](https://github.com/onnx/models/blob/main/vision/classification/mnist/model/mnist-8.onnx) model
* We build onnx-mlir as a Release build with NNPA accelerator enabled

**Comment by AlexandreEichenberger** [comment]
@cjvolzka Can you provide us with a link to the code needed to reproduce the issue, thanks

**Comment by cjvolzka** [comment]
I lost track of this over time. I don't have a C++ client I can easily share that shows the `omTensorGetNumElems()` returning `-1`. I whipped up a quick Python client that fails for what I'm assuming is the same root cause based on the error.

```
import json
import os
import numpy
import sys
from PyRuntime import ExecutionSession

model_lib = sys.argv[1]
if not os.path.exists(model_lib):
    raise FileNotFoundError('model lib "' + model_lib + '" was not found.')
session = ExecutionSession(model_lib)
print("input signature: " + session.input_signature())

input_dims = json.loads(session.input_signature())[0]["dims"]
numpy.random.seed(2)
input_data = numpy.random.rand(*input_dims).astype('float32')
outputs = session.run(input_data)
print(outputs)
```

It can be run with python 3.8 using
```
input signature: [    { "type" : "f32" , "dims" : [1 , 3 , 1200 , 1200] , "name" : "image" }

]
Traceback (most recent call last):
  File "sig_client.py", line 16, in <module>
    outputs = session.run(input_data)
ValueError: negative dimensions are not allowed
```

**Comment by AlexandreEichenberger** [comment]
You are missing a step. Look at our example https://github.com/onnx/onnx-mlir/blob/main/docs/mnist_example/mnist.py explained here https://github.com/onnx/onnx-mlir/blob/main/docs/mnist_example/README.md#write-a-python-driver-code

Maybe we could add a warning code if we are not passed a list of tensor. Same for the output, its a list of tensors.

you need this `outputs = session.run([input])`

**Comment by AlexandreEichenberger** [comment]
I am thinking that we could add in the executionSession in C++ and in Python a "verify input" entry point. 

The function would give the input tensor list, and the code would validate it with the json signature. The good part of this is that the user could call this the first time, or when it aborts on an exception (note that python does not support exceptions yet, though the C++ does. I should add exceptions from the compiler and the execution session of onnx-mlir into the python module).

That approach is lacking support for the bare metal C interface. Though we could also compile the check into the entry point itself, it would have the drawback to add overhead each time an inference is invoked... which I don't like too much. 

What do you think @tungld

**Comment by AlexandreEichenberger** [comment]
@cjvolzka Please try to add the one liner fix in #1482 to see if you get a more meaningful error message in your "wrong" code. We could keep it if we correctly assume that no model has zero inputs... I can make a better assert by checking that when zero inputs are given, that the signature indeed indicate that there are none if you feel that this is needed.

**Comment by cjvolzka** [comment]
> you need this outputs = session.run([input])

I'll update my client, but it currently doesn't seem to matter when the input takes a single tensor. It's not uncommon in python, if a method expects a list and you give it only an element, for the method itself to just wrap it in a list for you. I don't know if that's whats happening here, but I can use the original client to run the mnist-8.onnx and it didn't blow up.

Regardless I updated the client to do `outputs = session.run([input])` and I get the same error:
```
    output_tensors = session.run([input_data])
ValueError: negative dimensions are not allowed
```

**Comment by AlexandreEichenberger** [comment]
I verified with our Mnist example that either the `[input]' or 'input' works, as python automatically transforms the scalar into a vector of one element. I think we should encourage our users to use the brakes so that when there are multiple inputs, it is already there.

And with the new code, `[]` result in an error, but that should be a rare case. Nevertheless, I believe we should consider a input shape verifier, looking for @tungld 's input (or any other folks that are interested in this) on this one.

**Comment by AlexandreEichenberger** [comment]
Could you printf also `session.input_signature())[0]["dims"]`

**Comment by cjvolzka** [comment]
I'll probably continuously tweak this client for reporting issues. I actually used a newer version of it in a different issue just a little while ago. The current iteration now already prints that as `input_dims`. 

```
input signature:  [{'type': 'f32', 'dims': [1, 3, 1200, 1200], 'name': 'image'}]
output signature: [{'type': 'f32', 'dims': [1, -1, 4], 'name': 'bboxes'}, {'type': 'i64', 'dims': [1, -1], 'name': 'labels'}, {'type': 'f32', 'dims': [1, -1], 'name': 'scores'}]
using input_dims: [1, 3, 1200, 1200]
Traceback (most recent call last):
  File "/code/build/cjv-models/simple_client.py", line 25, in <module>
    output_tensors = session.run([input_data])
ValueError: negative dimensions are not allowed
```

**Comment by tungld** [comment]
> That approach is lacking support for the bare metal C interface. Though we could also compile the check into the entry point itself, it would have the drawback to add overhead each time an inference is invoked... which I don't like too much.
What do you think @tungld

I have a PR #1472 to verify the input tensors wherein a bare metal C function is introduced. So we can have two options:
1. Provide C++ and Java wrapper for the C function so that users will call them whenever they want.
2. Call the C function directly inside the entry point and the verification will be called everytime the entry point is called. 

I am using Option 2 in #1472, but it seems its not Alex's preference :). I could disable this verification call if we choose Option 1.

**Comment by gongsu832** [comment]
I would suggest a 1+2 => 3rd option, have the verification function in case the user wants to call it him/herself for whatever purpose, and our entry points should always call the verification function to make sure the inputs are correctly shaped.

**Comment by tungld** [comment]
About this issue `ValueError: negative dimensions are not allowed`, it did not seem to be related to inputs passing to the model. It seemed the model ran for a while and failed. `ValueError` is like that a MLIR value for some operation was invalid.
```
Traceback (most recent call last):
  File "sig_client.py", line 16, in <module>
    outputs = session.run(input_data)
ValueError: negative dimensions are not allowed
```

**Comment by tungld** [comment]
I narrowed down this issue. This model ran successfully until we extract shape information from the returned OMTensors. The returned OMTensors had wrong shape, so `omTensorGetShape` returned negative values and pybind11 failed to construct a python array. `omTensorGetNumElems()` would return a negative value too. I seemed there was an error in transmitting dimension sizes from MemRef to OMTensor.

The output signature of this model is:
```
output signature: [{'type': 'f32', 'dims': [1, -1, 4], 'name': 'bboxes'}, {'type': 'i64', 'dims': [1, -1], 'name': 'labels'}, {'type': 'f32', 'dims': [1, -1], 'name': 'scores'}]
```
Let's take the first returned tensor as an example, that is [1, -1, 4]. Though its second dimension is unknown at compile time, the dimension must be known at runtime. But, for this model, somehow, the shape of the first returned OMTensor is still [1, -1, 4].

It's still a mystery to me why this happened. I tested a simple addition whose output shape is unknown at compile time, but we could still get correct shape at runtime.
```mlir
module attributes {llvm.data_layout = "E-m:e-i1:8:16-i8:8:16-i64:64-f128:64-a:8:16-n32:64", llvm.target_triple = "s390x-ibm-linux"} {
  func @main_graph(%arg0: tensor<?x4x5xf32>, %arg1: tensor<?x4x5xf32>) -> tensor<?x4x5xf32> attributes {input_names = ["x", "y"], output_names = ["sum"]} {    %0 = "onnx.Add"(%arg0, %arg1) : (tensor<?x4x5xf32>, tensor<?x4x5xf32>) -> tensor<?x4x5xf32>
    return %0 : tensor<?x4x5xf32>
  }
  "onnx.EntryPoint"() {func = @main_graph} : () -> ()
}
```

**Comment by tungld** [comment]
This is a simple C program to test this model. 
```c
#include "OnnxMlirRuntime.h"
#include <iostream>

extern "C" OMTensorList *run_main_graph(OMTensorList *);
extern "C" OMTensor *omTensorCreateWithOwnership(
    void *, int64_t *, int64_t, OM_DATA_TYPE, int64_t);
extern "C" OMTensorList *omTensorListCreateWithOwnership(
    OMTensor **, int64_t, int64_t);
extern "C" void omTensorListDestroy(OMTensorList *list);
extern "C" OMTensor *omTensorListGetOmtByIndex(OMTensorList *, int64_t);

int main(int argc, char **argv) {
  // Init inputs.
  int64_t shape[4] = {1, 3, 1200, 1200};
  int64_t rank = 4;
  int64_t size = 1;
  for (int64_t i = 0; i < rank; ++i)
    size *= shape[i];
  float *data = (float *)malloc(size * sizeof(float));
  for (int64_t i = 0; i < size; ++i)
    data[i] = 1.0;
  OMTensor *tensor =
      omTensorCreateWithOwnership(data, shape, rank, ONNX_TYPE_FLOAT, true);

  int64_t inputNum = 1;
  OMTensor **inputTensors = (OMTensor **)malloc(inputNum * sizeof(OMTensor *));
  inputTensors[0] = tensor;
  OMTensorList *tensorListIn =
      omTensorListCreateWithOwnership(inputTensors, inputNum, true);

  // Call the compiled onnx model function.
  std::cout << "Start computing " << std::endl;
  OMTensorList *tensorListOut = nullptr;
  tensorListOut = run_main_graph(tensorListIn);
  std::cout << "Finish computing " << std::endl;

  OMTensor *out = omTensorListGetOmtByIndex(tensorListOut, 0);
  int64_t outRank = omTensorGetRank(out);
  int64_t *outShape = omTensorGetShape(out);
  std::cout << "First tensor's shape: " << std::endl;
  for (int64_t i = 0; i < outRank; ++i)
    std::cout << "Dim " << i << ": " << outShape[i] << std::endl;

  // Cleanup.
  omTensorListDestroy(tensorListOut);
  omTensorListDestroy(tensorListIn);
  return 0;
}
```

It finished without error but the returned OMTensor's shape was wrong:
```bash
$ g++ test-ssd.cpp ssd-10.so -I/home/tungld/dl/onnx-mlir/include -lcruntime -L/home/tungld/dl/onnx-mlir/build/Debug
/lib
$ ./a.out
Start computing
Finish computing
First tensor's shape:
Dim 0: 1
Dim 1: -1
Dim 2: 4
```

**Comment by tungld** [comment]
I found the root cause for this issue. It happened with ReduceMin. ReduceMin needs an identity value that is positive infinity, however our MathBuilder::posititiveInf returns a wrong value for i32. `std::numeric_limits<uint32_t>::max()` was used which was beyond the range of i32, then MLIR Value became `-1`.

PR #1486 has fixed this issue and I can run ssd-10:
```
$ ONNX_MLIR_HOME=/home/tungld/dl/onnx-mlir/build/Debug python ../utils/RunONNXModel.py ssd-10.onnx --compile-args="-O3 -mcpu=z14" --data-folder=/home/tungld/dl/models/test_data_set_0 --verify=ref
Temporary directory has been created at /tmp/tmpuj204oyc
Reading inputs from /home/tungld/dl/models/test_data_set_0 ...
  - 1st input: [1x3x1200x1200xfloat32]
  done.

Compiling the model ...
  took  40.12681828532368  seconds.

Loading the compiled model ...
  took  0.0003934027627110481  seconds.

Running inference ...
  took  358.3639371888712  seconds.

Reading reference outputs from /home/tungld/dl/models/test_data_set_0 ...
  - 1st output: [1x200x4xfloat32]
  - 2nd output: [1x200xint64]
  - 3rd output: [1x200xfloat32]
  done.

Verifying value of bboxes:[1, 200, 4] using atol=0.01, rtol=0.05 ...
  correct.

Verifying value of labels:[1, 200] using atol=0.01, rtol=0.05 ...
  correct.

Verifying value of scores:[1, 200] using atol=0.01, rtol=0.05 ...
  correct.
```
