### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by wm901115nwpu** [onnx/onnx-mlir#1277]
[202/250] Building CXX object src/Builder/CMakeFiles/OMBuilder.dir/FrontendDialectTransformer.cpp.o
FAILED: src/Builder/CMakeFiles/OMBuilder.dir/FrontendDialectTransformer.cpp.o
/usr/bin/c++ -DONNX_ML=1 -DONNX_NAMESPACE=onnx -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/Users/unicorn/MyProject/llvm-project/llvm/include -I/Users/unicorn/MyProject/llvm-project/build/include -I/Users/unicorn/MyProject/llvm-project/mlir/include -I/Users/unicorn/MyProject/llvm-project/build/tools/mlir/include -I/Users/unicorn/MyProject/onnx-mlir -I/Users/unicorn/MyProject/onnx-mlir/build -I/Users/unicorn/MyProject/onnx-mlir/third_party/onnx -I/Users/unicorn/MyProject/onnx-mlir/build/third_party/onnx -isystem /usr/local/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -DSUPPRESS_THIRD_PARTY_WARNINGS -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk   -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=gnu++14 -MD -MT src/Builder/CMakeFiles/OMBuilder.dir/FrontendDialectTransformer.cpp.o -MF src/Builder/CMakeFiles/OMBuilder.dir/FrontendDialectTransformer.cpp.o.d -o src/Builder/CMakeFiles/OMBuilder.dir/FrontendDialectTransformer.cpp.o -c /Users/unicorn/MyProject/onnx-mlir/src/Builder/FrontendDialectTransformer.cpp
/Users/unicorn/MyProject/onnx-mlir/src/Builder/FrontendDialectTransformer.cpp:326:11: error: no matching function for call to 'makeArrayRef'
          llvm::makeArrayRef(attr.floats().begin(), attr.floats().end()));
          ^~~~~~~~~~~~~~~~~~
/Users/unicorn/MyProject/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:481:15: note: candidate template ignored: could not match 'const T *' against 'google::protobuf::RepeatedField<float>::const_iterator' (aka 'RepeatedIterator<const float>')
  ArrayRef<T> makeArrayRef(const T *data, size_t length) {
              ^
/Users/unicorn/MyProject/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:487:15: note: candidate template ignored: could not match 'const T *' against 'google::protobuf::RepeatedField<float>::const_iterator' (aka 'RepeatedIterator<const float>')
  ArrayRef<T> makeArrayRef(const T *begin, const T *end) {
              ^
/Users/unicorn/MyProject/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:475:15: note: candidate function template not viable: requires single argument 'OneElt', but 2 arguments were provided
  ArrayRef<T> makeArrayRef(const T &OneElt) {
              ^
/Users/unicorn/MyProject/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:493:15: note: candidate function template not viable: requires single argument 'Vec', but 2 arguments were provided
  ArrayRef<T> makeArrayRef(const SmallVectorImpl<T> &Vec) {
              ^
/Users/unicorn/MyProject/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:499:15: note: candidate function template not viable: requires single argument 'Vec', but 2 arguments were provided
  ArrayRef<T> makeArrayRef(const SmallVector<T, N> &Vec) {
              ^
/Users/unicorn/MyProject/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:505:15: note: candidate function template not viable: requires single argument 'Vec', but 2 arguments were provided
  ArrayRef<T> makeArrayRef(const std::vector<T> &Vec) {
              ^
/Users/unicorn/MyProject/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:511:15: note: candidate function template not viable: requires single argument 'Arr', but 2 arguments were provided
  ArrayRef<T> makeArrayRef(const std::array<T, N> &Arr) {
              ^
/Users/unicorn/MyProject/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:516:37: note: candidate function template not viable: requires single argument 'Vec', but 2 arguments were provided
  template <typename T> ArrayRef<T> makeArrayRef(const ArrayRef<T> &Vec) {
                                    ^
/Users/unicorn/MyProject/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:521:38: note: candidate function template not viable: requires single argument 'Vec', but 2 arguments were provided
  template <typename T> ArrayRef<T> &makeArrayRef(ArrayRef<T> &Vec) {

how to solve it!!

**Comment by wm901115nwpu** [comment]
commit a7ac120a9ad784998a5527fc0a71b2d0fd55eccb (HEAD)
Author: Valentin Clement <clementval@gmail.com>
Date:   Fri Feb 25 21:05:09 2022 +0100

    [flang] Lower logical comparison and logical operations

same error

**Comment by AlexandreEichenberger** [comment]
You could consider using one of the docker images if building LLVM & onnx-mlir from scratch does not work for you.

**Comment by wm901115nwpu** [comment]
yes, I pip install onnx 1.11

**Comment by gongsu832** [comment]
You need to install the onnx under third_party/onnx.

**Comment by wm901115nwpu** [comment]
ok，I try it

**Comment by wm901115nwpu** [comment]
@gongsu832 it didn't work
