### ISSUE TITLE
Error caused by PR1326

### ISSUE THREAD

**Issue by chentong319** [onnx/onnx-mlir#1344]
@whitneywhtsang 
I got error for models with LoopOp recently. I suspect that the new changes to use new interface is the culprit
[loop-test.txt](https://github.com/onnx/onnx-mlir/files/8490759/loop-test.txt)
I attached a simple test case here. It should be named loop-test.mlir.
I tried this several days ago. I remember I got error complaining something like "env for IndexExpr not defined". At that time, I replaced it with an old version of Loop.cpp and it worked.
Today I got the error 
```
Assertion failed: (originalLoops.size() == ubs.size() && "expected same rank"), function iterateIE, file /Users/tongchen/Projects/onnx-mlir/src/Dialect/Krnl/DialectBuilder.cpp, line 98.
Abort trap: 6
```
Same error are seen on the important medical models, which was compiled correctly after my krnl.region PR#1304.

**Comment by AlexandreEichenberger** [comment]
@chentong319 Is the test for this loop case not yet in the current CIs?

**Comment by whitneywhtsang** [comment]
@chentong319 Thanks for reporting, I will find the PR that causes the failure and revert it first.
