### ISSUE TITLE
Einsum support via Decomposition

### ISSUE THREAD

**Issue by philass** [onnx/onnx-mlir#1367]
I'm considering implementing EinSum support at the ONNX decomposition stage.

More specifically breaking it into a series of matrix multiplications, reduceSums, and other operators depending on the input string.

Would you guys accept such a contribution?

**Comment by AlexandreEichenberger** [comment]
That would be perfectly acceptable for a reference implementation. 

If you implement EinSum in a series of ONNX ops, please add a lit test to verify that it works as advertised.

I just found that we have backend tests for Einsum that are currently not enabled, please look in the subdirectory `onnx-mlir/third_party/onnx/onnx/backend/test/case/node` to locate the Einsum specific tests to be added in `test/backend/inference_backend.py`. 

Feel free to proceed with small PRs that might be easier to review than one large one.
