### ISSUE TITLE
Upgrade to Opset-14

### ISSUE THREAD

**Issue by philass** [onnx/onnx-mlir#1369]
I was curious about what it would take for me to move the project to opset 14.

From looking through the changes in the ONNX changelog it seems that there are 12 ops that modified and 2 ops that are added

Below are ALL the changes in opset 14
# Ops that added more types
- Add:  Extend supported types to include uint8, int8, uint16, and int16
- Sub:  Extend supported types to include uint8, int8, uint16, and int16
- Div:  Extend supported types to include uint8, int8, uint16, and int16
- Mul:  Extend supported types to include uint8, int8, uint16, and int16
- CumSum:  Adds support for tensor(float16), (bfloat16)
- Relu: Adds support for tensor(int32), tensor(int8), tensor(int16), tensor(int64),
-  Identity: addition of the types seq(tensor(uint8)), seq(tensor(uint16)), seq(tensor(uint32)), seq(tensor(uint64)), seq(tensor(int8)), seq(tensor(int16)), seq(tensor(int32)), seq(tensor(int64)), seq(tensor(float16)), seq(tensor(float)), seq(tensor(double)), seq(tensor(string)), seq(tensor(bool)), seq(tensor(complex64)), seq(tensor(complex128))

# Ops that added attributes
- GRU: Addition of layout attribute
- LSTM: Addition of layout attribute
- RNN: Addition of layout attribute
- Reshape: Addition of allowzero attribute

# Ops with more involved changes
- BatchNormalization: 
  - Addition of training_mode attribute
  - Removal of mean, var return values (changes from 5 return types to 3)
  -  Add support for float16, bfloat16

# New Ops
- HardSwish
- Trilu

-----

My interest is in having opset 14 plumbed through to the ONNX Dialect level. I do not have familiarity with the other parts of the codebase (KRNL, and so on) and its not something the project I'm working depends on. However I wouldn't like to start this effort without considering what would actually be needed to get a change like this landed. My optimistic viewpoint is that there is only one breaking change which is in batchnormalization.

Would it be sufficient to get these change to the ONNX Dialect level to get this landed?

Also I see that there is some brief discussion on https://github.com/onnx/onnx-mlir/issues/1201, with requests for contributions. I was hoping that maybe a more realistic piece of work for me to land would be upgrading to 14 instead of 16.

**Comment by AlexandreEichenberger** [comment]
@philass In our group, Tong (@chentong319) is currently working on upgrading the opset to opset 16. When we migrate up, we typically start supporting all our current ops (including the currently supported op whose semantic is changing with the new versions), and then add support for new op on an as needed basis (typically driven by models of importance to clients). I am sure that Tong would welcome help.

**Comment by chentong319** [comment]
@philass I like your summary of changes in onnx with respect to onnx-mlir. Could we do that for onnx v1.11.0? Can we merge this issue with Issue #1201? 
I am working on moving the third_party/onnx to v1.11.0.and will list the remaining work items in that thread. The work items are mainly in two categories: 1. totally new operations.  2. existing operations with incompatible interface or semantics changes. In my first PR, I will update those operations to the new onset if they requires no change inside onnx-mlir (except the change of ONNXOps.td.inc). This the common case for additional types.
