### ISSUE TITLE
Question: How to convert mlir::Value from `memref` to `tensor`?

### ISSUE THREAD

**Issue by vasantha-helprack** [onnx/onnx-mlir#1377]
So far, I've tried `.cast<TensorType>` and looks like that is wrong. Can you please point me to a function or what files I can use as reference to get an idea if I have to implement this myself?

**Comment by philass** [comment]
`getBroadCastRankedType` in `ONNXOpHelpers.cpp` is a good place to look.

Specificall these lines
```cpp
    elementType = type1.cast<MemRefType>().getElementType();
    RankedTensorType ty1 =
        RankedTensorType::get(type1.cast<MemRefType>().getShape(), elementType);
```

**Comment by vasantha-helprack** [comment]
@philass, thanks for this, but I'm looking for something different. There is a method `matchAndRewrite` when implementing a conversion from one dialect to another,

The signature looks like this:
```
LogicalResult matchAndRewrite(Operation *op, ArrayRef<Value> operands, ConversionPatternRewriter &rewriter);
```

I want to access `llvm::dyn_cast<ONNXSqrtOp>(op).X()` (first operand) which has a different type than `operands[0]` (also first argument). Both are of type `mlir::Value`.

I want to convert `operands[0]` to the type of `op.X()` and I'm a bit stuck on this.

**Comment by chentong319** [comment]
I guess your question may be related to type converter for a conversion pass.

**Comment by tungld** [comment]
When we convert an ONNX op to Krnl, type will be converted from TensorType (used in ONNX) to MemRefType (used in Krnl) and buffers are allocated for MemRefs, I wonder why you need to convert back MemRefType to TensorType.

>llvm::dyn_cast<ONNXSqrtOp>(op).X() (first operand) has a different type than operands[0] (also first argument). Both are of type mlir::Value.

`op` is the operation before conversion, so its `X()` value would still have type of TensorType, while `operands` are **rewritten** values and they are converted to MemRefType by the previous conversion. I recommend to use operand adapter if you need to obtain values by name: e.g. `ONNXSqrtOpAdaptor operandAdaptor(operands);`
