### ISSUE TITLE
Failure codes for run_main_graph

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#1417]
Currently, we have no way to recover from an error in `run_main_graph`. 

So when an application calls `run_main_graph`, the call either succeeds or it abort the program. That may not be the most friendly behavior.

The function `run_main_graph` returns an `OMTensorList`, so it is not easy to add an `int` return code. However, we can easily repurpose some data inside the `OMTensorList` to hold an error code. For example, the `_owning` is declared as an `int64_t` but really need only 1 bit. So one could easily hide in the data structure an error code. We could then add a new call 'OMfailure(OMTensorList *list)` which returns the error code associated with the list. We can also add an "internal" function that sets the error code. 

Does that sounds reasonable? This feature would not break backward compatibility, except for the fact that with this new approach, failures would no longer results in asserts.

Initially, we could have an error for "zdnn mismatch"; midterms we could also have errors for failure to malloc, for example, or input mismatch.

**Comment by gongsu832** [comment]
In the C world for a function that returns a pointer, the common way for error reporting is to return NULL and set the thread-local global `errno`.

**Comment by AlexandreEichenberger** [comment]
Idea is that `run_main_graph` would return NULL (normally the address of the output tensor list) as well as set the thread-private errno. Here are possible uses of existing errno return values (posix). Several may fit the type of errors that we may want to return. The value that seems to fit best is indicated with a star. 

There are discussion if returning ERRNO is appropriate or if a custom variable with custom values is more appropriate or not.
https://stackoverflow.com/questions/11699596/how-to-set-errno-value

run out of memory:

ENOBUFS  No buffer space available (POSIX.1 (XSI STREAMS option)).
* ENOMEM Not enough space/cannot allocate memory (POSIX.1-2001).

libzdnn incompatible (typically mean that the compile version and the hardware version of the zdnn/NNPA are not compatible)

ELIBACC  Cannot access a needed shared library.
ENODEV No such device (POSIX.1-2001).
ENOTSUP  Operation not supported (POSIX.1-2001).
* EPERM  Operation not permitted (POSIX.1-2001).

input parameter mismatch between compiled model and runtime provided parameter list

E2BIG  Argument list too long (POSIX.1-2001).
* EDOM   Mathematics argument out of domain of function (POSIX.1   C99).

**Comment by AlexandreEichenberger** [comment]
I asked for feedback on applicability to zos. How about Window @sstamenova ?

**Comment by gongsu832** [comment]
z/OS errno.h defined errors can be found in https://www-40.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R5sc147314/$file/bpxbd00_v2r5.pdf

Windows errno.h defined errors can be found in https://docs.microsoft.com/en-us/cpp/c-runtime-library/errno-constants?view=msvc-170

**Comment by AlexandreEichenberger** [comment]
first version in https://github.com/onnx/onnx-mlir/pull/1428 which was just merged with master. Follow up will clean up the C++/Pyhton interface and document the feature.
