### ISSUE TITLE
Segmentation fault when using _mlir_ciface_main_graph()

### ISSUE THREAD

**Issue by Matsi13** [onnx/onnx-mlir#1444]
In the folder "onnx-mlir/docs/doc_example", I generated add.so from add.onnx, and linked it with add.cpp. . The instructions are as follows: 
python gen_add_onnx.py
onnx-mlir add.onnx
g++ --std=c++11 -O3 add.cpp ./add.so -o add -I $ONNX_MLIR_INCLUDE
./add
Then I got the error:"Segmentation fault (core dumped)". I saw a earlier issue about that, but I clone the project long after the bug was fixed.
[add.txt](https://github.com/onnx/onnx-mlir/files/8715655/add.txt)

**Comment by tungld** [comment]
It is not recommended to directly call `_mlir_ciface_main_graph`. The recommended way is via documented apis [here](http://onnx.ai/onnx-mlir/doxygen_html/OnnxMlirRuntime/index.html), e.g. https://github.com/onnx/onnx-mlir/tree/main/docs/mnist_example

Your way of using `_mlir_ciface_main_graph` was wrong. Its arguments should be pointers, and the first argument (not the last one) is the output. So you should instead use:
```C
extern "C" void _mlir_ciface_main_graph(MemRefDescriptor<float,2> *output, MemRefDescriptor<float,2> *input1, MemRefDescriptor<float,2> *input2);
...
_mlir_ciface_main_graph(&output, &input1, &input2);
```
The result should be obtained from `output` too:
```C
cout << output.allocated[i];
```

**Comment by Matsi13** [comment]
Thank you for your help! It's so kind of you to offer to help!&nbsp;&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tung D. ***@***.***&gt;; 
发送时间: 2022年5月19日(星期四) 下午2:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [onnx/onnx-mlir] Segmentation fault when using _mlir_ciface_main_graph() (Issue #1444)





 
It is not recommended to directly call _mlir_ciface_main_graph. The recommended way is via documented apis here, e.g. https://github.com/onnx/onnx-mlir/tree/main/docs/mnist_example
 
Your way of using _mlir_ciface_main_graph was wrong. Its arguments should be pointers, and the first argument (not the last one) is the output. So you should instead use:
 extern "C" void _mlir_ciface_main_graph(MemRefDescriptor<float,2&gt; *output, MemRefDescriptor<float,2&gt; *input1, MemRefDescriptor<float,2&gt; *input2); ... _mlir_ciface_main_graph(&amp;output, &amp;input1, &amp;input2);
 
The result should be obtained from output too:
 cout << output.allocated[i];
