### ISSUE TITLE
Discussion for `onnx-mlir --version`

### ISSUE THREAD

**Issue by whitneywhtsang** [onnx/onnx-mlir#1460]
#### Background
The current output from `onnx-mlir --version` only contains LLVM info, and we want to add onnx-mlir related version info.
```
> ./Debug/bin/onnx-mlir --version
LLVM (http://llvm.org/):
  LLVM version 15.0.0git
  Optimized build with assertions.
  Default target: powerpc64le-unknown-linux-gnu
  Host CPU: pwr8
```

#### Proposed New Outputs
```
> ./Debug/bin/onnx-mlir --version
onnx-mlir version 0.3.0, onnx version 1.11.0 (git@github.com:onnx/onnx-mlir.git 108c53c61c23b2ec19035672d9cd66ddfc78a910)
  DEBUG build with assertions.
  Default target: powerpc64le-unknown-linux-gnu
  Host CPU: pwr8
  LLVM version 15.0.0git (git@github.com:llvm/llvm-project.git 9778ec057cf4214241e4a970f3e764e3cf150181)
```

The implementation is drafted in https://github.com/onnx/onnx-mlir/pull/1440.

Note: The output of (repo hash) can be controlled by the existing LLVM cmake variable `LLVM_APPEND_VC_REV`.
When `LLVM_APPEND_VC_REV` is `OFF`:
```
> ./Debug/bin/onnx-mlir --version
onnx-mlir version 0.3.0, onnx version 1.11.0
  DEBUG build with assertions.
  Default target: powerpc64le-unknown-linux-gnu
  Host CPU: pwr8
  LLVM version 15.0.0git
```

#### Feedbacks are welcome.

**Comment by etiotto** [comment]
I like this proposal: is good to show the onnx-mlir version, along with the ONNX and LLVM version we used to build the code. Also the proposal does not require us to introduce new cmake options, as it leverages the existing LLVM_APPEND_VC_REV cmake variable.  I do not have a particular preference regarding the LLVM_APPEND_VC_REV default we should use.

**Comment by whitneywhtsang** [comment]
Thanks for your comment @etiotto .

> I do not have a particular preference regarding the LLVM_APPEND_VC_REV default we should use.

`LLVM_APPEND_VC_REV` is default to `ON` in LLVM.
