### ISSUE TITLE
Assertion on unranked tensors in code generated from Rewrite.td

### ISSUE THREAD

**Issue by NathanielMcVicar** [onnx/onnx-mlir#1461]
Rewrite.td has the following check (and a similar `HasRankOf`):
```
// Check the rank of a value is greater than a given integer.
class HasRankGT<int rank> :
  Constraint<CPred<"$0.getType().isa<ShapedType>() && "
                   "$0.getType().cast<ShapedType>().getRank() > " # rank>>;
```

Code generated from this will assert on unranked tensors because getRank() should only be called on ranked tensors. What's not clear to me is if rewrite patterns that use HasRankGT should generate those assertions, because they should never be run on operators with unranked inputs, or if they should simply fail to match (in other words, add `"$0.getType().isa<ShapedType>().hasRank() && "` to the check before `getRank()`). In particular we ran into this issue with the `SwapReshapeMatMulPattern` rule. Thanks!

**Comment by llehtahw** [comment]
In my opinion, failing to match is OK. And this way respects the semantics of constraints as `HasRankGT` and `HasRankOf`.

I've created #1456 to fix

**Comment by tungld** [comment]
Yes, we should check `"$0.getType().isa<ShapedType>().hasRank()` before `getRank()`. Thanks @llehtahw for the fix!

**Comment by AlexandreEichenberger** [comment]
just merged the PR, please close if this works for you @NathanielMcVicar
