### ISSUE TITLE
Name of the published libraries

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#1478]
I wonder if the name of our runtime library is not too generic to be integrated with multiple libs in the traditional system wide libs.

Maybe we should have something more onnx-mlir-y?

We don't have too much of an issue as long as we statically link libcruntime inside of our model, but I recall that on some systems, they want to use dynamic libs also.

@gongsu832 any comments?

**Comment by gongsu832** [comment]
We could add 'OM' to all the runtime libraries like we do for the compiler libraries, e.g., `libcruntime` -> `libOMcruntime`, etc. The concern is this will likely break some existing apps so we need to communicate with the dev folks.

**Comment by AlexandreEichenberger** [comment]
yes, absolutely we should consult with them. We might still be in the grace period... Watson AI Studio control everything from their app, and I believe the release just done by @cjvolzka is for LoZ which does static linking.... So we could change it I believe.

Also, as I see possibly more folks using the PyExecutionSessiona and the C++ Execution session, do you think we should consider adding these interface to the officially exported interfaces with according libraries?

**Comment by gongsu832** [comment]
> Also, as I see possibly more folks using the PyExecutionSessiona and the C++ Execution session, do you think we should consider adding these interface to the officially exported interfaces with according libraries?

Not sure I understand. The API for `PyExecutionSession` is officially published at http://onnx.ai/onnx-mlir/UsingPyRuntime.html

**Comment by AlexandreEichenberger** [comment]
got it, so we have the Java, Python, C, not the C++ ExecutionSession (which might be ok).

Somewhat unrelated, is it an issue that our Debug/lib dir has so many libs
```
root@1250b049ac2b:~/onnx-mlir/build# ls Debug/lib/
PyRuntime.cpython-38-x86_64-linux-gnu.so  libOMEnableMemoryPool.a            libOMONNXToZHigh.a                     libOMZLowOps.a
javaruntime.jar                           libOMFoldStdAlloc.a                libOMOpTransform.a                     libOMZLowRewrite.a
libAccelerator.a                          libOMHasOnnxSubgraphOpInterface.a  libOMOptimizeMemoryPools.a             libOMZLowToLLVM.a
libCompilerOptions.a                      libOMInstrumentONNX.a              libOMResultTypeInferenceOpInterface.a  libOnnxMlirCompiler.a
libCompilerPasses.a                       libOMInstrumentZHigh.a             libOMRewriteONNXForZHigh.a             libRuntimeNNPA.a
libCompilerUtils.a                        libOMKrnlOps.a                     libOMSeqToMemref.a                     libbenchmark.a
libDiagnostic.a                           libOMKrnlToAffine.a                libOMShapeInference.a                  libbenchmark_main.a
libExecutionSession.a                     libOMKrnlToLLVM.a                  libOMShapeInferenceOpInterface.a       libcruntime.a
libInitAccelerators.a                     libOMLayoutHelper.a                libOMSpecializedKernelOpInterface.a    libjniruntime.a
libModelLib.a                             libOMLowerKrnlRegion.a             libOMStickify.a                        libonnx.a
libNNPAAccel.a                            libOMLowerKrnlShape.a              libOMSupport.a                         libonnx_proto.a
libNNPACompilerUtils.a                    libOMMlirDialects.a                libOMTensorUtils.a                     libonnxifi.so
libOMBuilder.a                            libOMNNPASupport.a                 libOMVersion.a                         libonnxifi_dummy.so
libOMBundleMemoryPools.a                  libOMONNXOps.a                     libOMZHighConstPropagation.a           libonnxifi_loader.a
libOMConstPropHelper.a                    libOMONNXPreKrnlVerifyONNX.a       libOMZHighLayoutPropagation.a          librapidcheck.a
libOMDisconnectKrnlDimFromAlloc.a         libOMONNXRewrite.a                 libOMZHighOps.a
libOMElideConstants.a                     libOMONNXToKrnl.a                  libOMZHighToZLow.a
libOMElideKrnlGlobalConstants.a           libOMONNXToTOSA.a                  libOMZLowDummyOpForMultiDeref.a
```

If we were to export it, would we reduce the number by combining them in a few packages?

**Comment by gongsu832** [comment]
`PyRuntime.cpython-38-x86_64-linux-gnu.so` should also be named `libOMPyRuntime.cpython-38-x86_64-linux-gnu.so`. In fact, the default generated `model.so` should really be named `libmodel.so` but I think that may break more things.

As for having a lot of libraries, I'm not sure if this is common for compiler related stuff, seeing that llvm-project also produces a lot of libraries. It's not necessarily a problem if there is legitimate reason for this. For example, if for normal usage you typically only link against a few of these libraries, then it makes sense to keep them separate. However, if you typically link against almost all of them, then it makes much less sense to keep them separate.

**Comment by AlexandreEichenberger** [comment]
Mostly use now "OM" as a prefix for internal libraries.
