### ISSUE TITLE
Check of runtime input signature

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#1506]
@cjvolzka asked what check we do when the signature reports a runtime var. Right now in the code I see in KrnlEntryPoint, line 501:

```c++
        if (dim == -1)
          continue; // do not verify dynamic dimensions.
```

I think we could reasonably check for a non-negative value, i.e. return an error if the runtime dim is strictly smaller than 0.

Sounds reasonable?

**Comment by cjvolzka** [comment]
> I think we could reasonably check for a non-negative value, i.e. return an error if the runtime dim is strictly smaller than 0.

A couple of follow up thoughts:
* Should we return an error if the values is less than 1 instead of 0? Is there any case where a dimension size of zero makes sense at runtime?
* Do we need any special handling to confirm the shape is integers. This probably isn't an issue for strictly typed languages like C/C++/Java. However Python could define a shape like `[1.1, 2, 3]`. In that scenario would the verifier catch it, something implicitly/explicitly down casts it, or we blow up?

**Comment by AlexandreEichenberger** [comment]
> Do we need any special handling to confirm the shape is integers. This probably isn't an issue for strictly typed languages like C/C++/Java. However Python could define a shape like [1.1, 2, 3]. In that scenario would the verifier catch it, something implicitly/explicitly down casts it, or we blow up?

In the interface with python, I don't think the sizes can be anything but ints. See https://github.com/onnx/onnx-mlir/tree/main/docs/mnist_example.

```python
# Create an input arbitrarily filled of 1.0 values (file has the actual values).
input = np.full((1, 1, 28, 28), 1, np.dtype(np.float32))
# Run the model. It is best to always use the [] around the inputs as the inputs
# are an vector of numpy arrays.
outputs = session.run([input])
```

Since the vector input is created with a np.xxx command, it will have int sizes.

**Comment by tungld** [comment]
> Should we return an error if the values is less than 1 instead of 0? Is there any case where a dimension size of zero makes sense at runtime?

Dimension size of 0 (e.g. tensor<0xf32>) represents a scalar value in both ONNX and MLIR. E.g., in ONNX: https://github.com/onnx/onnx/blob/main/docs/IR.md#tensor-definition.

**Comment by tungld** [comment]
Implemented this check in https://github.com/onnx/onnx-mlir/pull/1508. Closing ..
