### ISSUE TITLE
emitError with no action

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#151]
@tungld 

in the LSTM code, I see a lot of emitError without actions. That is potentially a problem. In general, if it is due to error from user, we should give a message; and if its an error from the implementation, we can emit a message and then assert.
```
template <>
LstmState allocAndInitializeStates<ONNXLSTMOp, LstmState>(
    ConversionPatternRewriter &rewriter, Location loc, ONNXLSTMOp *op,
    OperandAdaptor<ONNXLSTMOp> operandAdaptor) {
  LstmState state;

  // Insert allocation and deallocation for the results of this operation.
  if (!isNoneType(op->Y())) {
    auto yMemRefType = convertToMemRefType(op->Y().getType());
    if (hasAllConstantDimensions(yMemRefType))
      state.allH = insertAllocAndDealloc(yMemRefType, loc, rewriter,
          checkInsertDealloc(op->getOperation(), 0));
    else
      emitError(loc, "Unsupported dynamic dimensions.");
  } else {
    state.allH = op->Y();
  }
```

see the emitError. Either the function can return a LogicalResult, or special value such as nullptr. There errors are then is then caught in the caller context. Or you can use an assert and the program will stop

**Comment by tungld** [comment]
@AlexandreEichenberger Thanks for pointing it out! I'll fix this issue.

**Comment by AlexandreEichenberger** [comment]
I actually have a PR with fixes for this, converted them into asserts, see #153 . @tungld Feel free to comment if fixes are appropriate. I explained also in a ErrorHandling doc the policy I used to determine when to use assert vs emitError.
