### ISSUE TITLE
Issue with linking to libprotobuf

### ISSUE THREAD

**Issue by nicholaiTukanov** [onnx/onnx-mlir#1515]
When running `cmake --build .` for installation, I get a ton of errors regarding undefined reference to `google::protobuf`. However, I have used `sudo apt-get install libprotobuf-dev protobuf-compiler` to get the libraries.

Is there a link flag/command that I am missing? I have followed all the commands listed in the installation markdown.

Note: I am running Ubuntu 16.04 on an Intel i7-4770K.

Any help would be appreciated.

**Comment by gongsu832** [comment]
Ubuntu release before Jammy (22.04) does not install a recent enough protobuf that meets the prereq. So if you don't use our docker images, you need to build protobuf yourself.

**Comment by nicholaiTukanov** [comment]
the docker images work perfectly! thank you!
