### ISSUE TITLE
cmake --build on Mac with M1 chip failed with error "ld: symbol(s) not found for architecture arm64"

### ISSUE THREAD

**Issue by Aaron-Hu** [onnx/onnx-mlir#1516]
Build onnx-mlir on my macbook-pro which has M1 chip inside. 
"cmake --build ." will failed with the following error:

ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by AlexandreEichenberger** [comment]
if you use `brew` for the prerequisites, the build works great now for M1 Macs
