### ISSUE TITLE
[NNPA] Accuracy issue on NNPA in Conv2D at C != 1, kH = 1, kW=1

### ISSUE THREAD

**Issue by imaihal** [onnx/onnx-mlir#1517]
See wrong results on NNPA at C(the number of channels)  != 1,  kernel height = 1, and kernel width = 1
No problem on CPU.

<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">

</head>

<body>

N | C | H | W | kH | kW | Result
-- | -- | -- | -- | -- | -- | --
1 | 1 | 32 | 32 | 1 | 1 | OK
1 | 1 | 32 | 32 | 2 | 1 | OK
1 | 1 | 32 | 32 | 1 | 2 | OK
1 | 1 | 32 | 32 | 2 | 2 | OK
1 | 2 | 32 | 32 | 1 | 1 | NG
1 | 2 | 32 | 32 | 2 | 1 | OK
1 | 2 | 32 | 32 | 1 | 2 | OK
1 | 2 | 32 | 32 | 2 | 2 | OK
1 | 3 | 32 | 32 | 1 | 1 | NG
1 | 3 | 32 | 32 | 2 | 1 | OK
1 | 3 | 32 | 32 | 1 | 2 | OK
1 | 3 | 32 | 32 | 2 | 2 | OK
1 | 3 | 32 | 32 | 3 | 1 | OK
2 | 2 | 32 | 32 | 1 | 1 | NG

</body>

</html>

**Comment by imaihal** [comment]
This issue should be fixed by PR https://github.com/onnx/onnx-mlir/pull/1576

**Comment by AlexandreEichenberger** [comment]
Congrats!
