### ISSUE TITLE
ONNX-MLIR exists issues？

### ISSUE THREAD

**Issue by dongbeiwudaxian** [onnx/onnx-mlir#1530]
hahha, sorry to use such an exaggerated title.Iam a freshman, after i run the end to end experiment of onnx-mlir ,  by  --EmitLLVMIR    - Lower the input to LLVM IR (LLVM MLIR dialect). i get llvm ir dialect, how can i convert it to llvm ir? i try use ./mlir-translate --mlir-to-llvmir,but it does not work! so, peaese tell me how to do?

**Comment by vegetablelearning** [comment]
I also encountered this problem. Have you solved it

**Comment by dongbeiwudaxian** [comment]
> If you compile with this option `--preserveLLVMIR` instead, you will get a file with extension `.ll` that is LLVM IR (outside of MLIR).
It has been solved! Thank you very much, brother. I wish you every success in your scientific research

**Comment by vegetablelearning** [comment]
> If you compile with this option `--preserveLLVMIR` instead, you will get a file with extension `.ll` that is LLVM IR (outside of MLIR).

Thank you very much. The problem has been solved perfectly
