### ISSUE TITLE
Error (on MAC) running the image "onnxmlirczar/onnx-mlir" ->. "error while loading shared libraries: libMhloDialect.so.15"

### ISSUE THREAD

**Issue by hongmin1** [onnx/onnx-mlir#1549]
$ docker image ls
REPOSITORY               TAG                     IMAGE ID       CREATED        SIZE
onnxmlirczar/onnx-mlir   latest                  05d162a0ef75   3 days ago     1.3GB

$ docker run 05d162a0ef75
onnx-mlir: error while loading shared libraries: libMhloDialect.so.15git: cannot open shared object file: No such file or directory

**Comment by gongsu832** [comment]
@Connor-XY Third party libraries `libMhloDialect.so` and `libMhloInferShapeEqualityOpInterface.so` built by `third-part/mlir-hlo` are not being installed by `make install`.

**Comment by antoinebrl** [comment]
Hi, I'm having the same issue
```
$ sudo docker image ls
REPOSITORY               TAG          IMAGE ID       CREATED         SIZE
onnxmlirczar/onnx-mlir   latest       82ed1bcba125   3 days ago      1.3GB
$ sudo docker run 82ed1bcba125
onnx-mlir: error while loading shared libraries: libMhloDialect.so.15git: cannot open shared object file: No such file or directory
$ uname -a
Linux 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Connor-XY** [comment]
Hi, we install the necessary shared libraries in this pull request: https://github.com/onnx/onnx-mlir/pull/1548. This problem should be solved after the pull request gets merged into the main branch.

**Comment by gcunhase** [comment]
Also getting the same error. If the fix is in the attached PR, does this mean that we can't do `docker pull onnxmlirczar/onnx-mlir`?

**Comment by gcunhase** [comment]
@Connor-XY what was the fix specifically for this bug? Thanks!

**Comment by Connor-XY** [comment]
In the corresponding CMakeLists.txt, we need to install the required library: https://github.com/onnx/onnx-mlir/pull/1548/files#diff-39f8695851610cfd5065c59ba5d02081f5c57ad8f76dc4a3519957b922e86bc2:~:text=install(TARGETS,)

**Comment by gcunhase** [comment]
@Connor-XY the required library is `MLIRMhloUtils`?

**Comment by AlexandreEichenberger** [comment]
Please try again now that #1548 has been merged. Please close if it works, or report failure so that we know more work needs to be done. Thanks

**Comment by gcunhase** [comment]
The PR worked for me. Thank you!
