### ISSUE TITLE
macOS 12.4

### ISSUE THREAD

**Issue by wm901115nwpu** [onnx/onnx-mlir#1551]
cmake --build build -j 1

[3/30] Building C object src/Runtime/jni/CMakeFiles/jniruntime.dir/jniwrapper.c.o
FAILED: src/Runtime/jni/CMakeFiles/jniruntime.dir/jniwrapper.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/Users/unicorn/MyCodes/llvm-project/llvm/include -I/Users/unicorn/MyCodes/llvm-project/build/include -I/Users/unicorn/MyCodes/llvm-project/mlir/include -I/Users/unicorn/MyCodes/llvm-project/build/tools/mlir/include -I/Users/unicorn/MyCodes/onnx-mlir/include -I/include -I/include/darwin -I/Users/unicorn/MyCodes/onnx-mlir -I/Users/unicorn/MyCodes/onnx-mlir/build -I/Users/unicorn/MyCodes/onnx-mlir/build/src/Runtime/jni/CMakeFiles/javaruntime.dir/native_headers -I/Users/unicorn/MyCodes/onnx-mlir/src/Runtime/jni/headless -fPIC -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -DSUPPRESS_THIRD_PARTY_WARNINGS -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -fPIC   -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -MD -MT src/Runtime/jni/CMakeFiles/jniruntime.dir/jniwrapper.c.o -MF src/Runtime/jni/CMakeFiles/jniruntime.dir/jniwrapper.c.o.d -o src/Runtime/jni/CMakeFiles/jniruntime.dir/jniwrapper.c.o -c /Users/unicorn/MyCodes/onnx-mlir/src/Runtime/jni/jniwrapper.c
In file included from /Users/unicorn/MyCodes/onnx-mlir/src/Runtime/jni/jniwrapper.c:30:
/Users/unicorn/MyCodes/onnx-mlir/build/src/Runtime/jni/CMakeFiles/javaruntime.dir/native_headers/com_ibm_onnxmlir_OMModel.h:2:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.

**Comment by gongsu832** [comment]
You are not setting JAVA_HOME

**Comment by wm901115nwpu** [comment]
ok，I know

**Comment by AlexandreEichenberger** [comment]
@gongsu832 is the setting  of JAVA_HOME documented?

**Comment by gongsu832** [comment]
No. It's only necessary on MacOS. And with PR https://github.com/onnx/onnx-mlir/pull/1552 you don't need to set it on MacOS either.
