### ISSUE TITLE
Is there a way to use PyRuntime on windows?

### ISSUE THREAD

**Issue by vasanthaganeshk** [onnx/onnx-mlir#1568]
In this link: https://github.com/onnx/onnx-mlir/blob/main/docs/UsingPyRuntime.md only `.so` file is mentioned. When I built on windows, I couldn't find an equivalent.

**Comment by sstamenova** [comment]
I think PyRuntime is very close, but not 100% accurately setup on Windows. A good start would be trying to get the `check-onnx-backend` tests running on Windows and addressing any issues there.

**Comment by AlexandreEichenberger** [comment]
@vasanthaganeshk did you get it to work? If so, please let us know how you did it so we may add instructions to our doc

**Comment by vasanthaganeshk** [comment]
@AlexandreEichenberger, sorry about the delay, I'm using a bit older commit but I was able to build `PyRuntime.cp310-win_amd64.pyd` when building with MinGW. Also, closing this issue. Thank you.
