### ISSUE TITLE
Is CUDA inference supported via PyRuntime?

### ISSUE THREAD

**Issue by gcunhase** [onnx/onnx-mlir#1582]
## Steps to reproduce
1. Create docker container for ONNX-MLIR
2. Download model: [resnet50-v1-7](https://github.com/onnx/models/blob/main/vision/classification/resnet/model/resnet50-v1-7.onnx)
3. Compile ONNX to .so:
```bash
python onnx-mlir.py --O3 --EmitLib model.onnx
```
4. Run inference:
```python
import numpy as np
import json
import os
from PyRuntime import ExecutionSession
import time

def process_performance_stats(timestamps, batch_size, mode):
    timestamps_ms = 1000 * timestamps
    throughput_imgps = (1000.0 * batch_size / timestamps_ms).mean()
    stats = {f"throughput_{mode}": throughput_imgps,
             f"latency_{mode}_mean": timestamps_ms.mean(),
             f"latency_{mode}_median": np.median(timestamps_ms),
             }
    for level in [90, 95, 99]:
        stats.update({f"latency_{mode}_{level}": np.percentile(timestamps_ms, level)})

    return stats

def run_inference(model_path):
        # Load the model mnist.so compiled with onnx-mlir.
        session = ExecutionSession(model_path)
        input_sig_json = json.loads(session.input_signature())
        output_sig_json = json.loads(session.output_signature())

        # Create an input arbitrarily filled of 1.0 values (file has the actual values).
        input_dims = input_sig_json[0]["dims"]
        input_dims = [1 if dim == -1 else dim for dim in input_dims]
        input = np.zeros(shape=input_dims, dtype=np.dtype(np.float32))

        # Obtain average latency
        timings = []
        for i in range(10):
            start_time = time.time()
            _ = session.run([input])
            timings.append(time.time() - start_time)
        timings = np.array(timings)
        stats = process_performance_stats(timings, batch_size=input_dims[0], mode="eval")
        print("ONNX-MLIR stats: {}".format(stats))

run_inference("./model.so")
```

## Observed behavior
The current runtime for the ONNX-MLIR `.so` compiled file is 3222.849 ms and for ONNXRT with CUDA backend is 2.548 ms. My hypothesis is that ONNX-MLIR is running inference on CPU. Is there a way to indicate CUDA backend in the `ExecutionSession` call similarly to how ONNXRT can set the provider as `CUDAExecutionProvider`?

## Expected behavior
Faster inference time than ONNXRT.

**Comment by AlexandreEichenberger** [comment]
We do not generate code for GPU at this time and we are not expecting to drive work on GPU for the foreseeable future. We welcome others to contribute GPU support.

We are currently working on accelerating Conv (which are heavily used in resnet). Current implementation is just a functional implementation, thus the difference in execution time.

**Comment by gcunhase** [comment]
Thank you for the clarification, closing this issue.
**Note**: this is related to issue https://github.com/onnx/onnx-mlir/issues/198#issuecomment-1205920849.

**Comment by pfeatherstone** [comment]
Will onnx-mlir ever target NVIDIA GPUs ? 
It would be really cool! You could have a program running models efficiently on NVIDIA GPUs without libcuda, libcudnn or any runtime libraries, just nvidia kernel drivers.
