### ISSUE TITLE
Compile of MLPerf 3D-Unet on BraTS 2019 model 224_224_160_dyanmic_bs.onnx fails with Assertion `!outputShape.hasValue() && "unhandled option in ConvTranspose"' failed

### ISSUE THREAD

**Issue by JonTriebenbach** [onnx/onnx-mlir#1586]
Trying to compile the MLPerf model 224_224_160_dyanmic_bs.onnx fails with the message:
```
onnx-mlir: /onnx-mlir/src/Dialect/ONNX/ONNXOps.cpp:2137: mlir::LogicalResult mlir::ONNXConvTransposeOp::inferShapes(std::function<void(mlir::Region&)>): Assertion `!outputShape.hasValue() && "unhandled option in ConvTranspose"' failed.
```
The model is here:
https://github.com/mlcommons/inference/tree/master/vision/medical_imaging/3d-unet-brats19
https://zenodo.org/record/3928973#.Yu022_HMIYE

The compile was with onnx-mlir version:
```
onnx-mlir version 0.3.0, onnx version 1.11.0 (https://github.com/onnx/onnx-mlir.git 57ca5af90cccdf8a1b0c3aa7426f021845fab544)
  LLVM version 15.0.0git (https://011b0981b5176f024edfd606bf25117b31361fa6@github.ibm.com/compiler/llvm-project.git e829978c1e3b06b4372ba0d01b2d4f4608c59151)
  Optimized build with assertions.
  Default target: s390x-ibm-linux
  Host CPU: z14
```
Please investigate this compile failure. Thanks.

**Comment by imaihal** [comment]
I didn't get this error when using 6fd7f69d4ad0a36f927082832093b8e575635545. It seems shape inference for ConvTransposeOp works now. 
And now I got the same with static model https://github.com/onnx/onnx-mlir/issues/1585
