### ISSUE TITLE
Semantics of ONNXPadConstantValuePad

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#16]
I wonder what is the current semantics of ONNXPadConstantValuePad.

From a test about ONNXPadConstantValuePad here: https://github.com/onnx/onnx-mlir/blob/master/test/mlir/onnx/onnx_shape_inference.mlir#L279
```mlir
func @test_PadConstantValuePad_1(%arg0 : tensor<16x13xf32>) -> tensor<*xf32> {
  %0 = "onnx.PadConstantValuePad"(%arg0) {constant_value = 0.000000e+00 : f32, mode = "constant", pads = [0, 2, 0, 0]} : (tensor<16x13xf32>) -> tensor<*xf32>
  "std.return"(%0) : (tensor<*xf32>) -> ()
}
// CHECK-LABEL: test_PadConstantValuePad_1
// CHECK: [[RES:%.+]] = "onnx.PadConstantValuePad"(%arg0) {constant_value = 0.000000e+00 : f32, mode = "constant", pads = [0, 2, 0, 0]} : (tensor<16x13xf32>) -> tensor<18x13xf32>
// CHECK: return [[RES]] : tensor<18x13xf32>
```

I guess `pads = [0, 2, 0, 0]` was interpreted as `[0, 2]` (first and second elements) are pads for the first dimension and `[0, 0]` (third and fourth elements) are pads for the second dimension.

On the other hand, in Convolution op or MaxPool op, `pads = [0, 2, 0, 0]` means that `[0, 0]` (first and third elements) are pads for the first dimension of the input and `[2, 0]` (second and fourth elements) are pads for the second dimension of the input. More information about pads format for Convolution op is here: https://github.com/onnx/onnx/blob/master/docs/Operators.md#conv

**Comment by tungld** [comment]
@chentong319 any thought on this?

**Comment by chentong319** [comment]
@tungld Thanks to point out. The pad is  [x1_begin, x2_begin...x1_end, x2_end,...]. I will modify the code.

**Comment by tungld** [comment]
@chentong319 Thanks for fixing this issue with PR #27!
We also need to fix this in ONNXPadConstantValuePad's shape inference method. Besides, there is one more issue (#15) which is related to the shape inference.

**Comment by chentong319** [comment]
@tungld I pushed a change for issue #15 and this one.
I changed the test case for max pool. Please check whether the change is correct.
