### ISSUE TITLE
Instrumentation doesn't work (not inserted before op) 

### ISSUE THREAD

**Issue by imaihal** [onnx/onnx-mlir#1600]
I found instrumentation does not work well after this commit 1081a5e8b9a7b7f70fc94ef60e56743afe716265 .

In following example, `krnl.runtime_instrument` should be inserted before and after onnx.Add op as shown in expected results below, but after the commit, inserted only after the op. The command for reproducing this is `onnx-mlir  --printIR --EmitMLIR --instrument-onnx-ops=ALL --InstrumentBeforeOp --InstrumentAfterOp --InstrumentReportTime <following example> `

It seems `instrumentBefore` in this line https://github.com/onnx/onnx-mlir/blob/main/src/Transform/ONNX/InstrumentONNXPass.cpp#L138 is not correct, but I'm still not sure the exact reason. (If I commented out this line, `krnl.runtime_instrument` is inserted also before the op)

Hi, @manbearian 
You are author of this PR https://github.com/onnx/onnx-mlir/pull/1363 . I will continue to investigate this, but can you check this as well ?

```
func @test_instrument_add_onnx(%arg0 : tensor<10x10xf32>, %arg1 : tensor<10x10xf32>) -> tensor<*xf32> {
  %0 = "onnx.Add"(%arg0, %arg1) : (tensor<10x10xf32>, tensor<10x10xf32>) -> tensor<*xf32>
  "std.return"(%0) : (tensor<*xf32>) -> ()
}
```
- Result
```
  func @test_instrument_add_onnx(%arg0: memref<10x10xf32>, %arg1: memref<10x10xf32>) -> memref<10x10xf32> {
    %0 = memref.alloc() {alignment = 16 : i64} : memref<10x10xf32>
    affine.for %arg2 = 0 to 10 {
      affine.for %arg3 = 0 to 10 {
        %1 = affine.load %arg0[%arg2, %arg3] : memref<10x10xf32>
        %2 = affine.load %arg1[%arg2, %arg3] : memref<10x10xf32>
        %3 = arith.addf %1, %2 : f32
        affine.store %3, %0[%arg2, %arg3] : memref<10x10xf32>
      }
    }
    "krnl.runtime_instrument"() {opID = 4712001061299159040 : i64, tag = 14 : i64} : () -> ()
    return %0 : memref<10x10xf32>
  }

```
- Expected result: Insert two `krnl.runtime_instrument` before and after onnx.Add op. 
```
 func @test_instrument_add_onnx(%arg0: memref<10x10xf32>, %arg1: memref<10x10xf32>) -> memref<10x10xf32> {
    "krnl.runtime_instrument"() {opID = 4712001061299159040 : i64, tag = 13 : i64} : () -> ()
    %0 = memref.alloc() {alignment = 16 : i64} : memref<10x10xf32>
    affine.for %arg2 = 0 to 10 {
      affine.for %arg3 = 0 to 10 {
        %1 = affine.load %arg0[%arg2, %arg3] : memref<10x10xf32>
        %2 = affine.load %arg1[%arg2, %arg3] : memref<10x10xf32>
        %3 = arith.addf %1, %2 : f32
        affine.store %3, %0[%arg2, %arg3] : memref<10x10xf32>
      }
    }
    "krnl.runtime_instrument"() {opID = 4712001061299159040 : i64, tag = 14 : i64} : () -> ()
    return %0 : memref<10x10xf32>
  }

```

**Comment by imaihal** [comment]
I think [InstrumentONNXPass.cpp#L72-L75)](https://github.com/onnx/onnx-mlir/blob/main/src/Transform/ONNX/InstrumentONNXPass.cpp#L72-L75) should be updated as follows. I will create PR for this.

```
    this->instrumentBefore = actions & (1 << onnx_mlir::InstrumentBeforeOp);
    this->instrumentAfter = actions & (1 << onnx_mlir::InstrumentAfterOp);
    this->reportTime = actions & (1 << onnx_mlir::InstrumentReportTime);
    this->reportMemory = actions & (1 << onnx_mlir::InstrumentReportMemory);
```

**Comment by manbearian** [comment]
> I think [InstrumentONNXPass.cpp#L72-L75)](https://github.com/onnx/onnx-mlir/blob/main/src/Transform/ONNX/InstrumentONNXPass.cpp#L72-L75) should be updated as follows. I will create PR for this.
> 
> ```
>     this->instrumentBefore = actions & (1 << onnx_mlir::InstrumentBeforeOp);
>     this->instrumentAfter = actions & (1 << onnx_mlir::InstrumentAfterOp);
>     this->reportTime = actions & (1 << onnx_mlir::InstrumentReportTime);
>     this->reportMemory = actions & (1 << onnx_mlir::InstrumentReportMemory);
> ```

Yes, the values in the enum are shift amounts, not the actual bit values.
This is brain-fart on my part when writing the code.

Would be good to add some tests for this to avoid similar bugs/regressions in the future.

**Comment by AlexandreEichenberger** [comment]
> Would be good to add some tests for this to avoid similar bugs/regressions in the future

would a lit test catch this?

**Comment by imaihal** [comment]
@manbearian Thanks for your comments!

@AlexandreEichenberger Yes. The lit test in PR https://github.com/onnx/onnx-mlir/pull/1601 catches this. [The first krnl.runtime_instrument()](https://github.com/onnx/onnx-mlir/pull/1601/files#diff-e6db4e339f9ec9205b00cf4f9649881d551ca101304eaf4b43cb84c1e750da31R9)  is not output in the current main, but will be fixed by PR1601.
