### ISSUE TITLE
`add.onnx.mlir` to `abc.dll` fails on windows

### ISSUE THREAD

**Issue by vasanthaganeshk** [onnx/onnx-mlir#1641]
Commit ID `onnx-mlir`: `1a26cf06239a656e2ab0d8ae8066aa40fb564527`
Platform: Windows
command used: `onnx-mlir.exe add.onnx.mlir`

Input file: `add.onnx.mlir:`
```c++
module {
  func @main_graph(%arg0: tensor<10x10x10xf32>, %arg1: tensor<10x10x10xf32>) -> tensor<10x10x10xf32> {
    %0 = "onnx.Add"(%arg0, %arg1) : (tensor<10x10x10xf32>, tensor<10x10x10xf32>) -> tensor<10x10x10xf32>
    return %0 : tensor<10x10x10xf32>
  }
}
```

Error:
```
add.onnx.mlir:2:3: error: custom op 'func' is unknown (tried 'builtin.func' as well)
  func @main_graph(%arg0: tensor<10x10x10xf32>, %arg1: tensor<10x10x10xf32>) -> tensor<10x10x10xf32> {
  ^
Error can't load file add.onnx.mlir

```

Please let me know if I'm doing something wrong here.

**Comment by AlexandreEichenberger** [comment]
Sorry, you probably lifted the example from our doc, and the MLIR format has changed over time. If I look at an example of our lit test:
```
func.func @test_add_expand_constant_lhs(%arg0: tensor<128x256xf32>) -> (tensor<128x256xf32>) {
  %cst = "onnx.Constant"() {value = dense<[1.0]> : tensor<1xf32>} : () -> tensor<1xf32>
  %0 = "onnx.Add"(%cst, %arg0) : (tensor<1xf32>, tensor<128x256xf32>) -> tensor<128x256xf32>
  return %0 : tensor<128x256xf32>

// CHECK-LABEL:  func.func @test_add_expand_constant_lhs
// ...
}
```

you will see that the approved format is now to add the `func.` qualifier.

Would you mind changing your example, trying it out, and then open a PR with the fix to the documentation? That would be supper appreciated. Tx

**Comment by vasanthaganeshk** [comment]
@AlexandreEichenberger, thank you. Closing this.

**Comment by AlexandreEichenberger** [comment]
thanks
