### ISSUE TITLE
arcfaceresnet100, densenet, and inception-v2-* models fail to compile using maccel=NNPA

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#1649]
When compiling arcfaceresnet100, densenet, or inception-v2-* models using `--EmitLib --O3 --mtriple=s390x-ibm-loz --mcpu=z16 --maccel=NNPA` from the onnx model zoo, I now get the following error:
```
onnx-mlir: /onnx-mlir/src/Accelerators/NNPA/Conversion/ZHighToZLow/ZHighToZLow.cpp:699: virtual mlir::LogicalResult onnx_mlir::zhigh::ZHighToZLowStickifiedConstantOpLowering::matchAndRewrite(mlir::Operation*, llvm::ArrayRef<mlir::Value>, mlir::ConversionPatternRewriter&) const: Assertion `(data.size() == (uint64_t)memRefSizeInBytes) && "The stickied tensor's buffer size and MemRef's size mismatched"' failed.
```

Notes:
* I was using https://github.com/onnx/onnx-mlir/commit/5387f468cefada003186be47cda9dd86f559b17a.
* These models compiled fine last week using https://github.com/onnx/onnx-mlir/commit/1a26cf06239a656e2ab0d8ae8066aa40fb564527.

**Comment by cjvolzka** [comment]
I just tried a build with https://github.com/onnx/onnx-mlir/commit/d0c506951d15f3cc7f9cb2614e3ee19783489b4d and that didn't encounter the issue. Based on the contents of commits sine then, the most likely commit that caused the regression is https://github.com/onnx/onnx-mlir/commit/0755f3f412a219a6290b9557e7f308ff20834728 from https://github.com/onnx/onnx-mlir/pull/1640 (FYI @tungld)

**Comment by tungld** [comment]
@cjvolzka did all the above models emit the same error as you showed?

**Comment by cjvolzka** [comment]
Yes. Same error in all 9 models when compiling for NNPA (1 arcfaceresnet-100, 5 densenet, 3 inception-v2)

**Comment by tungld** [comment]
@cjvolzka Thanks! I created a PR #1652 to fix this issue. I checked with densenet and it worked. Really appreciate it if you can check it in advance to see if the PR works on your side and if there is any other regression.

**Comment by AlexandreEichenberger** [comment]
PR #1652 is merged.

@cjvolzka once you verify that it works, please close the issue.

**Comment by cjvolzka** [comment]
Yep, that fixed it. Thanks @tungld
