### ISSUE TITLE
Informal Meeting, request for time that works for most.

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#1666]
Hello fellow ONNX-MLIR developers

We have had informal meeting on ONNX-MLIR development on Tuesday evening (8-9 EST, 5-6 PT, 8-9am Japan/China), mostly among IBMers and students that have worked with us.

We are thinking to open it up to the community in a more systematic way (thus this post), so that we may discuss free form what we are currently working on, suggestions that we may have, suggested directions, response to  RFC... Discussions are meant to be free of proprietary company info.

Would that time works for folks interested in participating? Evening on east cost kind of works for both cost, and is friendly to Asia where we have some of our IBM researchers participating in this project. We can consider other evenings (all but Friday as this would be Saturday morning in Asia).

We could start with informal, and if the need arise, we can adapt to a more presentation-style mode as we evolve.

Let us know, feel free to respond to this issue.

**Comment by philass** [comment]
Thanks for opening these meetings

I've shared this with the Groq compiler team. I'll share the feedback when they respond.

Most of the team is in Toronto and on EST time.

**Comment by philass** [comment]
I've talked to my colleagues. And I believe this time works for us

**Comment by AlexandreEichenberger** [comment]
create #1676 for meeting invite

**Comment by AlexandreEichenberger** [comment]
Added agenda and meeting notes on the GitHub wiki

**Comment by AlexandreEichenberger** [comment]
settled for now, can always reopen if folks want different times
