### ISSUE TITLE
Support for models with External Data

### ISSUE THREAD

**Issue by philass** [onnx/onnx-mlir#1696]
We briefly discussed this issue in the `onnx-mlir` Monday meeting. I wanted to add some more background to the problem, and create an issue so that we can track the progress

Its possible that an ONNX model stores some of its data externally https://github.com/onnx/onnx/blob/main/docs/ExternalData.md

As of right now there is no support for this in `onnx-mlir`.

**Comment by sorenlassen** [comment]
I can take this on.

**Comment by sorenlassen** [comment]
The implementation follows the spec and I hope the structure is clear. Please let me know if anything is unclear and would benefit from more comments or a different structure.
