### ISSUE TITLE
Upstreaming Groq changes

### ISSUE THREAD

**Issue by philass** [onnx/onnx-mlir#1703]
We have been working with `onnx-mlir` for years now at Groq. As a result we have added some additional features, bug fixes, and have some general divergence. 

Time permitting could we discuss a strategy for us upstreaming our changes in the `onnx-mlir` Tuesday meeting.

Below is hopefully a comprehensive list of what we have

- [x] Adding splitv11, squeezev11, unsqueezev11 decompositions
https://github.com/onnx/onnx-mlir/pull/1702
- [x] Topological Sorting check and implementation for onnx nodes 
#1725 
- [x] MatMul shape inference reuse for QLinearMatMul, MatMulInt, and MatMul
#1761
- [x] GatherND verifer fixes
#1754
- [x] FP16 protobuf ingestion
#1701 
- [x] Scatter verifier fix
https://github.com/onnx/onnx-mlir/pull/1760
- [x] ~~Lots of Constant Propagation (our implementation differs from the buffer implementation upstream)~~ We ended up moving our divergent const prop into our codebase. And don't need this merged to delete our fork
- [ ] Add pad support for Conv Transpose
#1771 
- [ ] Add Upsample shape inference
#1776  
- [ ] make valueInfo call permissive
#1779 
- [ ] derive kernel shape for conv op when not provided
#1780 

We see big benefits in minimizing our divergence from upstream. I'm actively working to upstream these changes. I want to make sure that we do it in a way that doesn't overwhelm.

**Comment by AlexandreEichenberger** [comment]
That would be great! We already have a presentation for this Tu, would next week work?

**Comment by philass** [comment]
Yes next week would work well too

**Comment by philass** [comment]
We are making really good progress on this

Only two PRs remaining:
- #1771 
- #1776

**Comment by philass** [comment]
Actually there are two more after those
- #1779
- #1780

But that is it!
