### ISSUE TITLE
Update version of onnx used by onnx-mlir

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#1748]
We're currently using onnx 1.11. The current version of onnx is 1.12. The primary end goal is to update to a version of onnx that includes includes https://github.com/onnx/onnx/pull/4544 (once it merges).

**Comment by AlexandreEichenberger** [comment]
Added Tong and Philip as likely candidate to upgrade our opset to the latest (17). According to a quick read of the operators, there is only a few new operators and no functionality change for existing ones, so it should be easy to add these new ops as unsupported yet.

Moving to the latest ONNX would fix a vulnerability reported in the onnx/onnx issue/pr

**Comment by philass** [comment]
I can likely add support for the ingestion of opset 17 by the end of next week

**Comment by cjvolzka** [comment]
Closing as duplicate of https://github.com/onnx/onnx-mlir/issues/1808
