### ISSUE TITLE
Is there any bug in OnnxBuilder::concat function?

### ISSUE THREAD

**Issue by i4oolish** [onnx/onnx-mlir#1751]
The source code is list as below, is the value for APInt is wrong?
Link: https://github.com/onnx/onnx-mlir/blob/main/src/Dialect/ONNX/DialectBuilder.cpp#L57
```c++
Value OnnxBuilder::concat(
    Type outputType, ValueRange inputs, int64_t axis) const {
  IntegerAttr concatAxisAttr = IntegerAttr::get(
      b.getIntegerType(64, /*isSigned=*/true), APInt(64, 0, /*isSigned=*/true));
  return b.create<ONNXConcatOp>(
      loc, toTensor(outputType), inputs, concatAxisAttr);
}
```

**Comment by tungld** [comment]
@i4oolish could you explain what's wrong with APInt?

**Comment by i4oolish** [comment]
> @i4oolish could you explain what's wrong with APInt?

It seems the input argument `axis` is not used in the concatAxisAttr, I am not sure about this.

**Comment by tungld** [comment]
> It seems the input argument axis is not used in the concatAxisAttr, I am not sure about this.

Oh, I see. Good catch. Thanks! Looking forward to your fix.

**Comment by tungld** [comment]
Given that this would affect all lowerings that use concat, I quickly created a PR #1759 to fix this.

@i4oolish thank you so much for reporting this issue!

**Comment by i4oolish** [comment]
> Given that this would affect all lowerings that use concat, I quickly created a PR #1759 to fix this.
> 
> @i4oolish thank you so much for reporting this issue!

It's my pleasure, thanks for your PR!
