### ISSUE TITLE
Upgrade ONNX-MLIR to ONNX v1.12.0 release.

### ISSUE THREAD

**Issue by mikeessen** [onnx/onnx-mlir#1808]
@AlexandreEichenberger @chentong319 @hamptonm1 @cjvolzka 

ONNX release v1.12.0 has been made available earlier this year.  Detail for the updates included are described on the ONNX releases web page [https://github.com/onnx/onnx/releases](https://github.com/onnx/onnx/releases).

The  ai.onnx opset version increased to 17 with the new operators: SequenceMap, LayerNormalization, DFT, HannWindow, HammingWindow, BlackmanWindow, MelWeightMatrix, and STFT.

The Scan operator was updated to remove an unused type constraint, but the version remains as opset 16.

Also included in the release are shape inference enhancements, bug fixes, infrastructure improvements, documentation updates, and wheel changes.

Let’s use this issue is to discuss moving to ONNX v1.12.0.  We plan on working on this without initially providing support for the new operators.

Note that the TreeEnsembleClassifier and TreeEnsembleRegressor operators show up as version 1 in ONNX-MLIR but were updated to version 3 in ONNX v1.11.0.

**Comment by mikeessen** [comment]
The SupportedONNXOps-cpu.md document at [https://github.com/onnx/onnx-mlir/blob/main/docs/SupportedONNXOps-cpu.md ](https://github.com/onnx/onnx-mlir/blob/main/docs/SupportedONNXOps-cpu.md )states that TreeEnsembleClassifier and TreeEnsembleRegressor are unsupported.  Is the document correct?  Should these be updated to version 3 in ONNX-MLIR when we move ONNX to v1.12.0?

**Comment by AlexandreEichenberger** [comment]
@mikeessen That is correct, we currently don't have code that lower these ops to CPU reference code. We typically mention a version only for the ops we support. 
If some of these ops are important to your projects, we encourage folks to contribute their implementations.

**Comment by hamptonm1** [comment]
> @mikeessen That is correct, we currently don't have code that lower these ops to CPU reference code. We typically mention a version only for the ops we support.
> If some of these ops are important to your projects, we encourage folks to contribute their implementations.

This looks good to me @mikeessen! Thanks for putting this together. Also @cjvolzka is it important to support these ops that @mikeessen mentioned or are we fine with what we are inheriting from `onn-xmlir` ?

**Comment by chentong319** [comment]
PR #1835 added the new Ops into onnx-mlir's ONNX dialect definition. Further implementation support is needed

**Comment by hamptonm1** [comment]
> PR #1835 added the new Ops into onnx-mlir's ONNX dialect definition. Further implementation support is needed

Thanks for the information.... I am assuming @mikeessen will still update the documentation for this?

**Comment by mikeessen** [comment]
@hamptonm1 @chentong319 Yes, I will update SupportedONNXOps-cpu.md for this.

**Comment by hamptonm1** [comment]
> @hamptonm1 @chentong319 Yes, I will update SupportedONNXOps-cpu.md for this.

FYI @philass so you do not have to do duplicate work :)

**Comment by cjvolzka** [comment]
Closing issue as completed as onnx-mlir has moved to onnx 1.12
