### ISSUE TITLE
Test building failure on Mac

### ISSUE THREAD

**Issue by chentong319** [onnx/onnx-mlir#1830]
Recently our test building keeps failure on Mac. The error message is "failed to load onnx module" in check-onnx-backend. This error is NOT caused by the PR that upgraded onnx to v1.12.0. I have a old PR passed all test previously but failed on Mac today after I triggered another test. Any idea about this error? Did we make any change to the test script or machine? @gongsu832

**Comment by gongsu832** [comment]
It certainly has something to do with updating onnx to v1.12.0 since they only start happening after that. If you look at the job log:
```
Successfully built onnx
Installing collected packages: typing-extensions, numpy, onnx
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed numpy-1.23.4 onnx-1.12.0 typing-extensions-4.4.0

```
I'm guessing it might have something to do with the deprecation warning although it does say onnx-1.12.0 has been successfully installed.

The problem with the Mac build is that we have no direct control over it. The env is setup by github actions servers. So it's very difficult to debug.

**Comment by gongsu832** [comment]
OK I see what's going on. Even though we force python 3.9 on the MacOS build, somehow onnx-mlir started to detect python 3.11. As a result, onnx was built with 3.9 but onnx-mlir was built with 3.11. Frankly, I'm getting rather annoyed with GitHub actions. The whole thing seems rather brittle.
```
-- Found Python3: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 (found version "3.11.0") found components: Interpreter Development Development.Module Development.Embed 
```

**Comment by gongsu832** [comment]
@chentong319 I have tried several ways to convince onnx and onnx-mlir to find the same python3 on MacOS with no luck. I gave up and I think the proper fix is for onnx to update their find_package command:
```
# find_package Python has replaced PythonInterp and PythonLibs since cmake 3.12
# Use the following command in the future; now this is only compatible with the latest pybind11
# find_package(Python ${PY_VERSION} COMPONENTS Interpreter Development REQUIRED)
find_package(PythonInterp ${PY_VERSION} REQUIRED)
find_package(PythonLibs ${PY_VERSION})
```
As you can see, they actually have a commented out find_package which is the right command to use. What onnx-mlir uses is:
```
find_package(Python3 ${LLVM_MINIMUM_PYTHON_VERSION} REQUIRED COMPONENTS Interpreter Development)
```
So onnx should use:
```
find_package(Python3 ${PY_VERSION} COMPONENTS Interpreter Development REQUIRED)
```

**Comment by chentong319** [comment]
@gongsu832 Thank you for the investigation to locate the source of error. The comment in onnx say  `this is only compatible with the latest pybind11`. Therefore, onnx will use this cmake until pybind11 is updated.
Anything we can do now for this build error?

**Comment by chentong319** [comment]
PR#1831 fixed this problem.
