### ISSUE TITLE
Investigate updating Scan Op

### ISSUE THREAD

**Issue by hamptonm1** [onnx/onnx-mlir#1838]
Scan Op is considered to be a more complicated op which according to the `ONNX` documentation has remained on version 16. Notice how Scan-17 is not available or listed: https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Scan-16

```
This version of the operator has been available since version 16 of the default ONNX operator set.
Other versions of this operator: 8, 9, 11
```

This is also reflected in the recent PR created to upgrade to opset 17, notice how the `scan op` remains at 16. So there are no changes here because a newer version is not available as of yet. Just because we upgrade `ONNX` versions, does not mean all of the op sets will be upgraded from 16 to 17: https://github.com/onnx/onnx-mlir/pull/1835/files

Further proof that no code updates were made to Scan Op from the `ONNX` side can be found in my PR that was recently merged (to upgrade onnx version). If there were any updates to Scan Op it would be reflected in the `src/Dialect/ONNX/ONNXOps.td.inc` file around line 5148, the argument defined would have changed but as we see in my recent PR with the pulled-in changes from `ONNX` the code in `src/Dialect/ONNX/ONNXOps.td.inc` does not change but rather the commentary is updated: https://github.com/onnx/onnx-mlir/pull/1818/files#diff-760d46a3e396ffde6025cb9d3ad43d3782dc67df9412a404fac9ef0885b4088bR5148

**Comment by hamptonm1** [comment]
@AlexandreEichenberger @chentong319 Since we did not update Scan Op there is no way to drive down test paths to verify this correct? Just doing a `git diff` of ONNX 1.11.0 to 1.12.0 shows that no code changes were made right? And I think viewing the documentation also solidifies this statement.

**Comment by chentong319** [comment]
1. It is confirmed that there is no change in the description of Scan Op in onnx from v1.11.0 to v1.12.0.  This means that Scan Op itself was not modified.
2. The change, mentioned in onnx git versioning document, may be the change within onnx package (for example shape inference for Scan). If the particular PR for that change is located, we can review the changed files. 
3. onnx-mlir passed the backend test with onnx v1.12.0.
I agree that there is nothing for onnx-mlir to do for Scan op for v1.12.0.

**Comment by hamptonm1** [comment]
FYI- @cjvolzka

**Comment by hamptonm1** [comment]
Okay I think we are all in agreement! Going to close this issue out.
