### ISSUE TITLE
Support for model-local functions?

### ISSUE THREAD

**Issue by gramalingam** [onnx/onnx-mlir#1841]
ONNX supports model-local functions: these are functions defined within a model. (See: https://github.com/onnx/onnx/blob/main/onnx/onnx.in.proto#L411 ). It would be great if the ONNX-MLIR converted supported translation of these functions into MLIR.

The current translator does support translation of ONNX FunctionProto into a MLIR function (see: https://github.com/onnx/onnx-mlir/blob/main/src/Builder/FrontendDialectTransformer.cpp#L1053 ). However, this is currently used only for schema-defined functions (these are ONNX ops registered as functions in the schema). Hopefully extending this to handle model-local functions won't be much work.

I think this would require extending `ImportONNXModel` which currently translates only the top-level graph of the model ( https://github.com/onnx/onnx-mlir/blob/main/src/Builder/FrontendDialectTransformer.cpp#L81 ), to also translated the functions contained in the model.

### Rationale

Model-local functions provide an extensibility mechanism. It allows users to use "custom ops" that can be defined as functions, and embed these function-definitions in the ONNX model (without requiring access to the schema-definitions of such custom ops, etc.)

### Examples

(a) See https://github.com/onnx/onnx/blob/main/onnx/test/cpp/parser_test.cc#L457 for a toy example.

(b) See https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/test/framework/function_test.cc#L76 (and other examples in the same file) for more examples.

**Comment by sorenlassen** [comment]
model local functions support was added in PR #2242
