### ISSUE TITLE
NNPA Regression - bertsquad-10 gives Warning: [Shape inference] the inferred dim (768)

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#1843]
When using commit 57aeab7123f9ca25a7fadf1cf361ed23e67b485a compiling [bertsquad-10](https://github.com/onnx/models/blob/main/text/machine_comprehension/bert-squad/model/bertsquad-10.onnx) for NNPA, I now see about 250 lines of
```
Warning: [Shape inference] the inferred dim (768) is different from the existing dim (1). Use the existing dim instead.
```
I do not see these warnings when compiling for CPU. The model does compile and run successfully for both CPU and NNPA.

When running the model for NNPA, the accuracy and performance drops compared to the 0.3.1 release (min relative tolerance to pass is 0.042310 now vs 0.007956) and runs slightly slower (approximately 162 ms now vs 142 ms)

The last time I recorded trying this model was e7ce6ea2c32d60f41c6fb68f99c2fd2200de5592 which did not get these warnings.

**Comment by tungld** [comment]
@cjvolzka I also see this warning. I'll check it.

**Comment by cjvolzka** [comment]
Thanks for taking a look @tungld. Yeah my first thought was the difference was something going to NNPA that wasn't before. I was thrown though when runtime increased because usually going to NNPA decreases runtime which made me think there might have been an unexpected bug. However the extra stickifications would explain the runtime change.

ok, I'll close this once the PR for the warning merges and I retest the model.
