### ISSUE TITLE
Not able to build ONNX

### ISSUE THREAD

**Issue by AkhilJ99** [onnx/onnx-mlir#185]
This happens when I run the "cmake .." command, I have already built the llvm project (For this I have used the instructions on the MLIR getting started page : [)](https://mlir.llvm.org/getting_started/)) and set the environment variable to the right path.

![error](https://user-images.githubusercontent.com/32807730/85529968-30651000-b62b-11ea-9780-5e3dba0a419d.png)

and this is the ouput of the CMakeError.log
`Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/akhil/Downloads/onnx-mlir/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_c1976/fast && /usr/bin/make -f CMakeFiles/cmTC_c1976.dir/build.make CMakeFiles/cmTC_c1976.dir/build
make[1]: Entering directory '/home/akhil/Downloads/onnx-mlir/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c1976.dir/src.c.o
/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_c1976.dir/src.c.o   -c /home/akhil/Downloads/onnx-mlir/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_c1976
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c1976.dir/link.txt --verbose=1
/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD    -rdynamic CMakeFiles/cmTC_c1976.dir/src.c.o  -o cmTC_c1976 
/usr/bin/ld: CMakeFiles/cmTC_c1976.dir/src.c.o: in function `main':
src.c:(.text+0x46): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x63): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_c1976.dir/build.make:87: cmTC_c1976] Error 1
make[1]: Leaving directory '/home/akhil/Downloads/onnx-mlir/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_c1976/fast] Error 2

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/akhil/Downloads/onnx-mlir/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_a5dee/fast && /usr/bin/make -f CMakeFiles/cmTC_a5dee.dir/build.make CMakeFiles/cmTC_a5dee.dir/build
make[1]: Entering directory '/home/akhil/Downloads/onnx-mlir/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a5dee.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_a5dee.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.16/Modules/CheckFunctionExists.c
Linking C executable cmTC_a5dee
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a5dee.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_a5dee.dir/CheckFunctionExists.c.o  -o cmTC_a5dee  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_a5dee.dir/build.make:87: cmTC_a5dee] Error 1
make[1]: Leaving directory '/home/akhil/Downloads/onnx-mlir/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_a5dee/fast] Error 2
`

**Comment by doru1004** [comment]
What Make version are you using?

**Comment by imaihal** [comment]
Are you using specific commit (`0dc91bfd11e6cced0c46c1a25cc96edea0d8fc22`) for llvm-project as written here? https://github.com/onnx/onnx-mlir/blob/master/README.md
I remember I saw this kind of error before when I used different commit.

```
git clone https://github.com/llvm/llvm-project.git
# Check out a specific branch that is known to work with ONNX MLIR.
cd llvm-project && git checkout 0dc91bfd11e6cced0c46c1a25cc96edea0d8fc22 && cd ..
```

**Comment by AkhilJ99** [comment]
my cmake version is "3.16.3".  I Have tried rebuilding with the specific commit version and got this error.


After running cmake ..
`-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- LLVM_PROJ_SRC /home/akhil/Downloads/Onnx-llvm/llvm-project/
-- LLVM_PROJ_BUILD /home/akhil/Downloads/Onnx-llvm/llvm-project/build
-- LLVM_PROJECT_LIB:/home/akhil/Downloads/Onnx-llvm/llvm-project/build/lib
-- LLVM_PROJ_BIN:/home/akhil/Downloads/Onnx-llvm/llvm-project/build/bin
-- ONNX_MLIR_TOOLS_DIR:/home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/bin
-- BUILD_SHARED_LIBS OFF
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Curses: /usr/lib/x86_64-linux-gnu/libcurses.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Linker detection: GNU ld
-- Found Protobuf: /usr/local/lib/libprotobuf.so (found version "3.12.3") 
Generated: /home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/third_party/onnx/onnx/onnx-ml.proto
Generated: /home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/third_party/onnx/onnx/onnx-operators-ml.proto
-- 
-- ******** Summary ********
--   CMake version         : 3.16.3
--   CMake command         : /usr/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 9.3.0
--   CXX flags             :  -Wnon-virtual-dtor
--   Build type            : Debug
--   Compile definitions   : 
--   CMAKE_PREFIX_PATH     : 
--   CMAKE_INSTALL_PREFIX  : /usr/local
--   CMAKE_MODULE_PATH     : /home/akhil/Downloads/Onnx-llvm/llvm-project/build/lib/cmake/llvm
-- 
--   ONNX version          : 1.6.0
--   ONNX NAMESPACE        : onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   ONNXIFI_ENABLE_EXT    : OFF
-- 
--   Protobuf compiler     : /usr/local/bin/protoc
--   Protobuf includes     : /usr/local/include
--   Protobuf libraries    : /usr/local/lib/libprotobuf.so
--   BUILD_ONNX_PYTHON     : OFF
-- Failed to find LLVM FileCheck
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- git Version: v0.0.0
-- Version: 0.0.0
-- Performing Test HAVE_CXX_FLAG_STD_CXX11
-- Performing Test HAVE_CXX_FLAG_STD_CXX11 - Success
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Success
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test HAVE_CXX_FLAG_WSHADOW
-- Performing Test HAVE_CXX_FLAG_WSHADOW - Success
-- Performing Test HAVE_CXX_FLAG_WERROR
-- Performing Test HAVE_CXX_FLAG_WERROR - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC
-- Performing Test HAVE_CXX_FLAG_PEDANTIC - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS - Success
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 - Failed
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS - Success
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED - Success
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WD654
-- Performing Test HAVE_CXX_FLAG_WD654 - Failed
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY - Failed
-- Performing Test HAVE_CXX_FLAG_COVERAGE
-- Performing Test HAVE_CXX_FLAG_COVERAGE - Success
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Found PythonInterp: /usr/bin/python (found version "2.7.18") 
-- Performing Test BENCHMARK_HAS_O3_FLAG
-- Performing Test BENCHMARK_HAS_O3_FLAG - Success
-- Performing Test BENCHMARK_HAS_CXX03_FLAG
-- Performing Test BENCHMARK_HAS_CXX03_FLAG - Success
-- Performing Test BENCHMARK_HAS_WNO_ODR
-- Performing Test BENCHMARK_HAS_WNO_ODR - Success
-- Found PythonLibs: python2.7
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.4.dev4
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
SATUSOMLibsOMBuilderOMKrnlOpsOMONNXOpsOMKrnlToAffineOMKrnlToLLVMOMONNXToKrnlOMONNXRewriteOMShapeInferenceOMShapeInferenceOpInterfaceOMAttributePromotionOMPromotableConstOperandsOpInterfaceOMResultTypeInferenceOpInterfaceOMElideConstantsOMElideKrnlGlobalConstantsOMPackKrnlGlobalConstantsOMEnableMemoryPool
-- incl dir/home/akhil/Downloads/Onnx-llvm/onnx-mlir/third_party/onnx/home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/third_party/onnx
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PythonInterp: Found unsuitable version "2.7.18", but
  required is at least "3" (found /usr/bin/python)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:391 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  docs/doc_check/CMakeLists.txt:1 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeOutput.log".
See also "/home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeError.log".
`

Output of the CMakeError.log

`Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_f961d/fast && /usr/bin/make -f CMakeFiles/cmTC_f961d.dir/build.make CMakeFiles/cmTC_f961d.dir/build
make[1]: Entering directory '/home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_f961d.dir/src.c.o
/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_f961d.dir/src.c.o   -c /home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_f961d
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f961d.dir/link.txt --verbose=1
/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD    -rdynamic CMakeFiles/cmTC_f961d.dir/src.c.o  -o cmTC_f961d 
/usr/bin/ld: CMakeFiles/cmTC_f961d.dir/src.c.o: in function `main':
src.c:(.text+0x46): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x63): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_f961d.dir/build.make:87: cmTC_f961d] Error 1
make[1]: Leaving directory '/home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_f961d/fast] Error 2


Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_c47fc/fast && /usr/bin/make -f CMakeFiles/cmTC_c47fc.dir/build.make CMakeFiles/cmTC_c47fc.dir/build
make[1]: Entering directory '/home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c47fc.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_c47fc.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.16/Modules/CheckFunctionExists.c
Linking C executable cmTC_c47fc
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c47fc.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_c47fc.dir/CheckFunctionExists.c.o  -o cmTC_c47fc  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_c47fc.dir/build.make:87: cmTC_c47fc] Error 1
make[1]: Leaving directory '/home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_c47fc/fast] Error 2



Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 failed with the following output:
Change Dir: /home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_74269/fast && /usr/bin/make -f CMakeFiles/cmTC_74269.dir/build.make CMakeFiles/cmTC_74269.dir/build
make[1]: Entering directory '/home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_74269.dir/src.cxx.o
/usr/bin/c++    -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors -DHAVE_CXX_FLAG_WSHORTEN_64_TO_32  -Wshorten-64-to-32   -Wshorten-64-to-32 -o CMakeFiles/cmTC_74269.dir/src.cxx.o -c /home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option '-Wshorten-64-to-32'
c++: error: unrecognized command line option '-Wshorten-64-to-32'
make[1]: *** [CMakeFiles/cmTC_74269.dir/build.make:66: CMakeFiles/cmTC_74269.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_74269/fast] Error 2


Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WD654 failed with the following output:
Change Dir: /home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_00f2a/fast && /usr/bin/make -f CMakeFiles/cmTC_00f2a.dir/build.make CMakeFiles/cmTC_00f2a.dir/build
make[1]: Entering directory '/home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_00f2a.dir/src.cxx.o
/usr/bin/c++    -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -fstrict-aliasing  -Wno-deprecated-declarations  -Wstrict-aliasing -DHAVE_CXX_FLAG_WD654  -wd654   -wd654 -o CMakeFiles/cmTC_00f2a.dir/src.cxx.o -c /home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option '-wd654'
c++: error: unrecognized command line option '-wd654'
make[1]: *** [CMakeFiles/cmTC_00f2a.dir/build.make:66: CMakeFiles/cmTC_00f2a.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_00f2a/fast] Error 2


Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WTHREAD_SAFETY failed with the following output:
Change Dir: /home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_94910/fast && /usr/bin/make -f CMakeFiles/cmTC_94910.dir/build.make CMakeFiles/cmTC_94910.dir/build
make[1]: Entering directory '/home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_94910.dir/src.cxx.o
/usr/bin/c++    -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -fstrict-aliasing  -Wno-deprecated-declarations  -Wstrict-aliasing -DHAVE_CXX_FLAG_WTHREAD_SAFETY  -Wthread-safety   -Wthread-safety -o CMakeFiles/cmTC_94910.dir/src.cxx.o -c /home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option '-Wthread-safety'
c++: error: unrecognized command line option '-Wthread-safety'
make[1]: *** [CMakeFiles/cmTC_94910.dir/build.make:66: CMakeFiles/cmTC_94910.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/akhil/Downloads/Onnx-llvm/onnx-mlir/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_94910/fast] Error 2


Source file was:
int main() { return 0; }
`

**Comment by aaronsm** [comment]
You can use this PR to build with the latest llvm.
https://github.com/onnx/onnx-mlir/pull/187

**Comment by aaronsm** [comment]
Your second attempt didn't work because you are used Python2 and not Python3.

cmake -DPYTHON_EXECUTABLE=full-path-to-python3 ..

**Comment by AkhilJ99** [comment]
> Your second attempt didn't work because you used Python2 and not Python3.
> 
> cmake -DPYTHON_EXECUTABLE=full-path-to-python3 ..

Thank you that helped in resolving the errors
