### ISSUE TITLE
Update readelf information with onnx-mlir commit.

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#1855]
When calling `readelf` on a compile model it shows the onnx and LLVM commits used but only the onnx-mlir version. It would be nice to enhance this to include the onnx-mlir commit as well.

example:
```
readelf -p .comment model.so 
String dump of section '.comment':
  [     0]  GCC: (GNU) 8.5.0 20210514 (Red Hat 8.5.0-10)
  [    2d]  onnx-mlir version 0.3.1, onnx version 1.12.0 (git@github.com:onnx/onnx-mlir.git 62de6adc89ea5c0cf8bc1f58857dfe74d589618c, https://github.com/llvm/llvm-project.git 438e59182b0c2e44c263f5bacc1add0e514354f8)
```

Bonus points to include the VENDOR name and version (if one specified at build time) but even just onnx-mlir commit would be a big help when debugging models.

**Comment by cjvolzka** [comment]
In case it helps, these are the original Issue https://github.com/onnx/onnx-mlir/issues/1206 and PR https://github.com/onnx/onnx-mlir/pull/1211 that added the information to .comment. The PR is a little out of date in terms of what the .comment currently is, but it shows the area to adjust.

**Comment by hamptonm1** [comment]
@cjvolzka So should we have this on two different lines now? 

I mean like the version and the commit next to each other:
```
onnx-mlir version 0.3.1 (git@github.com:onnx/onnx-mlir.git <some hash>)
onnx version 1.12.0 (git@github.com:onnx/onnx-mlir.git 62de6adc89ea5c0cf8bc1f58857dfe74d589618c)

```
Also do we need the `llvm` version here too?
https://github.com/llvm/llvm-project.git 438e59182b0c2e44c263f5bacc1add0e514354f8)

**Comment by cjvolzka** [comment]
I think breaking them up by lines is much easier to read, so if that plays nice with how .comments work, I think that's a good idea.

I can go either way on keeping or dropping the llvm version info and the onnx version for that matter. Personally I think the biggest one is to have _either_ the vendor name and vendor version (which can include commit info its `-xyz` suffix) _or_ the onnx-mlir version and commit. Those should then dictate everything else. However, I don't know the history of why the rest was included. (ie check some of the PRs that added them and see if there's anything documented or tag some of those reviewers if they have opinions).

**Comment by hamptonm1** [comment]
This is fixed!! So closing this out :)
