### ISSUE TITLE
Fix hard coding -1 to represent dynamic tensor shape during ONNX -> MLIR import

### ISSUE THREAD

**Issue by christopherbate** [onnx/onnx-mlir#1920]
You just upgraded to LLVM from `11/14`. There was ongoing effort to unify the constants `ShapedType::kDynamicSize` and `ShapedType::kDynamicSentinal` values in MLIR (https://reviews.llvm.org/D138282). This concluded on `11/18`. where dynamic or unknown tensor dimensions are now represented with `ShapedType::kDynamic`.

Currently in `src/Builder/FrontendDialectTransformer.cpp` there are a variety of places where conversion of TensorProto or TensorShapeProto transforms dynamic dimensions directly to a hard coded -1 value. When you upgrade past 11/18 this will silently create bugs and may be creating bugs now (https://github.com/onnx/onnx-mlir/issues/1897). Just need to replace that with ShapedType::kDynamicSize now, then when you upgrade past 11/18 it will become `ShapedType::kDynamic`.

**Comment by christopherbate** [comment]
I also see that elsewhere, there are other functions  e.g. in ONNXDimAnalysis that are using `ShapedType::isDynamic` or other utils and other ONNX ops using -1 hard coded elsewhere for dynamic dims. I guess there are more places that would need to be updated then.

**Comment by chentong319** [comment]
I start to use ty.isDynamicDim(dim).

**Comment by AlexandreEichenberger** [comment]
@christopherbate fine by you? it is by me.
