### ISSUE TITLE
Does onnx-mlir support onnx model with external_data?

### ISSUE THREAD

**Issue by wjxcsu** [onnx/onnx-mlir#1929]
I have encountered a problem. My onnx model is a bit large. The .onnx file only retains the model structure, and the weight data is stored in a separate file. It can also be considered that "onnx.external_data_helper.load_external_data_for_model"(a python function) is needed every time the model is loaded.
I use the ./onnx-mlir --EmitONNXIR command to convert the onnx file(only has model structure without the weight data) and an error will be reported. So will onnx-mlir support onnx models with external_data? :)

**Comment by chentong319** [comment]
I saw code in onnx Builder that reads in external data when the model is imported. I do not think onnx-mlir supports model structure without the weight data imported. It could be added with the new constant attribute (#1874).

**Comment by sorenlassen** [comment]
closing, the question has been answered affirmatively
