### ISSUE TITLE
Function inlining in ONNX-MLIR

### ISSUE THREAD

**Issue by philass** [onnx/onnx-mlir#1942]
# Background

ONNX supports Functions, which are essentially ops with known implementations or decompositions. Up until now we haven't been leveraging the fact that these decompositions can be scraped off of the ONNX schema. One of the intents of ONNX functions is to reduce the number of primitive operations that hardware vendors have to support. 

So by effectively leveraging Functions we should be able to support more models out of the box. As of right now the ops at the bottom are defined in the ONNX specification as functions. Leveraging ONNX functions would enable us to add support for all of the following operators without any op specific rewrites.

Having support for this will be even more important as ONNX is moving towards lowering the bar for new ops, provided they are defined as functions. So later opsets should see a large influx of new functions. 

# Proposal

The proposal would be to add two import options  a boolean `inlineFunctions`, and a set of `strings` called `functionsToNotInline`. If `inlineFunctions` is set as false, this feature will be ignored and we can carry on with business as usual. If inlineFunctions is set to true, then functions will be inlined unless they are in `functionsToNotInline`. The `functionsToNotInline`  set is important for people who have custom kernels for specific functions. This allows them to not decompose when it would be unfavorable. The key reason for having a set of string for opting out of decomposition as opposed to opting into decomposition is that we always want to inline when we don't have explicit handling for a function at some later stage in the compiler. 

The inlining implementation will follow [Soren's Function Inlining PR](https://github.com/onnx/onnx-mlir/pull/1785). However it will be rejigged to complement the existing handling of functions, instead of replacing it. 

# References
- [Function Proposal](https://github.com/onnx/onnx/blob/main/docs/proposals/FunctionsProposal.md)
- [ONNX Specification](https://github.com/onnx/onnx/blob/main/docs/Operators.md)
- [Soren's Function Inlining PR](https://github.com/onnx/onnx-mlir/pull/1785)

# ONNX Functions (in the spec)

Bernoulli | 15 | 15
-- | -- | --
BlackmanWindow | 17 | 17
CastLike | 15 | 15
Celu | 12 | 12
CenterCropPad | 18 | 18
Clip | 13, 12, 11, 6, 1 | 13
DynamicQuantizeLinear | 11 | 11
Elu | 6, 1 | 18
GreaterOrEqual | 16, 12 | 16
GroupNormalization | 18 | 18
HammingWindow | 17 | 17
HannWindow | 17 | 17
HardSigmoid | 6, 1 | 18
HardSwish | 14 | 14
LayerNormalization | 17 | 17, 18
LeakyRelu | 16, 6, 1 | 16
LessOrEqual | 16, 12 | 16
LogSoftmax | 13, 11, 1 | 13, 18
MeanVarianceNormalization | 13, 9 | 13, 18
Mish | 18 | 18
NegativeLogLikelihoodLoss | 13, 12 | 13
PRelu | 16, 9, 7, 6, 1 | 16
Range | 11 | 11
ReduceL1 | 18, 13, 11, 1 | 18
ReduceL2 | 18, 13, 11, 1 | 18
ReduceLogSum | 18, 13, 11, 1 | 18
ReduceLogSumExp | 18, 13, 11, 1 | 18
ReduceSumSquare | 18, 13, 11, 1 | 18
Relu | 14, 13, 6, 1 | 18
Selu | 6, 1 | 18
SequenceMap | 17 | 17
Shrink | 9 | 18
Softmax | 13, 11, 1 | 13, 18
SoftmaxCrossEntropyLoss | 13, 12 | 13
Softplus | 1 | 1
Softsign | 1 | 18
ThresholdedRelu | 10 | 18

**Comment by AlexandreEichenberger** [comment]
See meeting notes for comments, in summary:
* Stella suggested using a config file
*  Alex suggested that there is a way to define which function is inlined/not inlined based on high level options (e.g. accel/triple/machine/cpu combinations).
