### ISSUE TITLE
IndexExpr support for Floats

### ISSUE THREAD

**Issue by philass** [onnx/onnx-mlir#1958]
Moving to the new implementation for `Resize` with `IndexExpr` caused a bug.

The calculation for a given rank `i` is `axis[i] = floor(scales[i] * inputDim[i])`. Unfortunately `IndexExprs` don't have support for floats. 

The current implementation doesn't do this rounding correctly as it casts the `scales[i]` to an int. This causes the wrong result. 

`IndexExprs` could add support for floats however this is quite a large change, that would either effect many functions or result in the introduction of many new functions that mirror their Int equivalents.

**Comment by AlexandreEichenberger** [comment]
I saw that too when I was refactoring the code. I have to think a bit about it as indices are naturally about integers. But indeed ONNX has some computations that use float to compute an index, how unfortunate :-)

**Comment by AlexandreEichenberger** [comment]
PR #1974 added support and changed code for resize accordingly.
