### ISSUE TITLE
Some missing operations for RNNs

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#196]
These are some missing operations for running RNNs (There would be more missing operations, here we list those we have known so far). Please feel free to add more.

(PR: means still in pull request, Y: Yes, supported)
| ONNX operations | Shape inference | Lowering code |
| --- | --- | --- |
| Shape | Y| Y |
| Cast | Y | Y  |
| Squeeze | Y | Y |
| Tile |Y | Y  |
| Gather | Y| Y |
| Slice | Y| Y (constant shapes... upcoming llvm changes will add dynamic as well|
| ConstantOfShape |Y| Y |

**Comment by doru1004** [comment]
Any updates on the Slice Op? @AlexandreEichenberger @tungld

**Comment by AlexandreEichenberger** [comment]
@tungld @doru1004 Slice was just in, but still constant shape because we are missing MLIR changes; another patch #377 is handling this.

**Comment by tungld** [comment]
All ops are available.
