### ISSUE TITLE
Migration from MLIR-HLO to StableHLO

### ISSUE THREAD

**Issue by ashay** [onnx/onnx-mlir#1980]
Currently, onnx-mlir contains a lowering to the `mhlo` dialect, but it seems beneficial to lower to the StableHLO dialect for several reasons:

1. StableHLO supports versioning (thus forward and backward compatibility within major versions) and serialization.

2. StableHLO has a smaller codebase than MLIR-HLO, thus causing less churn in downstream projects like onnx-mlir due to updates (e.g. reorganized directories, renamed targets).

3. Unlike the CI for the StableHLO repository, the CI for the MLIR-HLO repository does not use CMake (it uses Bazel), so the CMake build for MLIR-HLO breaks often.  I fix these breakages in the MHLO green commits, but it's recurring work to fix them and submit patches upstream:

 - https://github.com/tensorflow/tensorflow/pull/57484
 - https://github.com/tensorflow/tensorflow/pull/57504
 - https://github.com/tensorflow/tensorflow/pull/57655
 - https://github.com/tensorflow/tensorflow/pull/58880
 - https://github.com/tensorflow/tensorflow/pull/59019
 - https://github.com/tensorflow/tensorflow/pull/59187
 - https://github.com/tensorflow/tensorflow/pull/59219
 - https://github.com/tensorflow/tensorflow/pull/59495

So my questions for the ONNXToMhlo maintainers are: (a) would there be any loss in functionality if we switched to using StableHLO and (b) would you (or someone familiar with that code) be willing to update the code to switch to StableHLO please?  Thanks!

**Comment by AlexandreEichenberger** [comment]
This is a question obviously for the folks that are working on mhlo within MLIR.

From a stability point of view, using the StableHLO makes a lot of sense, as we want stable interfaces. I assume that StableHLO has reached maturity by now, thus your request.

**Comment by ashay** [comment]
Thanks!

> I assume that StableHLO has reached maturity by now, thus your request.

That's my understanding as well, going by the status documented [here](https://github.com/openxla/stablehlo/blob/main/docs/status.md#status).

**Comment by burmako** [comment]
"I assume that StableHLO has reached maturity by now, thus your request". StableHLO is available as a drop-in replacement for MHLO in the role of an interface between ML frameworks and ML compilers. It supports everything that MHLO supports at the interface level, and then some - e.g. we have [a spec](https://github.com/openxla/stablehlo/blob/main/docs/spec.md), [an approved compatibility design](https://github.com/openxla/stablehlo/blob/main/rfcs/20220912-compatibility.md) that's almost fully implemented, and [a reference implementation](https://github.com/openxla/stablehlo/tree/main/stablehlo/reference) is underway.

We have recently migrated JAX from producing MHLO to producing StableHLO (https://github.com/google/jax/commit/a1480c454e69a2631dbd51cb2f4fccc2752c18a0), and that was fairly straightforward thanks to how close StableHLO is to MHLO. Based on this experience, I think that StableHLO would be a good fit for ONNX-MLIR as well.

We'll be happy to support the migration effort - please let us know if there's anything we can do to help.

**Comment by ShuaiShao93** [comment]
OpenXLA/IREE has removed the support for MHLO, so we are blocked by this issue. Is it possible to prioritize it?

**Comment by ashay** [comment]
Closing this issue since the related work was completed in https://github.com/onnx/onnx-mlir/pull/2573.

**Comment by taalhaataahir0102** [comment]
Hi all!
I don't know if it's the right place to ask this but I'm having the following error for `stablehlo`
I was trying to view the intermediate representation of a tf model. I've generated the mlir using `IREE`:
https://colab.research.google.com/github/openxla/iree/blob/main/samples/colab/tensorflow_hub_import.ipynb
But when I try to view the IR using `mlir-opt` it gives me the following issue:
`error: dialect 'stablehlo' does not implement the bytecode interface`
![image](https://github.com/onnx/onnx-mlir/assets/77788288/831610f1-4129-44f1-b655-3012781aca33)
My mlir version is 19.0.0
