### ISSUE TITLE
Three models failed after updating LLVM by PR#1977

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#1987]
After PR #1977 was merged, I noticed that there are 3 models failed:

<img width="447" alt="Screenshot 2023-02-01 at 16 35 13" src="https://user-images.githubusercontent.com/1230113/215980119-57aef808-9587-4a4d-a0ed-81599b0023b4.png">

More info: https://www.onnxmlir.xyz/jenkinx/job/ONNX-MLIR-Pipeline-Docker-Build/Model_20Zoo_20Report/

**Comment by tungld** [comment]
FYI @christopherbate, @AlexandreEichenberger

**Comment by christopherbate** [comment]
I noticed that link says 22 models are failing. So my PR caused just those three additional models to start failing?

**Comment by christopherbate** [comment]
There errors `invalid memref size ....` are all due to a -1 appearing instead of ShapedType::kDynamic. So there's some -1 issues that were not uncovered by existing `check-onnx-mlir` and `check-onnx-backend-*` tests

**Comment by tungld** [comment]
> So my PR caused just those three additional models to start failing?

Yes, exactly.

**Comment by AlexandreEichenberger** [comment]
Note that @sstamenova has noticed places where their build had -1 in different places, so you @christopherbate may want to look at her issue when she pushes there her differences
