### ISSUE TITLE
Build fails without ONNX_MLIR_ACCELERATORS option after PR#1977

### ISSUE THREAD

**Issue by imaihal** [onnx/onnx-mlir#1988]
It seems build fails when configuring without `-DONNX_MLIR_ACCELERATORS=NNPA`. I didn't see this before #1977 .

```
CMakeFiles/OMInitAccelerators.dir/InitAccelerators.cpp.o: In function `mlir::Operation::debug_getSuccessors()':
InitAccelerators.cpp:(.text._ZN4mlir9Operation19debug_getSuccessorsEv[_ZN4mlir9Operation19debug_getSuccessorsEv]+0x12): undefined reference to `mlir::SuccessorRange::SuccessorRange(mlir::Operation*)'
collect2: error: ld returned 1 exit status
src/Accelerators/CMakeFiles/OMInitAccelerators.dir/build.make:104: recipe for target 'Release/lib/libOMInitAccelerators.so' failed
make[2]: *** [Release/lib/libOMInitAccelerators.so] Error 1
CMakeFiles/Makefile2:12920: recipe for target 'src/Accelerators/CMakeFiles/OMInitAccelerators.dir/all' failed
make[1]: *** [src/Accelerators/CMakeFiles/OMInitAccelerators.dir/all] Error 2
```

**Comment by AlexandreEichenberger** [comment]
Can other corroborate this? I am building on x86 with this:
```
mkdir onnx-mlir/build && cd onnx-mlir/build
if [[ -z "$pythonLocation" ]]; then
  cmake -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=/usr/bin/c++ -DMLIR_DIR=/workdir/llvm-project/build/lib/cmake/mlir -DONNX_MLIR_ACCELERATORS=NNPA ..
else
  cmake -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=/usr/bin/c++ -DMLIR_DIR=/workdir/llvm-project/build/lib/cmake/mlir -DONNX_MLIR_ACCELERATORS=NNPA -DPython3_ROOT_DIR=$pythonLocation ..
fi
cmake --build .

# Run lit tests:
export LIT_OPTS=-v
cmake --build . --target check-onnx-lit
```

which includes NNPA and I have not seen any problems. I typically nuke the entire build dir when upgrading LLVM, as well as the onnx-mlir/third_party and rebuild onnx using `pip`.

**Comment by christopherbate** [comment]
He's saying it fails **without** NNPA specified. 

Here is what is likely causing that error:

There are several places in the CMake code where the upstream target `MLIRIR` is either missing or specified in the `DEPENDS` section of an `add_(onnx mlir)_library` command. 

These should be corrected to be placed under `LINK_LIBS PUBLIC`, as it is a link dependency. I only fixed the minimum needed to pass CI.

I'm not sure what changed between the old LLVM version and the new one that causes this issue to appear; it's surprising that it didn't surface before. My guess is that either upstream cmake function changes or changes in the dependency graph caused MLIRIR previously to be linked in transitively to most targets, but that is no longer the case.

**Comment by christopherbate** [comment]
I'll put the PR up

**Comment by AlexandreEichenberger** [comment]
Thanks for the quick PR

**Comment by imaihal** [comment]
@christopherbate Thanks for the fix!
