### ISSUE TITLE
Unable to compile model with -1 in --shapeInformation

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#1995]
After the latest llvm update, using `--shapeInformation` to make a static dimension static causes a compile failure.

For example compiling [yolov3-12.onnx](https://github.com/onnx/models/blob/main/vision/object_detection_segmentation/yolov3/model/yolov3-12.onnx) input0 normally has shape [-1,3,-1,-1]. To make the image shape static but keep the batch size dynamic with:
```
--O3 --EmitLib yolov3-12.onnx --onnx-op-stats TXT --shapeInformation 0:-1x3x416x416
```
now gives failure:
```
error: invalid tensor dimension size
onnx-mlir: /build/llvm-project/mlir/include/mlir/IR/StorageUniquerSupport.h:153: static ConcreteT mlir::detail::StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT, Traits>::get(mlir::MLIRContext*, Args ...) [with Args = {llvm::ArrayRef<long int>, mlir::Type, mlir::Attribute}; ConcreteT = mlir::RankedTensorType; BaseT = mlir::TensorType; StorageT = mlir::detail::RankedTensorTypeStorage; UniquerT = mlir::detail::TypeUniquer; Traits = {mlir::SubElementTypeInterface::Trait, mlir::ShapedType::Trait}]: Assertion `succeeded(ConcreteT::verify(getDefaultDiagnosticEmitFn(ctx), args...))' failed.
```

**Comment by AlexandreEichenberger** [comment]
I suggest that we tweak the reader to accept `-1`. It is still the recognized value when printing MLIR files along the compilation, so there is no reason to be different here.

**Comment by tungld** [comment]
Created #1998 to fix this issue. It is a matter of parsing  `--shapeInformation`. For users of onnx-mlir, I prefer to use -1 to denote a dynamic dimension as it is.
