### ISSUE TITLE
Dynamic dimensions in json signature now -9223372036854775808 instead of -1

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#1996]
After the latest llvm update, the json signature for dynamic dimensions in models is now `-9223372036854775808` instead of `-1`.

For example compiling [yolov3-12.onnx](https://github.com/onnx/models/blob/main/vision/object_detection_segmentation/yolov3/model/yolov3-12.onnx) where the first input normally has shape [-1,3,-1,-1] and the second input is [-1,2]. Compiling with:
```
--O3 --EmitLib yolov3-12.onnx --onnx-op-stats TXT
```
works fine. But afterward the json signature now looks like
(session.input_signature())
```
 [    { "type" : "f32" , "dims" : [-9223372036854775808 , 3 , -9223372036854775808 , -9223372036854775808] , "name" : "input_1" } ,    { "type" : "f32" , "dims" : [-9223372036854775808 , 2] , "name" : "image_shape" }]
```
(session.output_signature())
```
[   { "type" : "f32" , "dims" : [1 , -9223372036854775808 , 4] , "name" : "yolonms_layer_1/ExpandDims_1:0" } ,    { "type" : "f32" , "dims" : [1 , 80 , -9223372036854775808] , "name" : "yolonms_layer_1/ExpandDims_3:0" } ,    { "type" : "i32" , "dims" : [-9223372036854775808 , 3] , "name" : "yolonms_layer_1/concat_2:0" }]
```
where it used to have `-1` for the dynamic dimensions.

I'm guessing the `-9223372036854775808` is coming from MLIR's `ShapedType::kDynamic`. However I'm guessing we don't want to present that literal through onnx-mlir externalized interfaces (ie the json signature output of this issue and value to use for `--shapeInformation` for https://github.com/onnx/onnx-mlir/issues/1995).

Note: if we change the external interfaces from `-1` to something new, that should be a version bump in the next onnx-mlir release because it might force downstream users to make changes. Luckily the next onnx-mlir is already going to be 0.4.0 rather than 0.3.3 so if we _did_ want to change it, now's as good a time as any.

**Comment by AlexandreEichenberger** [comment]
I suggest that we tweak the reader to accept -1. It is still the recognized value when printing MLIR files along the compilation, so there is no reason to be different here.

**Comment by AlexandreEichenberger** [comment]
People interfacing values should remain easy to use... thus continuing `-1` is the way to go.

**Comment by tungld** [comment]
> People interfacing values should remain easy to use... thus continuing -1 is the way to go.

Agreed. PR #1998 is to handle `-1` at onnx-mlir's interface.
