### ISSUE TITLE
Models failing to download - blocking builds & PRs

### ISSUE THREAD

**Issue by sstamenova** [onnx/onnx-mlir#2001]
It looks like several of the backend tests that rely on model download are failing and it is impacting both local builds as well as the CI for PRs. For example:

https://github.com/onnx/onnx-mlir/pull/1993

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make[3]: *** [test/backend/CMakeFiles/download_model_for_test_inception_v1.dir/build.make:61: test/backend/Debug/models/inception_v1.tar.gz] Error 2
make[3]: *** Deleting file 'test/backend/Debug/models/inception_v1.tar.gz'
make[2]: *** [CMakeFiles/Makefile2:17407: test/backend/CMakeFiles/download_model_for_test_inception_v1.dir/all] Error 2
```

I'm not really familiar with this set up, so I am not sure whether we can reach out to the owners and figure out what's wrong or if it would be better to disable some tests temporarily.

**Comment by sstamenova** [comment]
@gongsu832 : Can you advise here?

**Comment by philass** [comment]
https://github.com/onnx/onnx/issues/4857

**Comment by sstamenova** [comment]
@philass : It sounds like we should disable the tests from the onnx-mlir side as well unless we're going to update onnx. Can you do that or should I have a look? Thanks!

**Comment by philass** [comment]
Sorry, just saw your message now.

I reviewed the PR. I think it was/is the correct course of action

**Comment by sstamenova** [comment]
Thank you @gongsu832

**Comment by sstamenova** [comment]
Looks like they have a solution in `onnx` to get models from a new location: https://github.com/onnx/onnx/issues/4857#event-8462803624

**Comment by gongsu832** [comment]
> Looks like they have a solution in `onnx` to get models from a new location: [onnx/onnx#4857 (comment)](https://github.com/onnx/onnx/issues/4857#event-8462803624)

OK that simplify things. Once that PR is merged upgrading `third_party/onnx` should allow the backend model tests to pass again.

**Comment by sstamenova** [comment]
onnx 1.13.1 is now available: https://github.com/onnx/onnx/releases/tag/v1.13.1

**Comment by gongsu832** [comment]
@philass Are you OK with upgrading to 1.13.1?

**Comment by cjvolzka** [comment]
Unless @philass has an objection some one else has already started a PR elsewhere, @mikeessen will take a look at pulling in 1.13.1.

**Comment by AlexandreEichenberger** [comment]
> @philass Are you OK with upgrading to 1.13.1?

I believe Philip stated in our last open-source meeting that he was fine by it.

**Comment by AlexandreEichenberger** [comment]
@cjvolzka,  @sstamenova may be on leave by now.
