### ISSUE TITLE
CMake Error at llvm-project/build/lib/cmake/llvm/AddLLVM.cmake:551 (add_dependencies):   The dependency target "MLIRLinalgAnalysis" of target "obj.LmhloPasses" does   not exist

### ISSUE THREAD

**Issue by leoluopy** [onnx/onnx-mlir#2005]
while build onnx-mlir , i met a build error:
CMake Error at llvm-project/build/lib/cmake/llvm/AddLLVM.cmake:551 (add_dependencies):
  The dependency target "MLIRLinalgAnalysis" of target "obj.LmhloPasses" does
  not exist
how to fix it ?
any one has idea ?

**Comment by sstamenova** [comment]
I would start by making sure that you have the right submodules.

`git submodule init && git submodule update --recursive`

It's most likely a mismatch between the mhlo submodule and the version of llvm.

In general, things that are useful in diagnosing an issue like this are:
* which commit are you using
* what platform are you on
* what commands are you running

**Comment by leoluopy** [comment]
yes thanks , after ' git submodule init && git submodule update --recursive ' , then i execute ' git pull ' , i found some hlo code upgraded , then it works .
