### ISSUE TITLE
Upgrade benchmark to the 1.8.0 official release

### ISSUE THREAD

**Issue by hamptonm1** [onnx/onnx-mlir#2006]
Latest release from `google/benchmark` is 1.7.1 which was made available to the public on November 11, 2022. It makes sense to pull in 1.7.2 which will include the PR I merged into that repository along with other updates : https://github.com/google/benchmark/releases

**Comment by hamptonm1** [comment]
@chentong319 @AlexandreEichenberger Are you guys in agreement with this? Also we can ask the broader community if need be :)

**Comment by AlexandreEichenberger** [comment]
Absolutely, would be great to upgrade, esp if it does not require much additional work

**Comment by hamptonm1** [comment]
> Absolutely, would be great to upgrade, esp if it does not require much additional work. Thanks for spotting the upgrade.

Wonderful!! I will keep you guys updated about when 1.7.2 is released :)

**Comment by hamptonm1** [comment]
This is completed!
