### ISSUE TITLE
Segmentation fault (core dumped) [645/647] Linking CXX executable Debug/bin/onnx-mlir-opt ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by leoluopy** [onnx/onnx-mlir#2014]
while building onnx-mlir , i met a core dump .  the logs are shown below:

[642/647] Generating add.so
FAILED: docs/doc_example/add.so /home/er/projects/er/workspace/onnx-mlir/build/docs/doc_example/add.so 
cd /home/er/projects/er/workspace/onnx-mlir/build/docs/doc_example && /home/er/.pyenv/versions/anaconda3-2020.11/bin/python3.8 /home/er/projects/er/workspace/onnx-mlir/build/docs/doc_example/gen_add_onnx.py && /home/er/projects/er/workspace/onnx-mlir/build/Debug/bin/onnx-mlir add.onnx
The model is:
ir_version: 8
producer_name: "onnx-example"
graph {
  node {
    input: "X1"
    input: "X2"
    output: "Y"
    op_type: "Add"
  }
  name: "test-model"
  input {
    name: "X1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 2
          }
        }
      }
    }
  }
  input {
    name: "X2"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 2
          }
        }
      }
    }
  }
  output {
    name: "Y"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 2
          }
        }
      }
    }
  }
}
opset_import {
  version: 17
}

The model is checked!
Segmentation fault (core dumped)
[645/647] Linking CXX executable Debug/bin/onnx-mlir-opt
ninja: build stopped: subcommand failed

my gcc version is 8.4
ninja version is 1.10.2
cmake version is 3.25.1
protobuf is 3.20.3

llvm repo is based at : ba8b8a73fcb6b830e63cd8e20c6e13b2a14d69bf
i am using command below to compile the repo:
cmake -G Ninja         -DCMAKE_CXX_COMPILER=/usr/local/gcc-8.4.0/bin/c++   -DCMAKE_C_COMPILER=/usr/local/gcc-8.4.0/bin/gcc      -DMLIR_DIR=${MLIR_DIR}         ..
cmake --build .

any one has any idea ?

**Comment by leoluopy** [comment]
@gongsu832
i am sorry to say that , opset 18  is not working neither.
the logs at below:

[642/647] Generating add.so
FAILED: docs/doc_example/add.so /home/algo_share/projects/peiyuanluo/workspace/onnx-mlir/build/docs/doc_example/add.so 
cd /home/algo_share/projects/peiyuanluo/workspace/onnx-mlir/build/docs/doc_example && /home/e0004587/.pyenv/versions/anaconda3-2020.11/bin/python3.8 /home/algo_share/projects/peiyuanluo/workspace/onnx-mlir/build/docs/doc_example/gen_add_onnx.py && /home/algo_share/projects/peiyuanluo/workspace/onnx-mlir/build/Debug/bin/onnx-mlir add.onnx
The model is:
ir_version: 8
producer_name: "onnx-example"
graph {
  node {
    input: "X1"
    input: "X2"
    output: "Y"
    op_type: "Add"
  }
  name: "test-model"
  input {
    name: "X1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 2
          }
        }
      }
    }
  }
  input {
    name: "X2"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 2
          }
        }
      }
    }
  }
  output {
    name: "Y"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 2
          }
        }
      }
    }
  }
}
opset_import {
  version: 18
}

The model is checked!
Segmentation fault (core dumped)
[645/647] Linking CXX executable Debug/bin/onnx-mlir-opt
ninja: build stopped: subcommand failed.

any other suggestions ?

**Comment by leoluopy** [comment]
@gongsu832
before i rebuild the onnx-mlir , all files in build directory is cleaned  by  ' rm  -rf * '

**Comment by gongsu832** [comment]
Again, what is your onnx version and the onnx-mlir commit hash you are building? Did you install onnx from `third_party/onnx`? Post the output of the command `cmake -G Ninja ...`

**Comment by chentong319** [comment]
You can try this python script to see the version of your installed onnx
import onnx

print(onnx.__version__)
```

**Comment by leoluopy** [comment]
@gongsu832
thanks for reply. 
i install form onnx/mlir , and i am using anaconda python env , the command for installing onnx is below:

onnx-mlir/third_party/onnx$ python -m pip install .
Processing /home/algo_share/projects/peiyuanluo/workspace/onnx-mlir/third_party/onnx
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: protobuf<4,>=3.20.2 in /home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages (from onnx==1.13.0) (3.20.3)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages (from onnx==1.13.0) (4.4.0)
Requirement already satisfied: numpy>=1.16.6 in /home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages (from onnx==1.13.0) (1.22.4)
Building wheels for collected packages: onnx
  Building wheel for onnx (PEP 517) ... done
  Created wheel for onnx: filename=onnx-1.13.0-cp38-cp38-linux_x86_64.whl size=12564965 sha256=61bca6309fe039b0d8498f095bc35a94bdef42497318a8abbf4b087e453515d9
  Stored in directory: /tmp/pip-ephem-wheel-cache-v8t3620f/wheels/e3/00/50/bf60589848885c95c98525b3aab58bfdee771efad81d433c2c
Successfully built onnx
Installing collected packages: onnx
  Attempting uninstall: onnx
    Found existing installation: onnx 1.13.0
    Uninstalling onnx-1.13.0:
      Successfully uninstalled onnx-1.13.0
Successfully installed onnx-1.13.0

**Comment by leoluopy** [comment]
the output of cmake configuration is below:
onnx-mlir/build$ cmake -G Ninja         -DCMAKE_CXX_COMPILER=/usr/local/gcc-8.4.0/bin/c++   -DCMAKE_C_COMPILER=/usr/local/gcc-8.4.0/bin/gcc      -DMLIR_DIR=${MLIR_DIR}         ..
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/gcc-8.4.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/gcc-8.4.0/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to Debug
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /usr/lib/x86_64-linux-gnu/libtinfo.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Using MLIRConfig.cmake in: /home/algo_share/projects/peiyuanluo/workspace/onnx-mlir/llvm-project/build/lib/cmake/mlir
-- Using LLVMConfig.cmake in: /home/algo_share/projects/peiyuanluo/workspace/onnx-mlir/llvm-project/build/lib/cmake/llvm
-- Linker detection: GNU ld
-- Performing Test C_SUPPORTS_FPIC
-- Performing Test C_SUPPORTS_FPIC - Success
-- Performing Test CXX_SUPPORTS_FPIC
-- Performing Test CXX_SUPPORTS_FPIC - Success
-- Building with -fPIC
-- Performing Test C_SUPPORTS_FNO_SEMANTIC_INTERPOSITION
-- Performing Test C_SUPPORTS_FNO_SEMANTIC_INTERPOSITION - Success
-- Performing Test CXX_SUPPORTS_FNO_SEMANTIC_INTERPOSITION
-- Performing Test CXX_SUPPORTS_FNO_SEMANTIC_INTERPOSITION - Success
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG - Success
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME - Success
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME - Success
-- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
-- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Failed
-- Performing Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
-- Performing Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Failed
-- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG
-- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG - Success
-- Performing Test C_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG
-- Performing Test C_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG - Success
-- Performing Test CXX_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG
-- Performing Test CXX_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG - Success
-- Performing Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG
-- Performing Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG - Failed
-- Performing Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG
-- Performing Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG - Failed
-- Performing Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG
-- Performing Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG - Success
-- Performing Test CXX_SUPPORTS_REDUNDANT_MOVE_FLAG
-- Performing Test CXX_SUPPORTS_REDUNDANT_MOVE_FLAG - Failed
-- Performing Test CXX_SUPPORTS_PESSIMIZING_MOVE_FLAG
-- Performing Test CXX_SUPPORTS_PESSIMIZING_MOVE_FLAG - Failed
-- Performing Test CXX_SUPPORTS_NOEXCEPT_TYPE_FLAG
-- Performing Test CXX_SUPPORTS_NOEXCEPT_TYPE_FLAG - Success
-- Performing Test CXX_WONT_WARN_ON_FINAL_NONVIRTUALDTOR
-- Performing Test CXX_WONT_WARN_ON_FINAL_NONVIRTUALDTOR - Failed
-- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE_FLAG
-- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE_FLAG - Success
-- Performing Test CXX_WSUGGEST_OVERRIDE_ALLOWS_ONLY_FINAL
-- Performing Test CXX_WSUGGEST_OVERRIDE_ALLOWS_ONLY_FINAL - Failed
-- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP
-- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP - Failed
-- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG
-- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG - Failed
-- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG
-- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG - Failed
-- Performing Test CXX_SUPPORTS_MISLEADING_INDENTATION_FLAG
-- Performing Test CXX_SUPPORTS_MISLEADING_INDENTATION_FLAG - Success
-- Performing Test C_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG
-- Performing Test C_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG - Failed
-- Performing Test CXX_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG
-- Performing Test CXX_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG - Failed
-- Performing Test LINKER_SUPPORTS_COLOR_DIAGNOSTICS
-- Performing Test LINKER_SUPPORTS_COLOR_DIAGNOSTICS - Failed
-- Looking for os_signpost_interval_begin
-- Looking for os_signpost_interval_begin - not found
-- BUILD_SHARED_LIBS        : OFF
-- LLVM_REQUIRES_EH         : ON
-- ONNX_MLIR_DEFAULT_TRIPLE : x86_64-unknown-linux-gnu
-- CMAKE_INSTALL_PREFIX     : /usr/local
-- Found Python3: /home/e0004587/.pyenv/versions/anaconda3-2020.11/bin/python3.8 (found version "3.8.5") found components: Interpreter Development Development.Module Development.Embed 
-- Could NOT find Java (missing: Java_JAVAC_EXECUTABLE Java_JAR_EXECUTABLE Java_JAVADOC_EXECUTABLE Java_JAVAH_EXECUTABLE Development) (found version "1.8.0.352")
-- Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2) 
CMake Warning at CMakeLists.txt:119 (message):
  Java Development component or JNI not found, JNI targets will not work


Generated: /home/algo_share/projects/peiyuanluo/workspace/onnx-mlir/build/third_party/onnx/onnx/onnx-ml.proto
Generated: /home/algo_share/projects/peiyuanluo/workspace/onnx-mlir/build/third_party/onnx/onnx/onnx-operators-ml.proto
Generated: /home/algo_share/projects/peiyuanluo/workspace/onnx-mlir/build/third_party/onnx/onnx/onnx-data.proto
-- Accelerators             : NONE
-- Onnx version             : 1.13.0
-- Product version          : 0.0.0-NOT_SPECIFIED
-- Tests optimization level : 3
-- Parallel backend tests   : OFF (install pytest-xdist to enable)
-- JNI backend tests         : OFF
-- Accelerator lit tests    : NONE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/leo/onnx-mlir/build

**Comment by leoluopy** [comment]
onnx-mlir commit id:  66b0e2be9bb39a084cc080a96852b3a9b99a8bd9
llvm commit id: ba8b8a73fcb6b830e63cd8e20c6e13b2a14d69bf
third_party onnx commit id: 1ba785612a79fe749aa1e478336e534743372639

**Comment by leoluopy** [comment]
@chentong319 
thanks for reply
python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 

[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
>>> onnx.__version__
'1.13.0'

**Comment by gongsu832** [comment]
Did you install gcc/g++ manually? If you were using a recent Ubuntu version like Focal, you shouldn't have to explicitly specify CMAKE_C/CXX_COMPILER when running cmake. Unless you know what you are doing, it's not recommended to install gcc/g++ manually. Since it's not just a simple matter of installing the compiler itself. You also have to have compatible level of libc, libstdc++, etc.

**Comment by leoluopy** [comment]
@gongsu832
yes after build gcc8.4 , i install it to /usr/local/gcc-8.4.0/ ,  CMAKE_C/CXX_COMPILER are used for set gcc version to 8.4 , i am working at ubuntu18.04 , so how should i change my building command ? 
looking forward to you reply .

**Comment by gongsu832** [comment]
As I mentioned before, Bionic is too old and we never tested onnx-mlir on it. You need a more recent Ubuntu version where gcc/g++ and all matching libc/libstdc++ etc have been installed system wide by default so you never have to explicitly specify CMAKE_C/CXX_COMPILER when running cmake. You should be able to simply run
```
cmake -G Ninja -DMLIR_DIR=${MLIR_DIR} ..
```
If you insist on Bionic, you are really on your own. You can run the command that caused the segfault through gdb
```
cd /home/er/projects/er/workspace/onnx-mlir/build/docs/doc_example
/home/er/.pyenv/versions/anaconda3-2020.11/bin/python3.8 /home/er/projects/er/workspace/onnx-mlir/build/docs/doc_example/gen_add_onnx.py
gdb --args home/er/projects/er/workspace/onnx-mlir/build/Debug/bin/onnx-mlir add.onnx
```
and get a backtrace and see what caused the segfault. My guess is that your manually installed gcc/g++ 8 aren't playing well with the rest of the system default libc/libstdc++ (which are still on level 7), etc.

**Comment by leoluopy** [comment]
@gongsu832 
sure , i am going to upgrade my ubuntu to 20.04 (Focal) , and i 'll try again .

**Comment by leoluopy** [comment]
@gongsu832 
thanks for your contribution for solving this problem . finally , i found this solution : 
if i am compiling onnx-mlir at ubuntu 18.04 , gcc8.4 will be required . both llvm-project and onnx-mlir should pass the macro to the build cmake command, the command example is below [note: gcc8.4 is installed to /usr/local/bin/]: 
-DCMAKE_C_COMPILER=/usr/local/bin/gcc -DCMAKE_CXX_COMPILER=/usr/local/bin/g++
