### ISSUE TITLE
gcc version in README

### ISSUE THREAD

**Issue by weimingzha0** [onnx/onnx-mlir#2018]
README states that "gcc >= 6.4", but src/Compiler/CompilerUtils.cpp includes charconv.h , which is only available for gcc 8 or higher.

**Comment by weimingzha0** [comment]
https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html 
charconv is only supported since gcc 8.1.
And no uses of from_chars/to_chars in .cpp file, so we should remove the include.

**Comment by AlexandreEichenberger** [comment]
@gongsu832 I let you asses if we should increase the gcc requirement

**Comment by tungld** [comment]
@weimingzha0  Could we close this as #2019 is expected to solve the issue?

**Comment by weimingzha0** [comment]
Yes
