### ISSUE TITLE
Warning as error

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#2027]
New issue that continues #936 .

I believe the warning due to the unused parameter in LLVM header files (isPossible) is now fixed in LLVM:
https://reviews.llvm.org/rG82ae83a8487df0747195d1abbda11920fda11eb8

However there remain some other unused parameters warnings (but much much fewer).

```
/workdir/llvm-project/mlir/include/mlir/IR/AttrTypeSubElements.h:412:37: warning: parameter 'derived' set but not used [-Wunused-but-set-parameter]
  412 | void walkImmediateSubElementsImpl(T derived,
      |                                   ~~^~~~~~~
```

LLVM indicates that it supports our gcc level
https://llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library
but obviously their tests may not test our specific compiler and/or do not flag warning as error.

@sstamenova suggested that we add a builedbot to mlir to force MLIR developers to address these issues upfront.
@gongsu832 was going to look into this.

**Comment by hamptonm1** [comment]
@AlexandreEichenberger The above issue was fixed on March 14th by Mehdi in the LLVM community: https://reviews.llvm.org/D146107. So about 2 weeks ago he committed these changes... I am assuming with the next llvm upgrade we should be able to pull in those changes. Should we keep this issue opened until it is verified then?

**Comment by hamptonm1** [comment]
@cjvolzka FYI

**Comment by AlexandreEichenberger** [comment]
> Should we keep this issue open until it is verified then?

I would think so

**Comment by hamptonm1** [comment]
Just in case: https://github.com/llvm/llvm-project/commit/8f072bbd74021d1aee913ae500d439a23b591297

**Comment by hamptonm1** [comment]
Okay I just pulled in the latest changes for llvm and rebuilt my container. It seems like the warning above is resolved. @sorenlassen just fixed a few new warnings that were introduced.

**Comment by hamptonm1** [comment]
@AlexandreEichenberger @sorenlassen Can you confirm on your end as well that this no longer appears? 

```
/workdir/llvm-project/mlir/include/mlir/IR/AttrTypeSubElements.h:412:37: warning: parameter 'derived' set but not used [-Wunused-but-set-parameter]
  412 | void walkImmediateSubElementsImpl(T derived,
      |                                   ~~^~~~~~~
```

If so we can close this one out and I know there is further work to be done here but that is most likely a separate issue.

**Comment by sorenlassen** [comment]
@hamptonm1 I'm not seeing any warnings on MacOS and I believe we know our Windows build checks there are no warnings there, but if you look at the linux builds they have some warnings

see e.g. https://www.onnxmlir.xyz/jenkins/job/ONNX-MLIR-Pipeline-Docker-Build/10634/console

you can run through all the builds by going to a recently merged PR like #2152 and click on the build links posted by the jenkins-droid as comments after the merge

**Comment by sorenlassen** [comment]
> walkImmediateSubElementsImpl

I haven't tracked that warning so not sure if it was resolved upstream or what happened

**Comment by hamptonm1** [comment]
> > walkImmediateSubElementsImpl
> 
> I haven't tracked that warning so not sure if it was resolved upstream or what happened

It has been :) https://reviews.llvm.org/D146107.

I do not see it anymore but will look into this new warning.

**Comment by sorenlassen** [comment]
@hamptonm1 @AlexandreEichenberger going by the issue title, should we keep this issue open until we change the compiler flags to error on warnings on all platforms? or shall we create another issue for that aspiration?

**Comment by cjvolzka** [comment]
@sorenlassen I was originally thinking this Issue was to change the compiler flags to error on warnings. Clearing the current warnings was more a prerequisite to that goal.

@hamptonm1 I'm indifferent either way. If there's another issue already opened to make the warnings error a build, we can use a comment to link them and then close this one. If there's not, we can continue under this Issue. Either way this one should stay open for the moment.

**Comment by hamptonm1** [comment]
@sstamenova @gongsu832 Is there an issue already open for the potential bot? If so we can close this one out and potentially fix the warnings as we go like what we are doing now.

**Comment by gongsu832** [comment]
The LLVM no warning buildbot for zLinux is running and needs some stable time after we upgraded to Ubuntu Jammy. I plan to ask the person in charge to move our bot from staging to production next week if nothing bad happens.

**Comment by hamptonm1** [comment]
> The LLVM no warning buildbot for zLinux is running and needs some stable time after we upgraded to Ubuntu Jammy. I plan to ask the person in charge to move our bot from staging to production next week if nothing bad happens.

Thanks, do you have an issue to track your work efforts or are you planning to open one?

**Comment by AlexandreEichenberger** [comment]
@hamptonm1 

here is the warning that I still see
```
/workdir/onnx-mlir/src/Transform/ONNX/Decompose.cpp: In copy constructor '{anonymous}::DecomposeONNXToONNXPass::DecomposeONNXToONNXPass(const {anonymous}::DecomposeONNXToONNXPass&)':
/workdir/onnx-mlir/src/Transform/ONNX/Decompose.cpp:736:25: warning: implicitly-declared 'mlir::Pass::Option<std::__cxx11::basic_string<char> >& mlir::Pass::Option<std::__cxx11::basic
_string<char> >::operator=(const mlir::Pass::Option<std::__cxx11::basic_string<char> >&)' is deprecated [-Wdeprecated-copy]
  736 |     this->target = pass.target;
      |                         ^~~~~~
In file included from /workdir/llvm-project/mlir/include/mlir/Pass/PassRegistry.h:17,
                 from /workdir/llvm-project/mlir/include/mlir/Pass/Pass.h:13,
                 from /workdir/onnx-mlir/src/Transform/ONNX/Decompose.cpp:25:
/workdir/llvm-project/mlir/include/mlir/Pass/PassOptions.h:176:13: note: because 'mlir::Pass::Option<std::__cxx11::basic_string<char> >' has user-provided 'mlir::detail::PassOptions::
Option<DataType, OptionParser>& mlir::detail::PassOptions::Option<DataType, OptionParser>::operator=(const mlir::detail::PassOptions::Option<DataType, OptionParser>&) [with DataType =
 std::__cxx11::basic_string<char>; OptionParser = llvm::cl::parser<std::__cxx11::basic_string<char> >]'
  176 |     Option &operator=(const Option &other) {
      |             ^~~~~~~~
```

No others... and that was when building on x86 linux.

**Comment by hamptonm1** [comment]
@AlexandreEichenberger Seems like a different warning but @sorenlassen opened a draft PR to resolve.

**Comment by gongsu832** [comment]
> > The LLVM no warning buildbot for zLinux is running and needs some stable time after we upgraded to Ubuntu Jammy. I plan to ask the person in charge to move our bot from staging to production next week if nothing bad happens.
> 
> @gongsu832 Thanks, do you have an issue to track your work efforts or are you planning to open one?

As far as I know, there is no issue needs to be opened. The necessary patch to enable the buildbot was already submitted by @sstamenova.

**Comment by cjvolzka** [comment]
Ok. If there's a patch to setup the buildbot that detects and lets us know of the warnings then I'm good with closing this.

**Comment by sorenlassen** [comment]
I noticed this warning in "GitHub Action MacOS amd64 / build" https://github.com/onnx/onnx-mlir/actions/runs/4724057833/jobs/8380798892?pr=2169
```
[613/689] Building CXX object src/Compiler/CMakeFiles/PyCompile.dir/PyOMCompileSession.cpp.o
In file included from /Users/runner/work/onnx-mlir/onnx-mlir/src/Compiler/PyOMCompileSession.cpp:17:
In file included from /usr/local/include/pybind11/numpy.h:12:
In file included from /usr/local/include/pybind11/pybind11.h:13:
In file included from /usr/local/include/pybind11/detail/class.h:12:
In file included from /usr/local/include/pybind11/detail/../attr.h:14:
In file included from /usr/local/include/pybind11/cast.h:15:
/usr/local/include/pybind11/detail/type_caster_base.h:591:13: warning: default label in switch which covers all enumeration values [-Wcovered-switch-default]
            default:
            ^
1 warning generated.
```

**Comment by sorenlassen** [comment]
warning in "Jenkins Linux ppc64le"
https://www.onnxmlir.xyz/jenkinp/job/ONNX-MLIR-Pipeline-Docker-Build/9773/
```
[ 47%] Building CXX object third_party/mlir-hlo/stablehlo/stablehlo/dialect/CMakeFiles/obj.StablehloOps.dir/StablehloBytecode.cpp.o
In file included from /workdir/llvm-project/mlir/include/mlir/IR/AttrTypeSubElements.h:20,
                 from /workdir/llvm-project/mlir/include/mlir/IR/StorageUniquerSupport.h:16,
                 from /workdir/llvm-project/mlir/include/mlir/IR/AttributeSupport.h:17,
                 from /workdir/llvm-project/mlir/include/mlir/IR/Attributes.h:12,
                 from /workdir/llvm-project/mlir/include/mlir/IR/BuiltinAttributeInterfaces.h:13,
                 from /workdir/llvm-project/mlir/include/mlir/IR/BuiltinTypes.h:12,
                 from /workdir/llvm-project/mlir/include/mlir/Dialect/Affine/IR/AffineMemoryOpInterfaces.h:17,
                 from /workdir/llvm-project/mlir/include/mlir/Dialect/Affine/IR/AffineOps.h:17,
                 from /workdir/onnx-mlir/src/Accelerators/NNPA/Transform/ZLow/ZLowRewrite.cpp:15:
/workdir/llvm-project/llvm/include/llvm/ADT/DenseMap.h: In member function 'virtual void onnx_mlir::zlow::ZLowRewritePass::runOnOperation()':
/workdir/llvm-project/llvm/include/llvm/ADT/DenseMap.h:1183:18: warning: '*((void*)(& removableStickOps)+16).llvm::SmallDenseMap<onnx_mlir::zlow::ZLowStickOp, llvm::detail::DenseSetEmpty, 4, llvm::DenseMapInfo<onnx_mlir::zlow::ZLowStickOp, void>, llvm::detail::DenseSetPair<onnx_mlir::zlow::ZLowStickOp> >::LargeRep::NumBuckets' may be used uninitialized in this function [-Wmaybe-uninitialized]
     return Small ? InlineBuckets : getLargeRep()->NumBuckets;
            ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/workdir/llvm-project/llvm/include/llvm/ADT/DenseMap.h:1174:18: warning: '*((void*)(& removableStickOps)+16).llvm::SmallDenseMap<onnx_mlir::zlow::ZLowStickOp, llvm::detail::DenseSetEmpty, 4, llvm::DenseMapInfo<onnx_mlir::zlow::ZLowStickOp, void>, llvm::detail::DenseSetPair<onnx_mlir::zlow::ZLowStickOp> >::LargeRep::Buckets' may be used uninitialized in this function [-Wmaybe-uninitialized]
     return Small ? getInlineBuckets() : getLargeRep()->Buckets;
            ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
