### ISSUE TITLE
failure of test_if_cpu with fold enabled

### ISSUE THREAD

**Issue by chentong319** [onnx/onnx-mlir#2033]
@sorenlassen and I encountered backend test failure on test_if_cpu when experimenting constant folding in onnx dialect. I figured out the reason is related to ownership of the returned tensor.
The data pointer of the returned tensor will be freed in the runtime driver if the tensor owns the data pointer. The special case is for constantOp, which is lowered to llvm.constant. The space for constant does not come from malloc. onnx-mlir (around line 120 of  file `src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.cpp`)  tried to handle the cases of constant, but missed the case for test_if_cpu with folding. The IF op is turned into an arith.select, which is not specially checked.
The IR with fold:
```
    %0 = "krnl.global"() {name = "constant_0", shape = [5], value = dense<[5.000000e+00, 4.000000e+00, 3.000000e+00, 2.000000e+00, 1.000000e+00]> : tensor<5xf32>} : () -> memref<5xf32>
    %1 = "krnl.global"() {name = "constant_1", shape = [5], value = dense<[1.000000e+00, 2.000000e+00, 3.000000e+00, 4.000000e+00, 5.000000e+00]> : tensor<5xf32>} : () -> memref<5xf32>
    %2 = affine.load %arg0[] : memref<i1>
    %3 = arith.select %2, %1, %0 : memref<5xf32>
    return %3 : memref<5xf32>
```
Compared without fold:
```
    %0 = affine.load %arg0[] : memref<i1>
    %1 = scf.if %0 -> (memref<5xf32>) {
      %2 = "krnl.global"() {name = "constant_0", shape = [5], value = dense<[1.000000e+00, 2.000000e+00, 3.000000e+00, 4.000000e+00, 5.000000e+00]> : tensor<5xf32>} : () -> memref<5xf32>
      scf.yield %2 : memref<5xf32>
    } else {
      %2 = "krnl.global"() {name = "constant_1", shape = [5], value = dense<[5.000000e+00, 4.000000e+00, 3.000000e+00, 2.000000e+00, 1.000000e+00]> : tensor<5xf32>} : () -> memref<5xf32>
      scf.yield %2 : memref<5xf32>
    }
    return %1 : memref<5xf32>
```
The reason is that constant folding moves all the constant to the beginning of the function. We should think more about the  impact of performance.
In my fold PR #2009 , I added a hack for this special case to let backend test pass. But it is NOT a correct fix. We need to figure out how to fix this with another PR.

**Comment by chentong319** [comment]
More details about the issue.
onnx-mlir uses the bufferization deallocation pass to insert dealloc for memref. However, deallocation will not be added for the returned memref, which will be used after function call. However, if a memref comes from a constant, its memory is not allocated from heap and then can not freed by caller. The ownership is recorded in the returned OMTenser. 
The tricky part is how to know the returned memref is an allocated memref or a constant.  Previously, we only follow the definition chain for view-like ops. IFOp created a selectOp. Any other possible definition case?
I think we can add an Identify Op for the returned memref. If deallocation pass adds deallocation,  then  the previous returned memref owns the data. We do not need to really generate the copy for Identify Op in the final code.

**Comment by sorenlassen** [comment]
Thanks for sharing. Your ideas sound good to me. I'm impressed by what you were able to figure out. As I mentioned to you when we talked last week, I tried to troubleshooting this issue last year and was completely stumped.
