### ISSUE TITLE
Print pass/fail message on modelzoo tests

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#2069]
Currently if a modelzoo test run times out or fails, the only console log we capture is the list of models skipped:
```
[2023-03-07 14:08:34,216] WARNING: The model bertsquad-12-int8 is excluded. Ignored.
[2023-03-07 14:08:34,233] WARNING: The model shufflenet-3 is excluded. Ignored.
[2023-03-07 14:08:34,241] WARNING: The model FasterRCNN-12-int8 is excluded. Ignored.
```

It'd be useful to also print a pass or fail message as well. Then if the build fails to upload the overall modelzoo results, we can use the logs to know how the models it attempted faired.

At a glance it might be as simple as a logger.info with the model name and the `state` at https://github.com/onnx/onnx-mlir/blob/main/utils/RunONNXModelZoo.py#L333-L334

**Comment by gongsu832** [comment]
Those warning messages were printed while the models are checking in parallel by the python `Parallel` package. They are not an indication of how far the check has progressed. There is a verbosity level for Parallel that you can crank up but that results in a huge amount of output which will completely clutter the console output even just at the INFO level I think. Parallel actually prints out a simple one line progress indicator showing how many jobs have finished/are running but the period between the printouts seems to be unpredictable. Need to look a bit more in how Parallel output works.

**Comment by gongsu832** [comment]
So it looks like on all the Linux Jenkins CI our modelzoo tests are stuck running the two failed models you reported:
```
    725 ?        R    1236:34 python3 /workdir/RunONNXModel.py --compile-args=-O3 --verify=ref --data-folder=/tmp/tmpjy3orvir/roberta-sequence-classification-9/test_data_set_0 --model=/tmp/tmpjy3orvir/roberta-sequence-classification-9/roberta-sequence-classification-9.onnx
   1094 ?        R    1234:29 python3 /workdir/RunONNXModel.py --compile-args=-O3 --verify=ref --data-folder=/tmp/tmpz8zpyu0i/gpt2-lm-head-10/GPT-2-LM-HEAD/test_data_set_0 --model=/tmp/tmpz8zpyu0i/gpt2-lm-head-10/GPT-2-LM-HEAD/model.onnx
```
Not sure why they just stuck instead of fail. Need to dig a bit deeper to see if there is any diag info.
