### ISSUE TITLE
Regression: roberta-sequence-classification-9 returns bad values on CPU

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#2072]
The [roberta-sequence-classification-9](https://github.com/onnx/models/blob/main/text/machine_comprehension/roberta/model/roberta-sequence-classification-9.onnx)  model returns incorrect results inferencing for CPU and NNPA on s390x using the latest onnx-mlir commits.

Unfortunately the last commit to post a modelzoo status at https://www.onnxmlir.xyz/jenkins/job/ONNX-MLIR-Pipeline-Docker-Build/Model_20Zoo_20Report/ is a couple of days old. Commit https://github.com/onnx/onnx-mlir/commit/e0a1504c9ae319ac6856ba67a334ab918fa8c193 appeared fine. Somewhere after that is when the issue started.

(CPU output (.tests is a flat text file made based on the example input and output from [roberta-sequence-classification-9.tar.gz](https://github.com/onnx/models/blob/main/text/machine_comprehension/roberta/model/roberta-sequence-classification-9.tar.gz). The "actual" values are what onnx-mlir returned. The "exp" values are from the model zoo's tar.gz))
```
onnxmlirczar/onnx-mlir --version
onnx-mlir version 0.4.0, onnx version 1.13.1 (https://github.com/onnx/onnx-mlir.git 115161446650842b58ea24c2bd3bf4ef95b0a2c0)


onnxmlirczar/onnx-mlir --O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z14 /workdir/roberta-sequence-classification-9.onnx -v
[/]/usr/local/bin/opt: opt -O3 --mtriple=s390x-ibm-loz --mcpu=z14 -o /workdir/roberta-sequence-classification-9.bc /workdir/roberta-sequence-classification-9.unoptimized.bc
[/]/usr/local/bin/llc: llc -O3 --mtriple=s390x-ibm-loz --mcpu=z14 -filetype=obj -relocation-model=pic -o /workdir/roberta-sequence-classification-9.o /workdir/roberta-sequence-classification-9.bc
[/]/usr/bin/c++: c++ /workdir/roberta-sequence-classification-9.o -o /workdir/roberta-sequence-classification-9.so -shared -fPIC -L/usr/local/lib -lcruntime
Shared library /workdir/roberta-sequence-classification-9.so has been compiled.

client/bin/modelzoo --lib ./roberta-sequence-classification-9.so -validate --file roberta-sequence-classification-9.tests
Iteration 0 dataset 0: Reading
gen_data_set_lists() loading 1 input tensor(s): 
gen_next_tensor() processing tensor with shape ( 1 1 ) totaling 1 elements of type ONNX_TYPE_INT64
gen_data_set_lists() loading 1 expected output tensor(s): 
gen_next_tensor() processing tensor with shape ( 1 2 ) totaling 2 elements of type ONNX_TYPE_FLOAT
Iteration 0 dataset 0: Running
Iteration 0 dataset 0: runMainGraph() took 60.5762 ms
Iteration 0 dataset 0: Validating
Comparing dataset 0 output tensor 0
Actual output tensor shape (1, 2) totaling 2 elements
Tolerance settings: a_tol = 0.010000, r_tol = 0.000000, ulps_tol = 1, x_cutoff = 10.000000
idx    actual              exp                 t   u   rtn 
----------------------------------------------------------------------------------------
0      0.384031            0.454576            F   F   F   abs_diff = 0.070545, tol_cutoff = 0.010000, min_pass_r_tol = 0.133191, ULPs diff = 145
1      -0.845578           -0.353323           F   F   F   abs_diff = 0.492255, tol_cutoff = 0.010000, min_pass_r_tol = 1.364915, ULPs diff = 654
----------------------------------------------------------------------------------------

```

Notes:
* Other models work fine with the same test application and in previous versions, this model worked fine with the client so I don't believe it's an issue with the test application.
* roberta-base-11 works fine for both CPU and NNPA so the issue is specific to this model and not all roberata models.

**Comment by gongsu832** [comment]
@tungld When checking the model with `RunONNXModel.py`, inference fails with an assertion:
```
# VERBOSE=true ONNX_MLIR_HOME=Debug python3 ../utils/RunONNXModel.py --compile-args=-O3 --verify=ref --data-folder=roberta-sequence-classification-9/test_data_set_0 --model=roberta-sequence-classification-9/roberta-sequence-classification-9.onnx
Temporary directory has been created at /tmp/tmpsuygud9a
Compiling the model ...
['Debug/bin/onnx-mlir', '-O3', '/tmp/tmpsuygud9a/model.onnx', '-o', '/tmp/tmpsuygud9a/model']
  took  159.20930814230815  seconds.

Loading the compiled model ...
  took  0.00029593193903565407  seconds.

Reading inputs from roberta-sequence-classification-9/test_data_set_0 ...
  - 1st input: [1x1xint64]
  done.

Running inference ...
  took  2760.7563071646728  seconds.

Reading reference outputs from roberta-sequence-classification-9/test_data_set_0 ...
  - 1st output: [1x2xfloat32]
  done.

Verifying value of output:[1, 2] using atol=0.01, rtol=0.05 ...
  at (0, 0) mismatch 1.165763258934021 (actual) vs 0.45457595586776733 (reference)
  at (0, 1) mismatch -1.39717698097229 (actual) vs -0.3533233106136322 (reference)
Traceback (most recent call last):
  File "/opt/Downloads/onnx-mlir/build-shared/../utils/RunONNXModel.py", line 532, in <module>
    main()
  File "/opt/Downloads/onnx-mlir/build-shared/../utils/RunONNXModel.py", line 526, in main
    raise AssertionError(
AssertionError:   mismatched elements 2/2.
```
But the assertion failure doesn't seem to end the subprocess `RunONNXModel.py`. Is there a particular reason why the code uses AssertionError instead of a normal print then exit?
```
                if mismatched_elements == 0:
                    print("  correct.\n".format(args.atol, args.rtol))
                else:
                    raise AssertionError(
                        "  mismatched elements {}/{}.\n".format(
                            mismatched_elements, total_elements))
```

**Comment by tungld** [comment]
> But the assertion failure doesn't seem to end the subprocess RunONNXModel.py. Is there a particular reason why the code uses AssertionError instead of a normal print then exit?

We use AssertionError so that the other script `RunONNXModelZoo.py` knows whether the model inference produces an error or not. By that way, we know a model is passed the test or not.

**Comment by gongsu832** [comment]
But if you look at the 19 failed models, none of them failed due to assertion. When `RunONNXModel.py` runs as a subprocess of `RunONNXModelZoo.py`, the AssertionError exception does not propagate across the two. What determines whether `RunONNXModel.py` failed or not is really its return code, which is checked by `execute_commands`. In other words, as long as `RunONNXModel.py` exit with a non-zero code, `RunONNXModelZoo.py` knows it failed.

But non-caught AssertionError does exit with a non-zero code 1. So `RunONNXModelZoo.py` shouldn't have been stuck. There must be some other problem to cause this model inference to stuck, just like the other GPT2 model.

**Comment by tungld** [comment]
Have you tried with `-0{0,1,2}` instead of `-03` (I am updating LLVM and haven't had chance to test these models)? I see one commit `111f39a` about SIMD but there was no model zoo record related to that commit. It looks like `RunONNXModelZoo.py` has stuck since `111f39a`

**Comment by gongsu832** [comment]
No I haven't. I will give it a try. By the way, how long do these inferences take typically? Perhaps we should add a timeout on the subprocess to handle this case when the inference somehow gets stuck?

**Comment by tungld** [comment]
> By the way, how long do these inferences take typically? Perhaps we should add a timeout on the subprocess to handle this case when the inference somehow gets stuck?

It depends on each model. For these failed models, it's 1 or 2 seconds for batch size 1.

**Comment by gongsu832** [comment]
Hmm...I just saw that inference is run through OMExecutionSession, not subprocess. So it's not easy to add a timeout.

I forgot to mention, the stucked GPT-2 inference was on a z13 so it shouldn't have anything to do with SIMD.

**Comment by tungld** [comment]
>  In any case, would 5 minutes be a reasonable upper limit for inference?

Looking at the model zoo report, it seemed most of models finished in under 5 minutes except ResNet101-DUC-12 and ResNet101-DUC-7 that took about 730 seconds.

**Comment by tungld** [comment]
Current status with the latest branch: `roberta-sequence-classification-9` and `gpt2-lm-head-10` get stuck, while `gpt2-10` returns bad values.

**Comment by cjvolzka** [comment]
I reran the test after https://github.com/onnx/onnx-mlir/pull/2094 merged and the test now passes. Thanks!
