### ISSUE TITLE
Add const to public interfaces where appropriate

### ISSUE THREAD

**Issue by NathanielMcVicar** [onnx/onnx-mlir#2075]
I've noticed that there are some missing consts on copied inputs, for example `int64_t* shape` for `omTensorCreate()`. This appears to be leading to unnecessary casting away constness for users. Is there any reason not to change this? If not, I can do a more thorough review of parameters where they could be added.

**Comment by gongsu832** [comment]
Mostly because we weren't paying attention in the beginning and now we want to keep them unchanged as much as possible for compatibility reasons. But I don't think adding const would be a problem. @cjvolzka agree?

**Comment by cjvolzka** [comment]
Agreed. We're already doing some other API changes for the next release so this would be minor by comparison. If possible it'd be nice to include this by the end of the week or it's all part of the same release.

**Comment by NathanielMcVicar** [comment]
Thanks so much for the resolution @cjvolzka! I'm going to close this.
