### ISSUE TITLE
struggling with a failure during onnx-mlir build

### ISSUE THREAD

**Issue by developerChans** [onnx/onnx-mlir#2095]
First of all, I have installed all the necessary prerequisites before building onnx-mlir. I am currently using VMware environment with Ubuntu20.04 LTS operating system, and the versions of each prerequisite are as follows: "python = 3.8, gcc = 9.4.0, protobuf = 3.21.11, cmake = 3.25.3, make = 4.2.1, ninja = 1.10.0".

I also installed llvm by following these steps:

```
$ git clone -n https://github.com/llvm/llvm-project.git
# Check out a specific branch that is known to work with ONNX-MLIR.
$ cd llvm-project && git checkout e864ac694540342d5e59f59c525c5082f2594fb8 && cd ..
$ mkdir llvm-project/build
$ cd llvm-project/build
$ cmake -G Ninja ../llvm \
   -DLLVM_ENABLE_PROJECTS=mlir \
   -DLLVM_TARGETS_TO_BUILD="host" \
   -DCMAKE_BUILD_TYPE=Release \
   -DLLVM_ENABLE_ASSERTIONS=ON \
   -DLLVM_ENABLE_RTTI=ON

$ cmake --build . -- ${MAKEFLAGS}
$ cmake --build . --target check-mlir
```

Then, I cloned onnx-mlir inside the llvm folder, created a build folder, and I am currently in the process of making a shell file. My shell file is as follows:

```
# MLIR_DIR must be set with cmake option now
MLIR_DIR=/home/user/llvm-project/build/lib/cmake/mlir
if [[ -z "$pythonLocation" ]]; then
  cmake -G Ninja \
        -DCMAKE_CXX_COMPILER=/usr/bin/c++ \
        -DMLIR_DIR=${MLIR_DIR} \
        ..
else
  cmake -G Ninja \
        -DCMAKE_CXX_COMPILER=/usr/bin/c++ \
        -DPython3_ROOT_DIR=$pythonLocation \
        -DMLIR_DIR=${MLIR_DIR} \
        ..
fi
cmake --build .

# Run lit tests:
export LIT_OPTS=-v
cmake --build . --target check-onnx-lit
```

However, I encountered two errors in /home/user/llvm-project/onnx-mlir/third_party/mlir-hlo/stablehlo/stablehlo/dialect/Base.td, which say "error: Variable not defined: 'F8E5M2', error: Variable not defined: 'F8E4M3FN'". Can you help me with what the problem might be?

**Comment by philass** [comment]
Do you care about the `MHLO` backend?

If you don't, you could try to add `-DONNX_MLIR_ENABLE_MHLO=OFF"` to your CMake command.
```
 cmake -G Ninja \
        -DCMAKE_CXX_COMPILER=/usr/bin/c++ \
        -DMLIR_DIR=${MLIR_DIR} \
        -DONNX_MLIR_ENABLE_MHLO=OFF\
        ..
```

**Comment by developerChans** [comment]
I haven't started onnx-mlir yet, so I'm not sure what part I'm interested in, but I'm currently trying to add a custom dialect (Quantized Operator) to the dialect of onnx-mlir. In addition, we plan to implement an Operator that operates by porting it with hardware. In this case, can I use the method you recommended?

**Comment by AlexandreEichenberger** [comment]
If you are doing this for a custom accelerator, I would recommend that you read on our supports for accelerator in the doc as well as look at the code for our NNPA accelerator.

If you believe that your quantized support may be of benefits for a general audience, then it might be appropriate to add it into our general set of dialects.

You may want to consider attending our Tu meetings (see wiki page) if you want to present what you are generally trying to do for us to get a better sense of what you are after.

**Comment by sorenlassen** [comment]
I can't recreate the particular error you saw but, in general, for third_party make sure you `git clone` onnx-mlir with the `--recursive` flag (see https://github.com/onnx/onnx-mlir/blob/main/docs/BuildOnLinuxOSX.md#build)

moreover, sometimes third_party stuff goes out of sync (`git status` output will say so) and you need to run
```
git submodule update --init --recursive
```

**Comment by AlexandreEichenberger** [comment]
Yes, I agree @sorenlassen

I typically nuke the `thrid_party` dir, then followed by a  `git submodule update --init --recursive ` and  a `pip install -e third_party/onnx` to reinstall ONNX.

maybe should do a script that does it and named `strange_errors_hope_this_will_help.sh` :-)

**Comment by developerChans** [comment]
Sorry for my very late reply. 
It was late because I was interested in onnxruntime open-source, so I was working on the source in parallel.

I feel grateful to all of you for your help.
Thanks to this, I was able to build onnx-mlir well.
