### ISSUE TITLE
Bug with `make check-onnx-backend` and `ONNX_MLIR_FLAGS` being ignored

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#2155]
For some reasons, the `ONNX_MLIR_FLAGS` is ignored when `TEST_CASE_BY_USER` is used.

```
ONNX_MLIR_FLAGS="-march=xxx" TEST_CASE_BY_USER=test_batchnorm_epsilon_cpu make check-onnx-backend
```
succeeds, which it should not as `-march=xxx` is not a valid machine option. Use that test to see that the flag is being ignored.

However, when I remove the `TEST_CASE_BY_USER` option

```
ONNX_MLIR_FLAGS="-march=xxx"  make check-onnx-backend

llc: error: invalid target 'xxx'.
llc -O3 --mtriple=x86_64-unknown-linux-gnu --march=xxx -filetype=obj -relocation-model=pic -o /tmp/tmpnmbpx6pd/inception_v1/inception_v1.o /tmp/tmpnmbpx6pd/inception_v1/inception_v1.bc
Error message: 
Program path: /workdir/llvm-project/build/bin/llc
```
the build fails, as expected, as the option `march` is invalid.

Same thing happens whether the env variables are defined on the fly, or exported using the `export ONNX_MLIR_FLAGS` command

**Comment by gongsu832** [comment]
It wasn't ignored and the test does fail. But the failure was not reported properly. Fixed in https://github.com/onnx/onnx-mlir/pull/2157
