### ISSUE TITLE
Question about empty tensor

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#216]
For ConstantOfShape operator (https://github.com/onnx/onnx/blob/master/docs/Operators.md#inputs-20), its input can be an empty tensor. 
```
input : T1
1D tensor. The shape of the expected output tensor. If empty tensor is given, the output would be a scalar. All values must be >= 0.
```

How do we import an empty tensor? How do we check that a tensor is empty or not?

**Comment by tjingrant** [comment]
Hi @tungld , reading the spec literally, given that T1 is a 1-D tensor, I'd expect its representation within MLIR to be `tensor<0xi64>` or something to that effect. I do not expect importing of such tensor to be an issue, given that MLIR should support it and for us it'd be an ONNX tensor with 1 dimension whose extent is 0. So checking for its emptiness should entail checking the size of its only dimension to be 0.

**Comment by tungld** [comment]
Thanks @tjingrant ! You are right, I found information about zero-element tensor in MLIR here: https://mlir.llvm.org/docs/LangRef/#tensor-type. A zero-element tensor type is `tensor<0xf32>`
