### ISSUE TITLE
Memory Leak with Java client

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#2171]
Applications using models compiled with --EmitJNI slowly leak memory after ever mainGraph() call.

## Reproduce:
 
1. Compile [mnist-12.onnx](https://github.com/onnx/models/blob/main/vision/classification/mnist/model/mnist-12.onnx) model using onnx-mlir using 
    * CPU: `--O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z14 --onnx-op-stats TXT`
    * NNPA: `--O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z16 --maccel=NNPA --onnx-op-stats TXT` 
2. Build the [Leaker.java.txt](https://github.com/onnx/onnx-mlir/files/11243310/Leaker.java.txt) Java application: `MODEL=mnist-12.jar; javac -cp mnist-12.jar Leaker.java`
    * Calls `mainGraph()` continuously for 5 min. Change `run_max_sec` to a different value if desired.
4. Run the Leaker Java application: `java -cp .:$MODEL Leaker`
5. Watch java RES memory usage: `top -d1 -u $USER

## Expected results:
Java does it's own memory management so usage may fluctuate, but it should remain about the same after 10-30 seconds.

## Actual Results
The program continues to slowly uses more and more memory, 

## Notes:
* Affects both CPU and NNPA. Leak is faster with NNPA but that is likely due to the model running faster.
* Issue is specific to Java clients. The same test on the same .so has no leak.
    * Extract the .so can from the .jar file. 
        * `unzip mnist-12.jar -d unzipped_jar`
    * Run with [leaker.cpp.txt](https://github.com/onnx/onnx-mlir/files/11243314/leaker.cpp.txt)
        * `MODEL=unzipped_jar/libmodel.so; g++ -g --std=c++11 -O3 leaker.cpp $MODEL -o leaker -I include && time ./leaker`
    *  C++ does not continuously use more memory
    * using `valgrind` says no leakers are possible

**Comment by cjvolzka** [comment]
Notes from an investigation by another internal team member (Thanks Tabari!)

> Based on my quick reading of the code, the JNI never frees the buffer that is created and associated with the `DirectByteBuffer` that is passed to the OMTensor constructor.

> Java doesn't know how to clean up directbytebuffers that are created via JNI (it doesn't know how to) so the wrapper needs to figure out when to do it as a part of the OMTensor lifetime.

> As an alternative, Instead of directly creating a DirectByteBuffer the alternative is to have the JNI invoke `ByteBuffer.allocateDirect`, and that will cause Java to perform the allocation and cleanup of the memory. It should work out since I'm not seeing any special requirements w.r.t. the allocation

**Comment by gongsu832** [comment]
The JNI wrapper doesn't allocate/free the buffers because they are (or should be) allocated/freed by the Java code using ByteBuffer.allocateDirect.

**Comment by tehbone** [comment]
They are not freed if `NewDirectByteBuffer` is used. It is up to the invoker to manage that memory.

**Comment by gongsu832** [comment]
Where do you see that? All I get from JNI doc https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html is:
```
NewDirectByteBuffer

jobject NewDirectByteBuffer(JNIEnv* env, void* address, jlong capacity);

Allocates and returns a direct java.nio.ByteBuffer referring to the block of memory starting at the memory address address and extending capacity bytes.

Native code that calls this function and returns the resulting byte-buffer object to Java-level code should ensure that the buffer refers to a valid region of memory that is accessible for reading and, if appropriate, writing. An attempt to access an invalid memory location from Java code will either return an arbitrary value, have no visible effect, or cause an unspecified exception to be thrown.
```
So I don't see the JNI spec mandating freeing NewDirectByteBuffer by the native code. Googling around and you get answers on both sides. Some say you need to free it yourself and some say it's subject to GC. I'm guessing it may be up to the JVM implementation.

**Comment by cjvolzka** [comment]
@gongsu832 what exactly is `jomt_data` (which is what I believe `NewDirectByteBuffer` is used to create if I'm reading the code correctly)? Is that the list of pointers to OMTensors that is inside the OMTensorList?

If so, do we still need to use `NewDirectByteBuffer`? Before 0.4.0 on the C side, it was possible for the OMTensorList to not own the OMTensor array that was inside if the OMTensorList. However since https://github.com/onnx/onnx-mlir/pull/2046, that has been simplified so the OMTensorList now always owns it's internal array of OMTensor pointers.

Could the JNI take advantage of that and now use something other than `NewDirectByteBuffer` which might be less ambiguous on who/what needs to free it?

**Comment by cjvolzka** [comment]
> @gongsu832 what exactly is `jomt_data` (which is what I believe `NewDirectByteBuffer` is used to create if I'm reading the code correctly)? ....

Ok, I see it now. It's not pointers to OMTensor objects. It's the data from the individual OMTensors in the list. I couldn't figure out why the OMTensorList would need that at first. Now I see it. 

It's needed so the JNI wrapper can create Java versions of the OMTensor objects a few lines lower at (https://github.com/onnx/onnx-mlir/blob/main/src/Runtime/jni/jniwrapper.c#L652). Those are then included in the Java OMTensorList that's ultimately returned by `omtl_java_to_native`

**Comment by gongsu832** [comment]
@tehbone Yes I found the JNI spec severely lacking and very painful for subtle things like this.

@cjvolzka `jomt_data` is the DirectByteBuffer object constructed from the tensor data buffer returned by the native code (model runtime output), and to be returned to Java code for users to consume. I was assuming that the Java GC is responsible for freeing it since the JNI spec didn't say otherwise. But if it were not subject to GC as @tehbone says, then a separate call would have to come down from the Java code to free it once the user is done with the tensor data buffer, something like the `finalize()` method as @tehbone suggested. I will see if I can make a PR to test.

**Comment by gongsu832** [comment]
`finalize()` is deprecated in Java 9. I'm looking into something like https://docs.oracle.com/javase/9/docs/api/java/lang/ref/Cleaner.html

**Comment by tehbone** [comment]
I also have created https://github.com/tehbone/onnx-mlir/commit/126d869f37b5cf49f05ca8095c71fc726ffbd767 which does not depend on `finalize()`. It produces an extra copy.

**Comment by tehbone** [comment]
After testing my latest PR, the downside to any GC-based approach which does not depend on a copy (i.e. Java-managed memory) is that nothing seems to exist to exert memory pressure on the GC to clean up the native memory. Relying on `finalize()` or a `cleaner` means that the heap only sees a smaller usage. The end result is that _if_ the GC doesn't run for a long period of time then the native storage can keep increasing and increasing until finally the GC runs. My understanding is that `ByteBuffer.allocateDirect()` _will_ keep track of allocations, but I don't know if that translates to forcing the GC to run if it needs the extra space.

Ultimately the most fool-proof method is to allow for a usage paradigm where the caller has more direct control over cleanup via `Autocloseable` or some other similar means.

**Comment by gongsu832** [comment]
@tehbone How did you test? I think that we would need a better way to see if there is memory leak. Observing the RES size in top isn't very assuring. With my tests with copy, cleaner auto close, and cleaner user close on Java 11, in all cases RES size of Leaker still creeps up from around 50MB to around 95MB in about an hour. We probably need a memory profiler to be certain.

**Comment by gongsu832** [comment]
Running Leaker under valgrind for one minute, with copy fix,

fake mainGraph with sleep (i.e., no JNI involved):
```
==1178640== LEAK SUMMARY:
==1178640==    definitely lost: 216 bytes in 7 blocks
==1178640==    indirectly lost: 100 bytes in 6 blocks
==1178640==      possibly lost: 1,722,661 bytes in 2,067 blocks
==1178640==    still reachable: 21,128,645 bytes in 7,429 blocks
==1178640==         suppressed: 0 bytes in 0 blocks
```

Real mainGraph with JNI:
```
==1179025== LEAK SUMMARY:
==1179025==    definitely lost: 864 bytes in 88 blocks
==1179025==    indirectly lost: 100 bytes in 6 blocks
==1179025==      possibly lost: 1,714,949 bytes in 2,090 blocks
==1179025==    still reachable: 21,633,569 bytes in 8,815 blocks
==1179025==         suppressed: 0 bytes in 0 blocks
```
So it looks like there are still some leaks.

**Comment by gongsu832** [comment]
OK it appears to be the input tensors constructed from Java OMTensor objects.
```
    409   LIB_TYPE_VAR_CALL(OMTensor **, jni_omts,
    410       malloc(jomtl_omtn * sizeof(OMTensor *)), jni_omts != NULL, env,
    411       japi->jecpt_cls, "jni_omts=%p", jni_omts);
```

**Comment by gongsu832** [comment]
OK I think you and I typed at literally the same time.
