### ISSUE TITLE
FuseCastCastPattern is unsound

### ISSUE THREAD

**Issue by sorenlassen** [onnx/onnx-mlir#2210]
The Cast canonicalization pattern FuseCastCastPattern
```
// onnx.Cast (onnx.Cast (%X, $type1)), $type2 = onnx.Cast (%X, $typ2)
def FuseCastCastPattern : Pat<
	(ONNXCastOp (ONNXCastOp $arg, $_), $type),
	(ONNXCastOp $arg, $type)>;
```
is unsound in some cases.

For instance the fusion of the two casts int32->bool->int16 to a single cast int32->int16 is unsound because int32->bool followed by bool->int16 changes, e.g., `-2` to `true` to `1`, whereas int32->int16 preserves `-2`.  

The soundness of cast fusion between integer types depends on whether casts truncate or saturate (see issue #2209). For instance, fusion of the two casts int32->uint32-int16 to a single cast int32->int16 is sound for truncation (where bits are reinterpreted and high bits are ignored when going from 32 bits to 16 bits) and is unsound for saturation where int32->uint32 changes, e.g., `-2` to `0` and the end result it `0` whereas the single cast int32-int16 preserves `-2`. Conversely, the fusion of the two casts float->int32-int16 to a single cast float->int16 is sound for saturation (assuming cast from float to integer maps out of range numbers to the min/max number for the integer type) whereas it is unsound for truncation where float->int32 preserves `70000` and then the int32-int16 cast truncates to `4464` whereas float-int16 changes `70000` to `32767` (max int16 number).

**Comment by chentong319** [comment]
Agree. Cast that results in data truncation can not be ignored.

**Comment by sorenlassen** [comment]
The pattern is now commented out. Reopening the issue to track the future effort to replace it with a version that fuses only casts that are sound to fuse.
