### ISSUE TITLE
Opset 19 tasks

### ISSUE THREAD

**Issue by philass** [onnx/onnx-mlir#2214]
Opset 19 recently landed.

I will try and land 5 PRs.

- [x] Constant, DequantizeLinear, Equal, Identity, If, Loop, Reshape, Scan, Shape, Size (Ops that add types )
- [x]  Cast, CastLike, QuantizeLinear (Ops that add saturate attribute)
- [x] Resize (adds multiple new attributes)
- [x] Pad (Added new wrap to the mode attribute)
- [x] AveragePool (added dilations)

**Comment by AlexandreEichenberger** [comment]
Thanks. For dilation, probably a source of inspiration is CONV.

**Comment by cjvolzka** [comment]
@philass this hasn't been updated in a while. Has it been completed or is there ongoing tasks?

**Comment by philass** [comment]
@cjvolzka Yes there are some ongoing tasks. Thanks for bringing this up.

This is the kick in the butt I needed to get back to this!

**Comment by cjvolzka** [comment]
@philass Is the documentation at https://github.com/onnx/onnx-mlir/blob/main/docs/SupportedONNXOps-cpu.md up to date? It looks like there's several supported Ops that say we only support up to OpSet 18 and no further. (for example `Equal | 7 - 18` means we only support up to 18)
