### ISSUE TITLE
Is there any way to return multiple values by krnl.call op?

### ISSUE THREAD

**Issue by negiyas** [onnx/onnx-mlir#2218]
I am developing an onnx.Unique op lowering path by using krnl.call op.
It seems that only one output is supported by current onnx-mlir implementation of krnl.call ( https://github.com/onnx/onnx-mlir/blob/main/src/Dialect/Krnl/Krnl.td#L50-L71 )

Since the Unique op returns multiple values, (e.g. Y, indices, inverse_indices, counts) with different shapes, I want to call C function returning multiple values. Any methods to get return multiple values with different shapes are acceptable, and API of the callee C function can be changed to deal with the issue.

Are there any recommended (or suggested) ways to return multiple values by krnl.call op according to the current onnx-mlir implementation?

**Comment by AlexandreEichenberger** [comment]
LSTM have multiple outputs... check how they implement returning multiple values
https://onnx.ai/onnx/operators/onnx__LSTM.html

**Comment by negiyas** [comment]
@AlexandreEichenberger Thanks for the answer, and sorry for my ambiguous question. 
Since onnx.Unique op is being developed using krnl.call op calling a C function returning multiple values, but krnl.call does not support C function returning multiple values at now. I am happy if krnl.call op can return multiple values in any way. 
I suppose that we can call the C function multiple times to get one return value by each call, but this way may not be smart and efficient.

**Comment by chentong319** [comment]
Krnl.Call does not support variadic output. I think it is doable to add that support. Krnl.Call add the return MemRef as parameter. We can discuss the detail if you'd like to add the code.

**Comment by chentong319** [comment]
I can add the support after PR #2205 is merged. I am working on another PR may need some change for Krnl.Call. I can postpone that change after the support of multiple output, if it is urgent.

**Comment by negiyas** [comment]
@chentong319 Thanks for the answer.
My request is not urgent. I am happy if you will support this function when it's good to support it.
> Krnl.Call does not support variadic output. 

Let me just confirm my issue. The argument number is not variadic, but optional arguments are included.
The following is the API of C function I want to use. I can change the API.
I hope that I can use this C function (or similar) with four (optional) arguments to store the output values. 

![image](https://github.com/onnx/onnx-mlir/assets/18544851/84e45943-7289-41da-8100-a240a42e7b66)

**Comment by chentong319** [comment]
#2251 added the support for multiple return values.
