### ISSUE TITLE
model tests changed in ONNX 1.14.0

### ISSUE THREAD

**Issue by philass** [onnx/onnx-mlir#2220]
ONNX has changed how they embed model tests in 1.14.0.  They now have the models in the repository and no longer point to external links.

See the following following PRs in ONNX
- https://github.com/onnx/onnx/pull/4861 
- https://github.com/onnx/onnx/pull/4960

This means that our logic for testing models no longer works, when we upgrade the ONNX dependency to 1.14.0. 

It is also unclear how long URLs we use to get the `onnx` files will work. 

cc @gongsu832

**Comment by AlexandreEichenberger** [comment]
@gongsu832 do you think you could look into the new testing infra? Much appreciated.

**Comment by philass** [comment]
Closed in https://github.com/onnx/onnx-mlir/pull/2304
