### ISSUE TITLE
Three yolo-v3 models in the model zoo failed after PR 

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#2225]
@sorenlassen I see three yolo-v3 models failed after your PR #2211. Not sure how they are related to each other.

https://www.onnxmlir.xyz/jenkinx/job/ONNX-MLIR-Pipeline-Docker-Build/Model_20Zoo_20Report/

<img width="518" alt="Screenshot 2023-05-08 at 15 40 37" src="https://user-images.githubusercontent.com/1230113/236752816-32f86c6a-7fe4-4818-a462-6f5e305fab56.png">

**Comment by sorenlassen** [comment]
I ran `onnx-mlir yolov3-10.onnx` in the debugger and, indeed, it crashes in a place with two consecutive casts that are no longer fused:
```
%688 = "onnx.Dim"(%685) {axis = 3 : si64} : (tensor<?x255x?x?xf32>) -> tensor<1xi64>
%690 = "onnx.Cast"(%688) {to = i32} : (tensor<1xi64>) -> tensor<1xi32>
%700 = "onnx.Cast"(%690) {to = i64} : (tensor<1xi32>) -> tensor<1xi64>
```
the crash is in `exploreSameInputDims(dim, op, sameDims)` with dim.first == %700 and dim.second == 2 in
```
  // Find the dynamic input dimensions that were transferred to the dynamic
  // output dimension.
  uint64_t dimIndex = dim.second;
  onnx_mlir::QuestionmarkIndexExpr qmOuputIE =
      shapeHelper->getOutputDims(tensorIndex)[dimIndex];
```
where tensorIndex == 0 and `shapeHelper->getOutputDims(tensorIndex).size()` == 1 so dimIndex == 2 exceeds its range

**Comment by sorenlassen** [comment]
note that the disabled FuseCastCastPattern would have combined the two casts into a single i64->i64 cast which, in turn, would probably have been eliminated by the CastEliminationPattern

**Comment by AlexandreEichenberger** [comment]
@tungld do you think its something related to dim analysis or to index expressions?

**Comment by tungld** [comment]
> do you think its something related to dim analysis or to index expressions?

Not sure which one is related. I am digging into this to see what happened.
