### ISSUE TITLE
intermittent Jenkins Linux amd64 CI failures

### ISSUE THREAD

**Issue by sorenlassen** [onnx/onnx-mlir#2231]
seems to be failing fairly frequently lately and typically succeeds when retried, e.g.:
https://www.onnxmlir.xyz/jenkinx/job/ONNX-MLIR-Pipeline-Docker-Build/11009/
https://www.onnxmlir.xyz/jenkinx/job/ONNX-MLIR-Pipeline-Docker-Build/11006/

cc @tungld 

I can't see from the logs why it failed:
```
{
  "url": "https://api.github.com/repos/onnx/onnx-mlir/statuses/a92406f8367c7c01345b1d7eb311439984d70139",
  "state": "failure",
  "description": "Build #11006 [synchronize] Merge branch main into s... failed after 28 min",
  "context": "Jenkins Linux amd64",
  "message": null
}
[...]
ERROR: script returned exit code -1
Finished: FAILURE
```

**Comment by chentong319** [comment]
My PR #2232 also suffered this failure even after I tried to build it again.

**Comment by sorenlassen** [comment]
I continue to see quite a lot of Linux amd64 CI failures which require a retry, e.g.:
https://www.onnxmlir.xyz/jenkinx/job/ONNX-MLIR-Pipeline-Docker-Build/11207/

How can I tell if this was because of OOM?

I'm not sure but I don't think much else was building at that time.

Is there any way we can reduce the frequency of these failures? (add memory or limit to fewer concurrent jobs?)

**Comment by sorenlassen** [comment]
I think the failures are less frequent now, yay, so closing this issue
