### ISSUE TITLE
Two ONNX models failed on Jenkins s390x due to timeout

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#2256]
There are two models in the onnx model zoo failed on Jenkins s390x after PR #2240. It seems they took a longer time to compile/run.

<img width="557" alt="Screenshot 2023-05-18 at 16 29 23" src="https://github.com/onnx/onnx-mlir/assets/1230113/d1fa0b99-557c-43a6-9b11-e9df6502d27d">

**Comment by sorenlassen** [comment]
I tried running `onnx-mlir ResNet101-DUC-12.onnx -O3` before and after PR #2240 and with `-pattern-shape-inference=true` and `-pattern-shape-inference=false` and I couldn't measure any difference in compile time. Can you reproduce the slowdown?

**Comment by tungld** [comment]
It's back now. Thanks!
