### ISSUE TITLE
NNPA Performance degradation on bertsquad-12.onnx

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#2257]
Using the latest commit c417429ef49ea1ed82f299474231aaec3622da5e [bertsquad-12.onnx ](https://github.com/onnx/models/blob/main/text/machine_comprehension/bert-squad/model/bertsquad-12.onnx) now takes 2016.73ms to run.

I don't know what commit caused the issue. The next commit I have a build to compare with was 4c0645e from three weeks ago. That one takes 164.32 ms on the same model, input, and compile options

`--O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z16 --maccel=NNPA --onnx-op-stats TXT`

# onnx-op-stats output
At a glance, I see many more more onnx.Concat and fewer zhigh.MatMul:

## current c417429ef49ea1ed82f299474231aaec3622da5e
```
Operations encountered:
-----------------------
   func.func               , 1
   func.return             , 1
   onnx.Add                , 63
   onnx.Cast               , 72
   onnx.Concat             , 72
   onnx.Constant           , 78
   onnx.ConstantOfShape    , 1
   onnx.Dim                , 33
   onnx.Gather             , 1
   onnx.MatMul             , 24
   onnx.Mul                , 149
   onnx.NoValue            , 1
   onnx.OneHot             , 1
   onnx.Reciprocal         , 25
   onnx.ReduceMeanV13      , 50
   onnx.Reshape            , 94
   onnx.Slice              , 5
   onnx.Split              , 1
   onnx.Sqrt               , 25
   onnx.Squeeze            , 4
   onnx.Sub                , 62
   onnx.Transpose          , 49
   onnx.Unsqueeze          , 13
  zhigh.Add                , 49
  zhigh.MatMul             , 74
  zhigh.Mul                , 86
  zhigh.Softmax            , 12
  zhigh.Stick              , 200
  zhigh.StickifiedConstant , 147
  zhigh.Tanh               , 12
  zhigh.Unstick            , 185
  ```

## old 4c0645e
```
Operations encountered:
-----------------------
   func.func               , 1
   func.return             , 1
   onnx.Add                , 62
   onnx.Cast               , 18
   onnx.Concat             , 56
   onnx.Constant           , 77
   onnx.ConstantOfShape    , 1
   onnx.Dim                , 41
   onnx.Gather             , 1
   onnx.Mul                , 149
   onnx.NoValue            , 1
   onnx.OneHot             , 1
   onnx.Reciprocal         , 25
   onnx.ReduceMeanV13      , 50
   onnx.Reshape            , 166
   onnx.Split              , 1
   onnx.Sqrt               , 25
   onnx.Squeeze            , 4
   onnx.Sub                , 62
   onnx.Transpose          , 49
   onnx.Unsqueeze          , 13
  zhigh.Add                , 50
  zhigh.MatMul             , 98
  zhigh.Mul                , 86
  zhigh.Softmax            , 12
  zhigh.Stick              , 250
  zhigh.StickifiedConstant , 147
  zhigh.Tanh               , 12
  zhigh.Unstick            , 210
```

There's also some minor changes in the output values between them but I expect that's because more functions are going to CPU over the 16 bit NNPA.

**Comment by tungld** [comment]
@cjvolzka PR #2250 would bring it back.

**Comment by cjvolzka** [comment]
I did a spot check with the current https://github.com/onnx/onnx-mlir/pull/2250. It's much improved but not quite back to where it was. Runtime is 192.963 ms with this commit. That's down from the 2016.73 ms when this issue opened but still higher from the original 164.32 ms.

At a glance, when compiling the model I notice all the Softmax are now running on CPU (according to compile time info) instead of NNPA. Although there appears to be less stick and unsticks now.

2250's https://github.com/onnx/onnx-mlir/commit/7cd96caef08faf221a66a5092c1b202ffc2659a6
```
Operations encountered:
-----------------------
   func.func               , 1
   func.return             , 1
   onnx.Add                , 62
   onnx.Cast               , 31
   onnx.Concat             , 44
   onnx.Constant           , 77
   onnx.ConstantOfShape    , 1
   onnx.Dim                , 29
   onnx.Gather             , 1
   onnx.Mul                , 149
   onnx.NoValue            , 1
   onnx.OneHot             , 1
   onnx.Reciprocal         , 25
   onnx.ReduceMeanV13      , 50
   onnx.Reshape            , 142
   onnx.Softmax            , 12
   onnx.Split              , 1
   onnx.Sqrt               , 25
   onnx.Squeeze            , 4
   onnx.Sub                , 62
   onnx.Transpose          , 49
   onnx.Unsqueeze          , 13
  zhigh.Add                , 50
  zhigh.MatMul             , 98
  zhigh.Mul                , 86
  zhigh.Stick              , 238
  zhigh.StickifiedConstant , 147
  zhigh.Tanh               , 12
  zhigh.Unstick            , 198
  ```

The old https://github.com/onnx/onnx-mlir/commit/4c0645e8bca1c476bbc65e4f725e90c8cc265781 are in the issue description for comparison

**Comment by cjvolzka** [comment]
I retested since https://github.com/onnx/onnx-mlir/pull/2250 merged. Overall results are similiar to my last pre-test results. Results are still not as good as the previous 0.4.0 release. That appears to be a different issue where Softmax is going to CPU instead of NNPA. I'll close this issue and open a new one since they are different causes.
