### ISSUE TITLE
Investigate why pattern-based shape inference fails when setting the default to True

### ISSUE THREAD

**Issue by hamptonm1** [onnx/onnx-mlir#2271]
This issue was created based on the following PR: https://github.com/onnx/onnx-mlir/pull/2270

FYI- @sorenlassen @tungld

**Comment by hamptonm1** [comment]
I guess I need to understand the flow of pattern-based shape inference... it apparently is utilizing `llvm::cast` somewhere when enabled. Some assertion is off and when running the onnx models it does not specify as to which file is impacted (which would help)...the process just aborts.

**Comment by sorenlassen** [comment]
Both failures were because inferShapes() methods made too stringent assumptions about the operand types and shapes. I fixed these in PR #2273. With these fixes the models should compile successfully with `-pattern-shape-inference=true`.
