### ISSUE TITLE
Windows CI pipeline is failing silently

### ISSUE THREAD

**Issue by NathanielMcVicar** [onnx/onnx-mlir#234]
As far as I can tell, the Windows CI pipeline isn't checking for and returning errors from the script, causing builds that fail to appear as green. An example is here: https://dev.azure.com/onnx-pipelines/onnx/_build/results?buildId=3115&view=logs&j=4060f429-1919-5440-1fce-77a91697330b&t=91a0b9d9-34dd-5af7-633c-c7e5328fed2f

Notice that the builder fails with the following error, but shows success.
```
MainUtils.cpp
D:\a\1\llvm-project\llvm\include\llvm/IR/User.h(48,32): warning C4141: 'inline': used more than once [D:\a\1\onnx-mlir\build\src\MainUtils.vcxproj]
D:\a\1\onnx-mlir\src\MainUtils.cpp(231,54): error C2065: 'outputBaseName': undeclared identifier [D:\a\1\onnx-mlir\build\src\MainUtils.vcxproj]
D:\a\1\onnx-mlir\src\MainUtils.cpp(233,61): error C3536: 'constPackFileName': cannot be used before it is initialized [D:\a\1\onnx-mlir\build\src\MainUtils.vcxproj]
D:\a\1\onnx-mlir\src\MainUtils.cpp(233,61): error C2664: 'std::error_code llvm::sys::fs::rename(const llvm::Twine &,const llvm::Twine &)': cannot convert argument 2 from 'int' to 'const llvm::Twine &' [D:\a\1\onnx-mlir\build\src\MainUtils.vcxproj]
D:\a\1\onnx-mlir\src\MainUtils.cpp(233,61): message : Reason: cannot convert from 'int' to 'const llvm::Twine' [D:\a\1\onnx-mlir\build\src\MainUtils.vcxproj]
```

I believe this is due to the way cmd.exe scripts returns (or, more often doesn't return) error codes. I am currently working on a local fully .yml implementation of the build, and it might be worth incorporating something like this into the project CI builds, depending on the philosophy around such things. Thanks!

edit:
I haven't experimented with this, but I think the script should internally check for failures between stages with something like:
```
if %ERRORLEVEL% NEQ 0 (
   echo ERROR Failed to build LLVM
   exit /b %ERRORLEVEL%
)
```

**Comment by AlexandreEichenberger** [comment]
@gongsu832 Do you mind looking into the issue? First it would be great if scripts were didn't fail silently, and also, can you look into why #204 created the issue in the first place? Thanks.

**Comment by gongsu832** [comment]
@AlexandreEichenberger I really know nothing about programming on WIndows. I think someone else setup that build system on Windows. https://github.com/onnx/onnx-mlir/pull/115

**Comment by caoimhinuibrian** [comment]
Will the .yml build you are working on run on Travis?

**Comment by caoimhinuibrian** [comment]
> @AlexandreEichenberger I really know nothing about programming on WIndows. I think someone else setup that build system on Windows. #115
@gongsu832 When you changed MainUtils.cpp in PR #204 you broke the Windows build. There is no longer a definition of outputBaseName in the function genConstPackObj (previously was named something else). At the bottom of this function there is a preprocessor #else which is reached on Windows. It uses outputBaseName. Please take a look and see what a suitable fix is.

**Comment by gongsu832** [comment]
Putting back the outputBaseName parameter should allow Windows to build although I have no way to test locally. Also, someone who wrote the original code (I guess @tjingrant ?) should take a look. I put a FIXME comment there.

**Comment by NathanielMcVicar** [comment]
@caoimhinuibrian I haven't used Travis CI personally, but I don't think what I have now would work because it uses ADO specific tasks. If support is required for both Travis and Azure pipelines I understand the current approach better.

**Comment by caoimhinuibrian** [comment]
@NathanielMcVicar OK, np ... I was just wondering if we could reduce the number of CI builds.

**Comment by caoimhinuibrian** [comment]
@NathanielMcVicar Just to clarify - your original comment was about silent build failures on Windows, I assume you are fixing that with your yaml build? Is there something else we need to do? I don't believe the TravisCI build fails silently, not sure about the Jenkins or CircleCI.

**Comment by NathanielMcVicar** [comment]
@caoimhinuibrian This is getting a little beyond my expertise. As far as I can tell the Jenkins and CircleCI builds are not publicly visible, so I can't speak to those. It looks like the Travis ones are Ubuntu only on three different architectures, and I wouldn't expect them to fail silently. I was speaking specifically about the Azure Windows CI. It is possible to use the same yml script across OSes on Azure (we have it set up for Windows and Ubuntu amd64 right now, but the IBM archs aren't available), but the way I've done it relies on Microsoft specific cross-platform tasks. Given all of this, it seems like the lowest friction solution would just be to update the Windows .cmd scripts to return an error code in all cases. Is there one person who manages all the CI who we could loop in? I agree having four distinct providers seems like a lot.

**Comment by jcwchen** [comment]
Hi @NathanielMcVicar,

Sorry that I did not handle this in the first place. I just encountered the same bug on AzurePipeline recently.
As you mentioned, since sometimes Azurepipline cannot catch the exit code normally, AzurePipeline needs to manually catch the error after those scripts like:
```
...
call cmake --build . --config Release --target onnx-mlir -- /m
if [ $? -ne 0 ]; then
  echo "build onnx-mlir failed."
  exit 1
fi
...
```
@NathanielMcVicar have you started to work on this? If not, I can help to propose a PR to fix this.
Thank you!

**Comment by NathanielMcVicar** [comment]
Hi @jcwchen, thanks for looking at this! If you already have something like that started, please feel free to submit the PR. If not, I was planning on tackling it in the morning (PST). If I don't hear from you I'll submit the PR then, just want to make sure we aren't duplicating work.

**Comment by NathanielMcVicar** [comment]
Thanks for tackling this @jcwchen. Looks great!

**Comment by tjingrant** [comment]
Closing because https://github.com/onnx/onnx-mlir/pull/241 resolved this issue. Thanks @jcwchen !
