### ISSUE TITLE
PyCompileAndRuntime does not work.

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#2364]
I tried to run the mnist example by using PyCompileAndRuntime, but it didn't work:
```
$ cd docs/mnist_example
$ python mnist-runPyCompileAndRuntime.py
Traceback (most recent call last):
  File "mnist-runPyCompileAndRuntime.py", line 11, in <module>
    session = OMCompileExecutionSession(inputFileName,sharedLibPath,"-O3")
RuntimeError: Cannot open library: './mnist.so'.
```

According to PyCompileAndRuntime definition [here](https://github.com/onnx/onnx-mlir/blob/main/src/Runtime/PyOMCompileExecutionSession.cpp#L26)
```C
PyOMCompileExecutionSession::PyOMCompileExecutionSession(
    std::string inputFileName, std::string sharedLibPath, std::string flags,
    bool defaultEntryPoint)
    : onnx_mlir::PyExecutionSessionBase(sharedLibPath, defaultEntryPoint) {
}
```

It constructs a PyExectionSessionBase with a `.so` file (`sharedLibPath`) that does not exist at the construction time.

**Comment by AlexandreEichenberger** [comment]
Something changed, and it's not working anymore. Easy fix, working on it.
