### ISSUE TITLE
Can arm64/v8 (Apple M1) be added to the docker image?

### ISSUE THREAD

**Issue by nicholaiTukanov** [onnx/onnx-mlir#2372]
When pulling the docker image on my mac, I get the following error:

```zsh
❯ docker pull onnxmlirczar/onnx-mlir-dev
Using default tag: latest
latest: Pulling from onnxmlirczar/onnx-mlir-dev
no matching manifest for linux/arm64/v8 in the manifest list entries
```

I can work around this by doing `docker pull --platform linux/amd64 onnxmlirczar/onnx-mlir-dev`, but I was wondering if ARM can be added as a platform for the image.

**Comment by nicholaiTukanov** [comment]
Furthermore, when trying to build using the example Dockerfile on Apple M1, make sure to replace `FROM onnxmlirczar/onnx-mlir-dev` with `FROM --platform=linux/amd64 onnxmlirczar/onnx-mlir-dev`.

**Comment by hamptonm1** [comment]
@nicholaiTukanov Thank you for your feedback!!!!

**Comment by hamptonm1** [comment]
> Note: when using the --platform=linux/amd64 method of running on Apple M1, I get the following warning when launching a container:
> 
> ```
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> ```
> 
> I haven't run into any issues yet, but wanted to mention this just in case.

Hmmm I have never received this warning personally in my IDE. I am using visual studio code and it has always worked for me without any warnings.

**Comment by hamptonm1** [comment]
However, I can test on my end (I do have an Apple M1) and update the docker documentation accordingly :)

**Comment by hamptonm1** [comment]
@nicholaiTukanov Hmm what you suggested did not work for me...... image is unknown is the error I get. Can you copy and paste your exact commands as to what works for you ?

**Comment by nicholaiTukanov** [comment]
> > When pulling the docker image on my mac, I get the following error:
> > ```shell
> > ❯ docker pull onnxmlirczar/onnx-mlir-dev
> > Using default tag: latest
> > latest: Pulling from onnxmlirczar/onnx-mlir-dev
> > no matching manifest for linux/arm64/v8 in the manifest list entries
> > ```
> > I can work around this by doing `docker pull --platform linux/amd64 onnxmlirczar/onnx-mlir-dev`, but I was wondering if ARM can be added as a platform for the image.
> 
> The workaround you mentioned is specified already in the documentation for building docker.

Ah whoops, I must have missed that.

> @nicholaiTukanov Hmm what you suggested did not work for me...... image is unknown is the error I get. Can you copy and paste your exact commands as to what works for you ?

What command did you use?

I used the following for pulling the image: `docker pull --platform linux/amd64 onnxmlirczar/onnx-mlir-dev`. However, I didn't end up using this workflow, and I instead just changed the first line in the example Dockerfile to: `FROM --platform=linux/amd64 onnxmlirczar/onnx-mlir-dev`

**Comment by hamptonm1** [comment]
Okay understood.... do you mind doing me a favor. Look at the instructions in `doc/docker.md` let me know if that section on specifically using an M1 machine works for you. I have no problems on my end and then we can close out this issue. Thanks!

**Comment by nicholaiTukanov** [comment]
@hamptonm1 I followed the instructions in doc/docker.md regarding the M1 and it works for me!

**Comment by hamptonm1** [comment]
Awesome! So I will close this issue out as resolved. Thanks!
