### ISSUE TITLE
Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Development   Development.Module Development.Embed) (found version "3.10.6")

### ISSUE THREAD

**Issue by SStarver** [onnx/onnx-mlir#2376]
- **error occured during onnx-mlir installation period, any suggestions?**
> CMake Error at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Development
  Development.Module Development.Embed) (found version "3.10.6")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.20/Modules/FindPython/Support.cmake:3165 (find_package_handle_standard_args)
  /usr/local/share/cmake-3.20/Modules/FindPython3.cmake:485 (include)
  CMakeLists.txt:88 (find_package)
>
>-- Configuring incomplete, errors occurred!
See also "/home/workspace/code_projects/onnx-mlir/build/CMakeFiles/CMakeOutput.log".
See also "/home/workspace/code_projects/onnx-mlir/build/CMakeFiles/CMakeError.log".

-  configuration steps
> follow  [this](https://github.com/onnx/onnx-mlir/blob/main/docs/BuildOnLinuxOSX.md)  commands

- enviroment
> self-build ubuntu 22.04 docker environment with python3=3.10.6 installed

- complete print info on terminal
>  -- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to Debug
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /usr/lib/x86_64-linux-gnu/libtinfo.so
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Using MLIRConfig.cmake in: /home/workspace/code_projects/llvm-project/build/lib/cmake/mlir
-- Using LLVMConfig.cmake in: /home/workspace/code_projects/llvm-project/build/lib/cmake/llvm
-- Linker detection: GNU ld
-- Performing Test C_SUPPORTS_FPIC
-- Performing Test C_SUPPORTS_FPIC - Success
-- Performing Test CXX_SUPPORTS_FPIC
-- Performing Test CXX_SUPPORTS_FPIC - Success
-- Building with -fPIC
-- Performing Test C_SUPPORTS_FNO_SEMANTIC_INTERPOSITION
-- Performing Test C_SUPPORTS_FNO_SEMANTIC_INTERPOSITION - Success
-- Performing Test CXX_SUPPORTS_FNO_SEMANTIC_INTERPOSITION
-- Performing Test CXX_SUPPORTS_FNO_SEMANTIC_INTERPOSITION - Success
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG - Success
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME - Success
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME - Success
-- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
-- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Failed
-- Performing Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
-- Performing Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Failed
-- Performing Test C_SUPPORTS_CMAKE_CXX_FLAGS
-- Performing Test C_SUPPORTS_CMAKE_CXX_FLAGS - Success
-- Performing Test CXX_SUPPORTS_CMAKE_CXX_FLAGS
-- Performing Test CXX_SUPPORTS_CMAKE_CXX_FLAGS - Success
-- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG
-- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG - Success
-- Performing Test C_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG
-- Performing Test C_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG - Success
-- Performing Test CXX_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG
-- Performing Test CXX_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG - Success
-- Performing Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG
-- Performing Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG - Failed
-- Performing Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG
-- Performing Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG - Failed
-- Performing Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG
-- Performing Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG - Success
-- Performing Test CXX_SUPPORTS_REDUNDANT_MOVE_FLAG
-- Performing Test CXX_SUPPORTS_REDUNDANT_MOVE_FLAG - Success
-- Performing Test CXX_SUPPORTS_PESSIMIZING_MOVE_FLAG
-- Performing Test CXX_SUPPORTS_PESSIMIZING_MOVE_FLAG - Success
-- Performing Test CXX_SUPPORTS_NOEXCEPT_TYPE_FLAG
-- Performing Test CXX_SUPPORTS_NOEXCEPT_TYPE_FLAG - Success
-- Performing Test CXX_WONT_WARN_ON_FINAL_NONVIRTUALDTOR
-- Performing Test CXX_WONT_WARN_ON_FINAL_NONVIRTUALDTOR - Failed
-- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE_FLAG
-- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE_FLAG - Success
-- Performing Test CXX_WSUGGEST_OVERRIDE_ALLOWS_ONLY_FINAL
-- Performing Test CXX_WSUGGEST_OVERRIDE_ALLOWS_ONLY_FINAL - Success
-- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP
-- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP - Failed
-- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG
-- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG - Failed
-- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG
-- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG - Failed
-- Performing Test CXX_SUPPORTS_MISLEADING_INDENTATION_FLAG
-- Performing Test CXX_SUPPORTS_MISLEADING_INDENTATION_FLAG - Success
-- Performing Test C_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG
-- Performing Test C_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG - Failed
-- Performing Test CXX_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG
-- Performing Test CXX_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG - Success
-- Performing Test LINKER_SUPPORTS_COLOR_DIAGNOSTICS
-- Performing Test LINKER_SUPPORTS_COLOR_DIAGNOSTICS - Failed
-- Looking for os_signpost_interval_begin
-- Looking for os_signpost_interval_begin - not found
-- BUILD_SHARED_LIBS        : OFF
-- LLVM_REQUIRES_EH         : ON
-- ONNX_MLIR_DEFAULT_TRIPLE : x86_64-unknown-linux-gnu
-- CMAKE_INSTALL_PREFIX     : /usr/local
CMake Error at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Development
  Development.Module Development.Embed) (found version "3.10.6")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.20/Modules/FindPython/Support.cmake:3165 (find_package_handle_standard_args)
  /usr/local/share/cmake-3.20/Modules/FindPython3.cmake:485 (include)
  CMakeLists.txt:88 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/workspace/code_projects/onnx-mlir/build/CMakeFiles/CMakeOutput.log".
See also "/home/workspace/code_projects/onnx-mlir/build/CMakeFiles/CMakeError.log".

**Comment by SStarver** [comment]
> * **error occured during onnx-mlir installation period, any suggestions?**
> 
> > CMake Error at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
> > Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Development
> > Development.Module Development.Embed) (found version "3.10.6")
> > Call Stack (most recent call first):
> > /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
> > /usr/local/share/cmake-3.20/Modules/FindPython/Support.cmake:3165 (find_package_handle_standard_args)
> > /usr/local/share/cmake-3.20/Modules/FindPython3.cmake:485 (include)
> > CMakeLists.txt:88 (find_package)
> > -- Configuring incomplete, errors occurred!
> > See also "/home/workspace/code_projects/onnx-mlir/build/CMakeFiles/CMakeOutput.log".
> > See also "/home/workspace/code_projects/onnx-mlir/build/CMakeFiles/CMakeError.log".
> 
> * configuration steps
> 
> > follow  [this](https://github.com/onnx/onnx-mlir/blob/main/docs/BuildOnLinuxOSX.md)  commands
> 
> * enviroment
> 
> > self-build ubuntu 22.04 docker environment with python3=3.10.6 installed
> 
> * complete print info on terminal
> 
> > -- The C compiler identification is GNU 11.3.0
> > -- The CXX compiler identification is GNU 11.3.0
> > -- Detecting C compiler ABI info
> > -- Detecting C compiler ABI info - done
> > -- Check for working C compiler: /usr/bin/cc - skipped
> > -- Detecting C compile features
> > -- Detecting C compile features - done
> > -- Detecting CXX compiler ABI info
> > -- Detecting CXX compiler ABI info - done
> > -- Check for working CXX compiler: /usr/bin/c++ - skipped
> > -- Detecting CXX compile features
> > -- Detecting CXX compile features - done
> > -- No build type selected, default to Debug
> > -- Performing Test Terminfo_LINKABLE
> > -- Performing Test Terminfo_LINKABLE - Success
> > -- Found Terminfo: /usr/lib/x86_64-linux-gnu/libtinfo.so
> > -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
> > -- Using MLIRConfig.cmake in: /home/workspace/code_projects/llvm-project/build/lib/cmake/mlir
> > -- Using LLVMConfig.cmake in: /home/workspace/code_projects/llvm-project/build/lib/cmake/llvm
> > -- Linker detection: GNU ld
> > -- Performing Test C_SUPPORTS_FPIC
> > -- Performing Test C_SUPPORTS_FPIC - Success
> > -- Performing Test CXX_SUPPORTS_FPIC
> > -- Performing Test CXX_SUPPORTS_FPIC - Success
> > -- Building with -fPIC
> > -- Performing Test C_SUPPORTS_FNO_SEMANTIC_INTERPOSITION
> > -- Performing Test C_SUPPORTS_FNO_SEMANTIC_INTERPOSITION - Success
> > -- Performing Test CXX_SUPPORTS_FNO_SEMANTIC_INTERPOSITION
> > -- Performing Test CXX_SUPPORTS_FNO_SEMANTIC_INTERPOSITION - Success
> > -- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG
> > -- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG - Success
> > -- Performing Test C_SUPPORTS_WERROR_DATE_TIME
> > -- Performing Test C_SUPPORTS_WERROR_DATE_TIME - Success
> > -- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME
> > -- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME - Success
> > -- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
> > -- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Failed
> > -- Performing Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
> > -- Performing Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Failed
> > -- Performing Test C_SUPPORTS_CMAKE_CXX_FLAGS
> > -- Performing Test C_SUPPORTS_CMAKE_CXX_FLAGS - Success
> > -- Performing Test CXX_SUPPORTS_CMAKE_CXX_FLAGS
> > -- Performing Test CXX_SUPPORTS_CMAKE_CXX_FLAGS - Success
> > -- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG
> > -- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG - Success
> > -- Performing Test C_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG
> > -- Performing Test C_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG - Success
> > -- Performing Test CXX_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG
> > -- Performing Test CXX_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG - Success
> > -- Performing Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG
> > -- Performing Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG - Failed
> > -- Performing Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG
> > -- Performing Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG - Failed
> > -- Performing Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG
> > -- Performing Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG - Success
> > -- Performing Test CXX_SUPPORTS_REDUNDANT_MOVE_FLAG
> > -- Performing Test CXX_SUPPORTS_REDUNDANT_MOVE_FLAG - Success
> > -- Performing Test CXX_SUPPORTS_PESSIMIZING_MOVE_FLAG
> > -- Performing Test CXX_SUPPORTS_PESSIMIZING_MOVE_FLAG - Success
> > -- Performing Test CXX_SUPPORTS_NOEXCEPT_TYPE_FLAG
> > -- Performing Test CXX_SUPPORTS_NOEXCEPT_TYPE_FLAG - Success
> > -- Performing Test CXX_WONT_WARN_ON_FINAL_NONVIRTUALDTOR
> > -- Performing Test CXX_WONT_WARN_ON_FINAL_NONVIRTUALDTOR - Failed
> > -- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE_FLAG
> > -- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE_FLAG - Success
> > -- Performing Test CXX_WSUGGEST_OVERRIDE_ALLOWS_ONLY_FINAL
> > -- Performing Test CXX_WSUGGEST_OVERRIDE_ALLOWS_ONLY_FINAL - Success
> > -- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP
> > -- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP - Failed
> > -- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG
> > -- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG - Failed
> > -- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG
> > -- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG - Failed
> > -- Performing Test CXX_SUPPORTS_MISLEADING_INDENTATION_FLAG
> > -- Performing Test CXX_SUPPORTS_MISLEADING_INDENTATION_FLAG - Success
> > -- Performing Test C_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG
> > -- Performing Test C_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG - Failed
> > -- Performing Test CXX_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG
> > -- Performing Test CXX_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG - Success
> > -- Performing Test LINKER_SUPPORTS_COLOR_DIAGNOSTICS
> > -- Performing Test LINKER_SUPPORTS_COLOR_DIAGNOSTICS - Failed
> > -- Looking for os_signpost_interval_begin
> > -- Looking for os_signpost_interval_begin - not found
> > -- BUILD_SHARED_LIBS        : OFF
> > -- LLVM_REQUIRES_EH         : ON
> > -- ONNX_MLIR_DEFAULT_TRIPLE : x86_64-unknown-linux-gnu
> > -- CMAKE_INSTALL_PREFIX     : /usr/local
> > CMake Error at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
> > Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Development
> > Development.Module Development.Embed) (found version "3.10.6")
> > Call Stack (most recent call first):
> > /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
> > /usr/local/share/cmake-3.20/Modules/FindPython/Support.cmake:3165 (find_package_handle_standard_args)
> > /usr/local/share/cmake-3.20/Modules/FindPython3.cmake:485 (include)
> > CMakeLists.txt:88 (find_package)
> 
> -- Configuring incomplete, errors occurred! See also "/home/workspace/code_projects/onnx-mlir/build/CMakeFiles/CMakeOutput.log". See also "/home/workspace/code_projects/onnx-mlir/build/CMakeFiles/CMakeError.log".

- self check

![image](https://github.com/onnx/onnx-mlir/assets/108868933/04130ead-0238-41df-af4c-2eccb3fbdede)

**Comment by sorenlassen** [comment]
I can't tell what's going wrong for you but you could try:
```
cmake -G Ninja \
      -DCMAKE_CXX_COMPILER=/usr/bin/c++ \
      -DMLIR_DIR=${MLIR_DIR} \
      -DPYTHON_EXECUTABLE=$(which python3) \
      ..
```
I found that works well on my MacBook as an alternative to `$pythonLocation` and `-DPython3_ROOT_DIR` 

(and verify that your python3 is good by checking that `python3 --version` returns something reasonable)

**Comment by SStarver** [comment]
> I can't tell what's going wrong for you but you could try:
> 
> ```
> cmake -G Ninja \
>       -DCMAKE_CXX_COMPILER=/usr/bin/c++ \
>       -DMLIR_DIR=${MLIR_DIR} \
>       -DPYTHON_EXECUTABLE=$(which python3) \
>       ..
> ```
> 
> I found that works well on my MacBook as an alternative to `$pythonLocation` and `-DPython3_ROOT_DIR`
> 
> (and verify that your python3 is good by checking that `python3 --version` returns something reasonable)

I've tried your  suggestion, but still get the same error information.  Anyway, thank you for the reply.
![image](https://github.com/onnx/onnx-mlir/assets/108868933/ed055625-eb9a-4fa1-9e90-0e2c150140f6)

**Comment by sorenlassen** [comment]
you could try one of the answers here: https://stackoverflow.com/questions/24174394/cmake-is-not-able-to-find-python-libraries

**Comment by SStarver** [comment]
> you could try one of the answers here: https://stackoverflow.com/questions/24174394/cmake-is-not-able-to-find-python-libraries

> Thanks a lot, this really helps.
It turns out that I've forgot installing 'python-dev' ...
>
> By running " apt-get install python3-dev", problem solved.

**Comment by SStarver** [comment]
> @SStarver please document what worked for you, so that other folks having similar issues would learn from your travails. Thanks

Tanks for the notice. Actually, I've post  the resolution in my last reply, but  you're right, an explicit comment would be better.

**Comment by SStarver** [comment]
By running " apt-get install python3-dev", my  problem solved.
My  environment is  a self-created docker of ubuntu.
