### ISSUE TITLE
Segmentation fault for MatMul on certain shape

### ISSUE THREAD

**Issue by chentong319** [onnx/onnx-mlir#2388]
I try to test the performance of onnx.MatMul for different shapes. I got segmentation error for certain shape, only on z16 without NNPA.
The test example is 
```
module {
  func.func @main_graph(%arg0 : tensor<?x?xf32>, %arg1 : tensor<?x?xf32>) -> tensor<*xf32> {
    %0 = "onnx.MatMul"(%arg0, %arg0) : (tensor<?x?xf32>, tensor<?x?xf32>) -> tensor<*xf32>
    return %0 : tensor<*xf32>
  }
  "onnx.EntryPoint"() {func = @main_graph} : () -> ()
}
```
I use RunONNXModel.py with --shape-info to specify the shape. The two inputs have shape of <nxm> and <mxn>. I keep nxm = 256x256 and try different values for n, starting from 2 and increased by double its value.
I got segmentation on n = 4, 8, 16, 32 and 64. The other values for n are fine. I added instrumentation and segmentation seems to occur inside matmul.

This segmentation is for z without NNPA. No problem on my Mac.  SIMD specific on Z? @AlexandreEichenberger 

```
Loading the compiled model ...
  took  4.572398029267788e-05  seconds.

Generating random inputs ...
  - 1st input's shape (8, 8192), element type float32. Value ranges [-0.1, 0.1]
  - 2nd input's shape (8192, 8), element type float32. Value ranges [-0.1, 0.1]
  done.

Running inference ...
#  0) before onnx.MatMul Time elapsed: 1689960367.087535 accumulated: 1689960367.087535 (matmul.mlir:3)
Segmentation fault (core dumped)
```

**Comment by chentong319** [comment]
test case error

**Comment by AlexandreEichenberger** [comment]
Was there any fixes needed to the code @chentong319 ?
