### ISSUE TITLE
Undefined symbol when running inference on NNPA

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#2422]
With the latest commit, I got an error when running a model on NNPA:
```
python: symbol lookup error: /tmp/tmpqjy1e8mn/model.so: undefined symbol: OMInitCompatibleAccelNNPA`
```

It seems it's related to this PR #2407 that changed the way libraries are linked.

**Comment by tungld** [comment]
@chentong319 any thought?

**Comment by gongsu832** [comment]
It's also missing `-lzdnn`. @chentong319 it seems that the options for the accelerators are not being collected.

**Comment by chentong319** [comment]
The library for NNPA is added in the constructor of NNPAAccelerator. The fix for repeatedly adding lib to configure by compiling module cleared those library. I will try to fix it.
