### ISSUE TITLE
Accuracy regression in several models

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#2436]
# Description
Running our regression tests, we noticed an expected accuracy reduction in the following models for both CPU and NNPA.
- bertsquad-10
- bertsquad-12
- gpt2-10
- gpt-lm-head-10
- roberta-sequence-classification-9

These models passed our previous regression tests. [onnx-mlir Commit comparison](https://github.com/onnx/onnx-mlir/compare/9e71c8e5...7d703df4) of previous [9e71c8e5](https://github.com/onnx/onnx-mlir/commit/9e71c8e5) to [7d703df4](https://github.com/onnx/onnx-mlir/commit/7d703df4).

Using bertsquad-12 CPU with settings `--O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z14 --onnx-op-stats TXT ./bertsquad-12.onnx` as an example:
It would previously pass with an a_tol of 0.01 and r_tol of 0.008205. 
![image](https://github.com/onnx/onnx-mlir/assets/42243335/f55f71d6-bb12-4d0d-aa88-00091f3f772a)

Afterward it only passes with an a_tol of 0.01 and r_tol of 0.351550
![image](https://github.com/onnx/onnx-mlir/assets/42243335/623c1648-d873-42df-b43b-10f2362d689a)

# Notes:
Based on a suggestion from @AlexandreEichenberger, the issue goes away if I add `--disable-simd` at model compile time.

**Comment by AlexandreEichenberger** [comment]
Fix is in #2444. I confirmed that the issue was not architecture specific. Reproduced the bug locally, tested with 3 of the above 5 benchmarks that the fix work. Once it is available, @cjvolzka can you run your battery of tests again?

**Comment by cjvolzka** [comment]
I completed the tests. The fix looks good. The CPU results pass with the original tolerances. I need to update the tolerances for a couple of NNPA models but they are minor adjustments to make single elements happy and not major adjustments like before the fix.

Thanks @AlexandreEichenberger for tackling this!
