### ISSUE TITLE
error: scales() and getSizes() can not be both defined

### ISSUE THREAD

**Issue by seanshpark** [onnx/onnx-mlir#2453]
This test ONNX model is from a model that has `Resize` Op exported from pytorch with op version 12.
Which has both `scales` and `sizes` input, and fails to read from onnx-mlir with
> error: scales() and getSizes() can not be both defined

I assume onnx-mlir should import to preserve backward compatibility but fails.

Test model: [ResizeTestv12.zip](https://github.com/onnx/onnx-mlir/files/12390316/ResizeTestv12.zip)

**Comment by sorenlassen** [comment]
this was supposed to be addressed by PR #2277

are you able to see exactly what the types and shapes of the Resize op is?

**Comment by seanshpark** [comment]
@sorenlassen , thanks for the comment!

> this was supposed to be addressed by PR 2277

I'm using `v0.4.0.1` and the patch has landed afterwards...

> are you able to see exactly what the types and shapes of the Resize op is?

Attached test model with Netron is like

![image](https://github.com/onnx/onnx-mlir/assets/4616940/cbaa4670-d0c2-4d97-b496-4a7ef3ecbf48)

Anyway, I'll try with latest code :)

**Comment by seanshpark** [comment]
onnx-mlir says patch exist for this.
- lets try with latest version
- onnx-mlir: 7ee11bce2338a64fb43d47c7e97e7c3b759d1d07
- llvm-project: f580901d5d30e37755212f1c09e5b587587fbfeb

**Comment by seanshpark** [comment]
Found that latest code is working fine :)
