### ISSUE TITLE
CMake paths are sometimes incorrect on Windows

### ISSUE THREAD

**Issue by NathanielMcVicar** [onnx/onnx-mlir#247]
Some paths in CMake on Windows assume binaries can be found at LLVM_PROJ_BUILD/bin whereas on Windows they are typically at LLVM_PROJ_BUILD/Release/bin. The LLVM_PROJ_BIN variable is correctly set across platforms, but is not always used (for example for finding llc in src/CMakeLists.txt:51). On a related note, tools that are built with extensions (i.e. llc.exe on Windows) aren't accounted for.

**Comment by NathanielMcVicar** [comment]
I wanted to call attention to some additional Windows issues here (aggregating to avoid spamming the issue tracker). Consider this list a work in progress, and please let me know if I'm simply making a mistake in our Windows builds! Thanks.

- There is an include of dlfcn.h in ExecusionSession.hpp (should this be Execution?). This is causing failures on some of our Windows build systems (all target, not built in onnx-mlir target). In particular the Windows version is 1) not POSIX compliant and 2) not included in the standard Windows 10 SDK that is suggested in the install instructions. I think this class may need some #ifdefs or other special handling for Windows.
- There is an interaction between ONNX version, Python version and pybind11 version on Windows. I haven't spent a lot of time characterizing it, but I have only been able to get things fully building using ONNX 1.7. This may very well be a problem on my end, but 1.7 does resolve it.

**Comment by doru1004** [comment]
@NathanielMcVicar would you be open to contributing the fixes for some of these issues? I think seeing the fixes as code would be helpful.

**Comment by NathanielMcVicar** [comment]
@doru1004 We do have a number of fixes locally we are planning to upstream soon. There didn't seem to be much demand for the library execution stuff on Windows, but if this is helpful I can look into adding them as well.

**Comment by doru1004** [comment]
Thanks a lot for the update! That sounds great! Please feel free to PR any fixes you have locally, others may find them useful as well.

**Comment by sstamenova** [comment]
#616 Fixed a few more of the issues on Windows. Of this list, the only remaining one is dlfcn.h (the need for equivalent on Windows).

**Comment by sstamenova** [comment]
#722 addresses the last issue left here. That's not to say all is well on Windows after, but all the bugs listed here will have been fixed.

**Comment by NathanielMcVicar** [comment]
Thanks so much Stella for resolving the rest of these! Future Windows problems can be new issues.
