### ISSUE TITLE
Improving macOS support

### ISSUE THREAD

**Issue by mshr-h** [onnx/onnx-mlir#252]
I've been using ONNX MLIR on macOS 10.15.6 for a few weeks now.
Basic functionality works correctly on my machine.
It looks like macOS is already supported but there are few areas which I can do to improve macOS support.
The following are my ideas.

- [x] Add macOS CI pipeline
- [x] Add CI status badge to README

If it's ok, I'll start working on it soon.

**Comment by tjingrant** [comment]
Hi @mshr-h thanks for reaching out!

Some of us use macOS as our primary development platform so using onnx-mlir on macOS should be supported most of the time (however, as you obviously noted, it does break from time to time because we don't have CI testing for it). I'm fine with the proposed work items; as for 

> Add macOS CI pipeline,

 could you make it happen on Travis?

**Comment by mshr-h** [comment]
> could you make it happen on Travis?
Ok.

**Comment by caoimhinuibrian** [comment]
10.15.5 seems to be the latest version of OSX that Travis has. I can add that to our TravisCI build if there is a consensus.

**Comment by mshr-h** [comment]
Here is the macOS versions which is supported by Travis.
https://docs.travis-ci.com/user/reference/osx#jdk-and-macos

There are two type of the latest osx_image, `osx_image: xcode12u` and `osx_image: xcode12`.
I'm not sure which one should be used for onnx-mlir.

**Comment by mshr-h** [comment]
I looked at README and I noticed that there is already a chapter `Installation on UNIX` which include macOS installation.
So we don't need to do `Add build instruction on macOS to document`.

**Comment by tjingrant** [comment]
@mshr-h to add travis support for osx, you'll need to have:
- A docker file for building dependent software (mostly llvm/mlir like here: https://github.com/onnx/onnx-mlir/blob/master/docker/prereq.amd64.Dockerfile), we call this docker image prereq image. 
- You'll need another much simpler dockerfile using the prereq image as a starting point to build onnx-mlir (like this one: https://github.com/onnx/onnx-mlir/blob/master/docker/x86.Dockerfile). The second image is used to build onnx-mlir every time Travis-CI is invoked.

This way, we effectively re-use llvm/mlir build across multiple Travis-CI runs, saving time & compute resources. The prereq image needs to be uploaded to docker hub (https://hub.docker.com/r/onnxmlirczar/onnx-mlir-llvmimage) once it's built, in order for Travis to access it and I can help you with the upload if you show me the dockerfile.

**Comment by mshr-h** [comment]
@tjingrant Thank you for your comment. I just noticed it after I sent PR. So I closed the PR.

I googled about macOS on Docker and I think it's not possible to use Docker for macOS CI.
Because:

- Docker doesn't support macOS as a guest OS. (I'm not a docker professional so it may be wrong.)
- Travis doesn't currently support Docker on macOS. ([https://docs.travis-ci.com/user/docker/](https://docs.travis-ci.com/user/docker/))

So we need to think of alternative ways of build caching mechanism.

**Comment by mshr-h** [comment]
GitHub Actions supports caching mechanism. ([Caching dependencies to speed up workflows - GitHub Docs](https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows))
I think this could be an option for macOS CI.

But there is limitations:

- TTL is 7 days
  - maybe too short?
- The total size of all caches in a repository is limited to 5 GB
  - `llvm-project` directory after building llvm/mlir is 4.2GB on my macOS machine, so it could be ok?

**Comment by tjingrant** [comment]
@mshr-h Github Action sounds like a reasonable choice! 7 days doesn't too bad and if the size of the cache is big enough then we should be okay!

**Comment by mshr-h** [comment]
@tjingrant I'll check Github Actions caching mechanism and see if it works.

**Comment by mshr-h** [comment]
@tjingrant I used [`utils/build-mlir.sh`](https://github.com/onnx/onnx-mlir/blob/master/utils/build-mlir.sh) which `CMAKE_BUILD_TYPE` is `Release`. I'll try `MinSizeRel`.

**Comment by mshr-h** [comment]
I tried `actions/cache@v2` on onnx-mlir compilation. I noticed that the cache targets are compressed when caching.
I cheched the compressed cache file size on different caching configuration (build type / cache target). The result is as follows:

| Cache target | CMAKE_BUILD_TYPE=Release | CMAKE_BUILD_TYPE=MinSizeRel |
| :--- | :---: | ---: |
| `llvm-project` (including `build` directory) | 1814 MB | 1658 MB |
| `llvm-project/build`| 629 MB | 681 MB |

The result shows that both `Release` and `MinSizeRel` are less than 5GB.

**Comment by doru1004** [comment]
I see two merged PRs for this, has the original issue been solved? Please close if so otherwise please let us know what's missing. Thanks a lot.
