### ISSUE TITLE
Failed to compile llama2-7b model due to "Type must be ranked" issue

### ISSUE THREAD

**Issue by chenqiny** [onnx/onnx-mlir#2524]
I tried to compile llama2-7b model.(models: https://huggingface.co/steerapi/Llama-2-7b-chat-hf-onnx)  
But I failed due to Type must be ranked isues.  
I am using ONNX-MLIR on x86 prebuild container:   
onnxmlirczar/onnx-mlir                                                             latest                 6053c88f8692   10 hours ago    1.9GB  
onnx-mlir version 0.4.2, onnx version 1.14.1 (https://github.com/onnx/onnx-mlir.git 2f1003b)  
LLVM version 18.0.0git (https://github.com/llvm/llvm-project.git f66cd9e9556a53142a26a5c21a72e21f1579217c)  
Optimized build with assertions.  
Default target: x86\_64-unknown-linux-gnu  
Host CPU: sandybridge

```
~/code/onnx-mlir/docker> ./onnx-mlir.py -O3 --EmitLib ~/code/Llama-2-7b-chat-hf-onnx/onnx/decoder_model_fp16.onnx
onnx-mlir: /workdir/onnx-mlir/src/Support/TypeUtilities.cpp:42: ArrayRef<int64_t> onnx_mlir::getShape(mlir::Type): Assertion `isRankedShapedType(ty) && "Type must be ranked"' failed.

~/code/onnx-mlir/docker> ./onnx-mlir.py -O3 --EmitLib ~/code/Llama-2-7b-chat-hf-onnx/onnx/decoder_model_merged.onnx
onnx-mlir: /workdir/onnx-mlir/src/Support/TypeUtilities.cpp:42: ArrayRef<int64_t> onnx_mlir::getShape(mlir::Type): Assertion `isRankedShapedType(ty) && "Type must be ranked"' failed.
~/code/onnx-mlir/docker> ./onnx-mlir.py -O3 --EmitLib ~/code/Llama-2-7b-chat-hf-onnx/onnx/decoder_model.onnx
onnx-mlir: /workdir/onnx-mlir/src/Support/TypeUtilities.cpp:42: ArrayRef<int64_t> onnx_mlir::getShape(mlir::Type): Assertion `isRankedShapedType(ty) && "Type must be ranked"' failed.
~/code/onnx-mlir/docker> ./onnx-mlir.py -O3 --EmitLib ~/code/Llama-2-7b-chat-hf-onnx/onnx/decoder_model_merged_quantized.onnx
onnx-mlir: /workdir/onnx-mlir/src/Support/TypeUtilities.cpp:42: ArrayRef<int64_t> onnx_mlir::getShape(mlir::Type): Assertion `isRankedShapedType(ty) && "Type must be ranked"' failed.
```

**Comment by chentong319** [comment]
Did you get the model from hugging face (guessed from the model name)?

**Comment by chenqiny** [comment]
Yes, from github.

Model Link:

https://huggingface.co/steerapi/Llama-2-7b-chat-hf-onnx/tree/main/onnx

> Did you get the model from hugging face (guessed from the model name)? Could you provide a link for me to download the model?

**Comment by chentong319** [comment]
Thanks.
I can reproduce the error. 
The error is caused by unranked tensor.

@tungld The error is in the SimplifyShapeRelatedPass. The assertion error came from the incorrect assumption that the type of ReshapeOp output is ranked.  Even if I add check to ignore Unranked tensor, the  SimplifyShapeRelatedPass still failed quietly.

Then I traced the source of unranked tensor. It came from ReshapeOp.  I create  #2539 to fix the shape inference for Reshape Op to avoid that unranked tensor of output.

Now we can run correctly with `--EmitONNXIR`. But there are still unranked tensor. The source is IfOp in the model.
```
    %1853 = "onnx.If"(%128) ({
      %4366 = "onnx.Squeeze"(%1851, %1464) {onnx_node_name = "/model/layers.0/self_attn/Squeeze"} : (tensor<1x1x?x128xf16>, tensor<1xi64>) -> tensor<1x?x128xf16>
      onnx.Yield {onnx_node_name = "/model/layers.0/self_attn/Squeeze_onnx.Yield_40"} %4366 : tensor<1x?x128xf16>
    }, {
      onnx.Yield {onnx_node_name = "/model/layers.0/self_attn/rotary_emb/Slice_onnx.Yield_38"} %1851 : tensor<1x1x?x128xf16>
    }) {input_names = [], onnx_node_name = "/model/layers.0/self_attn/If", output_names = ["/model/layers.0/self_attn/Identity_output_0"]} : (tensor<1xi1>) -> tensor<*xf16>
```
The condition for the IfOP is a constant. We should do constant folding on it.

**Comment by chentong319** [comment]
PR #2544 is created to fold IfOp with constant condition. 
With both PR, the error in the code gen:
```
opt: decoder_model_fp16.unoptimized.bc: error: can't skip to bit 107836664576 from 320
opt -O0 --mtriple=x86_64-apple-darwin22.3.0 --code-model small -o decoder_model_fp16.bc decoder_model_fp16.unoptimized.bc
Error message: 
Program path: /Users/chentong/Projects/llvm-project/build/bin/opt
```

**Comment by chentong319** [comment]
I also tried 7b-f32 model from github.com:microsoft/Llama-2-Onnx-7-32.git. Error in SimplifyShapeRelatedOps. At line 332, the size of slicedDims is 0.

**Comment by AlexandreEichenberger** [comment]
@chentong319 is this issue still open?

**Comment by chenqiny** [comment]
> @chentong319 is this issue still open?

@chentong319 @AlexandreEichenberger @tungld Thank you.

It works for me now after I applied "-store-constants-to-file /external/onnx-models/llama-7b/decoder\_model.onnx" option and use float32 model.

podman exec onnx-mlir31025 onnx-mlir -O3 --maccel=NNPA -store-constants-to-file /external/onnx-models/llama-7b/decoder\_model.onnx

**Comment by tungld** [comment]
> podman exec onnx-mlir31025 onnx-mlir -O3 --maccel=NNPA -store-constants-to-file /external/onnx-models/llama-7b/decoder_model.onnx

FYI, with new changes in onnx-mlir, you need `--mcpu=z16` to trigger NNPA code.

**Comment by AlexandreEichenberger** [comment]
@tung: would it make sense to issue a warning if we have a NNPA access but no `mcpu` flag?

**Comment by tungld** [comment]
Yes, it totally makes sense, I often forget --mcpu :)

**Comment by tungld** [comment]
@AlexandreEichenberger this PR #2589 is to issue a warning.
