### ISSUE TITLE
Int64 ops seems to be placed on NNPA device

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#2540]
When running on Roberta-base-11, I observe an i64 op being mapped to the NNPA. That appears to be an issue.

```
onnx-mlir --EmitONNXIR -O3 -mcpu=z16 -maccel=NNPA --shapeInformation=0:1x384 roberta-base-11.onnx 2>&1 |tee bibi-pytorch-dims.mlir
```

output list this
```
    %327 = "onnx.Mul"(%326, %325) {onnx_node_name = "Mul_28"} : (tensor<1x384xi32>, tensor<1x384xi32>) -> tensor<1x384xi32>
    %328 = "onnx.Cast"(%327) {onnx_node_name = "Cast_29", saturate = 1 : si64, to = i64} : (tensor<1x384xi32>) -> tensor<1x384xi64>
    %329 = "onnx.Add"(%328, %122) {device = "nnpa", onnx_node_name = "Add_31"} : (tensor<1x384xi64>, tensor<i64>) -> tensor<1x384xi64>
```

note that the last op is of type `i64` and is mapped to the NNPA. Is there a missing rule?

**Comment by tungld** [comment]
@AlexandreEichenberger thanks for reporting this! It was a bug in rewrite-onnx-for-zhigh pass. Lucky, the op is finally not going further to NNPA because the other pass `onnx-to-zhigh` will check element types. Created PR #2548 to fix the bug.
