### ISSUE TITLE
Using onnx-mlir through incremental stages

### ISSUE THREAD

**Issue by kwu91** [onnx/onnx-mlir#255]
Hello, 

I'm trying to use onnx-mlir on the [mnist-7 model](https://github.com/onnx/models/tree/master/vision/classification/mnist). My intention is to build a shared library through incremental stages instead of at once with `--EmitLib`. The purpose is to have the option of applying additional transformations. I will step through an example:

The first two sequences work fine:

```
onnx-mlir-opt --convert-onnx-to-krnl model.onnx > 1.model.krnl.mlir
onnx-mlir-opt --convert-krnl-to-affine 1.model.krnl.mlir > 2.model.affine.mlir
```

At this time, I want to apply some transformations. For example, I want to vectorize the affine loops by calling:
```
onnx-mlir-opt --affine-super-vectorize=virtual-vector-size=128 --lower-affine 2.model.affine.mlir > 3.model.vectorize.mlir
```

So far, everything is working until I want to lower everything into the LLVM Dialect by calling:

```
onnx-mlir-opt --convert-vector-to-scf --convert-krnl-to-llvm 3.model.vectorize.mlir > 4.model.llvm.mlir
```

I get the error:
```
error: failed to legalize operation 'vector.transfer_write'
```

I add the Vector Dialect as legal dialect in the `ConvertKrlnToLLVMPass`, which allows me to continue. `--convert-krnl-to-llvm` no longer gives any errors at this point. Next, I want to use `mlir-translate` to get LLVM-IR. 

```
mlir-translate --mlir-to-llvmir 4.model.llvm.mlir > 5.model.ll
```

I get the following error. It appears that CallOps to functions that return void are returning values. I made some changes to the `ConvertKrlnToLLVMPass`. 
```
5.model.llvm.mlir:447:134: error: void type only allowed for function results
    %423 = llvm.call @llvm.memcpy.p0i8.p0i8.i64(%415, %417, %421, %422) : (!llvm<"i8*">, !llvm<"i8*">, !llvm.i64, !llvm.i1) -> !llvm.void
```
The problematic line above will become something like this which `mlir-translate` accepts.
```
llvm.call @llvm.memcpy.p0i8.p0i8.i64(%415, %417, %421, %422) : (!llvm<"i8*">, !llvm<"i8*">, !llvm.i64, !llvm.i1) -> ()
```

`mlir-translate` still reports an error which is related to the lowering of the memref struct. I think the correct approach should be to generate an `LLVM::UndefOp` instead of loading from the argument. Otherwise, if an `InsertValueOp` is called afterwards, it will try to insert a value to the pointer of the struct which will give the error below.
```
error: custom op 'llvm.insertvalue' expected wrapped LLVM IR structure/array type
    %7 = llvm.insertvalue %6, %4[0 : i32] : !llvm<"{ float*, float*, i64, [4 x i64], [4 x i64] }*">
```
After my changes, the problematic line above will become something like below. 
```
%4 = llvm.mlir.undef : !llvm<"{ float*, float*, i64, [4 x i64], [4 x i64] }">
...
%7 = llvm.insertvalue %6, %4[0 : i32] : !llvm<"{ float*, float*, i64, [4 x i64], [4 x i64] }">
```

At this point `mlir-translate` works. I can then proceed to build an object file from the LLVM-IR and link with the appropraite runtime libraries to produce a working shared library.

***

I made a few changes to two test cases to reflect the change to the return value for void. Otherwise, the tests appear to pass.

```
Testing Time: 0.31s
  Unsupported:  1
  Passed     : 26
```

My changes are in my fork: https://github.com/onnx/onnx-mlir/compare/master...kwu91:fix-krnl-to-llvm

Let me know your thoughts and suggestions. Thanks!

**Comment by tjingrant** [comment]
@kwu91 thanks a bunch for tackling the problem, really appreciate your help! The change from llvm void type to empty list seems reasonable, but I'm surprised the change from loadOp to an undefOp works, given that the semantics of these two operations aren't exactly the same. Can you try running the backend test to see if results match up? You can invoke the backend test by running `make check-onnx-backend`. 

Regardless, I've looked at your changes and it seems like a very good starting point. We can discuss and iterate from here and this project would really benefit from your effort! Would you please submit a pull request based on the current state of your patch and we can work together from here?

**Comment by kwu91** [comment]
@tjingrant Thanks for the feedback! I've ran `make check-onnx-backend` and it looks okay although it seems like a lot of tests were skipped?

```
Ran 1790 tests in 81.552s

OK (skipped=1574)
```

I'll go ahead and make a PR.

**Comment by ArunaKote** [comment]
How to do Vector Dialect as legal dialect in the ConvertKrlnToLLVMPass?

Thank You

**Comment by tjingrant** [comment]
@ArunaKote I think we are in the process of adding vector dialect to our lowering workflow.

@AlexandreEichenberger can probably give you more context/details.

**Comment by ArunaKote** [comment]
OK .Thank You

**Comment by ArunaKote** [comment]
How do I lower MLIR to LLVM IR using ONNX-MLIR?

**Comment by doru1004** [comment]
> How to do Vector Dialect as legal dialect in the ConvertKrlnToLLVMPass?

There are several instance in MLIR and ONNX-MLIR which do this for other dialects, you'd have to have a look at those. You may also need to include the MLIR libs which support the Vector dialect.

**Comment by doru1004** [comment]
> How do I lower MLIR to LLVM IR using ONNX-MLIR?

If you have MLIR code generated by ONNX-MLIR you can use the `onnx-mlir-opt` tool to lower that to LLVM dialect.

**Comment by doru1004** [comment]
@kwu91 I see that your PR was merged, does this mean that your initial issue is now resolved? If so please feel free to close the issue.
@ArunaKote If there are still outstanding questions/issues please open a new issue so that we can track them appropriately.

**Comment by kwu91** [comment]
Thank you, I did forget. I will close this issue.
