### ISSUE TITLE
CTest unit tests failing on some operating systems/arch combinations

### ISSUE THREAD

**Issue by NathanielMcVicar** [onnx/onnx-mlir#258]
I am trying to enable ctest for our build pipelines. Unfortunately, there are a number of failures due to Google benchmark including gtest which includes some tests which can't be disabled through cmake options (I'm seeing this on Ubuntu 18.04 x64 and Windows x64). Some of these failing tests have been fixed in gtest upstream, but the ONNX MLIR submodule is to a fork that hasn't been merged recently. I was wondering what the motivation is for using a fork of Google benchmark and not pointing to the current master? If that can't be changed, would it be possible to merge master into the fork? Thanks!

edit: It might also be a good idea to enable the unit tests in the some of the other CI pipelines, to detect failures like this going forward. They are currently running in the Jenkins CI and Circle CI, but not on ADO or Travis.

**Comment by tjingrant** [comment]
> I was wondering what the motivation is for using a fork of Google benchmark and not pointing to the current master? 

It was to work around some peculiar constraint we were facing. The major change in the forked repo is that I made gtest a submodule of google benchmark (otherwise you either have to manually clone gtest or rely on cmake to download gtest on-the-fly during build time). I don't think we face the same set of constraints anymore and likely switching to the official version of google benchmark will work just fine.

> They are currently running in the Jenkins CI and Circle CI, but not on ADO or Travis.

I can look into enabling them in Travis; Bringing the testing script in ADO up-to-date would likely require some coordinated efforts with folks on Microsoft side of the things, wonder if @jcwchen can take a crack at translating our CircleCI build scripts (https://github.com/onnx/onnx-mlir/blob/master/.circleci/config.yml) to ADO? Likely it won't work out of the box and some fixing is required (https://github.com/onnx/onnx-mlir/issues/247), I can potentially take it from there.

**Comment by NathanielMcVicar** [comment]
> otherwise you either have to manually clone gtest or rely on cmake to download gtest on-the-fly during build time

Thanks for being so patient explaining all this! Given everything so far, I'm considering creating a PR that would point the benchmark submodule to master and set `BENCHMARK_ENABLE_GTEST_TESTS OFF`. This works for me locally, but as you say anyone who wants to use `gtest_add_tests` in the future would have to download gtest and there may be some benefit to have the default gtest suite as part of CI builds (although it's not clear to me what that is). Does this seem reasonable, or too radical at this point?

**Comment by tjingrant** [comment]
That sounds reasonable! 

> This works for me locally, but as you say anyone who wants to use gtest_add_tests in the future would have to download gtest and there may be some benefit to have the default gtest suite as part of CI builds (although it's not clear to me what that is)

Maybe we can set this flag `BENCHMARK_DOWNLOAD_DEPENDENCIES` to ON? As in https://github.com/google/benchmark/blob/e5ea03ce07997620980636b3ee7e6117d68bc6ad/CMakeLists.txt#L31 . It tells CMake to download gtest (among other things) when cmake scripts are run.

**Comment by gongsu832** [comment]
As I'm about to setup the model tests and switch over to googletest, should we just make googletest a submodule?

**Comment by NathanielMcVicar** [comment]
@tjingrant Does it make sense to remove the `PATH` setting from before `make test` on the various CI platforms (and buildbot) as part of the PR? It shouldn't be required anywhere anymore.

**Comment by tjingrant** [comment]
> Does it make sense to remove the PATH setting from before make test on the various CI platforms (and buildbot) as part of the PR? It shouldn't be required anywhere anymore.

If that works then sure (I suspect that OMTestConv may fail).

> edit: I could also try to add the Google tests to Travis CI as part of the PR if that makes sense to you.

That makes sense if it doesn't present too much trouble.

**Comment by NathanielMcVicar** [comment]
Hopefully I've done it correctly. Please take a look when you have a chance. I can't figure out where Jenkins CI is configured in the repo. Is the config only available to the IBM folks?

**Comment by NathanielMcVicar** [comment]
Fixed in #262
