### ISSUE TITLE
 Type mismatch error when using onnx exported by torch.onnx.dynamo_export

### ISSUE THREAD

**Issue by ShuoerWang** [onnx/onnx-mlir#2650]
error:
```
loc("onnx.If"("n4")): error: 'scf.if' op  along control flow edge from Region #0 to parent results: source type #0 'memref<8x4xf32>' should match input type #0 'memref<?x?xf32>'
```
code: https://pytorch.org/docs/stable/onnx_dynamo.html#a-simple-example
          (add export_output.save("mlp.onnx") at the end)
also tried exporting static shape:
```
export_options = torch.onnx.ExportOptions(dynamic_shapes=False)
export_output = torch.onnx.dynamo_export(model, tensor_x, export_options=export_options)
```
command: onnx-mlir --EmitMLIR mlp.onnx

**Comment by cjvolzka** [comment]
@ShuoerWang, I tried this today (using commit 737516a and `--EmitMLIR mlp.onnx`) and I was able to compile without issue. Are you still experiencing this problem or can this issue be closed?

**Comment by cjvolzka** [comment]
Closing since I haven't heard back and I was not able to replicate. Feel free to re-open if you are able to replicate the issue.
