### ISSUE TITLE
Model Zoo Report is empty 

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#2672]
I have recently seen that the model zoo report is empty. Not sure if it is related to the new organization of models in the model zoo or not. @gongsu832 any thoughts?

<img width="614" alt="Screenshot 2024-01-10 at 22 54 03" src="https://github.com/onnx/onnx-mlir/assets/1230113/4c68b799-ef41-4193-998c-a7ceaaa94fa9">

**Comment by AlexandreEichenberger** [comment]
The onnx folks moved the old onnx zoo repo under a new subdirectory, I would chat with @cjvolzka who I think found the correct new place for the data.

**Comment by cjvolzka** [comment]
All the "old" models in the zoo moved to https://github.com/onnx/models/tree/main/validated. So for example if a model path was https://github.com/onnx/models/tree/main/vision/classification/mnist it should become https://github.com/onnx/models/tree/main/validated/vision/classification/mnist

**Comment by gongsu832** [comment]
Sigh. First "archive", now "validated". Wonder what's next.

**Comment by tungld** [comment]
Solved by #2678
