### ISSUE TITLE
Discussion: Following Stablehlo llvm commits opposed to torch-mlir

### ISSUE THREAD

**Issue by hamptonm1** [onnx/onnx-mlir#2674]
This was a topic I brought up at the community meeting last night. Is there anyone opposed to following the llvm commits from `stablehlo` opposed to `torch-mlir`?

I ask this question because of the following:
1.  We need to update `stablehlo` anyways
2. `Stablehlo` always has an llvm commit associated with each update
3. `Stablehlo` frequently upgrades llvm compared to `torch-mlir` which does not have a steady cadence

**Comment by hamptonm1** [comment]
Thoughts?- @maxbartel @flemairen6 @philass 

FYI- @AlexandreEichenberger

**Comment by ashay** [comment]
That sounds great!  Is there a plan to update StableHLO at a specific cadence or is the plan to update as and when necessary?  Either is fine, I'm asking so I know what to expect.

**Comment by hamptonm1** [comment]
> That sounds great! Is there a plan to update StableHLO at a specific cadence or is the plan to update as and when necessary? Either is fine, I'm asking so I know what to expect.

I think it would make sense to update StableHLO at a specific cadence as well. Honestly, whoever has the update for that week can do both StableHLO and LLVM together. I am open to the thoughts of others too :)

**Comment by hamptonm1** [comment]
Any thoughts @Connor-XY ?

**Comment by Connor-XY** [comment]
I think this is a good idea since Torch-Mlir doesn't give out green commits for now. We can directly use the LLVM commit of the corresponding StableHLO. Since they update quite frequently, we only need to pick the latest commit and the corresponding LLVM commit should be compatible with StableHLO.

**Comment by hamptonm1** [comment]
I am glad everyone is on board!!

**Comment by flemairen6** [comment]
Just seeing the discussion now, but I'm also on board for this change, that's a good idea. Thanks!

**Comment by hamptonm1** [comment]
> Just seeing the discussion now, but I'm also on board for this change, that's a good idea. Thanks!

Wonderful!!! Thanks for your input :)

**Comment by hamptonm1** [comment]
I am marking this issue as done! Thanks everyone for the feedback :)
