### ISSUE TITLE
Regarding the issues with ONNXMaxPoolSingleOutOp lower

### ISSUE THREAD

**Issue by 2drag0n** [onnx/onnx-mlir#2683]
Attempting to convert the mnist onnx model to MLIR encountered the following issues:
model[https://github.com/onnx/models/blob/main/validated/vision/classification/mnist/model/mnist-12-int8.onnx]

1、loc("onnx.MaxPoolSingleOut"("Pooling66_quant")): error: 'arith.constant' op integer return type must be signless.
The prompt here is that the return type must be signless, but I see that the source code directly creates negativeInf. Is there a problem?
[https://github.com/onnx/onnx-mlir/blob/main/src/Conversion/ONNXToKrnl/NN/Pooling.cpp:24]

2、loc("onnx.MaxPoolSingleOut"("Pooling66_quant")): error: 'arith.cmpi' op operand #0 must be signless-integer-like, but got 'ui8'.
The prompt here is that the operand #0 type must be signless, and ui8 is signless. It seems that cmpi does not support ui8 yet?

**Comment by AlexandreEichenberger** [comment]
This errors comes from the fact that we don't have too much support for small int computations. Would you have time to add support @2drag0n ?

**Comment by 2drag0n** [comment]
@AlexandreEichenberger  Thank you for your reply. I am grateful for the opportunity to make a contribution, but I am sorry that I currently do not have time to do so. If I have time in the future, I am willing to add it.
