### ISSUE TITLE
onnx to mlir

### ISSUE THREAD

**Issue by ArunaKote** [onnx/onnx-mlir#269]
while converting onnx to mlir using onnx-mlir,
           I am getting this error:/llvm-project/mlir/lib/IR/StandardTypes.cpp:373: static mlir::MemRefType mlir::MemRefType::get(llvm::ArrayRef<long int>, mlir::Type, llvm::ArrayRef<mlir::AffineMap>, unsigned int): Assertion `result && "Failed to construct instance of MemRefType."' failed.
Aborted (core dumped)

Thank you

**Comment by caoimhinuibrian** [comment]
Is this still a problem?
If it is, please make a minimal testcase that demonstrates the issue and give instructions for reproducing it.

**Comment by ArunaKote** [comment]
I am trying to convert ONNX to MLIR using onnx-mlir --EmitMLIR .But I am getting error like:
error: unexpected output has non-Constant shape
onnx-mlir: /home/aruna/llvm-project/mlir/include/mlir/IR/Types.h:338: U mlir::Type::cast() const [with U = mlir::MemRefType]: Assertion `isa<U>()' failed.
Aborted (core dumped)
My Tensorflow model is like:

model = Sequential([
    Conv2D(16, 3, padding='same', activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH ,3)),
    MaxPooling2D(),
    Conv2D(32, 3, padding='same', activation='relu'),
    MaxPooling2D(),
    Conv2D(64, 3, padding='same', activation='relu'),
    MaxPooling2D(),
    Flatten(),
    Dense(512, activation='relu'),
    Dense(1, activation='sigmoid')
])


Thank You

**Comment by doru1004** [comment]
@ArunaKote is this model still failing? If so, can you post the ONNX model that corresponds to your TF code?

**Comment by ArunaKote** [comment]
I able to solve this issue by reinstalling onnx-mlir package.


Thank you

**Comment by doru1004** [comment]
Awesome I'll close this then.
