### ISSUE TITLE
LLVM ERROR: SmallVector unable to grow.

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#2693]
Using a recent onnx-mlir commit (58f3746), attempting to `--EmitONNXIR` from the attached [SmallVector.mlir.zip](https://github.com/onnx/onnx-mlir/files/14117712/SmallVector.mlir.zip) (generated using `--EmitONNXBasic`), I get the following error.

```
--O3 --EmitONNXIR --mtriple=s390x-ibm-loz --mcpu=z16 --maccel=NNPA SmallVector.mlir -v && cat test.onnx.mlir
Onnx-mlir command: onnx-mlir -o test --O3 --EmitONNXIR --mtriple=s390x-ibm-loz --mcpu=z16 --maccel=NNPA SmallVector.mlir -v
LLVM ERROR: SmallVector unable to grow. Requested capacity (9223372036854775808) is larger than maximum value for size type (4294967295)

```

However if I use an image built from the current released onnx-mlir (onnx-mlir version 0.4.1.1, commit 40615b3) the above works fine:
```
--O3 --EmitONNXIR --mtriple=s390x-ibm-loz --mcpu=z16 --maccel=NNPA SmallVector.mlir -v
Full MLIR code written to: 
	SmallVector.onnx.mlir

Constant-free MLIR Code written to: 
	SmallVector.tmp

Use:
	SmallVector.onnx.mlir
to continue lowering the code to other dialects.
```

## Notes
* The mlir file is a stripped out version of a model which can't be shared
* If I remove the `%33` Mode or the `%50` Reshape, I also don't get the error.

**Comment by tungld** [comment]
I think the error happened during shape-inference for `ONNXReshape`:
```
%20 = "onnx.Reshape"(%5, %19) {allowzero = 0 : si64, onnx_node_name = ""} : (tensor<25x1x36xf32>, tensor<?xi64>) -> tensor<*xf32>
```
The second input's dimension is unknown (`tensor<?xi64`) so it failed to infer the output shape.

This can be solved if `onnx.Mod` is folded into a constant by constant propagation. Then the other ops (e.g. reshape, slice, etc.) will be folded also and finally the shape inference for`onnx.Reshape` succeeds. 
I heard that @hamptonm1 is doing constant propagation for `onnx.Mod`.
