### ISSUE TITLE
Support Opset20 for ReduceMin/Max

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#2728]
ONNX 1.15.0 / OpSet 20 added support for bool data type. 
* Update onnx-mlir to support bool for ReduceMin and ReduceMax
* Update https://github.com/onnx/onnx-mlir/blob/01c5c9fb536a43cde36abccf562bb2f6cb594cb4/test/backend/inference_backend.py#L2489 https://github.com/onnx/onnx-mlir/blob/01c5c9fb536a43cde36abccf562bb2f6cb594cb4/test/backend/inference_backend.py#L2434 and regenerate https://github.com/onnx/onnx-mlir/blob/main/docs/SupportedONNXOps-cpu.md to show support for OpSet 20 for those Ops

**Comment by hamptonm1** [comment]
This is done!
