### ISSUE TITLE
Support Opset20 for ConstantOfShape

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#2729]
ONNX 1.15.0 / OpSet 20 added support for bfloat16 data type for ConstantOfShape. 
* Update onnx-mlir to support bfloat16 for ConstantOfShape
* Update https://github.com/onnx/onnx-mlir/blob/01c5c9fb536a43cde36abccf562bb2f6cb594cb4/test/backend/inference_backend.py#L621  and regenerate https://github.com/onnx/onnx-mlir/blob/main/docs/SupportedONNXOps-cpu.md to show support for OpSet 20 for ops

**Comment by hamptonm1** [comment]
@mikeessen I will close this out since your merged the PR :)
