### ISSUE TITLE
DequantizeLinear/QuantizeLinear lowering

### ISSUE THREAD

**Issue by SerenaC94** [onnx/onnx-mlir#2742]
Hello,

looking at the [supported operators list](https://github.com/onnx/onnx-mlir/blob/main/docs/SupportedONNXOps-cpu.md), it seems that it should be possible to run onnx-mlir on a model containing DequantizeLinear/QuantizeLinear ops. However, when I try to do it on a model that has been quantized through onnxruntime I get the following error:

```
onnx-mlir: /workdir/onnx-mlir/src/Conversion/ONNXToKrnl/Math/Elementwise.cpp:2153: auto onnx_mlir::ONNXElementwiseUnaryOpLowering<mlir::ONNXDequantizeLinearOp>::matchAndRewrite(mlir::ONNXDequantizeLinearOp, OpAdaptor, ConversionPatternRewriter &)::(anonymous class)::operator()(KrnlBuilder &, ValueRange) const [ElementwiseUnaryOp = mlir::ONNXDequantizeLinearOp]: Assertion `isScalarValue(operands[i]) && "unary expected scalar additional values"' failed.
```

Does this have to to with the limitation on per-tensor/per-axis quantization mentioned in the notes? If yes, is there an option that I can select in onnxruntime to generate a compatible model?

**Comment by QingChuanWS** [comment]
Hi, could you share an onnx model to help me to reproduce this problem?

**Comment by SerenaC94** [comment]
Unfortunately, I am not at liberty to disclose the model. I'll close this as we moved on from this project, but if anyone else finds the discussion useful feel free to reopen it.
