### ISSUE TITLE
Dynamic backend tests cause errors.

### ISSUE THREAD

**Issue by negiyas** [onnx/onnx-mlir#2743]
(Updated in 2024/05/08)
All issues errors with dynamic backend tests (on CPU) are fixed. Thanks!

(Updated in 2024/03/26)

PR #2735 enables dynamic backend tests, but the following backend tests still fail.
Accordingly PR #2735 temporally disables these failed dynamic backend tests to pass the Jenkins tests.

Please look at the failed tests if you have time. We may have to (1) fix the issues, (2) change the test conditions, or (3) remove the tests if we can confirm that they are not supported.

Please check the following marks if fixed some of them. Thanks.
PR #2753 executes the failed dynamic backend tests, and  you can look at the error log at https://www.onnxmlir.xyz/jenkins/job/ONNX-MLIR-Pipeline-Docker-Build/14379/consoleText .

[X] 1. "test_castlike_FLOAT_to_DOUBLE_cpu" # Fixed by PR#2762
[X] 2. "test_castlike_DOUBLE_to_FLOAT_cpu" # Fixed by PR#2762
[X] 3. "test_castlike_FLOAT_to_FLOAT16_cpu" # Fixed by PR#2762
[X] 4. "test_castlike_FLOAT16_to_FLOAT_cpu" # Fixed by PR#2762
[X] 5. "test_castlike_FLOAT16_to_DOUBLE_cpu" # Fixed by PR#2762
[X] 6. "test_castlike_DOUBLE_to_FLOAT16_cpu" # Fixed by PR#2762
[X] 7. "test_convtranspose_1d_cpu"
[X] 8. "test_convtranspose_3d_cpu"
[X] 9. "test_convtranspose_autopad_same_cpu"
[X] 10. "test_convtranspose_cpu"
[X] 11. "test_convtranspose_dilations_cpu"
[X] 12. "test_convtranspose_kernel_shape_cpu"
[X] 13. "test_convtranspose_output_shape_cpu"
[X] 14. "test_convtranspose_pad_cpu"
[X] 15. "test_convtranspose_pads_cpu"
[X] 16. "test_depthtospace_example_cpu"
[X] 17. "test_depthtospace_crd_mode_example_cpu"
[X] 18. "test_einsum_batch_diagonal_cpu"
[X] 19. "test_einsum_batch_matmul_cpu"
[X] 20. "test_einsum_inner_prod_cpu"
[X] 21. "test_einsum_sum_cpu"
[X] 22. "test_einsum_transpose_cpu"
[X] 23. "test_gathernd_example_int32_cpu" # Fixed by PR#2748
[X] 24. "test_gathernd_example_float32_cpu" # Fixed by PR#2748
[X] 25. "test_gathernd_example_int32_batch_dim1_cpu" # Fixed by PR#2748
[X] 26. "test_instancenorm_example_cpu" # Fixed by PR#2763
[X] 27. "test_instancenorm_epsilon_cpu" # Fixed by PR#2763
[X] 28. "test_constant_pad_cpu" # Fixed by PR#2754
[X] 29. "test_edge_pad_cpu" # Fixed by PR#2754
[X] 30. "test_reflect_pad_cpu" # FIxed by PR#2754
[X] 31. "test_spacetodepth_example_cpu"
[X] 32. "test_top_k_cpu"  # Fixed by PR#2735
[X] 33. "test_top_k_smallest_cpu" # Fixed by PR#2735
[X] 34. "test_top_k_negative_axis_cpu" # Fixed by PR#2735
[X] 35. "test_onnxmlir_top_k_float16_cpu" # Fixed by PR#2735
[X] 36. "test_onnxmlir_top_k_smallest_float16_cpu" # Fixed by PR#2735

(This issue replaces the issue #2639 , since the situation is changed by PR #2735.)

**Comment by AlexandreEichenberger** [comment]
Update on the 2 instance norm failing tests. When I compile a model with dynamic shape, and then set the shapes at runtime, it works. But when we compile a model with dynamic shape AND set the size of these shapes by a compiler option, the compiler exit with an error. @chentong319 has a similar problem with another program, and he will test his solution (setting the output type to the same as the original type). Once Tong confirms that this work on his case, will do the same on these 2 cases of instance norm.

**Comment by AlexandreEichenberger** [comment]
@chentong319 thanks for the suggested fix, it worked. PR #2763 implements the change for instance norm cases (added also group norm which needs the same pattern, even if it may not be tested at this time).

**Comment by negiyas** [comment]
I am closing this issue, since ll issues errors with dynamic backend tests (on CPU) are fixed. Thanks!
