### ISSUE TITLE
Performance degradation in Models running on NNPA

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#2769]
The following models are taking longer when running on NNPA now compared to the 0.4.1 release. 

* gpt2-10.onnx 
    * about 30% worse  
    * 0.4.1 - Total runMainGraph() time over all 100 inference(s) was 823.821 ms averaging 8.23821 ms per inference.
    * main - Total runMainGraph() time over all 100 inference(s) was 1187.16 ms averaging 11.8716 ms per inference.
* roberta-sequence-classification-9.onnx 
    * about 28% worse
    * 0.4.1 - Total runMainGraph() time over all 100 inference(s) was 497.415 ms averaging 4.97415 ms per inference.
    * main - Total runMainGraph() time over all 100 inference(s) was 692.769 ms averaging 6.92769 ms per inference.
* mobilenetv2-12.onnx 
    * about 6% worse
    * 0.4.1 - Total runMainGraph() time over all 100 inference(s) was 1705.98 ms averaging 17.0598 ms per inference.
    * main - Total runMainGraph() time over all 100 inference(s) was 1809.34 ms averaging 18.0934 ms per inference.
* shufflenet-v2-12.onnx
    * about 6% worse
    * 0.4.1 - Total runMainGraph() time over all 100 inference(s) was 852.561 ms averaging 8.52561 ms per inference.
    * main - Total runMainGraph() time over all 100 inference(s) was 905.177 ms averaging 9.05177 ms per inference.

**Comment by tungld** [comment]
@cjvolzka Were these two lines swapped? I saw `main` is faster than `0.4.1`
```
0.4.1 - Total runMainGraph() time over all 100 inference(s) was 1187.16 ms averaging 11.8716 ms per inference.
main - Total runMainGraph() time over all 100 inference(s) was 823.821 ms averaging 8.23821 ms per inference.
```

I tried gpt2-10 with the latest onnx-mlir, but could not get any number close to 8.2ms or 11.8 ms per inference.
```shell
$ /workdir/onnx-mlir/build/Debug/bin/onnx-mlir -O3 -mcpu=z16 -maccel=NNPA gpt2-10.onnx --EmitLib -v --onnx-op-stats TXT
```
 
I ran 3 warmup iterations, then 100 iterations on a shared machine:
```shell
$ numactl -C 21 python /workdir/onnx-mlir/utils/RunONNXModel.py --load-so=./gpt2-10.so --load-ref=./GPT2/test_data_set_0  -w 3 -n 100
```
 
These are the last 10 iterations:
```
  91st iteration, 0.008928904309868813, seconds
  92nd iteration, 0.005965786054730415, seconds
  93rd iteration, 0.008335268124938011, seconds
  94th iteration, 0.005891425535082817, seconds
  95th iteration, 0.008002739399671555, seconds
  96th iteration, 0.005918256938457489, seconds
  97th iteration, 0.007969923317432404, seconds
  98th iteration, 0.005898011848330498, seconds
  99th iteration, 0.0057859160006046295, seconds
  100th iteration, 0.005838800221681595, seconds
  Statistics 1 (excluding warmup), min, 5.756676e-03, max, 9.120632e-03, mean, 6.568274e-03, stdev, 1.071218e-03
  Statistics 2 (no warmup/quart.), min, 5.898012e-03, max, 6.679624e-03, mean, 6.068553e-03, stdev, 2.152642e-04
```

So it's 6.6ms on average and max 9.12ms per inference.

**Comment by cjvolzka** [comment]
> Were these two lines swapped? 

Yes, they were. I fixed the description above to correct for that. 

>I tried gpt2-10 with the latest onnx-mlir, but could not get any number close to 8.2ms or 11.8 ms per inference.

The machine I use for testing is a shared machine. I can't control what other activities happen on it so that may be influencing the raw numbers. The important part is the difference between the old release and the new one. 

To try and account for the background activity, I did each set of 100 about 3-5 times swapping between the main and 0.4.1 for each run. All of the "main" results for a series came out about the same as all the 0.4.1 results. So the background activity was likely affecting all the runs in the same way.

**Comment by tungld** [comment]
I created a PR #2775 to address this issue. I saw the performance was better, but still need your confirmation with your environment @cjvolzka. Thanks!

**Comment by AlexandreEichenberger** [comment]
PR was merged, so you should be able to pick it up from the main

**Comment by AlexandreEichenberger** [comment]
@cjvolzka would you be able to check if the new code address the concerns on GPT2?

**Comment by cjvolzka** [comment]
I had to wait until I slow time on the machine to get clear. The situation has improved for gpt2-10.onnx but hasn't been fully resolved. The old release is still faster by an appreciable amount. The current fix didn't seem to really affect the other models.

```
Testing v0.4.1.2/40615b3            gpt2-10.onnx Total runMainGraph() time over all 20 inference(s) was 181.929 ms averaging 9.09643 ms per inference.
Testing main-after-PR-2775/5ef91c1  gpt2-10.onnx Total runMainGraph() time over all 20 inference(s) was 197.918 ms averaging 9.89592 ms per inference.
Testing main-before-PR-2775/9514d68 gpt2-10.onnx Total runMainGraph() time over all 20 inference(s) was 249.405 ms averaging 12.4702 ms per inference.

Testing v0.4.1.2/40615b3            roberta-sequence-classification-9.onnx Total runMainGraph() time over all 20 inference(s) was 113.711 ms averaging 5.68555 ms per inference.
Testing main-after-PR-2775/5ef91c1  roberta-sequence-classification-9.onnx Total runMainGraph() time over all 20 inference(s) was 150.138 ms averaging 7.50692 ms per inference.
Testing main-before-PR-2775/9514d68 roberta-sequence-classification-9.onnx Total runMainGraph() time over all 20 inference(s) was 151.339 ms averaging 7.56693 ms per inference.

Testing v0.4.1.2/40615b3            mobilenetv2-12.onnx Total runMainGraph() time over all 20 inference(s) was 353.372 ms averaging 17.6686 ms per inference.
Testing main-after-PR-2775/5ef91c1  mobilenetv2-12.onnx Total runMainGraph() time over all 20 inference(s) was 368.238 ms averaging 18.4119 ms per inference.
Testing main-before-PR-2775/9514d68 mobilenetv2-12.onnx Total runMainGraph() time over all 20 inference(s) was 366.389 ms averaging 18.3194 ms per inference.

Testing v0.4.1.2/40615b3            shufflenet-v2-12.onnx Total runMainGraph() time over all 20 inference(s) was 176.038 ms averaging 8.80189 ms per inference.
Testing main-after-PR-2775/5ef91c1  shufflenet-v2-12.onnx Total runMainGraph() time over all 20 inference(s) was 184.371 ms averaging 9.21856 ms per inference.
Testing main-before-PR-2775/9514d68 shufflenet-v2-12.onnx Total runMainGraph() time over all 20 inference(s) was 183.39 ms averaging 9.1695 ms per inference.
````

**Comment by AlexandreEichenberger** [comment]
@cjvolzka were you able to run the GPT2 benchmark with reasonable input size? I think one of the concern was that if we optimized zDLC to work well with practical sizes we see in our customer's application, it might not translate to the BS=1 and token=10 kind of inputs. If you did, please let us know of the sizes that you use so that we may better replicate the degradation.

Tx

**Comment by tungld** [comment]
This PR #2778 makes roberta-sequence-classification-9.onnx faster: per inference it is 4.6 ms vs 6.4 ms.

**Comment by cjvolzka** [comment]
Thanks for the fixes @tungld!
