### ISSUE TITLE
Poor NNPA performance on xlm-roberta-base-language-detection-onnx 

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#2813]
Running the [HuggingFace protectai/xlm-roberta-base-language-detection-onnx](https://huggingface.co/protectai/xlm-roberta-base-language-detection-onnx/tree/main) has lower than expected NNPA performance for large inputs.

Compiling [model.onnx](https://huggingface.co/protectai/xlm-roberta-base-language-detection-onnx/blob/main/model.onnx) with  `--O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z16 --maccel=NNPA model.onnx --onnx-op-stats TXT --profile-ir=ZHigh` yields:
```
Operations encountered:
-----------------------
   func.func               , 1
   func.return             , 1
   krnl.runtime_instrument , 2204
   onnx.Add                , 51
   onnx.Cast               , 3
   onnx.Concat             , 109
   onnx.Constant           , 71
   onnx.CumSum             , 1
   onnx.Dim                , 170
   onnx.Div                , 12
   onnx.Equal              , 2
   onnx.Erf                , 12
   onnx.Expand             , 1
   onnx.Gather             , 4
   onnx.LayerNormalization , 25
   onnx.MatMul             , 12
   onnx.Max                , 12
   onnx.Mul                , 26
   onnx.NoValue            , 1
   onnx.Not                , 1
   onnx.Reshape            , 108
   onnx.Slice              , 1
   onnx.Sub                , 1
   onnx.Transpose          , 48
   onnx.Unsqueeze          , 2
   onnx.Where              , 1
  zhigh.MatMul             , 86
  zhigh.Softmax            , 12
  zhigh.Stick              , 85
  zhigh.StickifiedConstant , 148
  zhigh.Tanh               , 1
  zhigh.Unstick            , 97
```

The performance issue primarily appears to be the 12 onnx.MatMul operators. On large inputs (first in
[Input Examples.txt](https://github.com/onnx/onnx-mlir/files/15203148/Input.Examples.txt)), this op dominates runtime. 

The operators are:
```
                      'MatMul': {'count': 12,
                                 'nodes': {'/roberta/encoder/layer.0/attention/self/MatMul_1': 0.064281,
                                           '/roberta/encoder/layer.1/attention/self/MatMul_1': 0.064978,
                                           '/roberta/encoder/layer.10/attention/self/MatMul_1': 0.064231,
                                           '/roberta/encoder/layer.11/attention/self/MatMul_1': 0.06428,
                                           '/roberta/encoder/layer.2/attention/self/MatMul_1': 0.064216,
                                           '/roberta/encoder/layer.3/attention/self/MatMul_1': 0.064294,
                                           '/roberta/encoder/layer.4/attention/self/MatMul_1': 0.06423,
                                           '/roberta/encoder/layer.5/attention/self/MatMul_1': 0.064491,
                                           '/roberta/encoder/layer.6/attention/self/MatMul_1': 0.064219,
                                           '/roberta/encoder/layer.7/attention/self/MatMul_1': 0.064205,
                                           '/roberta/encoder/layer.8/attention/self/MatMul_1': 0.064305,
                                           '/roberta/encoder/layer.9/attention/self/MatMul_1': 0.064271},
                                 'time': 0.7720009999999999},
```
It's not clear to me offhand why these stay on the CPU vs NNPA but it appears to the source of the performance difference.
![image](https://github.com/onnx/onnx-mlir/assets/42243335/ab0d69bb-863f-41ba-b938-da042d378f0b)

## Notes:
* [model_optimized.onnx](https://huggingface.co/protectai/xlm-roberta-base-language-detection-onnx/blob/main/model_optimized.onnx)  xlm-roberta-base-language-detection-onnx model does not compile.
    * The model shows as OpSet 11 but has [LayerNormalization](https://onnx.ai/onnx/operators/onnx__LayerNormalization.html) nodes which didn't exist until Opset 17. So I'm unsure if we can support this model.
* The raw operator breakdown text and charts for both the large and small examples are attached in 
[profile.zip](https://github.com/onnx/onnx-mlir/files/15203250/profile.zip)
* If the test input is small (second example input in Input Examples.txt) then the majority of the runtime is in the zhigh.MatMaul. 
* ![image](https://github.com/onnx/onnx-mlir/assets/42243335/addc2b0e-f4ef-46c4-ba87-a9bb7e6e469a)

**Comment by tungld** [comment]
@cjvolzka I created a PR #2818 to fix this issue. Now all MatMuls run on NNPA:

```shell
Onnx-mlir command: /workdir/onnx-mlir/build/Debug/bin/onnx-mlir -EmitLib -O3 -mcpu=z16 -maccel=NNPA ./xlm-roberta-base-language-detection.onnx -v -onnx-op-stats TXT --profile-ir=ZHigh
The ONNX model has 278059028 elements in its initializers. This value would be close to and greater than the number of parameters in the model. Because there is no way to exactly count the number of parameters, this value can be used to have a rough idea of the number of parameters in the model.
Operations encountered:
-----------------------
   func.func               , 1
   func.return             , 1
   krnl.runtime_instrument , 2508
   onnx.Add                , 51
   onnx.Cast               , 3
   onnx.Concat             , 145
   onnx.Constant           , 69
   onnx.CumSum             , 1
   onnx.Dim                , 218
   onnx.Div                , 12
   onnx.Equal              , 1
   onnx.Erf                , 12
   onnx.Expand             , 1
   onnx.Gather             , 4
   onnx.LayerNormalization , 25
   onnx.Max                , 12
   onnx.Mul                , 26
   onnx.NoValue            , 1
   onnx.Not                , 1
   onnx.Reshape            , 144
   onnx.Slice              , 1
   onnx.Sub                , 1
   onnx.Transpose          , 48
   onnx.Unsqueeze          , 2
  zhigh.MatMul             , 98
  zhigh.Softmax            , 12
  zhigh.Stick              , 109
  zhigh.StickifiedConstant , 148
  zhigh.Tanh               , 1
  zhigh.Unstick            , 109
```

**Comment by imaihal** [comment]
From my investigation of model.onnx, 12 onnx.Matmul run on CPU because dynamic dimension analysis doesn't work. When we set static dimension using `-shapeInformation` option, all MatMul ops run on NNPA.

**Comment by AlexandreEichenberger** [comment]
What Sequence length is typically used for this model?

**Comment by AlexandreEichenberger** [comment]
Assuming a BS of 8 and a sequence length of 384, and running on CPU only to see if all the ops that should get parallelized on CPU are parallelized, it seems pretty good.
```
Gather stats from 19 measurement sets with 3 warmup; keep inner 8 experiment(s)
Report using runtime file "bibir.log" and compile file "bibic.log"
Statistic legend:
  op-name: num, average time (ms), cumulative time (ms), percent of total 

Statistics start all ops ordered_by time, tot_time,  3043.2328750
  onnx.MatMul-par, 96, 28.5752591, 2743.2248750, 90.1%
  onnx.Softmax-par, 12, 7.2553229, 87.0638750, 2.9%
  onnx.Add-par, 110, 0.5842568, 64.2682500, 2.1%
  onnx.Mul-par, 25, 2.0086750, 50.2168750, 1.7%
  onnx.Erf-par, 12, 2.3502187, 28.2026250, 0.9%
  onnx.Transpose-par, 48, 0.2726094, 13.0852500, 0.4%
  onnx.Div-par, 12, 0.9926042, 11.9112500, 0.4%
  onnx.LayerNormalization-par, 25, 0.1966250, 4.9156250, 0.2%
  onnx.Gather-par, 3, 0.2788750, 0.8366250, 0.0%
  onnx.Gemm-par, 4, 0.1906875, 0.7627500, 0.0%
  onnx.Cast-par, 2, 0.0837500, 0.1675000, 0.0%
  onnx.Tanh-par, 1, 0.0730000, 0.0730000, 0.0%
  onnx.Constant, 219, 0.0001737, 0.0380417, 0.0%
  onnx.CumSum, 1, 0.0285000, 0.0285000, 0.0%
  onnx.Reshape, 48, 0.0002812, 0.0135000, 0.0%
  onnx.Add, 13, 0.0001635, 0.0021250, 0.0%
  onnx.Equal, 1, 0.0017500, 0.0017500, 0.0%
  onnx.Unsqueeze, 2, 0.0003750, 0.0007500, 0.0%
  onnx.Cast, 1, 0.0006250, 0.0006250, 0.0%
  onnx.Mul, 1, 0.0005000, 0.0005000, 0.0%
  onnx.Not, 1, 0.0005000, 0.0005000, 0.0%
  onnx.Sub, 1, 0.0001250, 0.0001250, 0.0%
Statistics end all ops ordered_by time, tot_time,  3043.2328750
```

Surprisingly, there are a few Adds/Mul that are not parallelized but they take very very little time, so I suspect there were disabled because of the size of the trip count.

**Comment by cjvolzka** [comment]
> What Sequence length is typically used for this model?

I'm unsure what's normal. The model takes an encoded input of words and returns the likelyhood the input language is one of 20. For my testing I was using a sequence size of 249 (encoded second paragraph of Les Miserables) for the large test and 7 (encoded a single sentence) for the small one.

**Comment by cjvolzka** [comment]
> From my investigation of model.onnx, 12 onnx.Matmul run on CPU because dynamic dimension analysis doesn't work. When we set static dimension using `-shapeInformation` option, all MatMul ops run on NNPA.

Thanks for the tip! I confirmed on my end with a static batch size of 1 that the Ops go to the NNPA.
