### ISSUE TITLE
version of third_party/onnx is changed?

### ISSUE THREAD

**Issue by chentong319** [onnx/onnx-mlir#282]
I got a build error for my PR#281. The reason is that check document found multiple different lines for ONNXOps.td.inc which are not my changes. I tracked down and found the HEAD os onnx version is changed, but there is no PR to update ONNXOps.td.inc.
If the change of onnx is intended, I will update ONNXOps.td.inc with a separate PR.
Anyway to  make the process, or at least a notification to users, automatic when a submodule has been changed? E.g. tell user to update llvm when llvm HEAD is moved.

**Comment by gongsu832** [comment]
I think @doru1004 already commented on the pull request https://github.com/onnx/onnx-mlir/pull/281#issuecomment-682633240. The submodule version didn't change. The changes were introduced by the patch you are trying to submit. If you look at your patch, it's actually changing the submodules benchmark, googletest, onnx, and pybind11.

**Comment by chentong319** [comment]
It is true that my PR accidentally changed the submodules.
