### ISSUE TITLE
Compilation failing for static quantized Resnet50 Model on NNPA

### ISSUE THREAD

**Issue by Sunny-Anand** [onnx/onnx-mlir#2885]
**Problem**

Trying to compile a static quantized version of the [resentv2_50_Opset18.onnx] (https://github.com/onnx/models/tree/main/Computer_Vision/resnetv2_50_Opset18_timm) model fails with the below error:

> zdlc: /dlc-automation/onnx-mlir/src/Conversion/ONNXToKrnl/Math/Elementwise.cpp:2154: onnx_mlir::ONNXElementwiseUnaryOpLowering<mlir::ONNXDequantizeLinearOp>::matchAndRewrite(mlir::ONNXDequantizeLinearOp, onnx_mlir::ONNXElementwiseUnaryOpLowering<mlir::ONNXDequantizeLinearOp>::OpAdaptor, mlir::ConversionPatternRewriter&) const::<lambda(onnx_mlir::KrnlBuilder&, mlir::ValueRange)>: Assertion `isScalarValue(operands[i]) && "unary expected scalar additional values"' failed.

**Reproduce**
Attached is the [Sample Program](https://github.com/user-attachments/files/16355904/Archive.zip) for generating the static quantized model. 
Running the main.py
`python main.py --input_model resnetv2_50_Opset18.onnx --output_model resnetv2_50_Opset18_quant_output.onnx  --calibration_dataset ./test_images --preprocessed-input-model resnetv2_50_Opset18_pre.onnx`

The program generates a static quantized model with the name `resnetv2_50_Opset18_quant_output.onnx`.

On trying to compile the static quantized model on NNPA with the flags `--O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z16 --maccel=NNPA` it fails with the above error.

**Comment by tungld** [comment]
@Sunny-Anand please check if this issue has been solved with the PR #2887. Thanks!

**Comment by Sunny-Anand** [comment]
@tungld I verified the issue is fixed. Thanks for the resolution.
