### ISSUE TITLE
Compile error with --mtriple=s390x-ibm-zos

### ISSUE THREAD

**Issue by mikeessen** [onnx/onnx-mlir#2889]
After commit https://github.com/onnx/onnx-mlir/commit/58572e00c3805a5c07918909264ea52c612a7448 compiling with `--mtriple=s390x-ibm-zos` results in a compile failure.

The commit sets the default of `src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp`  to `true`.

Here's the compile command options and error output:

`-EmitObj  -O3 --onnx-op-stats=TXT --mtriple=s390x-ibm-zos --mcpu=z16 --maccel=NNPA /models/mnist-12.onnx`

```
[1/5] Tue Jul 23 17:54:56 2024 Importing ONNX Model to MLIR Module
[2/5] Tue Jul 23 17:54:56 2024 Compiling and Optimizing MLIR Module
Operations encountered:
-----------------------
  func.func        , 1
  func.return       , 1
  onnx.Add        , 1
  onnx.Constant      , 2
  onnx.NoValue      , 1
  onnx.Reshape      , 1
 zhigh.Conv2D       , 2
 zhigh.MatMul       , 1
 zhigh.MaxPool2D     , 2
 zhigh.Stick       , 2
 zhigh.StickifiedConstant , 5
 zhigh.Unstick      , 2
[3/5] Tue Jul 23 17:54:56 2024 Translating MLIR Module to LLVM and Generating LLVM Optimized Bitcode
[4/5] Tue Jul 23 17:54:56 2024 Generating Object from LLVM Bitcode
<inline asm>:1:1: error: HLASM Label has to start with an alphabetic character or the underscore character
.insn vrr,0xe60000000075,0,0,1,0,2,0
^
<inline asm>:1:1: error: HLASM Label has to start with an alphabetic character or the underscore character
.insn vrr,0xe60000000075,1,1,2,0,2,0
^
```

Please set the default for  `enable-compiler-stick-unstick`  to false for zOS and then  re-enable to a default of true for once this issue is corrected.

**Comment by AlexandreEichenberger** [comment]
Once fixed, we should revert #2888

**Comment by AlexandreEichenberger** [comment]
@mikeessen any progress on this?

**Comment by mikeessen** [comment]
> @mikeessen any progress on this?

Yes, I have made progress, but not yet ready to commit.

**Comment by AlexandreEichenberger** [comment]
@mikeessen I think your PR went in to fix this. Please close if appropriate

**Comment by mikeessen** [comment]
Thanks for reminder @AlexandreEichenberger 

Fixed with https://github.com/onnx/onnx-mlir/pull/2974
