### ISSUE TITLE
krnl.shape is not totally lowered to std dialect

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#289]
`krnl.shape` returns `shape.shape` as its return type. However, `shape.shape` is not lowered to std dialect.

Example
```mlir
func @test_krnl_shape() -> !shape.shape {
  %0 = alloc() : memref<10x10xf32>
  %1 = "krnl.shape"(%0) : (memref<10x10xf32>) -> !shape.shape
  return %1: !shape.shape
}
```
Applying passes: `--lower-krnl-shape` and  `--disconnect-dims`, we got
```mlir
func @test_krnl_shape() -> !shape.shape {
    %0 = shape.const_shape [10, 10] : !shape.shape
    %1 = alloc() : memref<10x10xf32>
    return %0 : !shape.shape
  }
```

Then, applying pass `--convert-shape-to-std` to lower to std, we got:
```mlir
func @test_krnl_shape() -> !shape.shape {
    %0 = shape.const_shape [10, 10] : !shape.shape
    %1 = alloc() : memref<10x10xf32>
    return %0 : !shape.shape
  }
```
We still have `shape.shape` here.

The reason why `shape.shape` was not lowered to std is `--convert-shape-to-std` does not support `shape.const_shape` with type `shape.shape`: https://github.com/llvm/llvm-project/blob/master/mlir/lib/Conversion/ShapeToStandard/ShapeToStandard.cpp#L145

**Comment by tungld** [comment]
FYI @doru1004.

**Comment by doru1004** [comment]
Fixed by https://github.com/onnx/onnx-mlir/pull/368

**Comment by doru1004** [comment]
Please re-open if further issues related to this arise.
