### ISSUE TITLE
Handling segfaults during inferences

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#2899]
Right now, I believe we have not worked out specific error handling during inference when executing the compiled .so file.

The question is:
* can we catch the errors gracefully
* can we recover, for example the heap allocated memory

Possibly in a process that uses 
* multiple threads for inferences,
* its own error handling for its errors (unrelated to onnx-mlir based inferences)

Based on a discussion with @cjvolzka @mikeessen @Sunny-Anand

**Comment by AlexandreEichenberger** [comment]
@gongsu832 do you have suggestions with regards to catching errors during execution of a .so and recovering `malloced` memory>

**Comment by gongsu832** [comment]
.so is native code so when it segfaults the process gets a SIGSEGV signal. So you can install a signal handler to catch it. In the signal handler you can clean up resources that are not automatically released (e.g., removing temp files, etc.), then exit gracefully. But you have to be careful that the signal handler is a fairly restricted environment in the sense that you can only call async-signal-safe functions (https://man7.org/linux/man-pages/man7/signal-safety.7.html)

**Comment by AlexandreEichenberger** [comment]
My thoughts exactly. Do you know of a malloc that let you "free" all of the malloced data in bulk? Like all the malloc data is gotten from a pool and we then may free the pool?

**Comment by gongsu832** [comment]
There is no need to free memory in the signal handler. All memories allocated by the process get reclaimed by the OS when the process exits/dies. Same goes for open file descriptors, etc. Basically, all "transient" resources residing in memory are reclaimed by the OS. What the signal handler needs to clean up manually are the "persistent" resources residing in the file system like temp files, pipes, etc. And of course you may also want to flush buffers to disk, etc.

**Comment by AlexandreEichenberger** [comment]
Oh I see, I was probably not clear on @cjvolzka's request. He wants to be able to recover... aka do a normal "return null". So transform the crash into an orderly return with an error code.

**Comment by gongsu832** [comment]
Trying to "recover" then continue after a segfault is typically a bad idea, unless you know exactly what happened and can fix the potentially already corrupted memory (which is typically impossible). The purpose of the signal handler is for you to do some clean up and die more gracefully and also maybe to provide some debug info (like a backtrace of the call stack) in order to ultimately fix the bug, rather than try to recover and continue (again, only possible if you know exactly what happened).
