### ISSUE TITLE
Mismatched name in function and entry point crash the compiler

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#2901]
When compiling this
```mlir
module attributes {} {
  func.func @main_graph(%arg0 : tensor<?x?xf32>, %arg1 : tensor<f32>, %arg2 : tensor<ui8>) -> tensor<*xui8> {
    %1 = "onnx.QuantizeLinear"(%arg0, %arg1, %arg2) {} : (tensor<?x?xf32>, tensor<f32>, tensor<ui8>) -> tensor<*xui8>
      return %1: tensor<*xui8>
  }
  "onnx.EntryPoint"() {func = @main_graph_different} : () -> ()
}
```
the program crashes because the `func.func` and `EntryPoint` do not use the same name.

This should not occur.

**Comment by AlexandreEichenberger** [comment]
@Sunny-Anand example of segfault.

**Comment by chentong319** [comment]
To my understanding, the two name should be the same.  I assume that the inconsistence is introduced by editing the .mlir file manually. We can add a check at compile time or runtime to handle the case.

**Comment by AlexandreEichenberger** [comment]
> We can add a check at compile time or runtime to handle the case.

yes, it should not crash the compiler.

**Comment by chentong319** [comment]
PR #2902 is created to fix this issue.
