### ISSUE TITLE
Is --EmitNativeLLVM possible?

### ISSUE THREAD

**Issue by jinchenglee** [onnx/onnx-mlir#2903]
Hi, I'm new to LLVM/MLIR, this might be a dumb question. 

I checked the onnx-mlir --help for emit options:

...
onnx-mlir options:
These are onnx-mlir frontend options

  Choose target to emit:
      --EmitONNXBasic                                                                  - Ingest ONNX and emit the basic ONNX operations without inferred shapes.
      --EmitONNXIR                                                                     - Ingest ONNX and emit corresponding ONNX dialect.
      --EmitMLIR                                                                       - Lower the input to MLIR built-in transformation dialect.
      --EmitLLVMIR                                                                     - Lower the input to LLVM IR (LLVM MLIR dialect).
...

When I employ the "--EmitLLVMIR", what I got, I believe, is the MLIR LLVM IR (aka the LLVM MLIR Dialect) not the native LLVM IR itself. Is it possible to get the native LLVM IR representation of the generated code, or it is not possible because there's no way from MLIR LLVM to native LLVM at all? Thanks.

**Comment by AlexandreEichenberger** [comment]
The emit options typically generate mlir files at various stages. However, you can experiment with compiling to a library (`-EmitLib`, but other target might work too) and asking the compiler to preserve files (`-preserveLLVMIR`, there are other "preserve" options too).

When I do so on a small example:
```
> onnx-mlir -preserveLLVMIR add.mlir   
[...]
> ls
add.ll          add.mlir        add.so
```
I believe the `.ll` might be the file you are looking into.

Check this out (and/or other similar options). If you eventually need support in an established pipeline, we can potentially add a new target for this.

**Comment by jinchenglee** [comment]
Thank you for quick response. Confirmed ```--preserveLLVMIR``` works.
