### ISSUE TITLE
lowering kernel dialect

### ISSUE THREAD

**Issue by ArunaKote** [onnx/onnx-mlir#291]
I got these while converting onnx to MLIR using -EmitMLIR.
1. "krnl.packed_const"() {file_name = "/tmp/packed_const-b91861.tmp", is_le = true, size_in_bytes = 0 : i64} : () -> i64
2."krnl.global"() 
3."krnl.getref"
These are not lowered to affine dialect while doing ----convert-krnl-to-affine.

How can I lower these ?

and where can I get list of all kernel dialect operations.

Thank You

**Comment by tungld** [comment]
Hi @ArunaKote 

Thanks for using onnx-mlir!

> 1. "krnl.packed_const"() {file_name = "/tmp/packed_const-b91861.tmp", is_le = true, size_in_bytes = 0 : i64} : () -> i64
> 2."krnl.global"()
> 3."krnl.getref"

For these ops, you can lower them using `convert-krnl-to-llvm`: https://github.com/onnx/onnx-mlir/blob/master/src/InitOMPasses.hpp#L68

For the list of all kernel dialect operations, please find them here: https://github.com/onnx/onnx-mlir/blob/master/src/Dialect/Krnl/KrnlOps.td

You can use --EmitLLVMIR to directly generate an LLVM code.

**Comment by ArunaKote** [comment]
If I use --EmitLLVMIR  I am getting this error:
static mlir::MemRefDescriptor mlir::MemRefDescriptor::fromStaticShape(mlir::OpBuilder&, mlir::Location, mlir::LLVMTypeConverter&, mlir::MemRefType, mlir::Value): Assertion `type.hasStaticShape() && "unexpected dynamic shape"' failed.

**Comment by ArunaKote** [comment]
If I use --EmitLLVMIR  I am getting this error:
static mlir::MemRefDescriptor mlir::MemRefDescriptor::fromStaticShape(mlir::OpBuilder&, mlir::Location, mlir::LLVMTypeConverter&, mlir::MemRefType, mlir::Value): Assertion `type.hasStaticShape() && "unexpected dynamic shape"' failed.

**Comment by ArunaKote** [comment]
If I use --EmitLLVMIR I am getting this error:
static mlir::MemRefDescriptor mlir::MemRefDescriptor::fromStaticShape(mlir::OpBuilder&, mlir::Location, mlir::LLVMTypeConverter&, mlir::MemRefType, mlir::Value): Assertion `type.hasStaticShape() && "unexpected dynamic shape"' failed.

**Comment by AlexandreEichenberger** [comment]
I suspect that your model has some dynamic dimensions. Can you check if the model goes through if you fix these dynamic dimensions to some static values? In general, the support for dynamic still need some work.

**Comment by ArunaKote** [comment]
I changed dynamic dimensions to static value.I able to get LLVM dialect --EmitLLVMIR.But when I give this file mlir-translate --mlir-to-llvmir Iam getting error like this:
error: custom op 'llvm.insertvalue' expected wrapped LLVM IR structure/array type
    %7 = llvm.insertvalue %6, %4[0 : i32] : !llvm.ptr<struct<(ptr<float>, ptr<float>, i64, array<2 x i64>, array<2 x i64>)>>

**Comment by tungld** [comment]
This would be a bug since the input for `insertvalue` cannot be a pointer but a struct or array. Could you please provide the input ONNX model that can reproduce this bug, so that we can identify the root cause? Thanks!

**Comment by ArunaKote** [comment]
This is the ONNXIR:
module {
  func @main_graph(%arg0: tensor<1x4xf32>) -> tensor<1x3xf32> attributes {input_names = ["input_2:0"], output_names = ["Identity:0"]} {
    %0 = "onnx.Constant"() {value = dense<[[-0.271809936, -0.12023776, 0.626025676, 0.376105517, 0.150733903], [-1.03279042, -0.675471127, 1.03124714, 1.92241752, 1.55713868], [0.78930509, 0.564916134, -1.47284496, -1.25398922, -2.13731647], [1.786150e+00, 1.6114707, -1.183676, -2.218970e+00, -1.69933403]]> : tensor<4x5xf32>} : () -> tensor<4x5xf32>
    %1 = "onnx.Constant"() {value = dense<[-1.35482359, -1.21271384, 1.29136693, 1.65940213, 0.99189496]> : tensor<5xf32>} : () -> tensor<5xf32>
    %2 = "onnx.Gemm"(%arg0, %0, %1) {alpha = 1.000000e+00 : f32, beta = 1.000000e+00 : f32, transA = 0 : i64, transB = 0 : i64} : (tensor<1x4xf32>, tensor<4x5xf32>, tensor<5xf32>) -> tensor<1x5xf32>
    %3 = "onnx.Sigmoid"(%2) {onnx_node_name = "StatefulPartitionedCall/sequential_1/dense_2/Sigmoid"} : (tensor<1x5xf32>) -> tensor<1x5xf32>
    %4 = "onnx.Constant"() {value = dense<[[-0.831427872, -0.0463701598, 1.69659245], [-2.43958282, -0.424170524, 1.4939487], [2.18066692, -0.175995603, -3.51097035], [-0.238860011, 1.63030732, -3.30913615], [2.34820676, -3.1109345, -1.30347252]]> : tensor<5x3xf32>} : () -> tensor<5x3xf32>
    %5 = "onnx.Constant"() {value = dense<[-1.46578705, 0.194344237, 0.790954172]> : tensor<3xf32>} : () -> tensor<3xf32>
    %6 = "onnx.Gemm"(%3, %4, %5) {alpha = 1.000000e+00 : f32, beta = 1.000000e+00 : f32, transA = 0 : i64, transB = 0 : i64} : (tensor<1x5xf32>, tensor<5x3xf32>, tensor<3xf32>) -> tensor<1x3xf32>
    return %6 : tensor<1x3xf32>
  }
  "onnx.EntryPoint"() {func = @main_graph, numInputs = 1 : i32, numOutputs = 1 : i32} : () -> ()
}

**Comment by tungld** [comment]
Thanks @ArunaKote for the code! I fixed this issue by the linked pull request #293 . Could you please check again with the pull request?

**Comment by ArunaKote** [comment]
OK.

Thank You

**Comment by AlexandreEichenberger** [comment]
I approved the change, Please ping us if it did not work for you. Thanks @tungld for the fix.
