### ISSUE TITLE
yolov3-10 and yolov3-12 models from the modelzoo run into segmentation fault when used for inference.

### ISSUE THREAD

**Issue by Sunny-Anand** [onnx/onnx-mlir#2973]
## Models with a Segmentation fault.

[yolov3-10](https://github.com/onnx/models/blob/main/validated/vision/object_detection_segmentation/yolov3/model/yolov3-10.onnx) and [yolov3-12](https://github.com/onnx/models/blob/main/validated/vision/object_detection_segmentation/yolov3/model/yolov3-12.onnx)
[Tests.zip](https://github.com/user-attachments/files/17346677/Archive.3.zip)

## Steps to reproduce on the community docker image

1. Pull in the latest community onnx-mlir-dev image ` docker pull onnxmlir/onnx-mlir-dev:390x`
2. Run the podman command to enter the community docker image, note while doing this mount the model folder which contains the above listed models and .test files. This also mounts the DLC modelzoo clients. 
```podman run --rm --entrypoint bash -v /devfield/sunny/models:/data:Z -v /devfield/sunny/zdlc-main/dlc-automation/:/code/:Z  -it --name onnx-mlir-sunny-y3-10  onnx-mlir-dev:sunny-yolov3```
3. The model.so file is generated in the /data folder where also the model and .tests files are present. Please ensure the full model file is imported, not the git lfs file pointer.
```
root@0b9851e27fe3:/workdir# ./onnx-mlir/build/Debug/bin/onnx-mlir --O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z16 --maccel=NNPA  /data/yolov3-10.onnx --onnx-op-stats TXT
```

```
[1/6] Fri Oct 11 16:46:51 2024 (0s) Importing ONNX Model to MLIR Module from "yolov3-10.onnx"
[2/6] Fri Oct 11 16:46:53 2024 (2s) Compiling and Optimizing MLIR Module
Operations encountered:
-----------------------
   func.func               , 1
   func.return             , 1
   onnx.Add                , 18
   onnx.Cast               , 51
   onnx.Ceil               , 7
   onnx.Concat             , 26
   onnx.Constant           , 179
   onnx.Conv               , 75
   onnx.Dim                , 9
   onnx.Div                , 9
   onnx.Exp                , 3
   onnx.LeakyRelu          , 72
   onnx.Loop               , 6
   onnx.Mul                , 17
   onnx.NoValue            , 1
   onnx.NonMaxSuppression  , 1
   onnx.ReduceMinV13       , 1
   onnx.Reshape            , 15
   onnx.Resize             , 2
   onnx.Sigmoid            , 9
   onnx.Slice              , 46
   onnx.Squeeze            , 7
   onnx.Sub                , 6
   onnx.Tile               , 6
   onnx.Transpose          , 4
   onnx.Unsqueeze          , 2
   onnx.Yield              , 6
  zhigh.Add                , 22
  zhigh.Div                , 4
  zhigh.Stick              , 29
  zhigh.StickifiedConstant , 1
  zhigh.Sub                , 1
  zhigh.Unstick            , 21
[3/6] Fri Oct 11 16:47:16 2024 (25s) Translating MLIR Module to LLVM and Generating LLVM Optimized Bitcode
[4/6] Fri Oct 11 16:47:44 2024 (53s) Generating Object from LLVM Bitcode
[5/6] Fri Oct 11 16:47:51 2024 (60s) Linking and Generating the Output Shared Library
[6/6] Fri Oct 11 16:47:52 2024 (61s) Compilation completed
-----------------------------

```

4. Execute the inference using the below command where the `code/client/bin/modelzoo is a DLC client.
 ```
root@0b9851e27fe3:/workdir# /code/client/bin/modelzoo --iterations 1 --validate --msg-level INFO --file /data/yolov3-10.tests --lib /data/yolov3-10.so --fc-parms 0.01,10.830992,5,10
Iteration 0 dataset 0: Running
Segmentation fault (core dumped)
```

**Comment by AlexandreEichenberger** [comment]
I assume that this is when using `-maccel=NNPA`.

**Comment by Sunny-Anand** [comment]
@AlexandreEichenberger yes `-maccel=NNPA` and `-mcpu=z16`

**Comment by AlexandreEichenberger** [comment]
Currently fails with the conjunction of dynamic shapes and `enable-compiler-stick-unstick`. So looking for that root cause now.

**Comment by AlexandreEichenberger** [comment]
@Sunny-Anand can you confirm if the PRs pushed to address this issue fixed the problem? Tx

**Comment by Sunny-Anand** [comment]
@AlexandreEichenberger The issue was fixed by the prs https://github.com/onnx/onnx-mlir/pull/2980 https://github.com/onnx/onnx-mlir/pull/2981. Thank you
