### ISSUE TITLE
In the conversion of onnx Stablehlo, why is there no xor, sign?

### ISSUE THREAD

**Issue by heshuju** [onnx/onnx-mlir#2986]
I‘m using some op in onnx-mlir. But I found onnx's op xor, sign can't convert to stablehlo.
I know how to add this conversion, but I don't understand why there is no such conversion. Is it because these two operators are not common?
https://github.com/onnx/onnx-mlir/blob/main/src/Conversion/ONNXToStablehlo/Math/Elementwise.cpp

**Comment by AlexandreEichenberger** [comment]
While I cannot speak for the StableHLO folks, they probably add operators as they need them for models.
I am sure your contribution would be highly appreciated .

@srcarroll you have been active with the HLO part lately, any recommendations?

**Comment by srcarroll** [comment]
As @AlexandreEichenberger  said, I think it's just one of those "add as needed" kind of things.  Likely no one using onnx-mlir has come across these ops yet (I personally haven't), or someone has and just hacked their own solution without sharing. 
 It's just still a work in progress, right? For example, I recently came across a `onnx.Sum` that didn't lower, which seems like a common enough op to have already been handled but wasn't. So I'm not surprised these less common ops aren't handled yet. Both of these ops have stablehlo counterparts, so adding these conversions would be easy and a welcome change.

**Comment by AlexandreEichenberger** [comment]
Thanks @srcarroll for your input. So I believe this is an invitation to contribute, @heshuju :-) 

Let me know if you have issues building and contributing. Once you have a PR, someone on our team will have to manually request for some of the CI to run, but that is an easy thing to do. Please feel free to request with an @AlexandreEichenberger  that I run the CIs for you.

**Comment by srcarroll** [comment]
One more note. A lot of missing lowerings to upstream MLIR are handled in `convert-onnx-to-krnl`, which I've never really used but I believe this is for handling in onnx runtime. There are conversions for both of these in there. So I guess people have come across these, but only those interested in using the onnxruntime path. @AlexandreEichenberger correct me if i'm wrong anywhere there.

**Comment by AlexandreEichenberger** [comment]
Not quite, we/IBM use extensively the ONNX to LLVM entirely within the onnx-mlir compiler. It gives you a `.so` that you can use with a C, C++, Java, or Ptyhon interface to execute an inference. Specifically, we use ONNX -> Krnl (our own loop dialect) -> Affine / SCF / Vector / Math ... -> LLVM dialect within onnx-mlir, and then use the LLVM tool chain (`llc`, `opt`...) to generate an object file with entry points (function calls) to invoke an inference. You can look at the `-EmitXXX` targets listed with `onnx-mlir -h` output.

The StableHLO path (which I have no direct experience with), goes ONNX->StableHLO within onnx-mlir compiler, and then let you "jump" to a purely "MLIR" lowering path, which is useful for companies that have already invested in a StableHLO to  IREE or other targets within an existing MLIR-based driver. @srcarroll feel free to correct me on the preferred usage of that StableHLO path.

**Comment by srcarroll** [comment]
Thanks for clarifying!

> and then let you "jump" to a purely "MLIR" lowering path
yah this is the only reason i use the stablehlo path. I just want to get onnx to pure MLIR as sanely as possible and this path is the best i've seen so far without introducing other projects into the stack. I actually have no investment in StableHLO or IREE, other than needing the former as a stepping stone. I'm aware that there's also an onnx to TOSA pass and TOSA is pure MLIR, but I've been hesitant to explore this path because stablehlo has been functional enough and I dont really have that much time.  What I would really like is a straight onnx to linalg pass. Not sure if this is feasible for all onnx ops but there are plenty that have simple conversions.

**Comment by heshuju** [comment]
I understand, thank you for this information.
