### ISSUE TITLE
Docker container compilation warning "cannot find -lcruntime"

### ISSUE THREAD

**Issue by hugulas** [onnx/onnx-mlir#300]
I started latest onnxmlir container in interactive mode with following command.

`docker run -ti -v /mnt/backup/models:/models --entrypoint=bash onnxmlirczar/onnx-mlir-build`

I scanned the onnx model zoo.

I got following warning messages.

`
/build/onnx-mlir/build/bin/onnx-mlir models/vision/classification/shufflenet/model/shufflenet-7.onn
/usr/bin/ld: cannot find -lcruntime
collect2: error: ld returned 1 exit status
Shared library /models/vision/classification/shufflenet/model/shufflenet-7.so has been compiled.
`

But if I use onnx-mlir built on s390 in native mode(not container), there is no "cannot find -lcruntime" error.

**Comment by hugulas** [comment]
If "/build/onnx-mlir/build/lib" is included in PATH  env of docker container, this problem will be resolved.

`export PATH=$PATH:/build/onnx-mlir/build/bin/:/build/onnx-mlir/build/lib`

**Comment by hugulas** [comment]
@tjingrant @caoimhinuibrian 

Is it possible add "export PATH=$PATH:/build/onnx-mlir/build/bin/:/build/onnx-mlir/build/lib" to docker files?

**Comment by caoimhinuibrian** [comment]
@hugulas Glad to see you found the problem. You can create a new docker image to change the PATH. a Dockerfile containing this:

FROM onnxmlirczar/onnx-mlir-build:x86

WORKDIR /build
ENV PATH=$PATH:/build/onnx-mlir/build/bin/:/build/onnx-mlir/build/lib

should do the trick. Just put that in an empty directory, cd to that and run:
docker build --tag yourTagName .

Then 
docker run -ti -v /mnt/backup/models:/models --entrypoint=bash yourTagName

**Comment by caoimhinuibrian** [comment]
Of course, you may want to put a lot more stuff in the Dockerfile, if you are planning to do development there. This is what my current Dockerfile looks like:
FROM onnxmlirczar/onnx-mlir-build:x86

# set the version of python
WORKDIR /build
ENV HOME=/build
ENV PYENV_ROOT=$HOME/.pyenv
ENV PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
RUN pyenv global 3.7.0
RUN pyenv rehash

# install needed packages
ENV PATH=$PATH:/build/bin
RUN apt-get update
RUN apt-get install -y python-numpy
RUN apt-get install -y python3-pip
RUN pip install --upgrade pip
RUN apt-get install -y gdb
RUN apt-get install -y lldb
RUN apt-get install -y emacs
RUN apt-get install -y libeigen3-dev
RUN pip install wheel
RUN pip install numpy
RUN pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
RUN git clone https://github.com/onnx/tutorials.git

# install the onnx we have in the build tree as a python package
#  -- needed to rebuild the ONNX dialect (use "make OMONNXOpsIncTranslation" in the onnx-mlir/build directory)
RUN pip install -e /build/onnx-mlir/third_party/onnx

# set env variables for make - these should be set in any shell that is started
ENV LLVM_PROJ_SRC=/build/llvm-project
ENV LLVM_PROJ_BUILD=/build/llvm-project/build

WORKDIR /build/onnx-mlir/build
#RUN make OMONNXOpsIncTranslation

# copy in vscode configuration info
WORKDIR /build/.vscode
ADD .vscode /build/.vscode
WORKDIR /build/.vscode-server
ADD .vscode-server /build/.vscode-server

# copy workspace folder (typically contains local/personal testcases etc)
WORKDIR /build/workspace
ADD workspace /build/workspace

# copy onnxruntime folder
WORKDIR /build/onnxruntime
ADD onnxruntime-linux-x64-1.4.0 /build/onnxruntime

# do stuff to fix git
WORKDIR /build/onnx-mlir
# reattach HEAD
RUN git checkout master
# make git see branches other than master
RUN git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
# pull in stuff from remote (like branches etc)
#RUN git submodule update --force --recursive --init --remote
RUN git fetch

WORKDIR /build

**Comment by gongsu832** [comment]
@hugulas `onnxmlirczar/onnx-mlir-build` is the wrong image. It was built 3 months ago. You are probably looking for `onnxmlirczar/onnx-mlir-build:x86`.
@caoimhinuibrian @tjingrant We need to clean up that `onnxmlirczar/onnx-mlir-build` image.

**Comment by hugulas** [comment]
@gongsu832 The suggestion works for me. I tried it on both s390 and x86.

root@05c86a733ad9:~# /build/onnx-mlir/build/bin/onnx-mlir /external/models/vision/classification/shufflenet/model/shufflenet-9.onnx
Shared library /external/models/vision/classification/shufflenet/model/shufflenet-9.so has been compiled.
