### ISSUE TITLE
The constant tensor is too large to be displayed in the mlir file. Is there any way to hide it? 

### ISSUE THREAD

**Issue by heshuju** [onnx/onnx-mlir#3001]
when constant tensor display in onnx mlir, it like this:
` %1 = onnx.Constant dense<[0.0221926179, 0.00564369094, 1.91152096E-4, -0.00446738815, -0.0362969041, 0.0318313651, 1.742120e-02, 0.0257105045, 0.0227131806, 0.011501695, 0.0309505314, 0.00954645406, -0.00425875699, 0.0359960757, -0.0334640704, 0.0346018374, 0.00598553848, 0.00192668044, 0.0132429702, 0.023419559, -0.0106620593, 0.0323680751, 0.0149645414, -4.154160e-02, -0.0127266347, -1.53154135E-4, -0.0244611166, -0.037651103, 0.018814113, -0.0252404809, 3.521700e-02, 0.0277824216, 0.0373903736, 0.0123981638, -0.0368827209, 0.0267461054, 0.0200817641, -0.00267487275, -0.0188788287, -0.00213495409, -0.00205782056, 0.0395172052, -0.0271563679, -0.0068331114, 0.0205806755, -0.0155680086, -0.0217741579, -0.0228119902, -0.020911172, -0.0249242391, -0.0172836035, -0.0242176261, 0.0346462876, 0.0277757049, -8.37683677E-4, -0.0213530026, -0.0225045681, 0.0193370786, 0.00669321418, -0.0123270703, 0.00923944544, 0.00111972296, -0.00427081715, -0.0186101012]> : tensor<64xf32>`
I hope something like 
`%1 = onnx.ConstantTensorHandle %val : tensor<64xf32>` 
this %val hold the data.

Is there any way to achieve it?

**Comment by tungld** [comment]
You can use this flag `--mlir-elide-elementsattrs-if-larger=N`, e.g. `onnx-mlir-opt --mlir-elide-elementsattrs-if-larger=10 file.mlir` to elide large constants (more than 10 elements in this example)
