### ISSUE TITLE
which llvm commit should be used now

### ISSUE THREAD

**Issue by daquexian** [onnx/onnx-mlir#304]
Thanks for your amazing work!

When I try to build onnx-mlir, I found the llvm version in docker onnxmlirczar/onnx-mlir-build:x86 is 0dc91bfd11e, and the version provided in readme is 1d01fc100bb5bef5f5eaf92520b2e52f64ee1d6e. However, neither these two versions fit the master onnx-mlir.

Maybe the readme and the docker should be updated?

**Comment by caoimhinuibrian** [comment]
@daquexian Thanks for your interest! Not sure what you are asking ... The current llvm version in utilities/clone-mlir is 1d01fc...d6e and thats also what the readme says (actually, these are forced to stay the same by doc check). I grabbed the latest onnxmlirczar/onnx-mlir-build:x86 (5 days old) and looked at the commit for llvm in it. It is also 1d01fc...d6e, so maybe you looked in the wrong place? I also don't know what you mean by "neither these two versions fit the master onnx-mlir"

**Comment by NathanielMcVicar** [comment]
On a related note, our team is maintaining a version building against the latest upstream LLVM locally. I don't know how many others are doing this, but it seems like a waste of effort if we aren't the only ones and also if this doesn't get leveraged when it is time to update ONNX MLIR. Is there, or should there be, somewhere to coordinate this? Maybe @tjingrant has ideas.

**Comment by daquexian** [comment]
@caoimhinuibrian @NathanielMcVicar Thanks for your reply! It's my fault. I used onnxmlirczar/onnx-mlir-build:latest but not onnxmlirczar/onnx-mlir-build:x86 yesterday. What's more I didn't pull the latest onnx-mlir source code so a old version of onnx-mlir code is used. After pulling the latest code I compiled onnx-mlir successfully.

**Comment by caoimhinuibrian** [comment]
@NathanielMcVicar @tjingrant The TravisCI build currently builds both with the preferred version of LLVM and also with the latest upstream version, so it's possible to see whether moving up to the latest version is feasible.

**Comment by NathanielMcVicar** [comment]
@caoimhinuibrian I see now! I didn't realize it was set up like that, but very cool. I guess the question is if we pushed our updated fork somewhere public and maintained would that be valuable to the project when it's time to update the preferred version (to reduce duplicated effort), or is it more trouble than it's worth? I understand we can't easily create the PR itself because of the docker setup. Thanks!

**Comment by caoimhinuibrian** [comment]
@NathanielMcVicar Sure, it doesn't hurt to make your fork visible. I think that many changes to LLVM won't cause onnx-mlir to break, so moving up is trivial in that case. Where changes to LLVM break us, someone needs to submit a PR to upgrade and with the fixes to the places that are broken by whatever API changes have occurred. Right now the onus is on the person who wants to move up to submit that PR. If you have a fork that has already got those fixes, it would be cool if you submitted them.

It would be good to have some fairly lightweight or automatic process for upgrading to later versions whenever there is no breakage, as that would allow people to make use of enhancements in MLIR more easily.

**Comment by caoimhinuibrian** [comment]
Re opening this to continue this discussion.

**Comment by NathanielMcVicar** [comment]
My understanding is that the difficulty is in updating the docker images since they are hosted on docker hub and not easy to update for folks outside of IBM. Is that not an issue? Either way, I'm happy to create a PR for comment and we can go forward from there.

**Comment by NathanielMcVicar** [comment]
Fixed in #309, for now
