### ISSUE TITLE
llvm-project

### ISSUE THREAD

**Issue by dushyanth-m** [onnx/onnx-mlir#315]
while converting .mlir file to .ll using llvm-project getting error as below the command used to convert is mlir-translate -mlir-to-llvmir m1.mlir >m4.ll

m1.mlir:5:11: error: custom op 'constant' is unknown
    %c0 = constant 0 : index

**Comment by tjingrant** [comment]
Not familiar with mlir-translate, but if you are looking for LLVM dialect representation of onnx model, simply run `onnx-mlir -EmitLLVMIR [your-model.onnx]`.

**Comment by doru1004** [comment]
@dushyanth-m did Tian's comment solve your problem?
