### ISSUE TITLE
Error in lowering ONNXIR

### ISSUE THREAD

**Issue by ArunaKote** [onnx/onnx-mlir#320]
the part of code giving error is:
%cst = constant unit
    %0 = "onnx.Reshape"(%arg0, %cst) {onnx_node_name = "StatefulPartitionedCall/sequential_1/flatten_1/Reshape", shape = dense<[-1, 784]> : tensor<2xi64>} : (tensor<1x28x28xf32>, none) -> tensor<1x784xf32>

In this I lowered this to affine and when I try to lower to LLVM dialect I am getting error as:
 error: failed to legalize operation 'std.constant'
    %cst = constant unit
or if I directly lower the onnx to LLVM  and try to run llvm I am getting error as undefined reference to `getEmbeddedConstPool'
How can I resolve this Constant issue?

Thank You

**Comment by tungld** [comment]
Could you try to call `canonicalize` pass before lowering to LLVM, e.g. `onnx-mlir-opt --canonicalize your_program.mlir`? This will eliminate `constant unit` if it is not used.

**Comment by ArunaKote** [comment]
Thank you. It Worked for me.

**Comment by doru1004** [comment]
@ArunaKote did this solve your problem?

**Comment by ArunaKote** [comment]
Yes.


Thank You

**Comment by doru1004** [comment]
Awesome, I'll close this issue then.
