### ISSUE TITLE
errors compiling LLVM IR output

### ISSUE THREAD

**Issue by SerenaC94** [onnx/onnx-mlir#324]
Hi,
I successfully lowered the MNIST model from ONNX model zoo into a model.ll file.
However, there seem to be some issues in the output since clang is not able to compile the output LLVM IR.

clang9 output:
```
/onnx-mlir$ clang model.ll 
model.ll:42:73: error: expected ')' at end of argument list
define { float*, float*, i64, [4 x i64], [4 x i64] } @main_graph(float* %0, float* %1, i64 %2, i64 %3, i64 %4, i64 %5, i64 %6, i64 %7, i64 %8, i64 %9, i64 %10) !dbg !3 {
                                                                        ^
```

clang4 output:
```
model.ll:38:114: error: expected ')' at end of argument list
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* noalias nocapture writeonly, i8* noalias nocapture readonly, i64, i1 immarg) #0
                                                                                                                 ^
1 error generated.
```

**Comment by agostini01** [comment]
Hey @SerenaC94 , I got the same error using clang-8.
But I am able to compile the LLVM IR of (much simpler) onnx models, and avoid the error by using clang-10.

I think updating the clang version will solve this problem.

Would you mind sharing a link to your model?

**Comment by doru1004** [comment]
@agostini01 thanks for answering this. @SerenaC94 did this solve your problem?

**Comment by SerenaC94** [comment]
Yes, thank you! @agostini01 and I talked somewhere else so I forgot to close the issue.

**Comment by doru1004** [comment]
Thanks a lot for the update. Happy to hear the issue was resolved.
