### ISSUE TITLE
Build onnx-mlir error: MLIRMlirOptMain NOTFOUND

### ISSUE THREAD

**Issue by jacky82226** [onnx/onnx-mlir#33]
I bumped into an error while running for build onnx-mlir:
`export LLVM_PROJ_SRC=/mypath/llvm-project/`
`export LLVM_PROJ_BUILD=/mypath/llvm-project/build`
`mkdir onnx-mlir/build && cd onnx-mlir/build`
`cmake ..`

The error is:
> -- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MLIRMlirOptMain
    linked by target "compiler" in directory /mypath/onnx-mlir/src
    linked by target "compiler" in directory /mypath/onnx-mlir/src
    linked by target "onnf_onnx_decompose" in directory /mypath/onnx-mlir/src
    linked by target "onnf_onnx_decompose" in directory /mypath/onnx-mlir/src
    linked by target "onnf_shape_inference" in directory /mypath/onnx-mlir/src
    linked by target "onnf_shape_inference" in directory /mypath/onnx-mlir/src
    linked by target "onnf_lower_frontend" in directory /mypath/onnx-mlir/src
    linked by target "onnf_lower_frontend" in directory /mypath/onnx-mlir/src
    linked by target "onnf" in directory /mypath/onnx-mlir/src
    linked by target "onnf" in directory /mypath/onnx-mlir/src
    linked by target "onnf_transform" in directory /mypath/onnx-mlir/src/transform
    linked by target "onnf_transform" in directory /mypath/onnx-mlir/src/transform
    linked by target "onnf-opt" in directory /mypath/onnx-mlir/src/tool/onnf_opt
    linked by target "onnf-opt" in directory /mypath/onnx-mlir/src/tool/onnf_opt
    linked by target "builder" in directory /mypath/onnx-mlir/src/builder
    linked by target "builder" in directory /mypath/onnx-mlir/src/builder
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

I have already built llvm successfully and installed gcc, cmake and libprotoc with ZLib. 
Why I encountered this error? Did I forget to install or export something? 

Thanks!

**Comment by tjingrant** [comment]
It sounds like you are using an older version of MLIR.
Can you try cloning it from https://github.com/clang-ykt/llvm-project?

**Comment by jacky82226** [comment]
> It sounds like you are using an older version of MLIR.
> Can you try cloning it from https://github.com/clang-ykt/llvm-project?

I was using the latest version of llvm-project.
Besides, I just tried to rebuild llvm-project with https://github.com/clang-ykt/llvm-project.
Unforunately, I still encountered the same error: MLIRMlirOptMain NOTFOUND.
Maybe it is because I built it in Windows?

**Comment by tjingrant** [comment]
Hi @jacky82226 MLIR is being actively developed (and thus modified in non-backward-compatible ways), so using the latest version of llvm-project may actually bring more harm than good. 

Let's check if you have MLIRMlirOptMain, can you visit llvm-project/build/lib and do the Windows equivalent of:
```
ls | grep MLIRMlirOptMain.a
```

You should find `MLIRMlirOptMain.a` there. If not, you didn't install our supported version lf llvm-project (from clang-ykt) right.

**Comment by jacky82226** [comment]
> Hi @jacky82226 MLIR is being actively developed (and thus modified in non-backward-compatible ways), so using the latest version of llvm-project may actually bring more harm than good.
> Let's check if you have MLIRMlirOptMain, can you visit llvm-project/build/lib and do the Windows equivalent of:
> ls | grep MLIRMlirOptMain.a
> 
> You should find MLIRMlirOptMain.a there. If not, you didn't install our supported version lf llvm-project (from clang-ykt) right.

Thank you for the instruction! I agree it is because I have not installed onnx-mlir successfully. 
Therefore, I tried to reinstall onnx-mlir several times, but I still cannot find MLIRMlirOptMain.a in my llvm-project/build/lib
It did not pop out any error message while building onnx-mlir in Windows and it only encountered a failure while testing. 
I am thinking maybe I need to try other cmake building parameters in Windows or I have to install something additionally. 
P.S. My ls under llvm-project/build/lib is as below: 

![image](https://user-images.githubusercontent.com/14194980/77208897-1b239700-6aba-11ea-9fea-f4b6e280b4cc.png)

**Comment by tjingrant** [comment]
@jacky82226 thanks for the screenshot, it looks like there's indeed no MLIRMlirOptMain.a in your build directory. If it helps, here's a link to where this library is defined: https://github.com/clang-ykt/llvm-project/blob/076475713c236081a3247a53e9dbab9043c3eac2/mlir/tools/mlir-opt/CMakeLists.txt#L14 .

For what is worth, you may want to try 
```
cmake --build . --target 
```
which essentially builds all targets.

**Comment by jacky82226** [comment]
> @jacky82226 thanks for the screenshot, it looks like there's indeed no MLIRMlirOptMain.a in your build directory. If it helps, here's a link to where this library is defined: https://github.com/clang-ykt/llvm-project/blob/076475713c236081a3247a53e9dbab9043c3eac2/mlir/tools/mlir-opt/CMakeLists.txt#L14 .
> For what is worth, you may want to try
> cmake --build . --target 
> 
> which essentially builds all targets.


I tried cmake --build . --target and it built successfully with MLIRMlirOptMain.
Thanks to @tjingrant !

**Comment by czlsccz** [comment]
Hi,now I have installed the onnx-mlir.But when I test the tool,use ./onnx-mlir --EmitONNXIR add.onnx,it occurs a error,like this
onnx-mlir: /home/yajuan.zhao/onnx-mlir/src/Builder/FrontendDialectTransformer.cpp:1109: void onnx_mlir::ImportFrontendModelFile(std::__cxx11::strit&, mlir::OwningModuleRef&, onnx_mlir::ImportOptions): Assertion `parse_success && "Onnx Model Parsing Failed."' failed.
Aborted (core dumped)
I want to konw how can I solve this question?Thanks!

**Comment by czlsccz** [comment]
when I used onnx-mlir tool,
./onnx-mlir --EmitLib add.onnx
I meet this question,
Error message: Executable "/home/yajuan.zhao/llvm-project/build/bin/opt" doesn't exist!
Program path: /home/yajuan.zhao/llvm-project/build/bin/opt
Command execution failed.
UNREACHABLE executed at /home/yajuan.zhao/onnx-mlir/src/MainUtils.cpp:196!
Aborted (core dumped)
Can anyone help me ?

**Comment by jcwchen** [comment]
Hi @czlsccz,
I haven't worked with onnx-mlir for a while and your error looks quite different from mine so I have no clue... My suggestion would be please make sure your llvm version is same as what README mentioned. Otherwise, please open another new issue under onnx-mlir to get the best help. Thanks.
