### ISSUE TITLE
Supporting EfficientNet

### ISSUE THREAD

**Issue by gperrotta** [onnx/onnx-mlir#351]
Hello,

I'm trying to compile EfficientNet v1 with onnx-mlir but it can't get past the shape inference pass. By debugging with onnx-mlir-opt it appears that _LRN_ operator is not registered for `ShapeInferenceInterface` and has not an `inferShapes` method.

To implement such method I was looking how they do it in [ONNX ShapeInference](https://github.com/onnx/onnx/blob/master/onnx/defs/nn/defs.cc) and noticed that it uses the same method as _BatchNorm, LpNorm, InstanceNorm and Shrink_ operators and very similar to _Dropout_ operator.

 _Dropout_ has an `inferShapes` implementation and I was going to adapt it for the other operators but I have some questions:
* How can I register an Operator for ShapeInferenceInterface since the operators file is auto-generated?
* Are there any steps other than registering the interface and implementing InferShapes?

Thanks.

**Comment by chentong319** [comment]
There are several steps needed to add ShapeInference code. I am working on simplify that process for users. I will add a the stub ShapeInference code for all operations with just emitError in the body. Then it will be easier for other to add the implementation.

**Comment by chentong319** [comment]
PR#345 is added for this purpose.

**Comment by gperrotta** [comment]
Just linking PR here: #354 

Thanks, @chentong319

**Comment by doru1004** [comment]
I see the PR referenced in this issue has been merged, can the issue be close or are there outstanding items to be resolved?

**Comment by doru1004** [comment]
Thanks! :)
