### ISSUE TITLE
Constants in ONNX models

### ISSUE THREAD

**Issue by doru1004** [onnx/onnx-mlir#36]
This issue is open to keep track the status of the handling of constant model inputs in ONNX-MLIR.

Trained ONNX models contain constant values that store the outcome of the training. As an example of such a model the MNIST model contains the following tensors as constants:

```
tensor<16x4x4x10xf32>
tensor<2xi64>
tensor<8x1x5x5xf32>
tensor<8x1x1xf32>
tensor<16x8x5x5xf32>
tensor<16x1x1xf32>
tensor<2xi64>
tensor<1x10xf32>
```

In the current version of ONNX-MLIR constants are emitted as part of the ONNX MLIR code as Constant ONNX dialect operations:
```mlir
%17 = "onnx.Constant"() {value = dense<[1, 256]> : tensor<2xi64>} : () -> tensor<2xi64>
```

The constants are then used as regular variables would be and are passed to other ONNX operations.

Constant operations are lowered to the KRNL IR dialect. For the constant operation above the corresponding KRNL code is:

```milr
    %c0_6041 = constant 0 : index
    %c1_6042 = constant 1 : index
    %c1_i64 = constant 1 : i64
    affine.store %c1_i64, %3[%c0_6041] : memref<2xi64>
    %c256_i64_6043 = constant 256 : i64
    affine.store %c256_i64_6043, %3[%c1_6042] : memref<2xi64>
```

Each constant value is defined individually:
```mlir
   %c1_i64 = constant 1 : i64
   %c256_i64_6043 = constant 256 : i64
```
as well as every index:
```mlir
   %c0_6041 = constant 0 : index
   %c1_6042 = constant 1 : index
```

Each value is then stored in a memref structure:
```milr
   affine.store %c1_i64, %3[%c0_6041] : memref<2xi64>
   affine.store %c256_i64_6043, %3[%c1_6042] : memref<2xi64>
```

These operations are then be mapped to LLVM dialect operations:

```llvm
    ; insert first value
    %62 = llvm.mlir.constant(1 : i64) : !llvm.i64
    %63 = llvm.extractvalue %59[1] : !llvm<"{ i64*, i64*, i64, [1 x i64], [1 x i64] }">
    %64 = llvm.mlir.constant(0 : index) : !llvm.i64
    %65 = llvm.mlir.constant(1 : index) : !llvm.i64
    %66 = llvm.mul %60, %65 : !llvm.i64
    %67 = llvm.add %64, %66 : !llvm.i64
    %68 = llvm.getelementptr %63[%67] : (!llvm<"i64*">, !llvm.i64) -> !llvm<"i64*">
    llvm.store %62, %68 : !llvm<"i64*">
    ; insert second value
    %69 = llvm.mlir.constant(256 : i64) : !llvm.i64
    %70 = llvm.extractvalue %59[1] : !llvm<"{ i64*, i64*, i64, [1 x i64], [1 x i64] }">
    %71 = llvm.mlir.constant(0 : index) : !llvm.i64
    %72 = llvm.mlir.constant(1 : index) : !llvm.i64
    %73 = llvm.mul %61, %72 : !llvm.i64
    %74 = llvm.add %71, %73 : !llvm.i64
    %75 = llvm.getelementptr %70[%74] : (!llvm<"i64*">, !llvm.i64) -> !llvm<"i64*">
    llvm.store %69, %75 : !llvm<"i64*">
```

Issues:
1. ONNX IR code may end up containing large arrays of constant values that make the code hard to inspect.
2. In the KRNL dialect, where constants have to be materialized using Standard and Affine operations, constant arrays are constructed one element at a time starting from their individual components. This then propagates to the LLVM dialect resulting in very slow compilation times.

### Potential solution for issue 1:

When we don't output intermediate representations of the model in ONNX or KRNL dialects, then we can leave the constant values inline.

Whenever we output the code in ONNX or KRNL we can use placeholders for the constants:
```mlir
%17 = "onnx.Constant"() {value = dense<CONST_VALUE_1> : tensor<2xi64>} : () -> tensor<2xi64>
```
To preserve the capability to round-trip, we have to allow for the above code to be read back and still be a complete program. The values of the constant operations can be emitted in a separate file (with the same base name as the original file but a custom extension like .constants) at the time we emit the ONNX dialect code above. When the code is read back in the constant values are going to be read from default .constants file or a user specified one.
This solution shields the user from seeing the constants in the code. At the same time, constants will be inline while optimization passes are run.

### Potential solution for issue 2:
- Lower constant operation to a krnl.constant operation which resides in the same module as the function requiring the constant values:

```milr
module {
  %shape = "krnl.constant"() {value : dense<[256, 10]> : memref<2xi64>} -> memref<2xi64>
  func @main_graph(%arg0: memref<1x1x28x28xf32>) -> memref<256x10xf32> {
    [... use %shape ...]
  }
  "krnl.entry_point"() {func = @main_graph, numInputs = 1 : i32, numOutputs = 1 : i32} : () -> ()
}
```

- The next step is to lower to LLVM. First we lower the constant operation to the LLVM equivalent:

```mlir
llvm.mlir.global internal constant @shape(dense<[256, 10]> : tensor<2xi32>) : !llvm<"<2 x i32>">
```
This already exists in the LLVM MLIR dialect.

The code usage of %shape should then be lowered to something similar to the following LLVM IR code:

```llvm
%0 = alloca [2 x i32], align 4
%1 = bitcast [2 x i32]* %0 to i8*
call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 %1, i8* align 4 bitcast ([2 x i32]* @shape to i8*), i64 8, i1 false)
[... use %1 ...]
```

This solution is only a proposal, feedback is welcome.

**Comment by tungld** [comment]
When importing Resnet50, the ONNXIR output is about 420 MB, and it runs overnight compiling to bitcode without completion. It makes me rethinking whether importing weights as constants is a good way or not. Maybe only import small data as constants and read large data from files as input tensors during runtime.

**Comment by AlexandreEichenberger** [comment]
@doru1004 @tjingrant can you determine if our work on handling constants has fixed this issue?

**Comment by doru1004** [comment]
@AlexandreEichenberger this was the blueprint for changes I have already done prior to Tian's further work. I can't remember the exact PRs but they have been merged already. Tian's work has also been merged on embedding constants has also been merged. I don't think there are any outstanding TODOs from this issue.

**Comment by AlexandreEichenberger** [comment]
work subsumed by other PR
