### ISSUE TITLE
MLIRAffine, MLIRLinalg, MLIRStandard not found

### ISSUE THREAD

**Issue by wangzhaode** [onnx/onnx-mlir#363]
Build llvm and miler success and not found these library, but there exist MLIRAffineOps, MLIRLinalgOps, MLIRStandardOps library. Is my MLIR version **WRONG**? But I can't do `git checkout b3b4cda104068e92b77f18c4e3fc0e0b8f3650e0` because it's not a tree.

My Version as below:
llvm-project: 52381938bcc8547316d79a4721281da7f934d9b8
onnx-mlir: 9fe2c87b1d649ef5ff6a2281d6a18e40ee47097e

**Comment by imaihal** [comment]
The commit of llvm-project looks old. Maybe you need to pull llvm-project if you can't find it.
You need to use this commit.  https://github.com/llvm/llvm-project/tree/b3b4cda104068e92b77f18c4e3fc0e0b8f3650e0

**Comment by wangzhaode** [comment]
Thanks, pull llvm-project can build these library.
