### ISSUE TITLE
Unable to build onnx-mlir from the source

### ISSUE THREAD

**Issue by xintin** [onnx/onnx-mlir#374]
Hi, 

I am referring [this link](https://onnx.ai/onnx-mlir/) to build the onnx-mlir from the source. 

```
mkdir onnx-mlir/build && cd onnx-mlir/build
cmake ..
cmake --build .
```

At the second step, it failed with the below error:
```
-- incl dir/home/gverma/onnx_experiments/onnx-mlir/third_party/onnx/home/gverma/onnx_experiments/onnx-mlir/build/third_party/onnx
CMake Error at /opt/cmake/cmake-3.16.4-Linux-x86_64/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PythonInterp: Found unsuitable version "2.7.17", but
  required is at least "3" (found /usr/bin/python)
```
Though I have Python3.6.9 installed. I fixed manually this by modifying CMakeCache.txt to use the Python3 version. 

Is this fine to fix CMakeCache.txt manually?

I am using: 
```
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
libprotoc 3.13.0
cmake version 3.16.4
```

Any help is highly appreciated.

**Comment by xintin** [comment]
I will check once again with updated libprotoc.

**Comment by tjingrant** [comment]
Could you try removing the build directory, re-run cmake while specifying the python executable using `-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3` flag? i.e., use the following as your second  step:
```
cmake -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 ..
```

**Comment by xintin** [comment]
Thank you for your help. The build was successful.
