### ISSUE TITLE
Update LLVM commit ID

### ISSUE THREAD

**Issue by NathanielMcVicar** [onnx/onnx-mlir#425]
Hi @tjingrant and @doru1004. We've brought the LLVM commit up to yesterday locally. Since this has been a pretty big one, it seems good to avoid anyone duplicating the effort. Would you all be OK with me submitting a patch? With the docker consolidation does it still have to come from the local repo? Thanks!

**Comment by doru1004** [comment]
Absolutely, we would definitely appreciate the PR.

**Comment by NathanielMcVicar** [comment]
@tjingrant I'm having trouble getting the Loop op test to work with update LLVM. Do you have any insight on what might be happening here? Thanks!
`
onnx-mlir/test/mlir/onnx/onnx_lowering.mlir split at line #3169:4:8: error: failed to materialize conversion for result #0 of operation 'std.call' that remained live after conversion
  %0 = "onnx.Loop"(%arg0, %arg1, %arg2) {body = @loop_body} : (tensor<i64>, tensor<i1>, tensor<1xi64>) -> tensor<1xi64>
       ^
onnx-mlir/test/mlir/onnx/onnx_lowering.mlir split at line #3169:4:8: note: see current operation: %12:2 = "std.call"(%10, %arg1, %1) {callee = @loop_body} : (memref<i64>, memref<i1>, memref<1xi64>) -> (tensor<i1>, tensor<1xi64>)
onnx-mlir/test/mlir/onnx/onnx_lowering.mlir split at line #3169:4:8: note: see existing live user here: %13 = krnl.dummy_cast %12#0 : (tensor<i1>) -> memref<i1>
`

**Comment by tjingrant** [comment]
Hi @NathanielMcVicar sorry for the delayed response. This seems to be problematic right at the lowering from standard to llvm? If that is the case then `krnl.dummy_cast` shouldn't be there, could you try inserting an extra pass of canonicalization (which hopefully will remove the dummy_cast operation)?

If things continue to fail, I'm happy to take a look at the code as is!

**Comment by NathanielMcVicar** [comment]
> Hi @NathanielMcVicar sorry for the delayed response. This seems to be problematic right at the lowering from standard to llvm? If that is the case then `krnl.dummy_cast` shouldn't be there, could you try inserting an extra pass of canonicalization (which hopefully will remove the dummy_cast operation)?

I updated to the latest, and I'm still seeing this issue. I tried moving Would inserting a canonicalization pass require moving the tests from onnx_lowering.mlir to onnx_lowering_with_canonicalize.mlir? This didn't resolve the issue, and inserting a --canonicalize pass between --shape-inference and --convert-onnx-to-krnl didn't either. Now that I'm back, if you have any other pointers I can follow up, or feel free to look at the linked PR. Thanks so much!

**Comment by NathanielMcVicar** [comment]
@tjingrant For what it's worth, the issue repro'd on the CI builds for the PR. Looking at the dialect conversion debug output, I wonder if the pattern may have to change. This is for ONNX to krnl only, if I'm understanding correctly.

**Comment by tjingrant** [comment]
@NathanielMcVicar Thanks for the heads up, I will look into it; I'm actually making some modifications to the Loop op lowering pattern changing subgraph from a function to a nested region (turns out onnx subgraph allows implicit capture of variables defined in parent's region); this change could potentially resolve the issue we're seeing here (or at least change its manifestation). Thus I'm probably going to hold on to this issue for a bit more time, if you don't mind.

**Comment by NathanielMcVicar** [comment]
@tjingrant Sure! In that case, would you be ok with me commenting out the loop test to get this change committed (or possibly moving it to it's own file and marking it Xfail)? If you'd prefer we hold off that's ok, but in the past I've found these LLVM updates very cumbersome to merge with subsequent ONNX MLIR commits because they touch so much code.

**Comment by tjingrant** [comment]
@NathanielMcVicar that sounds like a better plan. Please go ahead and disable loop op related tests and we can proceed to upgrade LLVM.
