### ISSUE TITLE
Input & Output Signatures

### ISSUE THREAD

**Issue by shizy818** [onnx/onnx-mlir#454]
Hello, will onnx-mlir support input & output signature for the compiled shared library?

**Comment by tjingrant** [comment]
Hi, @shizy818 can you explain what you mean? Do you mean, is there a way to query input and output signature from the compiled shared library?

**Comment by shizy818** [comment]
@tjingrant yes that's what I mean.

**Comment by tjingrant** [comment]
@shizy818 this is definitely on our mind. I hope to support this feature soon. Feel free to send me or other folks reminders if this feature is not done in the near future.

**Comment by shizy818** [comment]
@tjingrant Thank you very much!

**Comment by AlexandreEichenberger** [comment]
So that is RT support to query the inputs and outputs? Is that info that is already there, but that we have to make "queryable", or is it info that the compiler needs to generate first as its not yet present?

**Comment by tjingrant** [comment]
@AlexandreEichenberger the info is not present directly in our IR module. My plan is to enhance the EntryPoint function to record such information as names, shapes and types of each input/output tensor, and then lower them into callable functions in the .so file that returns such metadata.

**Comment by AlexandreEichenberger** [comment]
Got it, so there is some onnx-mlir work and RT work.

**Comment by shizy818** [comment]
@tjingrant Do we have this feature now?

**Comment by shizy818** [comment]
Done. Thank you all guys.
