### ISSUE TITLE
Using an initializer for the Transpose Op

### ISSUE THREAD

**Issue by kwu91** [onnx/onnx-mlir#471]
Hello, 

I have a very simplified use case where I have a model with a Transpose node using an initializer as its input. If I try to run `onnx-mlir --EmitONNXIR` on the model, I get the following error:

```
onnx-mlir: onnx-mlir/src/Transform/ONNX/ConstProp.cpp:54: mlir::RankedTensorType {anonymous}::constructRankedTensorType(mlir::ShapedType): Assertion `type.hasRank() && "Not a ranked type"' failed.
```

If I add a ShapeInferencePass at the very beginning, I am able to successfully generate a file to ONNX IR. 

```
diff --git a/src/MainUtils.cpp b/src/MainUtils.cpp
index 09b0d2f..9aef926 100644
--- a/src/MainUtils.cpp
+++ b/src/MainUtils.cpp
@@ -424,6 +424,7 @@ void registerDialects(mlir::MLIRContext &context) {
 }

 void addONNXToMLIRPasses(mlir::PassManager &pm) {
+  pm.addPass(mlir::createShapeInferencePass());
   pm.addNestedPass<FuncOp>(mlir::createDecomposeONNXToONNXPass());
   pm.addNestedPass<FuncOp>(mlir::createConstPropONNXToONNXPass());
   pm.addPass(mlir::createShapeInferencePass());
```

I'm curious to know if there might be any consequences if I add this pass there?

Below is the script I used to generate the aforementioned model.

```
import torch

torch.set_default_dtype(torch.float32)
SZ = 4

class TransposeModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.a = torch.nn.Parameter(torch.randn(SZ, SZ))

    def forward(self, x):
        t = torch.transpose(self.a, 0, 1)
        return t

model = TransposeModel()
x = []

dynamic_axes = {0 : "batch_size", 1: "batch_size"}
torch.onnx.export(model, x,
        'transpose.onnx',
	verbose=True,
        do_constant_folding=False,
        input_names = ['input'],
        output_names = ['output'],
        dynamic_axes={'input': dynamic_axes,
            'output': dynamic_axes})

```

Thanks!

**Comment by tungld** [comment]
@kwu91 Thanks for reporting this issue!

`createDecomposeONNXToONNXPass` does not require ranked tensors, so it is not necessary to do shape inference before it. One possible way is to remove the first call `pm.addNestedPass<FuncOp>(mlir::createConstPropONNXToONNXPass());` because we will call it again later after the shape inference. Could you please try it to see whether it could resolve the issue? Thanks!

**Comment by kwu91** [comment]
@tungld Removing the first call to createConstPropONNXToONNXPass instead seems to work for my models as well! Thanks! I'll wait for the changes to be merged!

**Comment by kwu91** [comment]
#472 Fixed my issue. Closing.
