### ISSUE TITLE
control flow LoopOp and IfOp mlir::verify failed

### ISSUE THREAD

**Issue by anlongstory** [onnx/onnx-mlir#478]
onnx-mlir is not allowed set input argument to then_branch or else_branch:

```mlir
module {
  func @main_graph(%arg0: tensor<1xf32>, %arg1: tensor<1xf32>) -> tensor<1xf32> attributes {input_names = ["input1", "input2"], output_names = ["res"]} {
    %0 = "onnx.Add"(%arg0, %arg1) : (tensor<1xf32>, tensor<1xf32>) -> tensor<*xf32>
    %1 = "onnx.Cast"(%0) {to = i1} : (tensor<*xf32>) -> tensor<*xi1>
    %2 = "onnx.If"(%1) {else_branch = @else_body, then_branch = @then_body} : (tensor<*xi1>) -> tensor<1xf32>
    return %2 : tensor<1xf32>
  }
  "onnx.EntryPoint"() {func = @main_graph, numInputs = 2 : i32, numOutputs = 1 : i32} : () -> ()
  func @else_body() -> tensor<1xf32> attributes {input_names = [], output_names = ["else_out"]} {
    %0 = "onnx.Mul"(%arg0, %arg1) : (tensor<1xf32>, tensor<1xf32>) -> tensor<1xf32>
    return %0 : tensor<1xf32>
  }
  func @then_body() -> tensor<1xf32> attributes {input_names = [], output_names = ["then_out"]} {
    %0 = "onnx.Add"(%arg0, %arg1) : (tensor<1xf32>, tensor<1xf32>) -> tensor<1xf32>
    return %0 : tensor<1xf32>
  }
}
```

Graph like this,  mlir::ModuleOp->dump()，”else_body“ and ”then_body“ need ”%arg0“ and ”%arg1“  , but two arguments is not set in func@else_body and func@then_body。

use mlir::verify(module->get()) get failed :
error info:  error: operand #0 does not dominate this use

LoopOp get the same problem，can you fix it？

**Comment by tjingrant** [comment]
The fix is on-going, basically, currently body graph is represented in MLIR as functions, this is incorrect because ONNX spec allows for implicit capture of variables in the parent scope. Thus I'm trying to translate the body graph instead to become a region.
