### ISSUE TITLE
How to upgrade the libprotoc package？

### ISSUE THREAD

**Issue by CHUNERnubi** [onnx/onnx-mlir#489]
I use virtual machine to realize the whole project. But in the following links, we encountered problems.
I execute` $ make --build .`.
The error returned is here.

```
/home/wcy/ONNX-MLIR/onnx-mlir/src/Builder/FrontendDialectHelper.cpp:141:40: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedField<long int>’ and ‘int’)
   return std::vector<T>(&data[0], &data[0] + size);
```

My Ubuntu system is 18.04, how to upgrade the package **libprotoc** to 3.11.0, my current version is 3.0.0.

How to upgrade this package？ Thank you in advance.

**Comment by tungld** [comment]
How about following the instruction here: https://github.com/protocolbuffers/protobuf/blob/master/src/README.md#c-installation---unix? You may need to install its python package also by using `pip install protobuf`.

**Comment by CHUNERnubi** [comment]
> How about following the instruction here: https://github.com/protocolbuffers/protobuf/blob/master/src/README.md#c-installation---unix? You may need to install its python package also by using `pip install protobuf`.

Ok, I'll have a try, thx

**Comment by CHUNERnubi** [comment]
I also have a problem that I can complete `cmake..` according to the official installation method.

When executing the `cmake -- build.` command, an error occurs, as shown below：
```
TypeError: __ init__ () got an unexpected keyword argument 'serialized_ options'
```
It should be the inconsistency between the versions of protobuf and protoc, but I'm installing it.

Previously, the command line returned the following information:

```
Using /usr/lib/python3/dist-packages
Searching for protobuf==3.0.0
Best match: protobuf 3.0.0
Adding protobuf 3.0.0 to easy- install.pth file
```

The `protobuf` version shown here is `3.0.0`, but I input `protoc -- version` from the command line to return `3.11.4`.
How to solve this problem? thank you.

**Comment by gongsu832** [comment]
After upgrading protobuf, you need to reinstall onnx so it picks up the new protobuf version. To do that:
```
cd third_party/onnx
rm -rf .setuptools-cmake-build
python3 setup.py install
```

**Comment by CHUNERnubi** [comment]
@gongsu832 Thank you for your help. When I run the following command，`sudo python3 setup.py install`
There are new problems.
```
Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    assert CMAKE, 'Could not find "cmake" executable!'
AssertionError: Could not find "cmake" executable!
```

**Comment by gongsu832** [comment]
Don't sudo. Become root properly `sudo su - root` then `python3 setup.py install`

**Comment by CHUNERnubi** [comment]
@gongsu832 thx.
