### ISSUE TITLE
Update LLVM upstream version

### ISSUE THREAD

**Issue by NathanielMcVicar** [onnx/onnx-mlir#539]
Hi @tungld @tjingrant. I would like to bring the LLVM version up to date again. We have the changes locally, but I don't want to start the PR if someone else is working on it. Please let me know if I should proceed. Thanks!

**Comment by caoimhinuibrian** [comment]
@NathanielMcVicar We would like to first move to LLVM 12 and tag this repo at that level before moving to the current commit. I was expecting the release a few days ago, but it doesn't seem to be here yet.

**Comment by NathanielMcVicar** [comment]
That makes sense. Thanks for the update, and if we can be helpful updating to the release feel free to ping me.

**Comment by NathanielMcVicar** [comment]
I understand the motivation for waiting, but LLVM just tagged a 12.0-rc5 with no end in sight. Would it make sense to move to the latest LLVM and create a 12.0 branch that works with the release when it becomes available? We have a pretty significant set of changes ready. Thanks!

**Comment by caoimhinuibrian** [comment]
@NathanielMcVicar we are currently at LLVM 12.0-rc3, I'm guessing you want to move to 13.0?

**Comment by NathanielMcVicar** [comment]
That's right, although more significantly we don't want all the effort we've done to support LLVM changes to have to be duplicated on your end. Particularly as the 12.0 RCs and 13.0 development diverges.

**Comment by caoimhinuibrian** [comment]
@NathanielMcVicar You can go ahead and submit your PRs against master. I've created an llvm 12 branch that we will track that release in.
