### ISSUE TITLE
Avoid find_package(PythonInterp...)

### ISSUE THREAD

**Issue by stephenneuendorffer** [onnx/onnx-mlir#559]
This mechanism is not robust in the presence of python2 and python3 installs and is deprecated in recent versions of cmake.  In our environment it tends to find python2 which seems to fail in various ways.  Unfortunately, this usage seems to be endemic in many of the sub-projects used in onnx.
The preference is to use find_package(Python3 ...) if python3 is needed.  (see https://cmake.org/cmake/help/git-stage/module/FindPython3.html)

I started down the path of fixing this, but because of the number of sub-projects, this isn't a simple patch, so in the short term I've resorted to setting -DPYTHON_EXECUTABLE to something sane.

**Comment by sstamenova** [comment]
@stephenneuendorffer : I believe #590 takes care of this. Can you confirm it resolved the issues in your environment?

**Comment by stephenneuendorffer** [comment]
Yes, thanks!
