### ISSUE TITLE
parallel interference cause crash

### ISSUE THREAD

**Issue by shizy818** [onnx/onnx-mlir#568]
Hello, we've done parallel predictions on the compiled model by `onnx-mlir --EmitLib`. Unfortunately it crashed:
```
g++ main.cc -std=c++11 -pthread -lbenchmark libmodel.so -o main && ./main
main() : creating thread, 0
main() : creating thread, 1
main() : creating thread, 2
main() : creating thread, 3
main() : creating thread, 4
main() : creating thread, 5
main() : creating thread, 6
main() : creating thread, 7
main() : creating thread, 8
main(1482,0x700002825000) malloc: *** error for object 0x7ff007809400: pointer being freed was not allocated
main(1482,0x7000028a8000) malloc: *** error for object 0x7ff008009400: pointer being freed was not allocated
main(1482,0x7000029ae000) malloc: *** error for object 0x7ff008809400: pointer being freed was not allocated
main(1482,0x700002825000) malloc: *** set a breakpoint in malloc_error_break to debug
main(1482,0x7000028a8000) malloc: *** set a breakpoint in malloc_error_break to debug
main() : creating thread, 9
main(1482,0x7000029ae000) malloc: *** set a breakpoint in malloc_error_break to debug
main(1482,0x70000292b000) malloc: *** error for object 0x7ff008809400: pointer being freed was not allocated
main(1482,0x70000292b000) malloc: *** set a breakpoint in malloc_error_break to debug
```

Is it a known issue? If needed, I can upload the test code. Thank you!

**Comment by tjingrant** [comment]
@shizy818 this is not a case we've tested, could you post the content of main.cc?

**Comment by gongsu832** [comment]
Running under gdb and produce a backtrace would also help.

**Comment by shizy818** [comment]
main.cc
```cc
#include <OnnxMlirRuntime.h>
#include <stdio.h>
#include <benchmark/benchmark.h>
#include <pthread.h>
using namespace std;
#define NUM_THREADS 10
extern "C" OMTensorList *run_main_graph(OMTensorList *);

static void *run(void *args)
{
  // Perform setup here
  int64_t shape[] = {1, 4}; // NHWC
  int64_t rank = 2;

  // Construct x1 omt filled with 1.
  int sz = 1 * 4;
  float x1Data[sz];
  for (int i = 0; i < sz; i++)
    x1Data[i] = 0.5f;
  OMTensor *x1 = omTensorCreate(x1Data, shape, rank, ONNX_TYPE_FLOAT);

  // Construct a list of omts as input.
  OMTensor *list[1] = {x1};
  OMTensorList *input = omTensorListCreate(list, 1);

  // Call the compiled onnx model function.
  for (int i = 0; i <= 100000; i++)
  {
    OMTensorList *outputList = run_main_graph(input);

    // Get the first omt as output.
    OMTensor *y = omTensorListGetOmtByIndex(outputList, 0);
  }
  cout << "thead exit" << endl;
  pthread_exit(NULL);
}

int main()
{
  pthread_t threads[NUM_THREADS];
  int rc;
  int i;
  for (i = 0; i < NUM_THREADS; i++)
  {
    cout << "main() : creating thread, " << i << endl;
    rc = pthread_create(&threads[i], NULL, run, NULL);
    if (rc)
    {
      printf("Error:unable to create thread, %d\n", rc);
      exit(-1);
    }
  }

  for (i = 0; i < NUM_THREADS; i++) {
    pthread_join(threads[i], NULL);
  }

  return 0;
}
```

I think this error is introduced by commit `Fix memory leak with C/C++ interface (1f0149b8808bc13bb60c3c43e0d9bb9db1caad86)`. 

On Linux env, test before it runs OK. Since this commit, it fails:
```
(base) root@volvas1:~/tent-onnx# ./main
main() : creating thread, 0
main() : creating thread, 1
main() : creating thread, 2
double free or corruption (!prev)
Aborted
```

Here is the simple onnx model: 
[tent.onnx.zip](https://github.com/onnx/onnx-mlir/files/6254342/tent.onnx.zip)

**Comment by shizy818** [comment]
@gongsu832 By the way, I tried gdb to check the backtrace but get nothing. The dynamical library is produced by LLVM code and can we still see the source code and stack trace?

**Comment by tjingrant** [comment]
@tungld wonder if you have any thoughts? 

Perhaps to support parallel inference, we should, instead of cleaning up global constants ourselves at the end of each inference run, set up a clean up function for users to call into themselves upon completing all inference tasks.

**Comment by chentong319** [comment]
@tungld In #556, is  globalBase set to Null after it is freed?

**Comment by tungld** [comment]
> Perhaps to support parallel inference, we should, instead of cleaning up global constants ourselves at the end of each inference run, set up a clean up function for users to call into themselves upon completing all inference tasks.

Sounds good to reuse the global constants across all tasks.

> @tungld In #556, is globalBase set to Null after it is freed?
I am afraid so. 

In addition to the free issue, there is another potential issue. globalBase only keeps the pointer to a newly allocated buffer for constants for local use. Each run creates a new local buffer and stores the pointer to the same globalBase. So, multiple tasks will try to store to the same location, which is problematic. It seems this leads to more memory leak though it may not affect the inference result (since they finally refer to the same constant). @tjingrant @chentong319 any thought on this?

**Comment by tungld** [comment]
@chentong319 @tjingrant @shizy818 I created to PR to address this issues. 

The idea is to allow loading constants once, running run_main_graph multiple times, then destroying the constants.

**Comment by gongsu832** [comment]
@shizy818 Indeed you won't be able to step into `run_main_graph` since the object code was compiled by `llc` and `opt` from LLVM bitcode, which apparently doesn't generate gdb consumable debug info. @tjingrant @chentong319 @tungld How do people normally debug in such situation?

**Comment by tjingrant** [comment]
@gongsu832 I think Kevin at some point was able to step through the generated code using gdb. Let me learn from Kevin and perhaps I can write something up.

**Comment by caoimhinuibrian** [comment]
@tjingrant @gongsu832 I believe i stepped through at the assembler level. Maybe we should add an option to onnx-mlir to have llc emit the dwarf info.

**Comment by tungld** [comment]
@shizy818 could you please try again with the current master branch? Thanks!

**Comment by shizy818** [comment]
@tungld Sure. Will try and let you know.

**Comment by shizy818** [comment]
@tungld We've tested both C & JNI API. Both look OK now.
