### ISSUE TITLE
Windows CI build is broken

### ISSUE THREAD

**Issue by sstamenova** [onnx/onnx-mlir#599]
The Windows CI build is very very broken. Issues identified so far:

1) The build of onnx-mlir.exe fails (see #598) but Windows CI hides it because the next step "succeeds"
2) The build of onnx-mlir.exe fails to link after 1) is fixed (due to protobuf version)
3) The tests don't run in the Windows CI build (see #590)

Right now the yml definition of the build invokes a single cmd script which does everything. If something fails somewhere in the middle of the script, the failure is lost if the next command succeeds. So since the tests were not running and the step was reporting success, the build failure went undetected by the Windows CI.

Ideally, this would be improved to reliably report build and test failures on Windows and I see a couple of options:
1) Split the build into individual steps where each step is a script that is a logical unit (build mlir, test mlir, build onnx-mlir, test onnx-mlir). This is useful because success/failure will be evaluated at the end of each step as opposed to only once at the very end and more failure will be caught. It would still use (at least a subset) of the existing cmd scripts which can continue to be matched to the .md files
2) Embrace yml and do away with the old cmd scripts. Each of the steps (such as calling cmake) can be implemented directly in yml and all the goodness of the build pipelines can be leveraged. This does mean that the scripts will not be used anymore and I'm not sure how/if it is possible to match the yml to the .md files.

**Comment by sstamenova** [comment]
@tjingrant : Do you have a preference of 1 vs 2? I can probably quickly do either and hopefully end this madness.

**Comment by NathanielMcVicar** [comment]
#241 was a fix for essentially the same issue on the build side. This seems compatible with approach 1.

**Comment by caoimhinuibrian** [comment]
@sstamenova we don't have any preference for how the Windows build works ... you should follow your own inclination

**Comment by sstamenova** [comment]
#605 Fixed the Windows-specific issues with the onnx-mlir build. There are some tests that remain red in the Windows CI build, but they were identified previously as failures in Release on all platforms (see #582).
