### ISSUE TITLE
Enable windows build/install.

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx-mlir#6]
Besides Linux build and install, windows build/install should also be supported (MLIR itself supports windows build, btw).

**Comment by tjingrant** [comment]
I'm not aware of anyone in our group who's familiar or even have access to a windows machine. I'm personally willing to work with someone from Microsoft to enable a windows-based CI. The trickest part is always in the linking stage (from my experience building onnx-mlir on Linux and Mac), so it'd be nice if there could be someone from your side who's familiar with the c++ compilation/linking on Windows to help out with this effort.

**Comment by linkerzhang** [comment]
Sounds good. we'll do that. keep this issue open to track it.

**Comment by jacky82226** [comment]
Thank you for the reporting. I am working on this.

**Comment by jacky82226** [comment]
After code modification and environment tuning, it seems that I finally build onnx-mlir successfully in Windows via Visual Studio 2019. However, while trying running onnx-mlir for mnist.onnx, it said that:
> size too big: 14829735431805717965 details: size_t to int conversion

I am not sure whether my installation is correct or not. Could @tjingrant provide me with the add.onnx for testing? 

I am writing the tutorial for Windows and will make a PR for code modification.

**Comment by doru1004** [comment]
Thanks a lot for fixing the install on Windows.

Regarding your error, without any more details about where the error occurs it's hard to figure out what's going on.

Have all regression and backend tests passed on your machine?

**Comment by jacky82226** [comment]
> Thanks a lot for fixing the install on Windows.
> 
> Regarding your error, without any more details about where the error occurs it's hard to figure out what's going on.
> 
> Have all regression and backend tests passed on your machine?

Not a problem!

Sorry for the late reply. I got stuck in running check-mlir-lit in Windows. After modifying some files, it has finally passed dependency linking errors. However, I encountered a testing failure said:

> 4>------ Rebuild All started: Project: check-mlir-lit, Configuration: Debug x64 ------
24>Running the ONNX MLIR regression tests
24>-- Testing: 9 tests, 4 workers --
24>FAIL: Open Neural Network Frontend :: krnl/ops.mlir (1 of 9)
24>FAIL: Open Neural Network Frontend :: krnl/reshape.mlir (2 of 9)
24>FAIL: Open Neural Network Frontend :: onnx/onnx_decompose.mlir (3 of 9)
24>FAIL: Open Neural Network Frontend :: onnx/onnx_canonicalization.mlir (4 of 9)
24>FAIL: Open Neural Network Frontend :: onnx/onnx_lowering.mlir (5 of 9)
24>FAIL: Open Neural Network Frontend :: onnx/onnx_lowering_with_dealloc.mlir (6 of 9)
24>FAIL: Open Neural Network Frontend :: onnx/onnx_shape_inference.mlir (7 of 9)
24>FAIL: Open Neural Network Frontend :: onnx/onnx_shape_inference_maxpool.mlir (8 of 9)
24>FAIL: Open Neural Network Frontend :: transform/attribute_promotion.mlir (9 of 9)
24>
24>Testing Time: 0.73s
24>********************
24>Failing Tests (9):
24>    Open Neural Network Frontend :: krnl/ops.mlir
24>    Open Neural Network Frontend :: krnl/reshape.mlir
24>    Open Neural Network Frontend :: onnx/onnx_canonicalization.mlir
24>    Open Neural Network Frontend :: onnx/onnx_decompose.mlir
24>    Open Neural Network Frontend :: onnx/onnx_lowering.mlir
24>    Open Neural Network Frontend :: onnx/onnx_lowering_with_dealloc.mlir
24>    Open Neural Network Frontend :: onnx/onnx_shape_inference.mlir
24>    Open Neural Network Frontend :: onnx/onnx_shape_inference_maxpool.mlir
24>    Open Neural Network Frontend :: transform/attribute_promotion.mlir
24>
24>  Unexpected Failures: 9

It seems that it did not provide any error messages so it is hard to debug. The building part for onnx-mlir and check-mlir-lit is looking fine. 

I am still tracking it. I would greatly appreciate any ideas. Thank you.

**Comment by jacky82226** [comment]
Worked with @byronChanguion and solved by the PR #86

**Comment by Xatter** [comment]
There's now an issue of a missing header file on windows. `unistd.h` used in `MainUtils.cpp` doesn't exist on Windows.

There are places where a windows version has been published, but I'm not sure if the right thing to do is include that in this project or to use a build preprocessor declaration to do `#ifdef WINDOWS` and include a different header that is standard on Windows that has the needed function.

**Comment by jacky82226** [comment]
Thanks for reporting this. I encountered the same error while testing the latest version on new Windows-CI. I think "unistd.h" is used for "fork()", but there is no proper substitute "fork()" on Windows. @doru1004 Do you have any idea how to tune it on Windows?

**Comment by Xatter** [comment]
@doru1004 is at IBM which I believe uses Linux primarily. I wonder if @byronChanguion at Microsoft who originally contributed the windows build instructions might know the best way forward? I also see that @migueldeicaza has also contributed here and is intimately familiar with cross-platform C++ from the Xamarin project and may have some words of wisdom

**Comment by jacky82226** [comment]
As far as I know, the easiest way to simulate fork() on Windows is using CreateProcess(). However, it won't inherit the parent's state, which would probably break the original logic here.

So I was wondering that is this fork() required for output? (Or simply for performance-wise)

**Comment by jacky82226** [comment]
Solving this new problem here. #115

**Comment by migueldeicaza** [comment]
I am mostly a Mac/Linux lifeform, I am afraid I can not be of much help with Windows build issues.

**Comment by tjingrant** [comment]
Thanks for all the help from @jacky82226 @byronChanguion @migueldeicaza , I believe this issue has been resolved.
