### ISSUE TITLE
Resolve circular dependency between ONNXOps  and KrnlOps

### ISSUE THREAD

**Issue by sstamenova** [onnx/onnx-mlir#638]
From the cmake for ONNXOps:

```
## TODO: remove dependency of ONNXOps on KrnlOps
# OMONNXOps depends on symbols in OMKrnlOps, we do not specify
# linking dependency explicitly here because OMKrnlOps also depends
# on OMONNXOps, which is circular.
```

There are some major benefits to resolving the circular dependency:
1) The majority of the cmake files in the project use add_dependencies to manage dependencies between the various libs instead of target_link_libraries. target_link_libraries automatically adds the requested link libraries as a dependency in addition to carrying over any compilation flags, include directories or other libs that have been marked as dependencies. This greatly simplifies dependency management.
2) We would be able to set ```-Wl,-z,defs``` and ensure that all symbols exist when building shared libraries eliminating the possibility for any issues with the shared libraries.

**Comment by gramalingam** [comment]
It would be great to remove the dependency of ONNXOps on KrnlOps!

**Comment by AlexandreEichenberger** [comment]
It is not that easy because we share code for shape inference and onnx-to-krnl lowering

**Comment by sstamenova** [comment]
> It is not that easy because we share code for shape inference and onnx-to-krnl lowering

Does it make sense to move the shared code to a new library?

**Comment by caoimhinuibrian** [comment]
> > It is not that easy because we share code for shape inference and onnx-to-krnl lowering
> 
> Does it make sense to move the shared code to a new library?

Yeah, we should fix this somehow ... looking into it

**Comment by AlexandreEichenberger** [comment]
@caoimhinuibrian, currently half way through a solution. Requires a bit of engineering, not too much as IndexExpr are creating code that currently explicitly use Krnl, but I can work around this. Will push a PR today, probably. Looking forward to your input

**Comment by caoimhinuibrian** [comment]
@AlexandreEichenberger oh ... I was looking at it ... will stop now. I was pursuing a dependency injection idea to solve

**Comment by AlexandreEichenberger** [comment]
#653 is implementing the changes. Please feel free to comment on it as you see fit
