### ISSUE TITLE
Leaky mlir namespace from header file

### ISSUE THREAD

**Issue by bxing-groq** [onnx/onnx-mlir#648]
Header file `/src/Dialect/ONNX/ONNXOpsHelper.hpp` ([link to line](https://github.com/onnx/onnx-mlir/blame/master/src/Dialect/ONNX/ONNXOpsHelper.hpp#L24) | [link to PR](https://github.com/onnx/onnx-mlir/commit/4d8b855c1737eeeae13739ea40a4a73749e6d275#r50246138)) leaks `using namespace mlir`. Generally, leaking namespaces from header files is an anti-pattern. All files that include them will be forced to use these namespaces, as do the files that include these files, etc...After many layers, the end-users might end up using a namespace unknowingly. If there happens to be a name overlap between global and `mlir` namespace, users might be confused which one they're using, especially for operators. What's worse, when moving some code from a `cpp` file that indirectly includes this header to another one that doesn't, suddenly nothing works...

From [Google C++ Style Guide: Namespaces](https://google.github.io/styleguide/cppguide.html#Namespaces)

> Do not use Namespace aliases at namespace scope in header files except in explicitly marked internal-only namespaces, because anything imported into a namespace in a header file becomes part of the public API exported by that file.

**Comment by AlexandreEichenberger** [comment]
will address this in a PR shortly

**Comment by AlexandreEichenberger** [comment]
implemented in PR #654
