### ISSUE TITLE
"operand #0 does not dominate this use" error using the code from llvm-12-release-branch 

### ISSUE THREAD

**Issue by SharonYuIBM** [onnx/onnx-mlir#652]
Hello, when trying to compile onnx models using the latest code from the `llvm-12-release-branch` branch, some models fail to be compiled with error: 

`operand #0 does not dominate this use`

For example, this one: 

[tent.onnx.zip](https://github.com/onnx/onnx-mlir/files/6427454/tent.onnx.zip)

This looks to be a regression since it model works before.

**Comment by caoimhinuibrian** [comment]
@doru1004 @chentong319 is this the same issue as #535?

**Comment by caoimhinuibrian** [comment]
fixed by #662
