### ISSUE TITLE
Circular dependency between OMONNXOps and OMONNXRewrite?

### ISSUE THREAD

**Issue by sstamenova** [onnx/onnx-mlir#681]
I am still trying to get HandleLLVMOptions included in the project correctly and one of the things it does by default is build with: ```-Wl,-z,defs``` which forces the build of the shared libraries to resolve all symbols. While adding the dependencies for the libraries, I found that OMONNXOps and OMONNXRewrite appear to have a circular dependency as well. OMONNXOps needs the set of ```mlir::ONNXXXXOp::getCanonicalizationPatterns``` functions defined in OMONNXRewrite while OMONNXRewrite needs a slew of functions defined by OMONNXOps (the dependency of OMONNXRewrite on OMONNXOps is already in the cmake files). Is this expected?

**Comment by AlexandreEichenberger** [comment]
I can look into this, probably early next week

**Comment by AlexandreEichenberger** [comment]
Surveying a bit the code pattern, here is what I see.

Dialect/ONNX/ONNXOps.td generates the build/src/Dialect/ONNXOps.hpp.inc (included in ), which defines the `getCaonicalizationPatterns` for the ops that need this, e.g. for the ONNXAddOp

``` C++
class ONNXAddOp : public ::mlir::Op<ONNXAddOp, ::mlir::OpTrait::ZeroRegion, ::mlir::OpTrait::OneResult, ::mlir::OpTrait::OneTypedResult<::mlir::Type>::Impl, ::mlir::OpTrait::ZeroSuccessor, ::mlir::OpTrait::NOperands<2>::Impl, ::mlir::MemoryEffectOpInterface::Trait, ShapeInference::Trait> {

[...]
  static void getCanonicalizationPatterns(::mlir::RewritePatternSet &results, ::mlir::MLIRContext *context);
[...]
};
```

These patterns are generated in the Transform/ONNX subdirectory, for example in Combine.cpp
```
void ONNXAddOp::getCanonicalizationPatterns(
    RewritePatternSet &results, MLIRContext *context) {
  results.insert<MulAddToGemmOptPattern>(context);
}
```
which are in turn generated by patterns in ONNXCombine.td, which as all ONNX based dialect DDR need the ONNXOps.td file.

So @sstamenova what do you propose? Should we pull basically the patterns that are defined by the ONNXOps.td (namely canonicalization, shape inference,...) all into the same library? Which would reside under the general src/Dialect/ONNX subdirectory?

**Comment by sstamenova** [comment]
That would be my expectation based on how the other dialects in mlir are defined. I don't have context, though, into why the decision was made to split some of them between the dialect lib and the transform lib fox ONNX MLIR.

**Comment by AlexandreEichenberger** [comment]
Yes, MLIR has migrated to a model where under a given Dialect, they have multiple folders. We could go to that model too.

**Comment by sstamenova** [comment]
Each dialect in MLIR has multiple libraries associated with it (corresponding to each folder) but the libraries do not have circular dependencies. For example, for MLIRAffine, there's libMLIRAffine and libMLIRAffineTransforms with MLIRAffineTransforms strictly dependent on libMLIRAffine, so the definitions for ```getCanonicalizationPatterns``` are in libMLIRAffine.

**Comment by AlexandreEichenberger** [comment]
@sstamenova yes, I am arriving at the same conclusion. If we are using DDR to generate basic optimization like canonicalization who are associated with the base dialect (where the ops are defined), then they need to be there too.

**Comment by sstamenova** [comment]
@AlexandreEichenberger : Do you think you could make the necessary changes to remove the circular dependency?

**Comment by AlexandreEichenberger** [comment]
@sstamenova yes, let me do it now.
