### ISSUE TITLE
Errors during check-onnx-lit

### ISSUE THREAD

**Issue by ericleaf** [onnx/onnx-mlir#70]
Hi, the first test of `check-onnx-lit` failed and gives me the following error massage:
```
FAIL: Open Neural Network Frontend :: onnx/onnx_canonicalization.mlir (1 of 10)
... ...
Testing Time: 0.11s
********************
Failing Tests (1):
    Open Neural Network Frontend :: onnx/onnx_canonicalization.mlir

  Expected Passes    : 9
  Unexpected Failures: 1
test/mlir/CMakeFiles/check-onnx-lit.dir/build.make:57: recipe for target 'test/mlir/CMakeFiles/check-onnx-lit' failed
make[3]: *** [test/mlir/CMakeFiles/check-onnx-lit] Error 1
CMakeFiles/Makefile2:3062: recipe for target 'test/mlir/CMakeFiles/check-onnx-lit.dir/all' failed
make[2]: *** [test/mlir/CMakeFiles/check-onnx-lit.dir/all] Error 2
CMakeFiles/Makefile2:3069: recipe for target 'test/mlir/CMakeFiles/check-onnx-lit.dir/rule' failed
make[1]: *** [test/mlir/CMakeFiles/check-onnx-lit.dir/rule] Error 2
Makefile:1009: recipe for target 'check-onnx-lit' failed
make: *** [check-onnx-lit] Error 2
```

Meanwhile, when I'm trying to emit MLIR with mobilenet/squeezenet ONNX model from ONNX model zoo, it gives me the following massage:
```
onnx-mlir: /home/hcye/workspace/onnx-llvm-project/mlir/include/mlir/IR/Types.h:279: U mlir::Type::cast() const [with U = mlir::RankedTensorType]: Assertion `isa<U>()' failed.
Aborted (core dumped)
```
I'm using the latest ONNX-MLIR and the LLVM repo mentioned in the readme. Thanks!

**Comment by tjingrant** [comment]
Could you set your environment var `LIT_OPTS` to be `-v` so that LIT can produce a more detailed error message?

Also, we are in active development at this stage, and we just managed to verify mnist works. We are currently working on enabling ResNet. I foresee that mobilenet/squeezenet can be supported relatively quickly (within weeks).

**Comment by ericleaf** [comment]
Hi, thanks for your reply. The detailed error massage is shown as follow:
```
FAIL: Open Neural Network Frontend :: onnx/onnx_canonicalization.mlir (1 of 10)
******************** TEST 'Open Neural Network Frontend :: onnx/onnx_canonicalization.mlir' FAILED ********************
Script:
--
: 'RUN: at line 1';   /home/hcye/workspace/onnx-mlir/build/bin/onnx-mlir-opt --canonicalize /home/hcye/workspace/onnx-mlir/test/mlir/onnx/onnx_canonicalization.mlir -split-input-file | /home/hcye/workspace/onnx-llvm-project/build/bin/FileCheck /home/hcye/workspace/onnx-mlir/test/mlir/onnx/onnx_canonicalization.mlir
--
Exit Code: 2

Command Output (stderr):
--
onnx-mlir-opt: Unknown command line argument '--canonicalize'.  Try: '/home/hcye/workspace/onnx-mlir/build/bin/onnx-mlir-opt --help'
onnx-mlir-opt: Did you mean '--pass-pipeline'?
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /home/hcye/workspace/onnx-llvm-project/build/bin/FileCheck /home/hcye/workspace/onnx-mlir/test/mlir/onnx/onnx_canonicalization.mlir
```
MNIST model is successfully emitted, and I will play with that first. Thanks for your information!

**Comment by tjingrant** [comment]
Hi @ericleaf , if you use the specific version of LLVM-Project we specified in README, everything should work fine (commit-id: 07e462526d0cbae40b320e1a4307ce11e197fb0a). You can run into this issue if you use the absolute latest version. 

Let me know if this solves your problem!

**Comment by chentong319** [comment]
I ran into the same problem with different llvm-project version.
Now I am using the commit-id as in the README.md. I got compilation error for onnx-mlir. Error message:
[ 98%] Linking CXX executable ../bin/onnx-mlir
/home/chentong/upstream-llvm-project/build/lib/libMLIRAffineToStandard.a(AffineToStandard.cpp.o): In function `_GLOBAL__sub_I_AffineToStandard.cpp':
AffineToStandard.cpp:(.text.startup._GLOBAL__sub_I_AffineToStandard.cpp+0x58): undefined reference to `mlir::registerPass(llvm::StringRef, llvm::StringRef, mlir::ClassID const*, std::function<std::unique_ptr<mlir::Pass, std::default_delete<mlir::Pass> > ()> const&)'
/home/chentong/upstream-llvm-project/build/lib/libMLIRStandardToLLVM.a(StandardToLLVM.cpp.o): In function `_GLOBAL__sub_I_StandardToLLVM.cpp':
StandardToLLVM.cpp:(.text.startup._GLOBAL__sub_I_StandardToLLVM.cpp+0x58): undefined reference to `mlir::registerPass(llvm::StringRef, llvm::StringRef, mlir::ClassID const*, std::function<std::unique_ptr<mlir::Pass, std::default_delete<mlir::Pass> > ()> const&)'
/home/chentong/upstream-llvm-project/build/lib/libMLIRTransforms.a(Canonicalizer.cpp.o): In function `_GLOBAL__sub_I_Canonicalizer.cpp':

It seems to be related to canonicalized. By the way, onnx-mlir is the latest master version.

**Comment by AlexandreEichenberger** [comment]
I assume that since  @ericleaf has not responded in more than a month, this fix solved his problem
