### ISSUE TITLE
MLIR removed EDSC helpers

### ISSUE THREAD

**Issue by NathanielMcVicar** [onnx/onnx-mlir#712]
Per the discussions here https://llvm.discourse.group/t/evolving-builder-apis-based-on-lessons-learned-from-edsc/879 and more recently here https://llvm.discourse.group/t/rfc-dsl-style-dialect-specific-builders/1823 MLIR upstream has removed the EDSC builder helpers (see changes May 19th to May 21st here https://github.com/llvm/llvm-project/commits?author=nicolasvasilache). Normally the right way to update ONNX MLIR for LLVM is pretty straightforward, but this requires a significant change, and there are a few options.

1. What we've done locally for now is just copy the EDSC headers over to ONNX MLIR. This involves bringing a lot of code into ONNX MLIR that doesn't necessarily belong.
2. Another option is that Google intends to publish builder helpers out of tree eventually. You can see a preview here https://github.com/google/iree-llvm-sandbox/tree/main/ModelBuilder, but this is not ready to be taken as a third_party module yet. We could simply wait to update LLVM until something is, but I don't know what the timeline is.
3. ONNX MLIR can develop it's own builder wrapper, with a minimal subset of required features, but this adds maintenance overhead.
4. Finally, the cleanest solution may be to remove use of helpers entirely and call . This is what MLIR did internally, but it requires some pretty significant code organization changes (passing some kind of OpBuilder around [MLIR uses the new implicit loc version]).

Are any of these options clearly better, or did I miss an obvious solution? Thanks!

**Comment by AlexandreEichenberger** [comment]
@NathanielMcVicar thanks for the info. From my read of  https://llvm.discourse.group/t/rfc-dsl-style-dialect-specific-builders/1823 ,  I have no strong position for most of the proposal, so  item 4. above is probably the best choice. 

However, probably like linalg, we are generating a lot of loops and some branches. Before using lambda, the code was very much unreadable. I believe the new EDSC like approach yielded much more readable code, e.g.
``` c++
    krnl_iterate({ii, jj, kk}, {ii1, jj1, kk1}, {zero, zero, zero}, {I, J, K},
        {}, [&](ValueRange args) {
          ValueRange indices = krnl_get_induction_var_value({ii1, jj1, kk1});
          Value i1(indices[0]), j1(indices[1]), k1(indices[2]);
          krnl_matmul(A, {zero, zero}, B, {zero, zero}, C, {zero, zero},
              {ii2, jj2, kk2}, {i1, j1, k1}, {I, J, K},
              {iRegTile, jRegTile, kRegTile}, {}, {}, {}, true, true, false);
        });
  }
```

You may not be familiar with the actual operations, but at a high level, we can see that there is a loop begin created with operations in it.  We often have nested loops that make this notation even more beneficial. 

I see a brief mention of this in the above discussion, but it was not the focus of most of the discussion.  I quote

> A potentially dangerous behavior can appear in the case of nested-region builders, for example, in
```
create.scf.forOp(..., [&](OpBuilder &nested, Location loc, …) {
  // `create` must be updated to point to the new builder before being used here
  DialectBuilder::Scoped raii(create, nested, loc);
  create.scf.yieldOp(...);
});
```
>one may forget to update the insertion point of the multi-dialect builder. 

Can you point me to a place that use this lambda functions in a "safe and approved ways", or is it discontinued.

Thanks

**Comment by NathanielMcVicar** [comment]
Thanks for taking a look! I'm not sure it's exactly what you're asking for, but is the example of fillVal from linalg op promotion helpful (https://github.com/llvm/llvm-project/commit/4519ca3d2e56fee3d9b83a8228db5d5605680d4a#diff-7515fba8de9c19178ad6a3af9aea55c80f69db87073739d0e5a7ae91b9e47538L262)? I couldn't find any with nested loops. I'm sure Nicolas would be happy to drop in and offer a much more complete answer than mine, if that would be useful.

**Comment by NathanielMcVicar** [comment]
I can go ahead with a PR to remove EDSC as per 4, but I think understanding these operations would let someone come up with cleaner solutions. If anyone is interested maybe we can discuss this in more detail offline?

**Comment by caoimhinuibrian** [comment]
@alexe @doru1004 @chentong319 do we want to discuss? or are we cool with this?

**Comment by AlexandreEichenberger** [comment]
@NathanielMcVicar would be great to have a discussion. The consensus here is that we would like to preserve the lambda for the iterate constructs, as it makes readability of the code much higher. Should we try to have Nicolas too?

**Comment by NathanielMcVicar** [comment]
That sounds good! @nicolasvasilache do you have any suggestions, or would you be willing to discuss with us? Thanks!

**Comment by NathanielMcVicar** [comment]
After speaking with Nicolas it sounds like there isn't going to be any more work on implicit builders or porting EDSC to an out-of-tree repo, so I think if ONNX MLIR wants to keep a structure similar to the current one something like solution 3 above would be required.

**Comment by AlexandreEichenberger** [comment]
I started looking at all of the EDSC's patches by @nicolasvasilache, it looks like there are builders that are structured for the SCF IfOp / ForOp in the EDSC-free MLIR. So we should be able to use the same scheme, with a bit of work. 

@NathanielMcVicar I wonder how could we migrate the code more smoothly than by yanking to the latest MLIR and getting 1000s of compile errors. Would be great to do it step by step, but we also need the "replacement" infrastructure. Any ideas?

**Comment by NathanielMcVicar** [comment]
My understanding is that there are other structured builders but EDSC provided an implicit builder, which isn't otherwise available, so we would have to manually pass a builder throughout the hierarchy, which ONNX MLIR doesn't currently do.

My thought as to how to do the transition smoothly would be to remove EDSC first and migrate the LLVM hash once that's complete. The downside to this approach is potential extra work if the solution is based on MLIR constructs that change and need to be updated along with other fixes for the LLVM hash.

Another option, which we currently use locally, is to make a copy of EDSC inside ONN XMLIR, then migrate LLVM, and then remove use of EDSC and the local copy. This is probably less work overall, but creates an ugly intermediate state.

**Comment by AlexandreEichenberger** [comment]
@NathanielMcVicar I will start migrating the structured builders (currently not attached to a class) to their original operation's builders. That will be a good start. Hopefully I can migrate most of the code that way.

**Comment by NathanielMcVicar** [comment]
@AlexandreEichenberger can we close this? I believe you have fully removed them. I also wanted to really thank you for being so responsive on EDSC and also doing the LLVM commit update while you were at it 💯

**Comment by AlexandreEichenberger** [comment]
implemented, thanks to all for their constructive feedback, it really help
