### ISSUE TITLE
using onnx-mlir docker

### ISSUE THREAD

**Issue by srplsnh** [onnx/onnx-mlir#729]
Running onnx-mlir using the docker fails with this message,
$ sudo docker run  onnxmlirczar/onnx-mlir --EmitMLIR  ./onnx-mlir/build/test/unit/Runtime/DocExampleTest/add.onnx
onnx-mlir: /workdir/onnx-mlir/src/Builder/FrontendDialectTransformer.cpp:1205: void onnx_mlir::ImportFrontendModelFile(std::string, mlir::MLIRContext&, mlir::OwningModuleRef&, onnx_mlir::ImportOptions): Assertion `parse_success && "Onnx Model Parsing Failed."' failed

Docker image downloaded today,
REPOSITORY                                     TAG                 IMAGE ID            CREATED             SIZE
onnxmlirczar/onnx-mlir                         latest              9406bfab1fa9        16 hours ago        1.28GB

Appreciate any help to resolve this.
Thanks !

**Comment by gongsu832** [comment]
onnx-mlir running inside the docker container has no access to the host file `./onnx-mlir/build/test/unit/Runtime/DocExampleTest/add.onnx` (the whole point of a container). You need to mount the host directory containing your .onnx file into the container, e.g.,
```
sudo docker run --rm -ti -v /path/to/your/onnx/file:/workdir onnxmlirczar/onnx-mlir --EmitMLIR /workdir/add.onnx
```

**Comment by srplsnh** [comment]
Got it. Thanks !
