### ISSUE TITLE
Compile error in KrnlOps.td

### ISSUE THREAD

**Issue by ANSHUMAN87** [onnx/onnx-mlir#732]
Please find below cmake config output:

![image](https://user-images.githubusercontent.com/32511895/122727807-13dad280-d295-11eb-90bc-6c55cda7e1cc.png)

I have followed all the steps mentioned at https://github.com/onnx/onnx-mlir#installation-on-unix

However while compiling i am getting below error:
![image](https://user-images.githubusercontent.com/32511895/122728031-54d2e700-d295-11eb-83df-35aadfd69d1c.png)

Looks like it is unable to include mlir headers while compilation. 
I had crosschecked the cmake dependencies configurations. All path seems correct.
Would anyone please help resolve the issue. TIA!

**Comment by gongsu832** [comment]
Things to check,

- Did you update onnx after building llvm-project? If yes you may want to rebuild llvm-project.
- Did you try to clean out onnx-mlir/build completely and do a build from scratch? cmake caches in the build directory often causes problems.

**Comment by ANSHUMAN87** [comment]
Thanks @gongsu832 for your response!
The issue is resolved now, the root cause was the version mismatch between llvm and onnx-mlir.
