### ISSUE TITLE
Asserting error for model yolo

### ISSUE THREAD

**Issue by chentong319** [onnx/onnx-mlir#733]
Error message is:
```
Assertion failed: (numElements != 1 && "splat of 1 element should already be detected"), function getKey, file /Users/shizy/Projects/github/llvm-project/mlir/lib/IR/AttributeDetail.h, line 115.
```
This is called from ConstPropHelper.cpp:143. I dumped the resType is <f32> and the sizeInBytes is 4. 
@tungld I think you are familiar with the constant from raw buffer. Could you take a look?
Currently, I commented out the assert in AttributeDetail.h:115 and the model is parsed. I think this assert is not correct.

**Comment by tungld** [comment]
@chentong319 I seemed it confused DenseElementsAttr of 1 element with a splat DenseElementsAttr. Will take this in detail.

**Comment by tungld** [comment]
@chentong319 where can we get the yolo model? Thanks!

**Comment by chentong319** [comment]
@tungld I put it in box https://ibm.box.com/s/nlcpg0542m1hsygwfr3ntvw41fuawr4z.

**Comment by tungld** [comment]
@chentong319 This error was caused by scalar tensors during constant propagation, e.g. `tensor<f32>`.  I created a PR to fix it.
