### ISSUE TITLE
Remove CircleCI status from README & replace with Jenkins x86 Linux build status

### ISSUE THREAD

**Issue by caoimhinuibrian** [onnx/onnx-mlir#747]

**Comment by gongsu832** [comment]
@caoimhinuibrian This is fixed in PR https://github.com/onnx/onnx-mlir/pull/734

Note it's failing the DCO due to:
Commit sha: 6b2a512, Author: chentong319, Committer: GitHub; Can not find "chentong319 chentong@us.ibm.com", in ["Tong Chen chentong@us.ibm.com", "Tong Chen chentong@us.ibm.com"].

**Comment by caoimhinuibrian** [comment]
@gongsu832 Cool, I approved #734 but it has conflicts

**Comment by gongsu832** [comment]
@caoimhinuibrian conflicts are fixed and ready to merge.
