### ISSUE TITLE
Long build time for Windows CI

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#776]
I think adding the WindowCI as mandatory is a good move but at this time:
1) the build takes 2:20 hours to build (last one that passed)
2) we don't have a way to test it (IBM team has access to Mac/Linux x86 but not Windows). Would it be possible to make a virtual machine available to our team for us to develop when there are errors specific to Windows.

My personal preference would be to make the Windows CI mandatory once these two points are addressed.

**Comment by caoimhinuibrian** [comment]
@NathanielMcVicar @sstamenova please chime in here

**Comment by caoimhinuibrian** [comment]
While I understand the concern about latency here, I also feel that the purpose of the CI testing is to prevent broken code getting into the repo, so really all tests that we feel are useful should be mandatory.

**Comment by AlexandreEichenberger** [comment]
> While I understand the concern about latency here, I also feel that the purpose of the CI testing is to prevent broken code getting into the repo, so really all tests that we feel are useful should be mandatory.

It currently take 5x more time for the Window CI to complete as our other CIs.

**Comment by NathanielMcVicar** [comment]
The build runs on a free Microsoft hosted Windows VM pipeline. These are available to everyone, so shouldn't be a problem for IBM folks to access, but are very small (currently 2 Xeon E5-2673 vCPUs and 7 GB RAM), hence the long build times. More information is available here: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#faq. I think if we wanted faster Windows VMs to be part of the regular CI someone would have to provide them.

**Comment by sstamenova** [comment]
Considering that most PRs currently take on the order of days to get approved and committed, I think a 2-hour build is not much of a detriment to the process, while it will guarantee that there are no breaks that accidentally get checked in. I would like to see the Windows CI become required regardless of how long the builds take and then we can look at improving the build time.

I can spend some time next week to see what can be done about the build times, but again, I think the Windows CI should be required regardless.

**Comment by caoimhinuibrian** [comment]
> Considering that most PRs currently take on the order of days to get approved and committed, I think a 2-hour build is not much of a detriment to the process,

Yes, I agree that a couple of hours does not seem to be a huge impediment

**Comment by caoimhinuibrian** [comment]
> I can spend some time next week to see what can be done about the build times, but again, I think the Windows CI should be required regardless.

Does the Windows build cache the llvm part currently?

**Comment by sstamenova** [comment]
> > I can spend some time next week to see what can be done about the build times, but again, I think the Windows CI should be required regardless.
> 
> Does the Windows build cache the llvm part currently?

It does not, that's one of the improvements, but it would require a new pipeline to build just llvm because the free hosted agents are stateless.

**Comment by NathanielMcVicar** [comment]
I think this is a significant difference, the macOS and Windows GitHub CI builds don't and the macOS one also takes over an hour. The fast Jenkins CI builds use docker and have LLVM cached. I don't see any reason why the Windows build can't use a similar Docker Hub cache (in which case the stateless MS hosted Windows VMs wouldn't be an issue).

**Comment by AlexandreEichenberger** [comment]
> Considering that most PRs currently take on the order of days to get approved and committed, I think a 2-hour build is not much of a detriment to the process

Except that a PR is often built 5-10 times before its squashed, so lower times are clearly appreciated. 
Also, smaller PR should be encouraged as they are easier to review, and this is building a disincentive to smaller PRs.

> I don't see any reason why the Windows build can't use a similar Docker Hub cache

That would be great indeed. LLVM is very large, so it takes a large amount of time to build.

> The build runs on a free Microsoft hosted Windows VM pipeline. 

Could we ask you to add some instructions here on how to pull a docker image and run it on these free Windows VM? @gongsu832 has done very helpful work by having docker images stored for us to quickly test (without having to rebuild llvm, a big help, and even at time without rebuilding MLIR). Would be great to have similar instructions for Windows.

I am in favor to add Windows CI, as it shifts more work on our team, we should have the tools to perform this additional work.

**Comment by NathanielMcVicar** [comment]
I've never used a Windows container in Docker before, but I'm sure I can figure it out. :)

**Comment by sstamenova** [comment]
@AlexandreEichenberger : Either Nate or I will have a look next week.

**Comment by AlexandreEichenberger** [comment]
@sstamenova @NathanielMcVicar how is it going? We are really looking forward to the faster times.

**Comment by NathanielMcVicar** [comment]
@AlexandreEichenberger I apologize for my radio silence. I've been on leave, but I would like to take a look at this now, if the situation hasn't changed. Our current thought is to cache LLVM as an Azure DevOps pipeline artifact. I don't see any reason this won't work with the free builders in the documentation, but I haven't tried. We would then rebuild on any change to utils/clone-mlir.sh.

**Comment by AlexandreEichenberger** [comment]
Would be great if you had a chance, and yes, its still taking significantly longer than the other builds.
