### ISSUE TITLE
zlib link issue with cmake --build . --target onnx-mlir

### ISSUE THREAD

**Issue by ananthdurbha** [onnx/onnx-mlir#79]
I am seeing following issue when building onnx-mlir

```
[ 98%] Built target OMShapeInference
[ 98%] Linking CXX executable ../bin/onnx-mlir
/usr/bin/ld: </path/to/workspace>/llvm-project/build/lib/libLLVMSupport.a(Compression.cpp.o): undefined reference to symbol 'crc32'
/usr/lib/x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
```

It seems above path to libz.so is returned by cmake command find_package(ZLIB REQUIRED)  (in src folder). Any suggestions ? (eg. do I need to update cmake find_package search path, or use static lib ? )

Thanks,
Yetanadur
(Ananth)

**Comment by tjingrant** [comment]
The fix is in part of this patch being reviewed - https://github.com/onnx/onnx-mlir/pull/77.

**Comment by jacky82226** [comment]
Encountered the same issue yesterday while installing onnx-mlir in Linux.
In `MLIR.cmake`, adding ${ZLIB_LIBRARIES} in SET(MLIRLibsOnce) can solve this issue for the latest commit.

**Comment by tjingrant** [comment]
I believe this issue has been resolved.
