### ISSUE TITLE
mtriple, mcpu and march

### ISSUE THREAD

**Issue by sstamenova** [onnx/onnx-mlir#797]
onnx-mlir right now provides `mtriple` and `mcpu` as options to both the onnx-mlir executable as well as the backend tests, however, it does not provide `march`. For tools such as `opt` or `clang` generally `mtriple` defines both `march` and `mcpu`, but for more granular control (if `mtriple` is not desirable), both `mcpu` and `march` exist as options.

Something to consider is whether `mcpu` is needed for onnx-mlir (since `mtriple` already exists as an option) and if `march` should be added as well.

**Comment by AlexandreEichenberger** [comment]
@sstamenova can we close this?

**Comment by sstamenova** [comment]
I would like to see an answer to the question before we close it. That way if it comes up again for someone, they can find it.

**Comment by sstamenova** [comment]
@gongsu832 or @etiotto : since you've touched these options in the past, are both `mcpu` and `mtriple` needed? Should `march` be added for completeness?

**Comment by gongsu832** [comment]
I don't think I did anything with these options. If I ever touched them, it was probably only because I need to preserve them when I made changes to other parts.

**Comment by etiotto** [comment]
From LLVM `llc` (similar for `opt`) documentation:
```
-mtriple=<target triple>
Override the target triple specified in the input file with the specified string.

-march=<arch>
Specify the architecture for which to generate assembly, overriding the target encoded in the input file. See the output of llc -help for a list of valid architectures. By default this is inferred from the target triple or autodetected to the current architecture.

-mcpu=<cpuname>
Specify a specific chip in the current architecture to generate code for. By default this is inferred from the target triple and autodetected to the current architecture.
``` 

So `-march` and `-mcpu` are used to provide finer level of control than `-mtriple`.  

Currently `onnx-mlir` has `-mtriple` and `-mcpu`, however it lacks `-march`.  I think, for completeness and flexibility we should provide `-march` as well.
