### ISSUE TITLE
Add JNI tests

### ISSUE THREAD

**Issue by gongsu832** [onnx/onnx-mlir#799]
Creating this issue to track the discussions about adding JNI tests.

From last meeting, the main issue appears to be whether JNI should use its own set of tests (option #1) or we can extend some of the existing C/C++ tests to also perform JNI tests (option #2). Both have pros and cons.

The pros of option #1 is that I already started porting some of the model level tests from DLC Classic so we save that part of the effort. However, we are still missing the node level tests that need to be ported. A separate set of tests for JNI also adds some maintenance overhead. This option also needs some additional 3rd party dependencies such as google test.

For option #2, I see that the current backend tests already provide both node level and model level tests. So being able to reuse them without having to maintain a separate set of tests and without introducing more 3rd party dependencies would be nice. However, @chentong319 mentioned that the backend tests are tied to onnx. So I dug a bit into `test/backend/test.py` and saw that we actually define our own subclass `DummyBackend` to override the `prepare` method. In other words, we have complete control over how each of the tests is compiled and run by `prepare` -> `EndiannessAwareExecutionSession` -> `ExecutionSession`. And it doesn't seem that hard to extend this path to compile and run each test with JNI codegen.

So unless there are other issues I'm not aware of about onnx backend test, I'm leaning towards option #2. And if there is no objection, I can take a stab at implementing it.

**Comment by AlexandreEichenberger** [comment]
@gongsu832 is this issue completed with the recent additional tests?

**Comment by gongsu832** [comment]
Done.
