### ISSUE TITLE
New  issues for yolo model with the latest master branch

### ISSUE THREAD

**Issue by chentong319** [onnx/onnx-mlir#817]
For the original model (dynamic shape), I got the following error:
```
error: Conv Pads defined as SAME_UPPER or SAME_LOWER requires compile time X sizes
error: Failed to scan Conv parameters successfully
error: shape inference failed
```
I guess the previous version just assumed the shape of the output tensor.

This error went away if the static shape of the input tensor for the model  is provided. However, the program did stop for extremely long time (> 30 minutes) just for `--EmitMLIR`. I checked and found it stuck in optimize-memory-pool pass.

**Comment by AlexandreEichenberger** [comment]
Yes, currently the code was just assigning bogus value to the padding. If the size is RT, then SAME_* needs to introduce actual computations to determine the size. 
I looked at the static yolo that you gave me, @chentong319 , and there were only pad sizes that were explicit.
If it is in the model, then we should really rework the CONV with shape helper framework to handle this problem systematically.

**Comment by AlexandreEichenberger** [comment]
Update #826 should fix this issue.
