### ISSUE TITLE
is ok that I could convert xxx.mlir back to onnx?

### ISSUE THREAD

**Issue by Joejiong** [onnx/onnx-mlir#860]
Hi friends, 
is ok that I could convert xxx.mlir back to onnx?

this is important for me, maybe others, because, when u get an raw trained model from some framework, then I transfer to mlir for optimization, and then, I don't want to directly use it to lower to llvm bitcode later obj. I want to transfer the optimized xxxx.mlir back to xxxx.onnx for other runtime system that already support onnx as input but not mlir as input.

**Comment by AlexandreEichenberger** [comment]
Hi @Joejiong, there is some interest in this functionality but this is currently not on our internal roadmap. We would be excited to review any PRs that you may have.

**Comment by Joejiong** [comment]
thx for the response.

**Comment by AlexandreEichenberger** [comment]
closed for lack of activity
