### ISSUE TITLE
Converting Krnl to affine or std

### ISSUE THREAD

**Issue by axmat** [onnx/onnx-mlir#888]
It seems that even after converting the Krnl dialect to the Affine dialect by using `onnx-mlir-opt --convert-krnl-to-affine --lower-affine input.mlir > out.mlir`, some operations of Krnl are not converted to Affine. How to get rid of the Krnl dialect ?

When I try to add the C wrappers using `mlir-opt --convert-std-to-llvm='emit-c-wrappers=1' --allow-unregistered-dialect out.mlir -o c.mlir` I am getting the following error:

`out.mlir:2939:24: error: custom op 'krnl.vector_type_cast' is unknown
                %198 = krnl.vector_type_cast %95 : memref<256x64xf32> to memref<256x4xvector<16xf32>>`

Thanks!

**Comment by AlexandreEichenberger** [comment]
To get a good feel, either read the code that plan the optimizations, and/or run `onnx-mlir` with the `-print-ir-after-all` options. There are indeed more opts to lower krnl just before LLVM. Others are needed if there are simd instructions.

**Comment by AlexandreEichenberger** [comment]
closed due to lack of activity
