### ISSUE TITLE
Updating onnx.md and krnl.md

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#916]
Right now, our doc dir has possibly outdated onnx.md and krnl.md files, which can be auto-generated from their respective Dialect/ONNX/ONNXOps.td and Dialect/Krnl/KrnlOps.td using the `make onnx-mlir-docs` command.

That make script generates the up to date files under the build directory. Kevin's suggestion is that we automatically move them under Docs/Dialect subdirectories, when we rebuild the *.td files

Would someone object? And someone knows how to do this in the cmake env?

**Comment by tungld** [comment]
Have you looked at [`make OMONNXOpsIncTranslation`](https://github.com/onnx/onnx-mlir/blob/master/utils/CMakeLists.txt#L24)? It automatically generates `.inc` files and move them to appropriate places. I hope we can do the same for `make onnx-mlir-docs`

**Comment by AlexandreEichenberger** [comment]
@tungld found a way, linked a PR that implements this change.

**Comment by AlexandreEichenberger** [comment]
implemented in #972
