### ISSUE TITLE
Support for SpaceToDepth operator

### ISSUE THREAD

**Issue by etiotto** [onnx/onnx-mlir#926]
Implement the SpaceToDepth operator. The operator outputs a copy of the input tensor where values from the `height` and `width` dimensions are moved to the `depth` dimension. The attr `blocksize` indicates the input block size.

* blocks of size `blocksize x blocksize` are rearranged into the depth dimension
* The new depth is `blocksize * blocksize * depth`
* The input tensor's height and width must be divisible by block_size.

Given input tensor `[N,C,H,W]` the output tensor has shape  `[N, C * blocksize * blocksize, H/blocksize, W/blocksize]`. 
The transformation can be seen as a sequence of a `reshape + transpose + reshape` operations:
 ```
    NC  = C * (blocksize * blocksize)
    NH = H / blocksize
    NW = W / blocksize

    tmp1 = reshape(input, [N, C, NH, blocksize, NH, blocksize])
    # new axis: [num, ch, scale_factor, scale_factor, new_height, new_width]
    tmp2 = transpose(tmp1, [0, 1, 3, 5, 2, 4])
    out = tensor.reshape(tmp2, [N, NC, NH, NW])
```

**Comment by AlexandreEichenberger** [comment]
PRs are being reviewed and merged

**Comment by etiotto** [comment]
PR #921 is not merged so I prefer to keep this work item open until then.
