### ISSUE TITLE
Use LLVM_DEBUG to add tracing code (rather than custom approaches)

### ISSUE THREAD

**Issue by etiotto** [onnx/onnx-mlir#930]
The standard way to add tracing code in the LLVM and MLIR projects is to use the `LLVM_DEBUG` macro (https://llvm.org/docs/ProgrammersManual.html#the-llvm-debug-macro-and-debug-option).  Currently there are "home brewed" solutions in various `onnx-mlir` source files.  We should migrate the code to consistently use the standard MLIR/LLVM solution.

**Comment by AlexandreEichenberger** [comment]
I believe all printf were transformed using the scheme recommended here. Will migrate some of the text here into our documentation.
