### ISSUE TITLE
OneHot in Bert model (opset 10) failed 

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#934]
When compiling [Bert opset 10 model](https://github.com/onnx/models/blob/41ccf18ba5a815dab714899ac234e9b1e4293c20/text/machine_comprehension/bert-squad/model/bertsquad-10.onnx), there were an error 
```
bertsquad-10.onnx.mlir:278:12: error: 'std.addi' op requires the same type for all operands and results
    %275 = "onnx.OneHot"(%232, %269, %274) {axis = 1 : si64, onnx_node_name = "bert/embeddings/one_hot"} : (tensor<?xi64>, tensor<1xi32>, tensor<2xf32>) -> tensor<?x2xf32>
           ^
bertsquad-10.onnx.mlir:278:12: note: see current operation: %15600 = "std.addi"(%15597, %1875) : (i64, i32) -> i64
```

This error was related to the lowering of OneHot.

**Comment by AlexandreEichenberger** [comment]
PR #967 is now merged into master, with more support for conversions.

@tungld  Let me know if that covers the cases experienced in Bert.

**Comment by tungld** [comment]
I confirmed we can compile Bert now.
