### ISSUE TITLE
third_party/onnx build problem

### ISSUE THREAD

**Issue by chentong319** [onnx/onnx-mlir#94]
I ran into two issues when trying "python setup.py install" and got them fixed. Not sure about the protocol of modifying third_part/onnx. I just post them as an issue now, in case anyone encounters them.

1. purest_runner not supported by pypi. Delete it from required list in setup.py

2. New version of protobuf  is causing problem, fixed by onnx#2482  (https://github.com/onnx/onnx/pull/2482) . It is a one-line change in CMakelist.txt

**Comment by Xatter** [comment]
As a workaround, I've found that if you use a `virtualenv` then all of these build issues go away.

```bash
$ virtualenv onnx-mlir -p python3
$ source onnx-mlir/bin/activate
$ pip install numpy onnx protobuf
```
