### ISSUE TITLE
OMTensorList _size bug

### ISSUE THREAD

**Issue by gongsu832** [onnx/onnx-mlir#979]
This is another 32-bit/64-bit int type mismatch bug uncovered by the JNI tests I'm trying to add.

The `_size` field of `OMTensorList` is defined as `size_t`, which is 8 bytes on most platforms. However, the APIs `omTensorListCreate` and `omTensorListCreateWithOwnership` take 4 bytes int as parameters. As we have seen before, this will result in the upper 4 bytes of `_size` getting garbage at random times depending on register usage.

We have been "lucky" so far since the API `omTensorListGetSize` returns a 32-bit int which gets the correct value even if the upper 4 bytes of `_size` has garbage. However, the following line in the OMTensorList destructor and function `omTensorListDestroy` will fail,
```
for (size_t i = 0; i < list->_size; i++)
```
since `i` will iterate over the huge int of the entire 8 bytes. For example, with the `inception_v1` model I have observed,
```
omTensorListDestroy _size=3ff00000001 _omts=0x3ffac575240 _owning=1
```
And the reason the bug was not uncovered by the C/C++ backend tests is the same as that of #929, i.e., `PyExecutionSession::pyRun` never tried to free the output tensors.

The fix should be fairly simple. Either we change the `_size` type to 32-bit int or change all related API calls to use 64-bit int. Either way, we should be explicit with the type and avoid using `size_t` since it's platform dependent.

**Comment by tungld** [comment]
>  Either we change the _size type to 32-bit int or change all related API calls to use 64-bit int.

@gongsu832 Gong, I changed all API calls to use 64-bit int in the PR #975 also, since it is easy to be done.

**Comment by gongsu832** [comment]
@tungld Thanks. We'd also need to change all the API calls in `src/Runtime/OMTensor.inc, OMTensorList.inc`, and their corresponding headers in `include/onnx-mlir/Runtime/OMTensor.h, OMTensorList.h`.

**Comment by tungld** [comment]
> We'd also need to change all the API calls in src/Runtime/OMTensor.inc, OMTensorList.inc, and their corresponding headers in include/onnx-mlir/Runtime/OMTensor.h, OMTensorList.h.

Yes, done.

**Comment by gongsu832** [comment]
@tungld While we are at it, perhaps we should rename the API `omTensorCreateEmptyDeprecated` to `omTensorCreateUntyped` or switch to `omTensorCreateEmpty`? It's weird to call something with `Deprecated` in the name.

**Comment by tungld** [comment]
@gongsu832 I asked the same question in my mind about this function name. Maybe `omTensorCreateUntyped` is more suitable since it does not set shape and data type.

**Comment by tungld** [comment]
@gongsu832 FYI, I just merged the PR. If it did not help fix this issue, please let me know. Thanks!

**Comment by gongsu832** [comment]
@tungld All JNI tests pass now. Thanks. Closing the issue.
