### ISSUE TITLE
Verify for ONNXScatterNDOp

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#983]
@DavidChan0519 Made this issue as a reminder of what remains to be done for shape inference. Thanks

-----------

Looking at the spec of the operation, I see that there are some conditions to the operation. Quoting the specs

Inputs

data (differentiable) : T
Tensor of rank r >= 1.
indices (non-differentiable) : tensor(int64)
Tensor of rank q >= 1.
updates (differentiable) : T
Tensor of rank q + r - indices_shape[-1] - 1.
Outputs

output (differentiable) : T
Tensor of rank r >= 1.
What we like to do in cases like this is verifying this info in a "verifier".  Instructions on how to add a verifier are shown here
https://github.com/onnx/onnx-mlir/blob/master/docs/HowToAddAnOperation.md#generate-the-proper-onnxtdinc

Verifier works in many environments, so we have to accommodate for the fact that tensors may not be ranked yet. A good example of code is found here:

onnx-mlir/src/Dialect/ONNX/ONNXOps.cpp
Line 3395 in 3f25ef2
 static LogicalResult verify(ONNXInstanceNormalizationOp op) { 
Would be great if you could add it.

**Comment by DavidChan0519** [comment]
> @DavidChan0519 Made this issue as a reminder of what remains to be done for shape inference. Thanks
> 
> Looking at the spec of the operation, I see that there are some conditions to the operation. Quoting the specs
> 
> Inputs
> 
> data (differentiable) : T Tensor of rank r >= 1. indices (non-differentiable) : tensor(int64) Tensor of rank q >= 1. updates (differentiable) : T Tensor of rank q + r - indices_shape[-1] - 1. Outputs
> 
> output (differentiable) : T Tensor of rank r >= 1. What we like to do in cases like this is verifying this info in a "verifier". Instructions on how to add a verifier are shown here [`master`/docs/HowToAddAnOperation.md#generate-the-proper-onnxtdinc](https://github.com/onnx/onnx-mlir/blob/master/docs/HowToAddAnOperation.md?rgh-link-date=2021-11-09T15%3A08%3A53Z#generate-the-proper-onnxtdinc)
> 
> Verifier works in many environments, so we have to accommodate for the fact that tensors may not be ranked yet. A good example of code is found here:
> 
> onnx-mlir/src/Dialect/ONNX/ONNXOps.cpp Line 3395 in [3f25ef2](https://github.com/onnx/onnx-mlir/commit/3f25ef25dc940958aafbacf5e66cb51ab4086738) static LogicalResult verify(ONNXInstanceNormalizationOp op) { Would be great if you could add it.

I have added the verify interface implementation for scatterND op already.
