### ISSUE TITLE
Error when using separated `krnl.iterate`

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#984]
I tested the following simple code:

```mlir
func @simple_unroll(%arg0 : memref<8xf32>) {
  %ii = krnl.define_loops 1
  %ii1, %ii2 = krnl.block %ii 2 : (!krnl.loop) -> (!krnl.loop, !krnl.loop) 
  krnl.unroll %ii2 : !krnl.loop
  krnl.iterate(%ii1) with (%ii -> %i = 0 to 8) {
    krnl.iterate(%ii2) with () {
      %i2 = krnl.get_induction_var_value(%ii2) : (!krnl.loop) -> index
      %foo = arith.addi %i2, %i2 : index
    }
  } 
  return
}
```

When lowering to affine using `convert-krnl-to-affine`, I got:
>onnx-mlir-opt: /home/tungld/dl/llvm-project/mlir/include/mlir/IR/OpDefinition.h:803: mlir::Block* >mlir::OpTrait::SingleBlock<ConcreteType>::getBody(uns
>igned int) [with ConcreteType = mlir::AffineForOp]: Assertion `!region.empty() && "unexpected empty region"' failed.
>PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.

However, there is no problem if we use a singe `krnl.iterate` for `%ii1` and `%ii2`, like this:
```mlir
func @simple_unroll(%arg0 : memref<8xf32>) {
  %ii = krnl.define_loops 1 
  %ii1, %ii2 = krnl.block %ii 2 : (!krnl.loop) -> (!krnl.loop, !krnl.loop)
  krnl.unroll %ii2 : !krnl.loop
  krnl.iterate(%ii1, %ii2) with (%ii -> %i = 0 to 8) {
    %foo = arith.addi %i, %i : index
  } 
  return
}
```

I wonder if this is a bug or my way of writing that code is not recommended. @AlexandreEichenberger @tjingrant any thought?

**Comment by AlexandreEichenberger** [comment]
@tungld currently the Krnl lowering is very finicky. What is missing here is the permute, in the first pattern. I found that for N nested loop with M unrolled loops, you need to declare all N together, then block, then have one permute with all of the N+M loop, even if some loops are not permuted and/or blocked, then one kernel iterate with if possible all of the bounds (safer that way), and then the loops.

**Comment by AlexandreEichenberger** [comment]
The hope is that there might be a pattern that satisfies all conditions; I have currently a PR #981 that tries to use @tjingrant latest suggestion #688 but I think some pattern may not fit, to be determined yet.

**Comment by tungld** [comment]
```mlir
func @simple_unroll(%arg0 : memref<8xf32>) {
  %ii = krnl.define_loops 1
  %ii1, %ii2 = krnl.block %ii 2 : (!krnl.loop) -> (!krnl.loop, !krnl.loop) 
  krnl.unroll %ii2 : !krnl.loop
  krnl.iterate(%ii1) with (%ii -> %i = 0 to 8) {
    krnl.iterate(%ii2) with () {
      %i2 = krnl.get_induction_var_value(%ii2) : (!krnl.loop) -> index
      %foo = arith.addi %i2, %i2 : index
    }
  } 
  return
}
```
This looks like a bug, `%ii2` is marked as unroll so there is not AffineForOp for `krnl.iterate(%ii2)`. Now `krnl.get_induction_var_value(%ii2)` will look for the induction variable of the corresponding AffineForOp, but AffineForOp does not exist, so empty region.

**Comment by AlexandreEichenberger** [comment]
I believe you may need a permute because of the block, try it to see if it helps

**Comment by tungld** [comment]
> I believe you may need a permute because of the block, try it to see if it helps

Thanks for your suggestion! I tried with permute but still got the same error. Now I know it is because unroll does not work well with get_induction_var. I am in the middle fixing the bug and can be partially generate code (without permute).
