### ISSUE TITLE
Check mismatch between compiler gen. call and runtime prototype

### ISSUE THREAD

**Issue by etiotto** [onnx/onnx-mlir#996]
Internal testing reports the following:

"For the runtime library I noted the prototype `void @omTensorSetDataPtr(i8*, i32, i8*, i8*)`. Comparing this with latest onnx-mlir source, it seems to me that the i32 parameter is really int64_t aka i64."

We need to verify whether that is a problem (or still a problem).

**Comment by AlexandreEichenberger** [comment]
This problem was detected by Kai Nache and he mentioned that he saw at least another instance of the same problem, so it would be good to do a general review of places with i32 param in our onnx-mlir code.

My recommendation would be to move all parameters of the runtime interface to i64, so that the code be as regular as possible.

**Comment by AlexandreEichenberger** [comment]
@gongsu832 would you be able to look into this?

**Comment by gongsu832** [comment]
As far as I know, the runtime library has moved everything to int64_t. I have no idea how internally you generate i32 or i64.

**Comment by etiotto** [comment]
This is probably fixed now because, the current code contains (KrnlToLLVM.cpp):
```
std::vector<ApiSpec> apiSpecs = {
 . . . 
   ApiSpec(API::SET_DATA, "omTensorSetDataPtr", voidTy, {opaquePtrTy, int64Ty, opaquePtrTy, opaquePtrTy}),
                                                                      ^^^^^
```
I see that @tungld has updated that line of code a month ago in #975.
Also we do have LIT tests that check for the correct call (krnl_to_llvm_omtensor_ownership.mlir):

```
module {
// Check that output OMTensor does not own the data pointer because data is a constant.
  func @return_constant() -> memref<8xf32> { 
    %0 = "krnl.global"() {name = "cst0", shape = [8], value = dense<[1., 2., 3., 4., 5., 6., 7., 8.]> : tensor<8xf32>} : () -> memref<8xf32>
    return %0 : memref<8xf32>
  }
  "krnl.entry_point"() {func = @return_constant, numInputs = 0 : i32, numOutputs = 1 : i32, signature = ""} : () -> ()

  // CHECK-LABEL: return_constant 
  // CHECK: llvm.call @_mlir_ciface_return_constant
  // CHECK: [[OWNING:%.+]] = llvm.mlir.constant(0 : i64) : i64
  // CHECK: llvm.call @omTensorSetDataPtr({{.*}}, [[OWNING]], {{.*}}, {{.*}}) : (!llvm.ptr<i8>, i64, !llvm.ptr<i8>, !llvm.ptr<i8>) -> ()
                                                                                                ^^^^
}
```

@tungld  assigning to you, can you pls close it after taking a peek ?

**Comment by AlexandreEichenberger** [comment]
closing due to inaction
