### ISSUE TITLE
Missing alignment specification for global constant

### ISSUE THREAD

**Issue by etiotto** [onnx/onnx-mlir#998]
Example:
```
% cat ~/tmp/test.mlir
func private @test() -> memref<6xi32>  {
  %0 = "krnl.global"() {name = "c", shape = [6], value = dense<[1,2,3,4,5,6]> : tensor<6xi32>} : () -> memref<6xi32>
  return %0 : memref<6xi32>
}

% onnx-mlir  ~/tmp/test.mlir --preserveBitcode                                            
Shared library /Users/etiotto@ca.ibm.com/tmp/test.so has been compiled.

% llvm-dis  ~/tmp/test.bc 
% cat ~/tmp/test.ll 
; ModuleID = '/Users/etiotto@ca.ibm.com/tmp/test.bc'
source_filename = "LLVMDialectModule"
target datalayout = "e"
target triple = "x86_64-apple-darwin20.6.0"

@c = internal constant [6 x i32] [i32 1, i32 2, i32 3, i32 4, i32 5, i32 6]

; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define { i32*, i32*, i64, [1 x i64], [1 x i64] } @test() local_unnamed_addr #0 !dbg !3 {
  ret { i32*, i32*, i64, [1 x i64], [1 x i64] } { i32* getelementptr inbounds ([6 x i32], [6 x i32]* @c, i32 0, i32 0), i32* getelementptr inbounds ([6 x i32], [6 x i32]* @c, i32 0, i32 0), i64 0, [1 x i64] [i64 6], [1 x i64] [i64 1] }, !dbg !7
}
. . . 
```

The definition for the global variable `c`:
```
@c = internal constant [6 x i32] [i32 1, i32 2, i32 3, i32 4, i32 5, i32 6]
```
should have an alignment specification, for example 16 (code generated by clang for a global array of ints has alignment 16):
```
% cat ~/tmp/constant.c
int arr[] = {1, 2, 3, 4, 5, 6};

% clang -S -emit-llvm  ~/tmp/constant.c
% cat constant.ll
; ModuleID = '/Users/etiotto@ca.ibm.com/tmp/constant.c'
source_filename = "/Users/etiotto@ca.ibm.com/tmp/constant.c"
target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-macosx11.0.0"

@arr = global [6 x i32] [i32 1, i32 2, i32 3, i32 4, i32 5, i32 6], align 16
```

**Comment by tungld** [comment]
I have no idea about whether we should set default alignment for global constants or not. But, just in case we want to do that, we can set it in `krnl.global`, e.g.
```
%0 = "krnl.global"() {alignment = 16 : i64, name = "c", shape = [6], value = dense<[1,2,3,4,5,6]> : tensor<6xi32>} : () -> memref<6xi32>
```

**Comment by tungld** [comment]
> Setting the alignment to 16 can degrade performance. I have seen LLVM result in slower binary when alignment is explicitly stated at 16 bytes.

So do I.

I wonder whether `target datalayout` has any effect on performance or not. I see that alignment is mentioned in its description: https://llvm.org/docs/LangRef.html#langref-datalayout

**Comment by AlexandreEichenberger** [comment]
@tungld nice find. From a quick read, `target data layout` is a good way to say the alignment for the default type sizes. 

There is one for the "aggregate" (is that struct or unions?). Looking at LinuxOne, for structs, it was complicated. It basically looked at the largest type in the struct, and then made the entire structure aligned to that.

For our tensors, we are mainly looking at arrays, and to see if the alignment of the array is just the default alignment of the element type of the array, or something larger. For POWER LE, it seems that its 16 bytes regardless of the element type, if the array is longer than 8 bytes. For LinuxOne/Z it seems to be the alignment of the element type, from my read of it.

**Comment by gongsu832** [comment]
Quote from https://www.gnu.org/software/libc/manual/html_node/Aligned-Memory-Blocks.html
```
3.2.3.6 Allocating Aligned Memory Blocks

The address of a block returned by malloc or realloc in GNU systems is always a multiple of eight (or sixteen on 64-bit systems). ...
```
The default alignment on 64-bit systems is typically 16 bytes. So it's hard to believe the performance degradation is actually due to the alignment itself. More likely explicitly setting alignment to 16 bytes may have other side effects that caused the performance degradation.

**Comment by etiotto** [comment]
> @tungld nice find. From a quick read, target data layout is a good way to say the alignment for the default type sizes.

Yup that is the case. The missing datalayout problem is tracked in #997.

> There is one for the "aggregate" (is that struct or unions?).

Aggregate means both struct and unions (and class too). 

> Looking at LinuxOne, for structs, it was complicated. It basically looked at the largest type in the struct, and then made the entire structure aligned to that.

Yes aggregate types should be aligned according to the alignment of their most strictly aligned member.

> For our tensors, we are mainly looking at arrays, and to see if the alignment of the array is just the default alignment of the element type of the array, or something larger. 

The *minimum* alignment for an array should be equal to the alignment of its element type. However we are allowed to specify a more stringent alignment (in C users can achieve that via extensions like GCC's `__attribute__((aligned(num)))`).

**Comment by etiotto** [comment]
So here is a proposal:
  - if `krnl.global` was generated with an explicit alignment we should respect it and the corresponding LLVM IR should have the same `align` specifier value. 
  - if `krnl.global` was not created with an explicit alignment specifier we should respect the target architecture convention and set the `align` specifier in the generated LLVM IR  to convey the same value that clang would.

**Comment by etiotto** [comment]
Looks Like we have agreement. I'll start working on the patch for this.
